export const meta = {
  name: 'rta-1002b-plans-bf',
  description: 'Audio-DNA s-rta-1002b: Boris feedback BF1-BF9 — timeline-bug repro, then 7 plans (opus architect) -> blind seats -> rulings',
  phases: [{ title: 'Diagnose' }, { title: 'Plan' }, { title: 'Attack' }, { title: 'Rule' }],
}
const MAIN = '/Users/boriskarpman/projects/RealTimeAudio'
const RPT = '.harmony/.reports/s-rta-1002b'
const SP = '/private/tmp/claude-501/-Users-boriskarpman-projects-RealTimeAudio/73d4f54c-e9d5-409c-8b5d-694bfd57c171/scratchpad'
const BF = `${MAIN}/.harmony/boris-feedback-backlog.md (Boris's message verbatim + items BF1-BF9) and ${MAIN}/.harmony/binding-decisions.md section "2026-10-02 (s-rta-1002b)" (his answers, verbatim in quotes; the rest is Harmony's consequence text)`
const COMMON = `
CONTEXT: Audio-DNA (C++20 / JUCE 8.0.4 / OpenGL 4.1, macOS M1 Pro 32 GiB 120 Hz, Command Line Tools only, no Xcode). Repo ${MAIN}, main HEAD 5e47d17. Session s-rta-1002b (secondary Harmony, autonomous). Boris (owner, non-technical VJ) evaluated the app and sent feedback: READ ${BF}. The repo CLAUDE.md is loaded for you: obey its Sacred Rules, UI Patterns (ResettableSlider, showMenuAsync, etc.) and Pitfall index (read the full docs/claude/pitfalls.md entry for any pitfall you touch); the trigger table names the docs/claude/*.md to read for your area. Boris's earlier rulings: BORIS_DECISIONS.md (esp. "Playback Behaviour", "Timeline", "Clip Cells", "Layer Strip", "Inspector Tabs") and .harmony/binding-decisions.md — a new answer beats an older ruling only where Boris said so; flag every other conflict. APP map: .harmony/APP-INVENTORY.md.
SEVEN PLANS ARE WRITTEN IN PARALLEL (one per lane): bf9 (deck change stops the old deck; Persistent removed), bf6 (Timeline source follows the clip / layer playhead), ui (BF3 codec + Show in Finder; BF8 double-click deck rename), bf7 (bars wherever beats), bf2 (per-venue sync dial), bf1 (record output / layer to a clip), bf45 (envelope editor + envelopes from an audio sample). Also planned elsewhere: tsan-r5 (Relaxed<T> for config scalars + the httplib reader; built AFTER bf9). Pre-registered BUILD ORDER: bf9 -> bf6 -> ui -> bf7 -> bf2 -> bf1 -> bf45 -> tsan-r5, at most 3 building at once in separate worktrees, merged one at a time. Where your lane must touch a file another lane also touches (likely: MainComponent.cpp, ClipInspector, LayerInspector, SignalInspector, DeckView / deck tab row, TopBar, CompositorEngine, Layer.h / Clip.h / Composition.h, serialization), name the exact functions / blocks so Harmony can sequence merges; do not plan edits inside another lane's core.
PLAN FORMAT (mandatory): (1) GOAL in one line, and Boris's words it serves (quote verbatim); (2) ESTABLISHED facts, each labelled VERIFIED (you read it / ran it: cite file:line) or INFERRED; (3) DESIGN FORK(S): every defensible alternative, evidence, your choice, why the runner-up loses; (4) numbered ITEMS: files + functions, exact behaviour change, RED-first test(s) (a unit test in tests/ that drives real code and FAILS on main 5e47d17 — say how — or a named probe row with a pre-registered bar), GREEN bar, risk; plus BUILD STAGES (one builder context each, dependency order; which stages could ship alone); (5) GATES Harmony runs herself after the merge (commands / probes / bars, pre-registered decision rules; perf only via INTERLEAVED A/B, >= 5 runs per arm; a bar whose teeth equal the drift is INFO); for ANY visible UI: the VISUAL WORK GATE — a critic panel (visual-design + UX + graphic-design + logic critics; a dedicated interaction-logic critic for anything stateful / navigational) on decoded window captures (Quartz window id only) BEFORE Boris sees it, then an artifact page he opens; (6) DOCS: docs/claude/*.md sections, CLAUDE.md lines (24,002 of its 25,000-byte cap after lane hyg; any addition paid by moving text into docs/claude/*.md), APP-INVENTORY.md, BORIS_DECISIONS.md; new pitfalls written "Pitfall NN" (Harmony assigns; next free 64); (7) RISKS with the cheapest discriminating test; (8) WHAT ONLY BORIS CAN CHECK (feel / taste on the live rig); (9) QUESTIONS that are genuinely Boris's (product / taste only, plain words, no jargon) — each with a DEFAULT so the build never blocks.
RIG RULES the plan must respect (builders obey them; plan nothing that needs a violation): at most ONE live Audio-DNA at a time (lock helper); launch only via open -g ... [--args --test-mode]; NEVER open an Output window in any gate; no synthetic input (UI states via REST / composition files / a TEMPORARY env-var hook reverted before merge); NEVER lldb / debugserver / gdb / dtrace / Instruments / sample on any binary; never a full-screen screencapture (window-only by Quartz window id); never copy + re-sign an app bundle; sanitizer options abort_on_error=0; probe HTTP clients use Connection: close; check ps for CPU burners before perf verdicts; a background run is capped at 2 h.
You are read-only on source (read-only commands, git log / show / grep, scratch experiments under /private/tmp that do not launch the app). Every claim about current code cites file:line you actually read. Write a SKELETON plan (the 9 headings) via Bash heredoc to the REPORT_FILE path within your first ~10 tool calls, then REWRITE it as sections firm up. Final reply (text) = a short manifest: plan path, goal, fork choices, item ids + titles, build stages, files shared with other lanes, Boris questions with defaults.`

const ATK_S = { type: 'object', properties: { seat: { type: 'string' }, verdict: { type: 'string', enum: ['ADOPT', 'AMEND', 'REJECT'] }, attacks: { type: 'array', items: { type: 'object', properties: { severity: { type: 'string', enum: ['MUST', 'SHOULD', 'NIT'] }, claim: { type: 'string' }, evidence: { type: 'string' }, fix: { type: 'string' } }, required: ['severity', 'claim', 'evidence'] } } }, required: ['seat', 'verdict', 'attacks'] }
const DIAG_S = { type: 'object', properties: { status: { type: 'string', enum: ['DONE', 'PARTIAL', 'BLOCKED'] }, root_cause: { type: 'string' }, evidence: { type: 'string' }, repro: { type: 'string' }, what_timeline_is_today: { type: 'string' }, report_path: { type: 'string' }, lock_released: { type: 'boolean' }, app_left_running: { type: 'boolean' }, output_window_opened: { type: 'boolean' } }, required: ['status', 'root_cause', 'evidence', 'repro', 'what_timeline_is_today', 'report_path', 'lock_released', 'app_left_running', 'output_window_opened'] }
const paper = a => `### SEAT ${a.seat} — VERDICT ${a.verdict}\n` + (a.attacks || []).map((t, i) => `A${i + 1} [${t.severity}] ${t.claim}\n  EVIDENCE: ${t.evidence}\n  FIX: ${t.fix || ''}`).join('\n')

const LENS = {
  live: { key: 'live', t: 'LIVE-SHOW / REAL-TIME seat: attack what a performing VJ would see go wrong (timing on the beat, hard cuts, black frames, latency, CPU / GPU cost at 60 fps, render-thread waits, Sacred Rules), and every path the plan forgot (MIDI / OSC / REST / routines / undo / save-load / autopilot / Ableton Link).' },
  state: { key: 'state', t: 'STATE / CONCURRENCY seat: attack model-state correctness — which thread writes / reads each new or changed field (Pitfalls 33, 35, 36, 55, 58, 63; Relaxed<T>), save / load round-trip and old-file compatibility, undo exactness, deck / layer / clip id rules, anything left half-removed.' },
  ux: { key: 'ux', t: 'UX / VISUAL seat (Boris is a non-technical VJ performing live): attack discoverability, control placement and size, labels in plain words, consistency with existing patterns (ResettableSlider, right-click reset, showMenuAsync, inspectors, the Boris rulings in BORIS_DECISIONS.md "Per-Mockup Feedback"), what will feel wrong on stage, and whether the plan\'s visual gate (critic panel + interaction-logic critic) is concrete.' },
  gates: { key: 'gates', t: 'GATES / TESTS seat: attack the verification — can each RED test actually fail on main 5e47d17 (or is it a test that cannot fail)? Do tests drive real code? Are probe rows runnable under the rig rules with pre-registered bars? Is every Boris requirement (quote) covered by at least one gate? Is the visual gate concrete (decoded captures, named critics)?' },
  dsp: { key: 'dsp', t: 'SIGNAL / AUDIO seat: attack the audio-analysis and signal math — analysis-thread budget and zero allocation (Sacred Rule 3), rate domains (Pitfall 29), beat-clock integrity (Pitfalls 30, 32, 42, 48), envelope extraction / band splitting / time-stretch correctness, numerical edge cases (silence, very short / long samples, tempo changes).' },
}

const seats = (lane, lenses) => parallel(lenses.map(l => () => agent(`BLIND COUNCIL SEAT (attack; you see no other seat). Lane ${lane}. Your temperament: ${l.t}
Read Boris's words (${BF}) and the plan ${MAIN}/${RPT}/plan-${lane}.md IN FULL; verify its load-bearing claims against the source and docs (cite file:line you read). Attack it: what is wrong, missing, untestable, unsafe, or not what Boris asked for. Each attack: severity MUST (ships a defect, misses Boris's requirement, or has a test that cannot fail) / SHOULD / NIT, the claim, your evidence, the fix. No praise. Your structured output IS the paper the ruling receives.
REPORT_FILE: ${RPT}/attack-${lane}-${l.key}.md`, { agentType: 'authored-council-seat', model: 'sonnet', effort: 'medium', schema: ATK_S, phase: 'Attack', label: `attack:${lane}:${l.key}` })))

const rule = (lane, atks) => agent(`ARCHITECT RULING on the blind council's attacks, lane ${lane}. Read your plan ${MAIN}/${RPT}/plan-${lane}.md and Boris's words (${BF}). The seats' papers are INLINE below (not on disk). FIRST write them VERBATIM to ${MAIN}/${RPT}/attack-${lane}-papers.md (Bash heredoc); then for EVERY attack: ACCEPT (exact plan amendment) or REJECT (evidence: file:line / scratch run). Then write "## ARCHITECT RULING (s-rta-1002b)": numbered amendments that OVERRIDE the plan body, the final BUILD STAGES, the FINAL consolidated gate list with pre-registered bars (Harmony copies gate strings only from this list), and the final Boris questions with defaults. Write it via Bash heredoc to the REPORT_FILE (do not edit the plan). Final reply (text) = short manifest: ruling path, accepted / rejected attack ids, amendment count, ready_to_build yes/no, Boris questions with defaults.
SEAT PAPERS:
${atks.map(paper).join('\n\n')}
REPORT_FILE: ${RPT}/ruling-${lane}.md`, { agentType: 'architect', model: 'opus', phase: 'Rule', label: `rule:${lane}` })

const chain = async (lane, planPrompt, lenses, pre) => {
  const extra = pre ? await pre() : ''
  const plan = await agent(`${planPrompt}
${extra}
${COMMON}
REPORT_FILE: ${RPT}/plan-${lane}.md`, { agentType: 'architect', model: 'opus', phase: 'Plan', label: `plan:${lane}` })
  if (!plan) { log(`${lane}: plan returned null`); return { lane, plan: null } }
  const atks = (await seats(lane, lenses)).filter(Boolean)
  const r = await rule(lane, atks)
  return { lane, plan: String(plan).slice(0, 3000), attacks: atks.map(a => ({ seat: a.seat, verdict: a.verdict, musts: (a.attacks || []).filter(t => t.severity === 'MUST').length, n: (a.attacks || []).length })), rule: String(r || '').slice(0, 3000) }
}

const diag6 = async () => {
  phase('Diagnose')
  const d = await agent(`DIAGNOSIS TASK (lane-name: diag6) — definitive, instrument-and-run evidence, NO fix. Boris (verbatim): "Timeline control is not working for parameter control" and, asked how: "when I set any clip parameter to timeline it should be locked to the clips playhead, same with layer, not necessary for composition controls".
FACTS to start from: the parameter source picker (UniversalParamControl.cpp ~:311, APP-INVENTORY.md:105) lists Manual / Audio signals / BPM-sync / Oscillators / Envelopes / Clip Position / Timeline / Macros; binding-decisions.md rulings 8 ("BUILD THE DRAWABLE TIMELINE CURVE") and 13 ("THE RECORDING IS A SET OF PER-CONTROL TIMELINES", (a) "A TIMELINE IS A CONNECTION SOURCE") at ~:258-350; docs/claude/recording.md and rendering.md (signal routing).
DO: (1) establish what "Timeline" as a connection source IS today in code (what it reads, its time base, who advances it, which thread evaluates it) — cite file:line; (2) REPRODUCE Boris's case in the real app: a clip parameter (e.g. an effect param or the clip opacity / a dashboard knob) and a layer parameter connected to Timeline, the clip playing, and the parameter value sampled over time — set the state via a composition file and / or REST in --test-mode (no synthetic input), read values via /api/state or the test server; ALSO a unit / scratch test against the real classes if that isolates it faster (build in the worktree ${MAIN}/.claude/worktrees/diag6 — branch diag/bf6 at 5e47d17 — own build dir; configure like main: -DCMAKE_BUILD_TYPE=Release -DAUDIODNA_BUILD_TEST_SERVER=ON -DFETCHCONTENT_FULLY_DISCONNECTED=ON and -DFETCHCONTENT_SOURCE_DIR_<DEP>=${MAIN}/build/_deps/<dep>-src for JUCE, HTTPLIB, CATCH2, MELATONIN_INSPECTOR, SYPHON); (3) name the ROOT CAUSE with the evidence that proves it (values printed, not inferred), and what would make the value follow the clip's playhead.
RIG: live app via the lock helper: LANE=diag6 . ${SP}/lib/lock.sh then acquire_lock / start_app APP OUTDIR test / quit_app / release_lock (at most one Audio-DNA; never remove another lane's lock). Launch ONLY open -g ... --args --test-mode. NEVER open an Output window; no synthetic input; NEVER lldb / dtrace / sample; never a full-screen screencapture; never copy + re-sign an app bundle; probe HTTP clients use Connection: close; after the batch 0 UserNotificationCenter windows (Quartz kCGWindowListOptionAll) >= 15 s after the last quit. Never cd; scripts under ${SP}/diag6/. Do NOT commit anything to main; you may commit scratch tests on diag/bf6 only. Write the report to ${MAIN}/${RPT}/diag-bf6.md (main checkout; not committed by you).
REPORT_FILE: ${RPT}/diag-bf6.md`, { agentType: 'builder', model: 'opus', effort: 'high', schema: DIAG_S, phase: 'Diagnose', label: 'diag:bf6' })
  return `DIAGNOSIS (builder diag6, instrumented; report ${RPT}/diag-bf6.md): ${d ? JSON.stringify(d).slice(0, 6000) : 'FAILED — diagnose yourself from source and say the evidence is read-through only'}`
}

const P = {
  bf9: `PLAN lane bf9 — deck change stops the old deck; the Persistent layer feature is REMOVED; ignore-column stays.
Boris (verbatim): "When I change decks, they clipped kept playing, and it was invisible. This is not good. Whatever is in the layer should be what is playing and there should be nothing else. I'm going back on what I asked for before and I want to remove the persistent. The only thing remotely persistent should be to ignore column controls so if we want to have something stay on a certain layer and we want to play with the other layers in the composition, that stays in the other layers can be switched by a column switch."
This SUPERSEDES: CLAUDE.md Development Rule 15 ("An inactive deck keeps time": DeckClock::tick in the deckActive fence; crossfades, media clocks and autopilot keep running on off-screen decks), docs/claude/performance-controls.md "Persistent Layers" (CompositorEngine::compositePersistentLayers, Layer::persistent, Layer::canBePersistent, LayerInspector Persistent toggle) and the three 2026-09-26 BORIS_DECISIONS.md entries now marked SUPERSEDED. Pitfall 38 (one autopilot beat-crossing baseline per instance, multi-deck) and Pitfall 35 may change meaning — re-read and say.
Cover: what exactly STOPS on a deck change (clip transport / media clocks / video decode / crossfades in flight / autopilot / routines / beat-snapped pending triggers / Layer Router / feedback history / persistent GL state), cross-deck transitions (P25: both decks render during the transition — when does the old deck stop?), every path that switches decks (UI tab, MIDI / keyboard bindings, OSC, REST, routines, composition load), what the deck shows when you COME BACK to it (OPEN Boris question — default: the clips that were showing when you left resume from where they paused; isolate this as ONE policy point so the other answer is a small change), removal of Persistent end to end (model field, compositor path, inspector toggle + tooltip, serialization — old files with persistent=true load cleanly and ignore it, REST / OSC / bindings, tests, probes, docs, APP-INVENTORY, CLAUDE.md capability text "persistent layers across deck switches"), and proof that ignore-column is untouched.
Fence: tsan-r5 (planned, built after you) converts Layer / Clip / Composition config scalars to Relaxed<T>; removing Layer::persistent shrinks its scope — list the fields you remove or whose threading changes.`,
  bf6: `PLAN lane bf6 — a clip parameter connected to the "Timeline" source follows that clip's playhead; a layer parameter connected to Timeline follows its layer's playing clip's playhead; composition parameters need not support it.
Boris (verbatim): "Timeline control is not working for parameter control" / "when I set any clip parameter to timeline it should be locked to the clips playhead, same with layer, not necessary for composition controls".
Start from the DIAGNOSIS below (instrumented by a builder); plan the fix of its root cause, not a symptom. Reconcile with binding-decisions.md rulings 8 and 13 (the drawable timeline curve; per-control timelines; recording / routines) and with the existing "Clip Position" source (APP-INVENTORY.md:105, ClipPositionSignal): say how Timeline and Clip Position differ after the fix (or whether they merge — a Boris question if it changes what he sees). Cover: in / out points, loop modes, reverse / ping-pong, speed, retrigger, crossfade (two live chains, Pitfall 35), still images / sources with no playhead, what the editor shows (the curve's time axis = the clip), save / load, routines replay, undo.`,
  ui: `PLAN lane ui — two small UI features. BF3: show each video clip's codec (plus resolution and frame rate) and give easy access to the file in Finder. Boris (verbatim): "Codec display for each video and easy access to that video in finder". Defaults taken (Boris did not object): codec + resolution + fps in the Clip inspector and the clip cell tooltip; "Show in Finder" in the clip cell right-click menu and a button in the Clip inspector. BF8: Boris (verbatim): "Need to be able to rename each deck with double click" — double-click a deck tab = rename in place (Enter saves, Esc cancels, click-away = ?, empty name = ?); today right-click > Rename Deck... (docs/claude/performance-controls.md:51; Pitfall 36 deck ids; "Deck tab row: right-click a tab = its menu, never a deck switch"). Cover: where the codec info comes from without decoding on the message / GL thread (Pitfalls 51, 53, 56, 58 — probe at open time and cache), image sequences / stills / sources (what to show), missing files, how Show in Finder is invoked (juce::File::revealToUser) and REST / test hooks for the gates; does a single click on a tab still switch decks immediately (double-click must not cause a switch-then-rename glitch); undo of a rename; save / load.`,
  bf7: `PLAN lane bf7 — bars wherever the app has beats. Boris (verbatim): "Add bars to all places we have beats". Default taken: every beat-count setting also offers bar values (4/4: 1 bar = 4 beats), beat counters read bar.beat. MUST reconcile with BORIS_DECISIONS.md "Routines feel rulings" (2026-09-26): "we only need longer than 4 bar counts for routines and that should be displayed with the routine and nothing else. Top bar count should go 1-2-3-4-1 etc" — say how both hold (or ask Boris, with a default).
FIRST INVENTORY EVERY place a beat count / beat duration / beat division / beat counter appears: UI controls (ClipInspector beat division / content beats / beat snap granularity / autopilot beat-count / transitions / SignalInspector oscillator + envelope beat-duration / Hits quantize / routines / top bar counter / quantizeMode / anything else), REST / OSC parameters, saved files. Table: place | today's values | proposed values incl. bars | storage change (beats stay the stored unit? old files?) | UI change. Then plan. Cover time signature (4/4 only is the default; a Boris question if anything else is cheap), Ableton Link (quantum), phrase restarts.`,
  bf2: `PLAN lane bf2 — one very fine "sync" dial, saved per venue: shifts the audio-driven signals and the beat clock / BPM later (delay) or earlier (advance) so the visuals line up with the sound in each room.
Boris (verbatim): "We need a nice clean way to adjust the delay or speeding ahead for each room so we can set it per room. Like if the audio is slower than the video, this delays or advances signals and bpm with one very sensitive dial." and, answering: "default, -500 to +500 in 1 ms steps plus can enter in the amount then click plus or minus to fine tune, we will rarely have an early delay so that is not a worry just a control we have in case we want to have all early without loudness signals". Defaults he accepted: venue profiles saved by name and picked at soundcheck; EARLY moves only beat-locked things (beat clock / beat phase, BPM-synced oscillators / envelopes, beat-snapped triggers, autopilot, beat uniforms) — loudness / onset signals cannot be early; LATE delays everything audio-driven.
Cover: where the delay lives (a ring of FeatureSnapshots read by the render thread at now - delay vs a delay on the analysis side; render never waits; zero allocation; 500 ms at the hop rate = how many snapshots), the beat clock / totalBeatCount + beatPhase integration (Pitfall 42), beat-snapped triggers and quantize, Ableton Link (its own offset?), tap / manual BPM, the onsetCount delta consumers (Pitfall 30), downbeat level (Pitfall 32), REST / OSC / MIDI control of the dial, where venue profiles are stored (AppSettings settings.json beside other machine settings vs the composition — argue it), the UI (a dial + typed value + plus / minus buttons; where it sits; ResettableSlider default 0), and a gate that measures the shift end to end (e.g. a click track via the test server's audio injection if one exists, the visual / uniform response time, before / after).`,
  bf1: `PLAN lane bf1 — record the output (or a selected layer) into a clip that is playable the moment it ends; start and stop snapped to the bar.
Boris (verbatim): "Sampling to other layers/ clip. Think how to do this, like set a clip to record output of the composition and they be able to use it as soon as it is done. This would be good to have it automatically start and end on bars or beats, quantized" and, answering: "whole ouput of select layer, stop start and snap to bar, next empty cell on top layer no need to select it, video files yes". Harmony's reading (recorded): source = the whole output OR the selected layer (offer both; default whole output); press to start, press to stop, both snapped to the next bar line; the recording lands in the NEXT EMPTY CELL of the TOP layer automatically; saved as video files. BORIS_DECISIONS.md "No stop model" ("this is a playing app. there is no stop buttons anywhere") governs playback — say why a record toggle is not a playback stop.
Cover: reuse of the existing recorder (VideoRecorder: FFmpeg H.264 / ProRes / MJPEG, triple buffer, Pitfall 25; docs/claude/integration.md) vs a new path; capturing a single layer's output (which FBO / stage — after its effects + transform?) and the canvas size (Pitfall 37); the codec / GOP for a recorded clip that must play forward AND reverse smoothly in this app (Pitfalls 56, 60, 62 — the GOP cache), finalize off the message thread, then loading into the cell through the existing media-open path (Pitfalls 53, 56, 58) so it is usable at once; where the files go (beside the saved composition; an unsaved composition?) and naming; recording what you are recording into (feedback); what happens when the top layer has no empty cell; a deck change mid-recording (bf9: decks stop); CPU / GPU cost while performing (readback at 60 fps) with an interleaved A/B perf gate; REST / MIDI / keyboard binding for the record toggle (BindingManager actions).`,
  bf45: `PLAN lane bf45 — (BF4) a hand-editable, bigger envelope editor and (BF5) envelopes extracted from an audio sample.
Boris (verbatim): "Need to manually change envelopes. Need to expand envelope controls and setup format" / "Make it so when you load a sample into the envelope that it will emulate the envelope of the audios behavior. So basically use a sample to extract the envelope live, and then different envelopes can be pulled out of that sample with the envelope creator" and, answering: BF4 "default is good, bigger envelope, what would it's own window look like? perhaps we don't create it's own window till later when we have finalized the ui or would you rather do it now to build it then change the ui placement?" (Harmony recommended: one self-contained editor component in a bigger in-place panel now, own window later) and BF5 "all defaults good" (the sample is SILENT — it only drives visuals; its envelope is stretched to the envelope's set beat / bar length; separate envelopes for lows / mids / highs).
Today: EnvelopeSignal (control-point, BPM-locked); SignalInspector Envelope: curve-type (3) + beat-duration (5) + amplitude + phase + looping / one-shot + a PAINT-ONLY curve editor (NOT draggable) (APP-INVENTORY.md:75, :285). Default editing: drag / add / delete points, bend the segment between points, lengths incl. bars (lane bf7 adds bar values app-wide — coordinate), bigger editor.
Cover: the editor component (hit-testing, snapping to beat / bar grid, min / max points, keyboard, undo, ResettableSlider rules for its knobs), the model change (per-segment curve / tension; save / load + old files), the signal evaluation on the render thread (no allocation, no locks; how an edit is published — Relaxed / snapshot, Pitfall 63), the sample path: decode the audio file off the message / GL / analysis threads, compute per-band (low / mid / high) loudness envelopes offline at load (band edges, smoothing, normalisation), map to the envelope's beat length, and whether the result becomes editable points (simplification) or a dense curve the editor can still bend; supported formats; long / short samples; save (copy or reference the sample file?).`,
}

const results = await Promise.all([
  chain('bf9', P.bf9, [LENS.live, LENS.state, LENS.gates]),
  chain('bf6', P.bf6, [LENS.state, LENS.gates], diag6),
  chain('ui', P.ui, [LENS.ux, LENS.gates]),
  chain('bf7', P.bf7, [LENS.ux, LENS.gates]),
  chain('bf2', P.bf2, [LENS.dsp, LENS.live, LENS.gates]),
  chain('bf1', P.bf1, [LENS.live, LENS.state, LENS.gates]),
  chain('bf45', P.bf45, [LENS.ux, LENS.dsp, LENS.gates]),
])
return results
