export const meta = {
  name: 'rta-1002b-plans-bf9c',
  description: 'Audio-DNA s-rta-1002b: bf9b re-plan with recon fact sheets first (3 sonnet readers) -> opus plan under a context budget -> 4 seats -> ruling',
  phases: [{ title: 'Recon' }, { title: 'Plan' }, { title: 'Attack' }, { title: 'Rule' }],
}
const MAIN = '/Users/boriskarpman/projects/RealTimeAudio'
const RPT = '.harmony/.reports/s-rta-1002b'
const SP = '/private/tmp/claude-501/-Users-boriskarpman-projects-RealTimeAudio/73d4f54c-e9d5-409c-8b5d-694bfd57c171/scratchpad'
const BF = `${MAIN}/.harmony/boris-feedback-backlog.md (Boris's message verbatim + items BF1-BF9) and ${MAIN}/.harmony/binding-decisions.md section "2026-10-02 (s-rta-1002b)" (his answers, verbatim in quotes; the rest is Harmony's consequence text)`
const COMMON = `
CONTEXT: Audio-DNA (C++20 / JUCE 8.0.4 / OpenGL 4.1, macOS M1 Pro 32 GiB 120 Hz, Command Line Tools only, no Xcode). Repo ${MAIN}, main HEAD 5e47d17. Session s-rta-1002b (secondary Harmony, autonomous). Boris (owner, non-technical VJ) evaluated the app and sent feedback: READ ${BF}. The repo CLAUDE.md is loaded for you: obey its Sacred Rules, UI Patterns (ResettableSlider, showMenuAsync, etc.) and Pitfall index (read the full docs/claude/pitfalls.md entry for any pitfall you touch); the trigger table names the docs/claude/*.md to read for your area. Boris's earlier rulings: BORIS_DECISIONS.md (esp. "Playback Behaviour", "Timeline", "Clip Cells", "Layer Strip", "Inspector Tabs") and .harmony/binding-decisions.md — a new answer beats an older ruling only where Boris said so; flag every other conflict. APP map: .harmony/APP-INVENTORY.md.
SEVEN PLANS ARE WRITTEN IN PARALLEL (one per lane): bf9 (deck change stops the old deck; Persistent removed), bf6 (Timeline source follows the clip / layer playhead), ui (BF3 codec + Show in Finder; BF8 double-click deck rename), bf7 (bars wherever beats), bf2 (per-venue sync dial), bf1 (record output / layer to a clip), bf45 (envelope editor + envelopes from an audio sample). Also planned elsewhere: tsan-r5 (Relaxed<T> for config scalars + the httplib reader; built AFTER bf9). Pre-registered BUILD ORDER: bf9 -> bf6 -> ui -> bf7 -> bf2 -> bf1 -> bf45 -> tsan-r5, at most 3 building at once in separate worktrees, merged one at a time. Where your lane must touch a file another lane also touches (likely: MainComponent.cpp, ClipInspector, LayerInspector, SignalInspector, DeckView / deck tab row, TopBar, CompositorEngine, Layer.h / Clip.h / Composition.h, serialization), name the exact functions / blocks so Harmony can sequence merges; do not plan edits inside another lane's core.
PLAN FORMAT (mandatory): (1) GOAL in one line, and Boris's words it serves (quote verbatim); (2) ESTABLISHED facts, each labelled VERIFIED (you read it / ran it: cite file:line) or INFERRED; (3) DESIGN FORK(S): every defensible alternative, evidence, your choice, why the runner-up loses; (4) numbered ITEMS: files + functions, exact behaviour change, RED-first test(s) (a unit test in tests/ that drives real code and FAILS on main 5e47d17 — say how — or a named probe row with a pre-registered bar), GREEN bar, risk; plus BUILD STAGES (one builder context each, dependency order; which stages could ship alone); (5) GATES Harmony runs herself after the merge (commands / probes / bars, pre-registered decision rules; perf only via INTERLEAVED A/B, >= 5 runs per arm; a bar whose teeth equal the drift is INFO); for ANY visible UI: the VISUAL WORK GATE — a critic panel (visual-design + UX + graphic-design + logic critics; a dedicated interaction-logic critic for anything stateful / navigational) on decoded window captures (Quartz window id only) BEFORE Boris sees it, then an artifact page he opens; (6) DOCS: docs/claude/*.md sections, CLAUDE.md lines (24,002 of its 25,000-byte cap after lane hyg; any addition paid by moving text into docs/claude/*.md), APP-INVENTORY.md, BORIS_DECISIONS.md; new pitfalls written "Pitfall NN" (Harmony assigns; next free 64); (7) RISKS with the cheapest discriminating test; (8) WHAT ONLY BORIS CAN CHECK (feel / taste on the live rig); (9) QUESTIONS that are genuinely Boris's (product / taste only, plain words, no jargon) — each with a DEFAULT so the build never blocks.
RIG RULES the plan must respect (builders obey them; plan nothing that needs a violation): at most ONE live Audio-DNA at a time (lock helper); launch only via open -g ... [--args --test-mode]; NEVER open an Output window in any gate; no synthetic input (UI states via REST / composition files / a TEMPORARY env-var hook reverted before merge); NEVER lldb / debugserver / gdb / dtrace / Instruments / sample on any binary; never a full-screen screencapture (window-only by Quartz window id); never copy + re-sign an app bundle; sanitizer options abort_on_error=0; probe HTTP clients use Connection: close; check ps for CPU burners before perf verdicts; a background run is capped at 2 h.
You are read-only on source (read-only commands, git log / show / grep, scratch experiments under /private/tmp that do not launch the app). Every claim about current code cites file:line you actually read. Write a SKELETON plan (the 9 headings) via Bash heredoc to the REPORT_FILE path within your first ~10 tool calls, then REWRITE it as sections firm up. Final reply (text) = a short manifest: plan path, goal, fork choices, item ids + titles, build stages, files shared with other lanes, Boris questions with defaults.`

const ATK_S = { type: 'object', properties: { seat: { type: 'string' }, verdict: { type: 'string', enum: ['ADOPT', 'AMEND', 'REJECT'] }, attacks: { type: 'array', items: { type: 'object', properties: { severity: { type: 'string', enum: ['MUST', 'SHOULD', 'NIT'] }, claim: { type: 'string' }, evidence: { type: 'string' }, fix: { type: 'string' } }, required: ['severity', 'claim', 'evidence'] } } }, required: ['seat', 'verdict', 'attacks'] }
const DIAG_S = { type: 'object', properties: { status: { type: 'string', enum: ['DONE', 'PARTIAL', 'BLOCKED'] }, root_cause: { type: 'string' }, evidence: { type: 'string' }, repro: { type: 'string' }, what_timeline_is_today: { type: 'string' }, report_path: { type: 'string' }, lock_released: { type: 'boolean' }, app_left_running: { type: 'boolean' }, output_window_opened: { type: 'boolean' } }, required: ['status', 'root_cause', 'evidence', 'repro', 'what_timeline_is_today', 'report_path', 'lock_released', 'app_left_running', 'output_window_opened'] }
const paper = a => `### SEAT ${a.seat} — VERDICT ${a.verdict}\n` + (a.attacks || []).map((t, i) => `A${i + 1} [${t.severity}] ${t.claim}\n  EVIDENCE: ${t.evidence}\n  FIX: ${t.fix || ''}`).join('\n')

const LENS = {
  live: { key: 'live', t: 'LIVE-SHOW / REAL-TIME seat: attack what a performing VJ would see go wrong (timing on the beat, hard cuts, black frames, latency, CPU / GPU cost at 60 fps, render-thread waits, Sacred Rules), and every path the plan forgot (MIDI / OSC / REST / routines / undo / save-load / autopilot / Ableton Link).' },
  state: { key: 'state', t: 'STATE / CONCURRENCY seat: attack model-state correctness — which thread writes / reads each new or changed field (Pitfalls 33, 35, 36, 55, 58, 63; Relaxed<T>), save / load round-trip and old-file compatibility, undo exactness, deck / layer / clip id rules, anything left half-removed.' },
  ux: { key: 'ux', t: 'UX / VISUAL seat (Boris is a non-technical VJ performing live): attack discoverability, control placement and size, labels in plain words, consistency with existing patterns (ResettableSlider, right-click reset, showMenuAsync, inspectors, the Boris rulings in BORIS_DECISIONS.md "Per-Mockup Feedback"), what will feel wrong on stage, and whether the plan\'s visual gate (critic panel + interaction-logic critic) is concrete.' },
  gates: { key: 'gates', t: 'GATES / TESTS seat: attack the verification — can each RED test actually fail on main 5e47d17 (or is it a test that cannot fail)? Do tests drive real code? Are probe rows runnable under the rig rules with pre-registered bars? Is every Boris requirement (quote) covered by at least one gate? Is the visual gate concrete (decoded captures, named critics)?' },
  dsp: { key: 'dsp', t: 'SIGNAL / AUDIO seat: attack the audio-analysis and signal math — analysis-thread budget and zero allocation (Sacred Rule 3), rate domains (Pitfall 29), beat-clock integrity (Pitfalls 30, 32, 42, 48), envelope extraction / band splitting / time-stretch correctness, numerical edge cases (silence, very short / long samples, tempo changes).' },
}

const seats = (lane, lenses) => parallel(lenses.map(l => () => agent(`BLIND COUNCIL SEAT (attack; you see no other seat). Lane ${lane}. Your temperament: ${l.t}
Read Boris's words (${BF}) and the plan ${MAIN}/${RPT}/plan-${lane}.md IN FULL; verify its load-bearing claims against the source and docs (cite file:line you read). Attack it: what is wrong, missing, untestable, unsafe, or not what Boris asked for. Each attack: severity MUST (ships a defect, misses Boris's requirement, or has a test that cannot fail) / SHOULD / NIT, the claim, your evidence, the fix. No praise. Your structured output IS the paper the ruling receives.
REPORT_FILE: ${RPT}/attack-${lane}-${l.key}.md`, { agentType: 'authored-council-seat', model: 'sonnet', effort: 'medium', schema: ATK_S, phase: 'Attack', label: `attack:${lane}:${l.key}` })))

const rule = (lane, atks) => agent(`ARCHITECT RULING on the blind council's attacks, lane ${lane}. Read your plan ${MAIN}/${RPT}/plan-${lane}.md and Boris's words (${BF}). The seats' papers are INLINE below (not on disk). FIRST write them VERBATIM to ${MAIN}/${RPT}/attack-${lane}-papers.md (Bash heredoc); then for EVERY attack: ACCEPT (exact plan amendment) or REJECT (evidence: file:line / scratch run). Then write "## ARCHITECT RULING (s-rta-1002b)": numbered amendments that OVERRIDE the plan body, the final BUILD STAGES, the FINAL consolidated gate list with pre-registered bars (Harmony copies gate strings only from this list), and the final Boris questions with defaults. Write it via Bash heredoc to the REPORT_FILE (do not edit the plan). Final reply (text) = short manifest: ruling path, accepted / rejected attack ids, amendment count, ready_to_build yes/no, Boris questions with defaults.
TURN BUDGET (binding): your agent type stops HARD at 120 turns (tool calls) with no final message -- two planners and one ruling died exactly so today. Write the papers file and a ruling SKELETON (all section headings) by turn 8; REWRITE the ruling file every ~10 turns; verify ONLY the MUST attacks against source (cheap greps); be DONE writing by turn 90 and then reply.
SEAT PAPERS:
${atks.map(paper).join('\n\n')}
REPORT_FILE: ${RPT}/ruling-${lane}.md`, { agentType: 'architect', model: 'opus', phase: 'Rule', label: `rule:${lane}` })

const chain = async (lane, planPrompt, lenses, pre) => {
  const extra = pre ? await pre() : ''
  const plan = await agent(`${planPrompt}
${extra}
${COMMON}
REPORT_FILE: ${RPT}/plan-${lane}.md`, { agentType: 'architect', model: 'opus', phase: 'Plan', label: `plan:${lane}` })
  if (!plan) { log(`${lane}: plan returned null`); return { lane, plan: null } }
  const atks = (await seats(lane, lenses)).filter(Boolean)
  const r = await rule(lane, atks)
  return { lane, plan: String(plan).slice(0, 3000), attacks: atks.map(a => ({ seat: a.seat, verdict: a.verdict, musts: (a.attacks || []).filter(t => t.severity === 'MUST').length, n: (a.attacks || []).length })), rule: String(r || '').slice(0, 3000) }
}

const diag6 = async () => {
  phase('Diagnose')
  const d = await agent(`DIAGNOSIS TASK (lane-name: diag6) — definitive, instrument-and-run evidence, NO fix. Boris (verbatim): "Timeline control is not working for parameter control" and, asked how: "when I set any clip parameter to timeline it should be locked to the clips playhead, same with layer, not necessary for composition controls".
FACTS to start from: the parameter source picker (UniversalParamControl.cpp ~:311, APP-INVENTORY.md:105) lists Manual / Audio signals / BPM-sync / Oscillators / Envelopes / Clip Position / Timeline / Macros; binding-decisions.md rulings 8 ("BUILD THE DRAWABLE TIMELINE CURVE") and 13 ("THE RECORDING IS A SET OF PER-CONTROL TIMELINES", (a) "A TIMELINE IS A CONNECTION SOURCE") at ~:258-350; docs/claude/recording.md and rendering.md (signal routing).
DO: (1) establish what "Timeline" as a connection source IS today in code (what it reads, its time base, who advances it, which thread evaluates it) — cite file:line; (2) REPRODUCE Boris's case in the real app: a clip parameter (e.g. an effect param or the clip opacity / a dashboard knob) and a layer parameter connected to Timeline, the clip playing, and the parameter value sampled over time — set the state via a composition file and / or REST in --test-mode (no synthetic input), read values via /api/state or the test server; ALSO a unit / scratch test against the real classes if that isolates it faster (build in the worktree ${MAIN}/.claude/worktrees/diag6 — branch diag/bf6 at 5e47d17 — own build dir; configure like main: -DCMAKE_BUILD_TYPE=Release -DAUDIODNA_BUILD_TEST_SERVER=ON -DFETCHCONTENT_FULLY_DISCONNECTED=ON and -DFETCHCONTENT_SOURCE_DIR_<DEP>=${MAIN}/build/_deps/<dep>-src for JUCE, HTTPLIB, CATCH2, MELATONIN_INSPECTOR, SYPHON); (3) name the ROOT CAUSE with the evidence that proves it (values printed, not inferred), and what would make the value follow the clip's playhead.
RIG: live app via the lock helper: LANE=diag6 . ${SP}/lib/lock.sh then acquire_lock / start_app APP OUTDIR test / quit_app / release_lock (at most one Audio-DNA; never remove another lane's lock). Launch ONLY open -g ... --args --test-mode. NEVER open an Output window; no synthetic input; NEVER lldb / dtrace / sample; never a full-screen screencapture; never copy + re-sign an app bundle; probe HTTP clients use Connection: close; after the batch 0 UserNotificationCenter windows (Quartz kCGWindowListOptionAll) >= 15 s after the last quit. Never cd; scripts under ${SP}/diag6/. Do NOT commit anything to main; you may commit scratch tests on diag/bf6 only. Write the report to ${MAIN}/${RPT}/diag-bf6.md (main checkout; not committed by you).
REPORT_FILE: ${RPT}/diag-bf6.md`, { agentType: 'builder', model: 'opus', effort: 'high', schema: DIAG_S, phase: 'Diagnose', label: 'diag:bf6' })
  return `DIAGNOSIS (builder diag6, instrumented; report ${RPT}/diag-bf6.md): ${d ? JSON.stringify(d).slice(0, 6000) : 'FAILED — diagnose yourself from source and say the evidence is read-through only'}`
}

const RECON = [
  { key: 'model', t: `MODEL OWNERSHIP + PERSISTENCE: the Composition / Deck / Layer / Clip structs — list their fields grouped as (i) layer SETTINGS (effects, opacity, blend, transition, autopilot, keying, feedback, persistent, ignoreColumn, type...), (ii) layer PLAYING state (LayerRuntimeCell trigger tuple, crossfade, pending trigger...), (iii) clip content + clip runtime (Relaxed<T> fields); where the vectors live (Composition::decks, Deck::layers, Layer::clips?) and activeDeckIndex; every deck lifecycle path (addDeck / appendDeck / appendDeckFromFile / duplicateDeck / remove / Save Deck / Load Deck; Pitfall 36 id minting) and composition save / load (the JSON keys for decks / layers / clips, persistent, deck-transition settings, schema versioning, old-file handling); withDeckDetached / FencedPtrSlot (Pitfalls 55, 58).` },
  { key: 'render', t: `RENDER + PLAY PATH: how one frame is built — CompositorEngine (active deck's layers, compositePersistentLayers, the cross-deck transition of P25), DeckClock::tick for inactive decks (CLAUDE.md rule 15 deckActive fence), Autopilot instances per deck (Pitfall 38), LayerRuntimeCell / trigger tuple reads and CAS writes (Pitfall 63), crossfade two live chains and GL history keys (LayerStateKey deck + layer, Pitfall 35), feedback history, Layer Router (active deck only), syncMedia / media clocks / video decode for off-screen decks, RoutineEngine replay (which deck's layers it drives), beat-snapped pending triggers (processPendingTrigger).` },
  { key: 'control', t: `CONTROL / UI / TESTS: the deck tab row (switch, right-click menu, Rename Deck...), DeckView grid (whose clips it shows; how the playing clip is highlighted), LayerStrip (whose layers it shows), LayerInspector (Persistent toggle + tooltip, Ignore Column), the column trigger path (MainComponent::handleColumnTrigger) and clip trigger path (TriggerClipCmd and other undo commands), BindingManager actions that switch decks or trigger clips / columns incl. ByPosition / ThisItem / Selected targeting, OSC and REST (ApiServer / TestServer) routes that switch decks, trigger clips, set persistent or deck transitions, MIDI; then EVERY test (tests/*.cpp: file + case name) and EVERY probe row (.harmony/probe-*.sh / *.py / *.json) that asserts persistent layers, deck-switch behaviour, inactive-deck clocks / fades / autopilot, or cross-deck transitions — with file:line and what it asserts.` },
]
const recon = async () => {
  const outs = await parallel(RECON.map(r => () => agent(`READ-ONLY RECON for a planner (lane bf9b, Audio-DNA repo ${MAIN}, main HEAD 9a832a0). Topic: ${r.t}
OUTPUT (your final text IS the deliverable, passed verbatim to an architect): a FACT SHEET of <= 250 lines — tables / terse bullets, EVERY row cites file:line you actually read, no prose, no design opinions, no speculation (mark anything not read as UNVERIFIED). Use narrow reads (grep -n, sed -n ranges of <= 60 lines). Iron rule: no edits, no builds, no app launches.`, { agentType: 'Explore', model: 'sonnet', effort: 'high', phase: 'Recon', label: `recon:bf9b:${r.key}` })))
  return 'RECON FACT SHEETS (3 read-only readers, verbatim; verify only what your design leans on):\n' + RECON.map((r, i) => `=== ${r.key} ===\n${String(outs[i] || 'MISSING — research this area yourself, narrowly').slice(0, 30000)}`).join('\n\n')
}
const BUDGET = `
CONTEXT BUDGET (binding — two planners died today at ~550k context mid-research with only a skeleton on disk): the research is DONE for you in the fact sheets below and in ${RPT}/plan-bf9.md + ${RPT}/ruling-bf9.md (written on the superseded premise "deck change stops the old deck": use their ESTABLISHED facts, never their design). Verify only the claims your design leans on, with narrow reads (grep -n; sed -n ranges <= 60 lines; never cat a whole source file). Write the plan file within your first 5 tool calls and REWRITE it at least every 8 tool calls. Stop researching and finish writing once your design is decided.`
const P = {
  bf9b: `PLAN lane bf9b — decks are boxes of clips; the layers are one shared playing stack; switching decks never changes what plays. (Supersedes lane bf9's premise.)
Boris (verbatim, 1): "When I change decks, they clipped kept playing, and it was invisible. This is not good. Whatever is in the layer should be what is playing and there should be nothing else. I'm going back on what I asked for before and I want to remove the persistent. The only thing remotely persistent should be to ignore column controls so if we want to have something stay on a certain layer and we want to play with the other layers in the composition, that stays in the other layers can be switched by a column switch."
Boris (verbatim, 2 — the clarification, same day): "when I switch between decks, do not change the clips playing in the layers or how they are playing. treat the decks as just a box of clips and I can switch between 20 decks looking for a clip and the playing will not be affected. does that make sense?"
THE MODEL (Harmony's consequence text, recorded in BORIS_DECISIONS.md "Decks are boxes of clips" and binding-decisions.md; defaults put to Boris, no answer yet = default): the layers are ONE shared stack for the show; what is in a layer is what plays and is on screen, whichever deck the grid shows; a deck switch changes only which clips the grid shows (no change to any playing clip, its position, speed, fade or effects; nothing plays invisibly); firing a clip from ANY deck puts it in its row's layer (row N -> layer N), replacing what played there through the layer's transition; a column fire fires that column of the deck being shown, skipping layers set to Ignore Column; layer settings (layer effects / opacity / blend / transition / autopilot / keying / feedback ...) belong to the shared layer — one set for all decks (old shows: the first deck's layer settings win); every deck shows the show's layer rows; the deck-to-deck transition fade (P25 cross-deck transitions) is REMOVED (nothing to fade); the layer strip shows each layer's playing clip and the deck it came from; Persistent is REMOVED; ignore-column stays.
SUPERSEDES: CLAUDE.md Development Rule 15 ("An inactive deck keeps time" — reword: the playing layers keep time whatever deck is shown), docs/claude/performance-controls.md Persistent Layers + Layer Router "active deck only" text, the P25 cross-deck transitions (docs/claude/rendering.md), Pitfalls 35 / 36 / 38 meanings (re-read; say what changes), the three 2026-09-26 BORIS_DECISIONS.md entries marked SUPERSEDED.
RESEARCH INPUT: see CONTEXT BUDGET below.
BINDING INPUT CONTRACTS (rulings already made this session — satisfy them, never re-litigate; amend only with evidence): (1) ${RPT}/ruling-bf9.md: Stage P of ${RPT}/plan-bf9.md (Persistent removed end to end; Ignore Column Trigger untouched), as amended by that ruling's amendments 1-17 (commit order C0 lever, C1 failing tests, C2 removal readers-first, C3 probes, C4 docs), is YOUR Stage 0 — built first on your branch, reaching main only inside your merge; and its requirement-to-gate table + gates K1-K8 (ruling-bf9.md ~:455-520, each tied to a quoted clause of Boris's, RED on main where marked) are pre-registered for your lane: carry them into your final gate list. (2) ${RPT}/ruling-bf6.md contracts your plan must PROVIDE for lane bf6 (Timeline follows the clip / layer playhead), with exact names / signatures in a section "CONTRACTS FOR LATER LANES": C1 the playing-clip accessor — one message-thread function from a shared layer (or layer row) to the clip it is playing (~:91); C2 the walk — visit each shared layer exactly once and each clip of every deck box exactly once per tick (~:96); C3 at every activation that does not seek the player, the stored model playhead equals the player (~:219). Lane bf1 (record into the next empty cell of the TOP layer) needs "the top layer's row in the shown deck" — name it too.
Cover EXHAUSTIVELY: today's data model (Composition / Deck / Layer / Clip ownership, where the playing state lives: LayerRuntimeCell trigger tuple — Pitfall 63, Relaxed<T> fields, DeckClock, Autopilot instances per deck, Layer Router, feedback / temporal GL history keyed by deck + layer (Pitfall 35), crossfade two-chain rule, routines replay (which deck's layers?), beat-snapped pending triggers, MIDI / OSC / REST / keyboard bindings with ByPosition / ThisItem / Selected targeting, undo commands, the layer strip, deck tabs, Save Deck / Load Deck / Duplicate Deck / composition save-load and OLD FILES); the DESIGN FORK: (A) restructure — Composition owns the shared layer stack (settings + playing state), Deck owns only a clip grid, a playing layer references its clip by stable clip id (+ deck id) — vs (B) keep per-deck Layer containers for clips and lift only the playing state + layer settings into a composition-level stack — vs any better option; how a playing clip whose deck is REMOVED or REPLACED keeps playing (or stops — a Boris question if it is a product choice; default: it keeps playing until replaced) and how a Duplicate Deck re-minting clip ids (Pitfall 36) interacts; what the grid highlights when the playing clip lives in another deck; layer-count differences between decks; old composition / deck files migrate (first deck's layer settings win; persistent=true ignored; deck transition settings ignored) with a round-trip test.
Fence: lanes planned in parallel — bf6 (Timeline source follows the clip / layer playhead), ui (codec + Show in Finder; double-click deck rename), bf7 (bars wherever beats), bf2 (sync dial), bf1 (record output / layer into the next empty cell of the TOP layer — of which deck? say), bf45 (envelope editor), tsan-r5 (Relaxed<T> for config scalars + httplib reader; built after you), bf10 (MilkDrop canvas size). bf9b is built FIRST: name the model APIs the others must use after it.
Probes / tests that encode the OLD behaviour (probe-deck-clock, probe-deck-path, probe-deck-tabs, probe-crossfade, probe-routines, test_* for persistent / deck transitions / DeckClock): list EVERY row / case whose expectation changes BECAUSE OF THE RULING, with the new expectation and the Boris quote that changes it (never silently re-threshold; rows unaffected by the ruling must stay green as they are).`,
}
const res = await chain('bf9b', P.bf9b + BUDGET, [LENS.live, LENS.state, LENS.gates, LENS.ux], recon)
return res
