export const meta = {
  name: 'rta-1002b-plans',
  description: 'Audio-DNA s-rta-1002b: TSan analyzer family fix -> tsan-r5 plan (opus) -> 3 blind seats -> ruling; MKV/WebM index plan -> 2 seats -> ruling',
  phases: [{ title: 'Analyzer' }, { title: 'Plan' }, { title: 'Attack' }, { title: 'Rule' }],
}
const MAIN = '/Users/boriskarpman/projects/RealTimeAudio'
const RPT = '.harmony/.reports/s-rta-1002b'
const OLDSP = '/private/tmp/claude-501/-Users-boriskarpman-projects-RealTimeAudio/267d1ba0-b658-4610-9f47-ef72f4b49872/scratchpad'
const R30 = '.harmony/.reports/s-rta-0930'
const R02 = '.harmony/.reports/s-rta-1002'
const COMMON = `
CONTEXT: Audio-DNA (C++20 / JUCE 8.0.4 / OpenGL 4.1, macOS M1 Pro 32 GiB 120 Hz, Command Line Tools only, no Xcode). Repo ${MAIN}, main HEAD 5b507b1 (tsan lane merged at b844b65: LayerRuntimeCell 16-byte CAS tuple, Relaxed<T> for Clip runtime fields / 23 manual scalars / activeDeckIndex, Pitfall 63). Session s-rta-1002b (secondary Harmony, autonomous). The repo CLAUDE.md is loaded for you: obey its Sacred Rules (audio callback sacred; inter-thread data only through the established lock-free channels; UI->hot path via std::atomic<T> / Relaxed<T>; never add a new mutex without explicit discussion; render thread never waits for analysis) and its Pitfall index (read the full entry in docs/claude/pitfalls.md for any pitfall you touch). Boris's rulings: BORIS_DECISIONS.md "Playback Behaviour" and .harmony/binding-decisions.md — read the entries relevant to your area.
A concurrent BUILD lane "hyg" runs in worktree .claude/worktrees/hyg: it converts std::cerr in src/audio/AudioEngine.cpp + DeviceGuard.cpp (and any other non-message-thread cerr site) to logLine, adds them to tests/test_log_line_lint.cpp, renumbers "Pitfall NN" comments and reorders docs/claude/pitfalls.md. It merges BEFORE your lane is built: do not plan edits to those lines.
PLAN FORMAT (mandatory): (1) GOAL in one line; (2) ESTABLISHED facts, each labelled VERIFIED (you read it / ran it: cite file:line) or INFERRED; (3) the DESIGN FORK(S): every defensible alternative, the evidence for each, your choice and why the runner-up loses; (4) numbered ITEMS, each with: files + functions, the exact behaviour change, the RED-first test(s) (a unit test in tests/ that drives real code and FAILS on main HEAD 5b507b1 — say how it fails — or a named probe row with a pre-registered bar), the GREEN bar, and the risk; plus BUILD STAGES (items grouped so one builder context can finish a stage; the stage order); (5) GATES Harmony will run herself after the merge (commands / probes / bars, pre-registered decision rules; perf bars only via INTERLEAVED A/B launch by launch, >= 5 runs per arm; a bar whose teeth equal the run-to-run drift is INFO, not a gate); (6) DOCS: which docs/claude/*.md sections and CLAUDE.md lines change — CLAUDE.md is 24,006 of its 25,000-byte cap, any addition is paid by moving text into docs/claude/*.md; new pitfalls are written "Pitfall NN" (Harmony assigns; next free is 64); (7) RISKS (named, with the cheapest discriminating test); (8) WHAT ONLY BORIS CAN CHECK; (9) QUESTIONS that are genuinely Boris's (product / taste) — each with a DEFAULT so the build does not block.
RIG RULES the plan must respect (builders obey them; plan nothing that needs a violation): at most ONE live Audio-DNA at a time (lock helper); launch only via open -g ... [--args --test-mode]; NEVER open an Output window in any gate; no synthetic input (UI states via REST / composition files / a temporary env-var hook reverted before merge); NEVER lldb / debugserver / gdb / dtrace / Instruments / sample on any binary; never a full-screen screencapture; never copy + re-sign an app bundle (mutants only from a normal cmake build dir); sanitizer options always abort_on_error=0 (TSan also exitcode=0 for app launches); probe HTTP clients use Connection: close; before any perf verdict check ps for orphaned CPU burners; a background run is capped at 2 h (split long gates).
You are read-only on source (read-only commands, git log / show / grep, scratch experiments under /private/tmp that do not launch the app). Iron rule: every claim about current code cites file:line you actually read. Write a SKELETON plan file (the 9 headings) within your first ~10 tool calls via Bash heredoc to the REPORT_FILE path, then REWRITE it as sections firm up; never hold the plan only in your head. Your final reply (text) = a short manifest: plan path, goal, fork choices, item ids + titles, build stages, Boris questions with defaults.`

const A0_S = { type: 'object', properties: { status: { type: 'string', enum: ['DONE', 'PARTIAL', 'BLOCKED'] }, commit: { type: 'string' }, digest_path: { type: 'string' }, red_evidence: { type: 'string' }, green_evidence: { type: 'string' }, reassignments: { type: 'string' }, scenario_e_summary: { type: 'string' }, deviations: { type: 'string' } }, required: ['status', 'commit', 'digest_path', 'red_evidence', 'green_evidence', 'reassignments', 'scenario_e_summary'] }
const ATK_S = { type: 'object', properties: { seat: { type: 'string' }, verdict: { type: 'string', enum: ['ADOPT', 'AMEND', 'REJECT'] }, attacks: { type: 'array', items: { type: 'object', properties: { severity: { type: 'string', enum: ['MUST', 'SHOULD', 'NIT'] }, claim: { type: 'string' }, evidence: { type: 'string' }, fix: { type: 'string' } }, required: ['severity', 'claim', 'evidence'] } } }, required: ['seat', 'verdict', 'attacks'] }
const paper = a => `### SEAT ${a.seat} — VERDICT ${a.verdict}\n` + (a.attacks || []).map((t, i) => `A${i + 1} [${t.severity}] ${t.claim}\n  EVIDENCE: ${t.evidence}\n  FIX: ${t.fix || ''}`).join('\n')

const seatRun = (lane, planPath, lenses) => parallel(lenses.map(l => () => agent(`BLIND COUNCIL SEAT (attack; you see no other seat). Lane ${lane}. Your temperament: ${l.t}
Read the plan ${MAIN}/${planPath} IN FULL and verify its load-bearing claims against the source and the reports it cites (cite file:line you read). Attack it: find what is wrong, missing, untestable or unsafe. Each attack: severity MUST (the plan as written ships a defect, misses its goal, or has a test that cannot fail) / SHOULD / NIT, the claim, your evidence, the fix. No praise. Your structured output IS the paper the ruling receives (you need not write a file).
REPORT_FILE: ${RPT}/attack-${lane}-${l.key}.md`, { agentType: 'authored-council-seat', model: 'sonnet', effort: 'medium', schema: ATK_S, phase: 'Attack', label: `attack:${lane}:${l.key}` })))

const ruleRun = (lane, planPath, atks) => {
  const papers = atks.map(paper).join('\n\n')
  return agent(`ARCHITECT RULING on the blind council's attacks, lane ${lane}. Read your plan ${MAIN}/${planPath}. The seats' papers are INLINE below (they are not on disk). FIRST write them VERBATIM to ${MAIN}/${RPT}/attack-${lane}-papers.md (Bash heredoc), then for EVERY attack: ACCEPT (with the exact plan amendment) or REJECT (with evidence: file:line / scratch run). Then write "## ARCHITECT RULING (s-rta-1002b)": numbered amendments that OVERRIDE the plan body, the final BUILD STAGES, and the FINAL consolidated gate list with pre-registered bars (this list is the one Harmony copies gate strings from). Write it via Bash heredoc to the REPORT_FILE (a separate file; do not edit the plan). Your final reply (text) = a short manifest: ruling path, accepted / rejected attack ids, amendment count, ready_to_build yes/no, Boris questions with defaults. Harmony decides adoption after reading it.
SEAT PAPERS:
${papers}
REPORT_FILE: ${RPT}/ruling-${lane}.md`, { agentType: 'architect', model: 'opus', phase: 'Rule', label: `rule:${lane}` })
}

const A0 = `BUILDER TASK (lane-name: tsan-analyze), work in the MAIN checkout ${MAIN} — ONLY the file .harmony/probe-tsan-analyze.py plus new report files under ${RPT}/. Do not touch src/, tests/, the worktree .claude/worktrees/hyg, or any other file.
PROBLEM (filed, s-rta-1002 ledger 3): probe-tsan-analyze.py's family-B classification mis-keys config-scalar races (e.g. layer.autopilotEnabled, written by perf/play's preamble applyLayerFlag, MainComponent.cpp ~6348-6352) as family B (the Layer trigger-tuple family). In the s-rta-1002 G3 sweep the lane-arm scenario e uniques F76 / F81 read "family B" until the printed source lines were checked.
STEPS:
1. Read the analyzer (its family definitions / regexes) and the family definitions in ${R30}/ruling-tsan.md (search "family" / "A:" / "B:"; around :415-440) and ${R30}/plan-tsan.md. Find the s-rta-1002 G3 raw data and the exact analyzer command line used: ${R02}/gate-tsan/tsan-gate.sh, ${R02}/gate-tsan/g3x.sh, ${R02}/gate-tsan/g3-launches.tsv; raw logs under ${OLDSP}/gate/tsan/ (g3/, g3*.log, the per-launch TSan report dirs the tsv names). If the raw per-launch report files are gone, say so (BLOCKED for steps 2-4) and do step 5 from ${R02}/gate-tsan/g3-analyze.txt.
2. RED: run the CURRENT analyzer over that data exactly as the gate did; save output to ${MAIN}/${RPT}/tsan-analyze-before.txt; quote the lines that key an autopilotEnabled / visible / solo (config scalar) race as family B.
3. FIX: family B = ONLY the Layer trigger tuple (the fields LayerRuntimeCell now holds: activeClipColumn / previousClipColumn / pendingTriggerColumn / crossfadeProgress and any other tuple field the ruling lists) + Clip playing / hasBeenTriggered / beatsPlayed (match on the racing field / source line, not on a file name alone). ADD two explicit classes: R5 "config scalar" (Layer visible / bypassed / solo / mute / autopilotEnabled / transitionSpeed / blendMode..., Clip speed / reverse / loopMode / inPoint / outPoint / beatSnapMode, effect paramValues / dryWet, source params, macros, Composition outputWidth / outputHeight / globalTransitionSpeed / quantizeMode) and R7 "httplib reader" (a stack with an ApiServer / TestServer / httplib frame on one side). Anything that matches no class prints as "UNCLASSIFIED" with its top src frames — never silently folded into a family. Keep the CLI and output format backward compatible (existing gate scripts parse it: check tsan-gate.sh's grep lines).
4. GREEN: re-run on the same data -> ${MAIN}/${RPT}/tsan-analyze-after.txt; produce the per-unique reassignment list (id: old family -> new class) and confirm nothing else moved; re-run the analyzer's own self-test / unit cases if it has any.
5. DIGEST: write ${MAIN}/${RPT}/scenario-e-digest.md: every unique report of scenario e (both arms) AND every report in scenarios a-d now keyed R5 / R7 / UNCLASSIFIED: id, arm, scenario, launches seen, new class, both access stacks' top 4 src frames (file:line function), thread names, and the racing field when inferable from the source line. End with per-arm counts per class.
6. Commit on main (stage by path: git add .harmony/probe-tsan-analyze.py and git add -f the ${RPT}/ files): "fix(s-rta-1002b tsan-analyze): family B = trigger tuple + clip transport only; explicit R5 / R7 / UNCLASSIFIED classes". Never git commit -a.
No app launches, no builds needed. NEVER lldb / dtrace / sample. Return the structured result.`

const tsanChain = async () => {
  phase('Analyzer')
  const a0 = await agent(A0, { agentType: 'builder', model: 'sonnet', effort: 'high', schema: A0_S, phase: 'Analyzer', label: 'build:tsan-analyze' })
  if (!a0) log('tsan-analyze builder returned null — planning proceeds on the old analysis')
  const a0txt = a0 ? JSON.stringify(a0).slice(0, 6000) : 'NONE (analyzer fix failed; use the printed source lines in g3-analyze.txt, not its family labels)'
  phase('Plan')
  const plan = await agent(`PLAN lane tsan-r5 — finish Audio-DNA's thread-race work: the R5 config-scalar class and R7 (the httplib thread reads the live model unfenced), race-free by design and gated by ThreadSanitizer, with zero behaviour change and no perf regression.
WHY: the tsan lane (s-rta-1002, merged b844b65) fixed families A-E by design; its ruling filed this follow-up (${R30}/ruling-tsan.md amendments 1 / 12 / 15, the "tsan-r5" scope at ~:205-215, scenario e at ~:346, ~:371-372; ${R30}/plan-tsan.md R5-R8 at ~:530-560). Baseline: G3 scenario e lane arm = 8 reports (applyLayerFlag visible / solo / autopilotEnabled vs CompositorEngine / Autopilot / DeckClock reads).
READ FIRST: the analyzer fix + digest just produced (result inline below; digest ${RPT}/scenario-e-digest.md); ${R02}/tsan.md (the merged lane's report: Relaxed<T>, LayerRuntimeCell, test_shared_field_types, test_render_thread_lint, the [tsan] Catch2 targets and probe-tsan-unit.sh); ${R02}/gate-tsan/SUMMARY.txt; the harness .harmony/probe-tsan.sh / probe-tsan.py / probe-tsan-analyze.py (scenarios a-e); docs/claude/pitfalls.md 31, 48, 55, 58, 63.
SCOPE you must cover and enumerate EXHAUSTIVELY (a table: field / structure | writer thread(s) + site | reader thread(s) + site | current protection | your treatment):
 (a) R5 config scalars — Layer visible / bypassed / solo / mute / autopilotEnabled / transitionSpeed / type / blendMode / keying / feedback; Clip speed / reverse / loopMode / inPoint / outPoint / beatSnapMode / presetBeatsPlayed; EffectSlot paramValues / dryWet; source params; macros; Composition outputWidth / outputHeight / globalTransitionSpeed / quantizeMode — plus any further model scalar the render / analysis / decode threads read that a UI / REST / OSC / MIDI / routine path writes (find them; do not trust this list to be complete).
 (b) NON-scalar config the render thread iterates (strings, vectors: effect-slot add / remove / reorder, source param vectors, macro lists, mapping lists, preset load): for EACH mutation path prove it is fenced (withDeckDetached / FencedPtrSlot / Pitfall 55 / 58) or show it is a structural race (a use-after-free class, higher severity than a scalar race).
 (c) R7 — every ApiServer (7070) and TestServer (8080) route: which thread executes it, what model state it reads or WRITES, and how it is (not) fenced; /api/status, /api/composition, /api/state (ApiServer.cpp ~:360 / 384 / 1540) at least. Also every other non-message thread that touches the model: OSC receiver, MIDI input callback, Ableton Link, decode / worker threads, the analysis thread.
DESIGN FORKS you must decide with evidence: F1 R5 scalars — per-field Relaxed<T> (mechanical, the tsan lane's wrapper) vs a published per-frame config snapshot vs message-thread-only mutation with the render reading a copy; name every MULTI-FIELD invariant a per-field scheme can tear (inPoint / outPoint, outputWidth / outputHeight -> FBO resize, ...) and how each is kept. F2 R7 — (i) marshal the read to the message thread (callAsync + a bounded wait; timeout -> 503; ApiServer::stop() must never wait on the message thread, Pitfall 58), (ii) a snapshot the message thread publishes (atomic shared_ptr / triple buffer) that httplib reads, (iii) a fence; include probe-latency impact (the probes poll /api/state heavily; Pitfall 31 bodyless POST answered immediately) and the write routes (if any route mutates the model on the httplib thread, that is in scope). F3 the TSan gate design: scenario e + NEW scenarios — f: slider / param writes during render (REST set_param bursts over every R5 field class while rendering), g: R7 polling (/api/composition + /api/state at high rate while loads, deck add / duplicate / remove and composition swaps run) — RED on a TSan build of main 5b507b1, GREEN = 0 app-attributed reports on the lane arm for a-g (a report wholly inside JUCE / system frameworks is listed separately); threaded [tsan] Catch2 tests that FAIL on main under TSan and keep teeth in ctest.
Harmony constraint: no new mutex on the render path and the render thread never waits; slider-to-visual latency must not grow by a frame unless measured and justified; REST responses must stay correct and timely for the existing probes (name every probe the change could slow and its timeout).
Harmony constraint: this lane is large — split it into BUILD STAGES a single builder context can finish (each stage RED-first and committed), in dependency order, and say which stages could ship alone if the lane must stop early.
Analyzer fix result (from the builder, verbatim JSON): ${a0txt}
${COMMON}
REPORT_FILE: ${RPT}/plan-tsan-r5.md`, { agentType: 'architect', model: 'opus', phase: 'Plan', label: 'plan:tsan-r5' })
  if (!plan) { log('tsan-r5 plan returned null — check whether plan-tsan-r5.md exists'); return { a0, plan: null } }
  const atks = (await seatRun('tsan-r5', `${RPT}/plan-tsan-r5.md`, [
    { key: 'memmodel', t: 'CONCURRENCY-CORRECTNESS seat: attack whether the design removes EVERY R5 / R7 race the plan enumerates AND the ones it missed (find a model field read off the message thread that the table omits); multi-field invariants a per-field scheme tears; structural (vector / string) mutation vs render iteration = use-after-free; the R7 marshal / snapshot design under the C++ memory model; shutdown ordering (ApiServer::stop vs the message thread, Pitfall 58); Relaxed<T> under Layer / Clip copy / move / serialization.' },
    { key: 'realtime', t: 'REAL-TIME / LIVE-SHOW seat: attack render-thread cost and any waiting, slider / knob / MIDI-CC / OSC -> visual latency, REST response latency for the probes and for Boris\'s external controllers (REST 7070 is a production API), routine replay (perf/play preamble), the per-frame cost of any snapshot copy, what a performer would see go wrong.' },
    { key: 'gates', t: 'GATES / TESTS seat: attack the verification — can each RED test actually fail on main 5b507b1 under TSan (or is it a test that cannot fail)? Do the new scenarios f / g actually drive every enumerated field class while the render reads it? Are launch counts enough for low-rate races (>= 5 per arm for a flake verdict), are sanitizer options right, do the [tsan] ctest targets keep teeth, are parity probes named and runnable under the rig rules, is the perf A/B interleaved with a bar above the drift?' },
  ])).filter(Boolean)
  const rule = await ruleRun('tsan-r5', `${RPT}/plan-tsan-r5.md`, atks)
  return { a0, plan, attacks: atks.map(a => ({ seat: a.seat, verdict: a.verdict, musts: (a.attacks || []).filter(t => t.severity === 'MUST').length, n: (a.attacks || []).length })), rule }
}

const mkvChain = async () => {
  const plan = await agent(`PLAN lane mkvidx — Audio-DNA video: MKV / WebM files keep a 1-entry index after open, so keyRels_ = {0} and the GOP cache's reverse / ping-pong window is always the whole share (filed s-rta-0930 ledger 4: "extra decodes bounded, no stall; documented. Fix candidate: refresh keyRels_ / gopFramesEst_ after the first seek").
FIRST establish whether a fix is worth it: VERIFY the mechanism (FFmpeg's matroska demuxer reads Cues lazily -> AVStream index entries appear only after the first seek? cite the libavformat source or a scratch ffprobe / tiny C++ libav experiment under /private/tmp on a generated MKV / WebM with a long GOP — ffmpeg CLI may generate fixtures; never launch the app), and MEASURE (or bound from the lane evidence) the cost today: extra decodes per reverse step / per ping-pong turn on a 1080p long-GOP MKV vs the same content in MP4. Include a DO-NOTHING option and choose it if the cost is negligible for a live show (say the bar).
READ: ${R30}/plan-gop2.md, ${R30}/ruling-gop2.md, ${R30}/gop2.md, ${R30}/gate-gop2/ (gates + probes used), .harmony/.reports/s-rta-0929b/ gopcache reports (search gopcache), docs/claude/pitfalls.md 56, 60, 62, the VideoPlayer* / GopCache* sources (keyRels_, gopFramesEst_, decodeStep, VideoRing::pick).
If you choose a fix: items with RED-first unit tests (driving the real demux / cache code on a generated fixture) and the probe rows (probe-video / the gop probes) with pre-registered bars, interleaved A/B for any timing claim. Fence: tsan-r5 (a concurrent plan) may touch Clip runtime fields (speed / reverse / loopMode) — do not plan edits to Clip.h / Layer.h / Composition.h; VideoPlayer* / GopCache* / VideoRing are yours.
${COMMON}
REPORT_FILE: ${RPT}/plan-mkvidx.md`, { agentType: 'architect', model: 'opus', phase: 'Plan', label: 'plan:mkvidx' })
  if (!plan) { log('mkvidx plan returned null'); return { plan: null } }
  const atks = (await seatRun('mkvidx', `${RPT}/plan-mkvidx.md`, [
    { key: 'decode', t: 'DECODE-CORRECTNESS seat: attack the mechanism claims (does the index really stay at 1 entry; when does it grow; seek-flag / timestamp-base edge cases for MKV / WebM incl. VP9 / AV1 / H.264 in MKV; the refresh racing the decode thread; the do-nothing verdict if chosen — is the cost really negligible on 4K?).' },
    { key: 'gates', t: 'GATES / TESTS seat: attack the verification — can each RED test fail on main 5b507b1, are fixtures generated reproducibly, are the probe rows runnable under the rig rules with pre-registered bars and interleaved A/B, is parity with MP4 / MOV reverse playback covered?' },
  ])).filter(Boolean)
  const rule = await ruleRun('mkvidx', `${RPT}/plan-mkvidx.md`, atks)
  return { plan, attacks: atks.map(a => ({ seat: a.seat, verdict: a.verdict, musts: (a.attacks || []).filter(t => t.severity === 'MUST').length, n: (a.attacks || []).length })), rule }
}

const [t, m] = await Promise.all([tsanChain(), mkvChain()])
return { tsanr5: t, mkvidx: m }
