export const meta = {
  name: 'rta-0930-plans',
  description: 'Audio-DNA s-rta-0930: three plans (Fable limit -> opus max) (tsan / gop2 / bt2) -> blind attack seats -> architect ruling per plan',
  phases: [{ title: 'Plan' }, { title: 'Attack' }, { title: 'Rule' }],
}
const MAIN = '/Users/boriskarpman/projects/RealTimeAudio'
const RPT = '.harmony/.reports/s-rta-0930'
const OLDR = '.harmony/.reports/s-rta-0929b'
const OLDSP = '/private/tmp/claude-501/-Users-boriskarpman-projects-RealTimeAudio/bd9a1c96-8ac1-42b0-a088-3d8fb87be738/scratchpad'

const COMMON = `
CONTEXT: Audio-DNA (C++20 / JUCE 8.0.4 / OpenGL 4.1, macOS M1 Pro 32 GiB 120 Hz, Command Line Tools only, no Xcode). Repo ${MAIN}, main HEAD 655d232. Session s-rta-0930 (secondary Harmony, autonomous). The repo CLAUDE.md is loaded for you: obey its Sacred Rules (audio callback sacred; inter-thread data only through the established lock-free channels; UI->hot path via std::atomic<T>; never add a new mutex without explicit discussion; render thread never waits for analysis) and its Pitfall index (read the full entry in docs/claude/pitfalls.md for any pitfall you touch). Boris's rulings: BORIS_DECISIONS.md "Playback Behaviour" and .harmony/binding-decisions.md — read the entries relevant to your area before planning.
THREE LANES ARE PLANNED IN PARALLEL and will be built in parallel in separate git worktrees off main, then merged one at a time:
 - lane tsan: cross-thread publication of Layer / Clip / Composition model fields (Layer.h, Clip.h, LayerClock.h, Renderer.cpp, CompositorEngine.cpp, TriggerCommands.h, ManualWrite.cpp, LayerStrip.cpp, DeckView.cpp, MainComponent.cpp trigger / deck-switch paths) + the std::cerr races (AnalysisThread.cpp, VideoPlayer.cpp open() log lines only).
 - lane gop2: VideoPlayer / GOP cache policy (VideoPlayer*.{h,cpp}, GopCache*, the video probes).
 - lane bt2: audio device lifecycle (AudioEngine, GuardedAudioDeviceManager, the device reconcile / notice code in MainComponent.cpp, probe-btguard.sh).
Keep your lane's edits inside its territory; where you must touch another lane's file, name the exact function / lines so Harmony can sequence the merge.
PLAN FORMAT (mandatory): (1) GOAL in one line; (2) ESTABLISHED facts, each labelled VERIFIED (you read it / ran it: cite file:line) or INFERRED; (3) the DESIGN FORK(S): every defensible alternative, the evidence for each, your choice and why the runner-up loses; (4) numbered ITEMS, each with: files + functions, the exact behaviour change, the RED-first test(s) (a unit test in tests/ that drives real code and FAILS on main HEAD 655d232 — say how it fails — or a named probe row with a pre-registered bar), the GREEN bar, and the risk; (5) GATES Harmony will run herself after the merge (commands / probes / bars, pre-registered decision rules; perf bars only via INTERLEAVED A/B launch by launch, >= 5 runs per arm; a bar whose teeth equal the run-to-run drift is INFO, not a gate); (6) DOCS: which docs/claude/*.md sections and CLAUDE.md lines change — CLAUDE.md is 23,999 of its 25,000-byte cap, any addition is paid by moving text into docs/claude/*.md; new pitfalls are written as "Pitfall NN" (Harmony assigns numbers; next free is 63); (7) RISKS (named, with the cheapest discriminating test); (8) WHAT ONLY BORIS CAN CHECK; (9) QUESTIONS that are genuinely Boris's (product / taste) — with a DEFAULT so the build does not block.
RIG RULES the plan must respect (builders obey them; plan nothing that needs a violation): at most ONE live Audio-DNA at a time (lock helper); launch only via open -g ... [--args --test-mode]; NEVER open an Output window in any gate; no synthetic input (UI states via REST / composition files / a temporary env-var hook reverted before merge); NEVER lldb / debugserver / gdb / dtrace / Instruments / sample on any binary; never a full-screen screencapture; never copy + re-sign an app bundle (mutants only from a normal cmake build dir); sanitizer options always abort_on_error=0 (TSan also exitcode=0 for app launches); probe HTTP clients use Connection: close; before any perf verdict check ps for orphaned CPU burners.
You are read-only on source (you may run read-only commands, git log / show / grep, and scratch experiments under /private/tmp that do not launch the app). Iron rule: every claim about current code cites file:line you actually read.`

const PLANS = [
  {
    key: 'tsan', out: `${RPT}/plan-tsan.md`,
    prompt: `PLAN lane tsan — make Audio-DNA's cross-thread model-field publication race-free, gated by ThreadSanitizer.
GOAL: every data race the s-rta-0929b TSan sweep found (29 unique, 5 families) is removed by design, with the ONE MEDIUM (F2: a clip trigger writes Layer activeClipColumn / previousClipColumn / pendingTriggerColumn / crossfadeProgress on the message thread while the render thread reads AND writes them -> one-frame wrong opacity / crossfade flash; worst case a lost update where the render thread's fade-end store lands after the trigger's stores and the new clip hard-cuts) fixed properly, not merely silenced.
READ FIRST: ${OLDR}/sweep.md (the table + families), every ${OLDR}/verify-sweep-F*.md (20 REAL, 9 BENIGN; F2's "Smallest fix" (a) relaxed-atomic wrappers vs (b) single-writer mailbox drained at the top of renderOpenGL), ${OLDR}/prebuild.md (the TSan build recipe: -DADNA_SANITIZE=thread, RelWithDebInfo, FETCHCONTENT_SOURCE_DIR_*), and the sweep harness copied to ${RPT}/tsan-harness/ (run_batch.sh, scen.py, mkfix.sh, analyze.py; paths inside still point at ${OLDSP} — the plan says how the builder adapts them). Raw TSan stacks: ${OLDSP}/sweep/detail.txt and unique.json (may be read).
Harmony constraint: fix ALL five families, including the BENIGN std::cerr family A (F1, F8, F23-F26) and the "benign-in-practice" F3 / F6 / F15, so the TSan gate's pass bar can be ZERO app-attributed reports in the sweep scenarios a / b / c (a report whose both stacks are wholly inside JUCE / system frameworks is classified separately and listed, not silently ignored).
Harmony constraint: no new mutex on the render path and the render thread never waits; a column / clip trigger must not gain a frame of latency unless the plan measures it and justifies it (VJ timing); undo capture in MainComponent::handleColumnTrigger (MainComponent.cpp ~4781-4840) and TriggerClipCmd (TriggerCommands.h) needs its before / after state synchronously — the design must keep Undo exact; Layer lives by value in std::vector<Layer> (moved / copied), so a bare std::atomic member does not compile — say what wrapper / structure you use and how Layer's copy / move and Deck / Composition serialization stay correct.
The design fork you MUST decide with evidence: (a) relaxed-atomic (or acquire / release) wrappers per field, (b) single-writer: message thread posts trigger intents into an SPSC / atomic mailbox the render thread applies (render thread becomes the only writer of the clock tuple), (c) a per-frame published snapshot (seqlock / triple buffer) of the tuple, or a hybrid (e.g. (b) for the trigger tuple where the render thread also writes, (a) for single-writer scalars such as Clip::playing / playheadPosition UI reads / manual floats / activeDeckIndex). Also cover: the render write-back of clip->playheadPosition (Renderer.cpp:1823) vs a retrigger's playheadPosition = inPoint (a retrigger that does not restart); getActiveClip's double read of activeClipColumn (Layer.h:195-198) -> clips[size_t(-1)] UB; whether any composition swap / vector<Layer> reallocation can overlap a render read (FencedPtrSlot / withDeckDetached, Pitfall 55 / 58) — prove or refute.
TSAN GATE (plan it concretely): build TSan apps of (i) the pre-merge main and (ii) the lane (normal cmake builds in their own build dirs); run the adapted sweep scenarios a / b / c with >= 3 launches per scenario per arm, interleaved; RED = the pre-merge arm reproduces families B-E; GREEN = 0 app-attributed reports on the lane arm. Also plan a TSan-built unit-test target (or threaded Catch2 tests) that FAILS on main under TSan (TSan exitcode non-zero for tests) and passes on the lane, so ctest keeps the teeth after the session. The normal (non-sanitized) build and full ctest must stay green; behaviour parity for triggers, crossfades, beat-snapped triggers (pendingTriggerColumn / processPendingTrigger), routines replay, REST /api/trigger_* and existing probes (probe-crossfade.sh, probe-routines, probe-step3, probe-deck-clock, etc.).
${COMMON}
REPORT_FILE: ${RPT}/plan-tsan.md`
  },
  {
    key: 'gop2', out: `${RPT}/plan-gop2.md`,
    prompt: `PLAN lane gop2 — close the GOP-cache follow-ups left by lane gopcache (merged 8015c76, Pitfall 62).
GOAL: (1) GC7: with the GOP cache capped at 256 MB (env ADNA_GOPCACHE_BUDGET_MB=256), four 1080p GOP-250 clips reversing at once must meet the pre-registered GC7 bar — they run 27.8 uploads/s per player (bar >= 20 PASS) but late frames were 123 > 40 FAIL (main: 17/s, late 1793) — tune the capped-window policy so late <= 40 without regressing the uncapped numbers; (2) the probe artefact: probe-vupload u8 "cap 0.0" rows read None in a capped-only A/B run — fix the probe; (3) ledger R3: an MPEG-TS file (no keyframe index) reversed shows pre-keyframe garbage frames (parity with main's forward seek — decide whether reverse should skip non-decodable pre-key output, and whether forward seek should too, with evidence); (4) VFR residual: one cached frame per index -> 20 of 85 frames of the VFR test file are never shown in reverse (decide: fix or document as by-design with numbers).
READ FIRST: ${OLDR}/plan-gopcache.md (esp. GC7 and its HARMONY ADOPTION section), ${OLDR}/gopcache.md and ${OLDR}/gopcache-fix.md (Fix round 2 = R1 / R2 / R3, VFR), ${OLDR}/review-gopcache-*.md, the GC7 evidence ${RPT}/evidence-0929b/ab-ab256.log + ab-ab256/ (summary.txt, ab.tsv, r*_A/B.log), ${RPT}/evidence-0929b/r3-parity.log, .harmony/probe-vupload*.{sh,py} (u7-u12), docs/claude/pitfalls.md Pitfalls 56 / 60 / 62, and the source (src/media/VideoPlayer*, GopCache* — find them).
Harmony constraint: forward playback must stay golden-trace identical (the golden forward traces added by lane gopcache); the render thread never waits (Pitfall 56); budget semantics min(2 GiB, RAM/16) + memory-pressure hook unchanged unless the plan proves a change is needed.
Harmony constraint: GC7's bar stays as pre-registered (late <= 40 at 256 MB x 4 players, per-player >= 20/s); do not re-threshold. If the plan concludes the bar is unreachable by design at 256 MB, say so with numbers and propose what Harmony should do (that is a Harmony ruling, not a silent change).
${COMMON}
REPORT_FILE: ${RPT}/plan-gop2.md`
  },
  {
    key: 'bt2', out: `${RPT}/plan-bt2.md`,
    prompt: `PLAN lane bt2 — close the btguard follow-ups left by lane btguard (merged 6c73bb0, Pitfall 61).
GOAL: (1) C3: drop the redundant startup setSourceMode re-open (today the device opens 2 times at launch and 4 after a file -> input switch; lane btguard dropped C3 as out of scope under ruling BG3) — every avoidable CoreAudio open is another pass through the JUCE 8.0.4 CoreAudio path whose overflow crashed the app; (2) reconcile case (iii): when the app has NO allowed input (the persistent plain notice tells the performer to plug a wired / built-in mic in) and an allowed mic is plugged in after launch, the app adopts it and clears the notice — today it does not (review-btguard-coreaudio-r2.md SHOULD-1, executed repro), so the notice's own instruction is false.
READ FIRST: ${OLDR}/plan-btguard.md (incl. HARMONY ADOPTION, rulings BG1-BG8), ${OLDR}/btguard.md, ${OLDR}/btguard-fix.md, ${OLDR}/review-btguard-*.md, ${OLDR}/attack-btguard-*.md, .harmony/probe-btguard.sh, docs/claude/pitfalls.md Pitfall 61, docs/claude/integration.md (audio devices), and the source (GuardedAudioDeviceManager, AudioEngine, MainComponent device-gone reconciler — find them).
Harmony constraint: the app must still NEVER open a Bluetooth / BLE / AirPlay / wireless-Continuity device on any path (Pitfall 61), including a hot-plug adoption; the reconciler stays coalesced; adoption happens ONLY when the app currently has no allowed input (never switch away from a working input the performer is using — switching policy while an input works is Boris's product call: list it as a question with default "do not switch"). No device-picker UI is added.
Harmony constraint: tests cannot plug hardware: plan how the RED-first tests drive the reconcile path (unit tests with a fake device type / fake device list, as test_device_policy does; live probe rows via REST or env-var hooks, never synthetic input, never a system audio-setting change). The startup open count (probe-btguard's 'opens' counter) is the C3 teeth.
${COMMON}
REPORT_FILE: ${RPT}/plan-bt2.md`
  },
]

const LENSES = {
  tsan: [
    { key: 'memmodel', t: 'CONCURRENCY-CORRECTNESS seat: attack whether the design actually removes EVERY race (families A-E, all 29 unique ids) and the lost-update, under the C++ memory model — orderings, tuple consistency, multiple writers, the copyable wrapper semantics under vector<Layer> copy / move / reallocation, serialization, composition swap / withDeckDetached overlap, undo exactness. Find the race the plan leaves.' },
    { key: 'realtime', t: 'REAL-TIME / LIVE-SHOW seat: attack render-thread cost and waiting, trigger-to-visual latency (a VJ fires columns on the beat), beat-snapped triggers, crossfade timing and retrigger-restart parity, routines replay, MIDI / OSC / REST trigger paths, UI playhead display; what would a performer see go wrong?' },
    { key: 'gates', t: 'GATES / TESTS seat: attack the verification — can each RED test actually fail on main 655d232 (or is it a test that cannot fail)? Is the TSan gate reproducible given races that hit 1/6 launches, are the scenario counts enough, are sanitizer options right (abort_on_error=0), can the TSan unit-test target keep teeth in ctest, are the parity probes named and runnable under the rig rules?' },
  ],
  gop2: [
    { key: 'decode', t: 'DECODE / CACHE-CORRECTNESS seat: attack the capped-window policy (eviction, look-ahead, prefetch under a 256 MB cap, four players sharing one budget), the MPEG-TS pre-key decision, the VFR decision, forward-play golden-trace identity, thread / memory-pressure interactions.' },
    { key: 'gates', t: 'GATES / PERF-METHOD seat: attack the verification — GC7 bar teeth vs run-to-run drift, interleaved A/B design (>= 5 per arm), the u8 artefact fix, RED-first tests that can fail on main, orphaned-CPU-burner and load controls, which existing probes must re-run.' },
    { key: 'vj', t: 'LIVE-SHOW / VJ seat: attack what a performer sees — reverse / ping-pong feel under a memory cap, garbage or frozen frames on MPEG-TS / VFR clips, a column of reversing clips, switching direction mid-play, low-RAM machines.' },
  ],
  bt2: [
    { key: 'coreaudio', t: 'COREAUDIO / JUCE DEVICE-LIFECYCLE seat: attack the plan against JUCE 8.0.4 AudioDeviceManager / CoreAudio behaviour — change-notification timing, device-list refresh, the known 8.0.4 overflow, re-entrancy of the reconciler, aggregate devices, the startup open sequence after dropping the re-open, the Bluetooth guard on every new path.' },
    { key: 'gates', t: 'GATES / PRODUCT seat: attack the verification (RED-first tests that can fail on main; how hot-plug is simulated without hardware or synthetic input; the opens counter teeth) and the product behaviour (the notice text vs what the app now does; never switching away from a working input; what a performer sees at a gig when a mic is plugged in mid-show).' },
  ],
}

const PLAN_S = { type: 'object', properties: { lane: { type: 'string' }, plan_path: { type: 'string' }, goal: { type: 'string' }, fork_choice: { type: 'string' }, items: { type: 'array', items: { type: 'object', properties: { id: { type: 'string' }, title: { type: 'string' }, files: { type: 'string' } }, required: ['id', 'title'] } }, cross_lane_touches: { type: 'string' }, boris_questions: { type: 'array', items: { type: 'string' } }, summary: { type: 'string' } }, required: ['lane', 'plan_path', 'goal', 'items', 'summary'] }
const ATK_S = { type: 'object', properties: { seat: { type: 'string' }, verdict: { type: 'string', enum: ['ADOPT', 'AMEND', 'REJECT'] }, attacks: { type: 'array', items: { type: 'object', properties: { severity: { type: 'string', enum: ['MUST', 'SHOULD', 'NIT'] }, claim: { type: 'string' }, evidence: { type: 'string' }, fix: { type: 'string' } }, required: ['severity', 'claim', 'evidence'] } } }, required: ['seat', 'verdict', 'attacks'] }
const RUL_S = { type: 'object', properties: { lane: { type: 'string' }, ruling_path: { type: 'string' }, accepted: { type: 'array', items: { type: 'string' } }, rejected: { type: 'array', items: { type: 'string' } }, amendments: { type: 'string' }, boris_questions: { type: 'array', items: { type: 'string' } }, ready_to_build: { type: 'boolean' } }, required: ['lane', 'ruling_path', 'accepted', 'rejected', 'amendments', 'ready_to_build'] }

const results = await pipeline(
  PLANS,
  p => agent(p.prompt, { agentType: 'architect', model: 'opus', effort: 'max', schema: PLAN_S, phase: 'Plan', label: 'plan:' + p.key }),
  (plan, p) => plan ? parallel(LENSES[p.key].map(l => () => agent(`BLIND COUNCIL SEAT (attack; you see no other seat). Lane ${p.key}. Your temperament: ${l.t}
Read the plan ${MAIN}/${p.out} IN FULL and verify its load-bearing claims against the source and the reports it cites (cite file:line you read). Attack it: find what is wrong, missing, untestable or unsafe. Each attack: severity MUST (the plan as written ships a defect, misses a goal, or has a test that cannot fail) / SHOULD / NIT, the claim, your evidence, the fix. No praise. Position paper <= 60 lines.
REPORT_FILE: ${RPT}/attack-${p.key}-${l.key}.md`, { agentType: 'authored-council-seat', model: 'sonnet', effort: 'medium', schema: ATK_S, phase: 'Attack', label: `attack:${p.key}:${l.key}` }))).then(a => ({ plan, attacks: a.filter(Boolean) })) : null,
  (x, p) => x ? agent(`ARCHITECT RULING on the blind council's attacks, lane ${p.key}. Read your plan ${MAIN}/${p.out} and the attack papers ${LENSES[p.key].map(l => `${MAIN}/${RPT}/attack-${p.key}-${l.key}.md`).join(', ')}. For EVERY attack: ACCEPT (with the exact plan amendment) or REJECT (with evidence: file:line / measurement). Then write the consolidated amendments as a section the builder can execute directly: "## ARCHITECT RULING (s-rta-0930)" — numbered amendments that OVERRIDE the plan body, plus the final gate list with pre-registered bars. Write it to REPORT_FILE (a separate file; do not edit the plan). Harmony decides adoption after reading it.
REPORT_FILE: ${RPT}/ruling-${p.key}.md`, { agentType: 'architect', model: 'opus', effort: 'max', schema: RUL_S, phase: 'Rule', label: 'rule:' + p.key }).then(r => ({ plan: x.plan, attacks: x.attacks.map(a => ({ seat: a.seat, verdict: a.verdict, musts: (a.attacks || []).filter(t => t.severity === 'MUST').length, shoulds: (a.attacks || []).filter(t => t.severity === 'SHOULD').length })), ruling: r })) : null,
)
return results
