export const meta = {
  name: 'rta-0930-plans2',
  description: 'Audio-DNA s-rta-0930: tsan plan (2nd attempt, opus max) -> 3 blind seats -> ruling with papers inline; bt2 ruling on the seats',
  phases: [{ title: 'Plan' }, { title: 'Attack' }, { title: 'Rule' }],
}
const MAIN = '/Users/boriskarpman/projects/RealTimeAudio'
const RPT = '.harmony/.reports/s-rta-0930'
const OLDR = '.harmony/.reports/s-rta-0929b'
const OLDSP = '/private/tmp/claude-501/-Users-boriskarpman-projects-RealTimeAudio/bd9a1c96-8ac1-42b0-a088-3d8fb87be738/scratchpad'
const COMMON = `
CONTEXT: Audio-DNA (C++20 / JUCE 8.0.4 / OpenGL 4.1, macOS M1 Pro 32 GiB 120 Hz, Command Line Tools only, no Xcode). Repo ${MAIN}, main HEAD 655d232. Session s-rta-0930 (secondary Harmony, autonomous). The repo CLAUDE.md is loaded for you: obey its Sacred Rules (audio callback sacred; inter-thread data only through the established lock-free channels; UI->hot path via std::atomic<T>; never add a new mutex without explicit discussion; render thread never waits for analysis) and its Pitfall index (read the full entry in docs/claude/pitfalls.md for any pitfall you touch). Boris's rulings: BORIS_DECISIONS.md "Playback Behaviour" and .harmony/binding-decisions.md — read the entries relevant to your area before planning.
THREE LANES ARE PLANNED IN PARALLEL and will be built in parallel in separate git worktrees off main, then merged one at a time:
 - lane tsan: cross-thread publication of Layer / Clip / Composition model fields (Layer.h, Clip.h, LayerClock.h, Renderer.cpp, CompositorEngine.cpp, TriggerCommands.h, ManualWrite.cpp, LayerStrip.cpp, DeckView.cpp, MainComponent.cpp trigger / deck-switch paths) + the std::cerr races (AnalysisThread.cpp, VideoPlayer.cpp open() log lines only).
 - lane gop2: VideoPlayer / GOP cache policy (VideoPlayer*.{h,cpp}, GopCache*, the video probes).
 - lane bt2: audio device lifecycle (AudioEngine, GuardedAudioDeviceManager, the device reconcile / notice code in MainComponent.cpp, probe-btguard.sh).
Keep your lane's edits inside its territory; where you must touch another lane's file, name the exact function / lines so Harmony can sequence the merge.
PLAN FORMAT (mandatory): (1) GOAL in one line; (2) ESTABLISHED facts, each labelled VERIFIED (you read it / ran it: cite file:line) or INFERRED; (3) the DESIGN FORK(S): every defensible alternative, the evidence for each, your choice and why the runner-up loses; (4) numbered ITEMS, each with: files + functions, the exact behaviour change, the RED-first test(s) (a unit test in tests/ that drives real code and FAILS on main HEAD 655d232 — say how it fails — or a named probe row with a pre-registered bar), the GREEN bar, and the risk; (5) GATES Harmony will run herself after the merge (commands / probes / bars, pre-registered decision rules; perf bars only via INTERLEAVED A/B launch by launch, >= 5 runs per arm; a bar whose teeth equal the run-to-run drift is INFO, not a gate); (6) DOCS: which docs/claude/*.md sections and CLAUDE.md lines change — CLAUDE.md is 23,999 of its 25,000-byte cap, any addition is paid by moving text into docs/claude/*.md; new pitfalls are written as "Pitfall NN" (Harmony assigns numbers; next free is 63); (7) RISKS (named, with the cheapest discriminating test); (8) WHAT ONLY BORIS CAN CHECK; (9) QUESTIONS that are genuinely Boris's (product / taste) — with a DEFAULT so the build does not block.
RIG RULES the plan must respect (builders obey them; plan nothing that needs a violation): at most ONE live Audio-DNA at a time (lock helper); launch only via open -g ... [--args --test-mode]; NEVER open an Output window in any gate; no synthetic input (UI states via REST / composition files / a temporary env-var hook reverted before merge); NEVER lldb / debugserver / gdb / dtrace / Instruments / sample on any binary; never a full-screen screencapture; never copy + re-sign an app bundle (mutants only from a normal cmake build dir); sanitizer options always abort_on_error=0 (TSan also exitcode=0 for app launches); probe HTTP clients use Connection: close; before any perf verdict check ps for orphaned CPU burners.
You are read-only on source (you may run read-only commands, git log / show / grep, and scratch experiments under /private/tmp that do not launch the app). Iron rule: every claim about current code cites file:line you actually read.`


const P = {
    key: 'tsan', out: `${RPT}/plan-tsan.md`,
    prompt: `PLAN lane tsan — make Audio-DNA's cross-thread model-field publication race-free, gated by ThreadSanitizer.
GOAL: every data race the s-rta-0929b TSan sweep found (29 unique, 5 families) is removed by design, with the ONE MEDIUM (F2: a clip trigger writes Layer activeClipColumn / previousClipColumn / pendingTriggerColumn / crossfadeProgress on the message thread while the render thread reads AND writes them -> one-frame wrong opacity / crossfade flash; worst case a lost update where the render thread's fade-end store lands after the trigger's stores and the new clip hard-cuts) fixed properly, not merely silenced.
READ FIRST: ${OLDR}/sweep.md (the table + families), every ${OLDR}/verify-sweep-F*.md (20 REAL, 9 BENIGN; F2's "Smallest fix" (a) relaxed-atomic wrappers vs (b) single-writer mailbox drained at the top of renderOpenGL), ${OLDR}/prebuild.md (the TSan build recipe: -DADNA_SANITIZE=thread, RelWithDebInfo, FETCHCONTENT_SOURCE_DIR_*), and the sweep harness copied to ${RPT}/tsan-harness/ (run_batch.sh, scen.py, mkfix.sh, analyze.py; paths inside still point at ${OLDSP} — the plan says how the builder adapts them). Raw TSan stacks: ${OLDSP}/sweep/detail.txt and unique.json (may be read).
Harmony constraint: fix ALL five families, including the BENIGN std::cerr family A (F1, F8, F23-F26) and the "benign-in-practice" F3 / F6 / F15, so the TSan gate's pass bar can be ZERO app-attributed reports in the sweep scenarios a / b / c (a report whose both stacks are wholly inside JUCE / system frameworks is classified separately and listed, not silently ignored).
Harmony constraint: no new mutex on the render path and the render thread never waits; a column / clip trigger must not gain a frame of latency unless the plan measures it and justifies it (VJ timing); undo capture in MainComponent::handleColumnTrigger (MainComponent.cpp ~4781-4840) and TriggerClipCmd (TriggerCommands.h) needs its before / after state synchronously — the design must keep Undo exact; Layer lives by value in std::vector<Layer> (moved / copied), so a bare std::atomic member does not compile — say what wrapper / structure you use and how Layer's copy / move and Deck / Composition serialization stay correct.
The design fork you MUST decide with evidence: (a) relaxed-atomic (or acquire / release) wrappers per field, (b) single-writer: message thread posts trigger intents into an SPSC / atomic mailbox the render thread applies (render thread becomes the only writer of the clock tuple), (c) a per-frame published snapshot (seqlock / triple buffer) of the tuple, or a hybrid (e.g. (b) for the trigger tuple where the render thread also writes, (a) for single-writer scalars such as Clip::playing / playheadPosition UI reads / manual floats / activeDeckIndex). Also cover: the render write-back of clip->playheadPosition (Renderer.cpp:1823) vs a retrigger's playheadPosition = inPoint (a retrigger that does not restart); getActiveClip's double read of activeClipColumn (Layer.h:195-198) -> clips[size_t(-1)] UB; whether any composition swap / vector<Layer> reallocation can overlap a render read (FencedPtrSlot / withDeckDetached, Pitfall 55 / 58) — prove or refute.
TSAN GATE (plan it concretely): build TSan apps of (i) the pre-merge main and (ii) the lane (normal cmake builds in their own build dirs); run the adapted sweep scenarios a / b / c with >= 3 launches per scenario per arm, interleaved; RED = the pre-merge arm reproduces families B-E; GREEN = 0 app-attributed reports on the lane arm. Also plan a TSan-built unit-test target (or threaded Catch2 tests) that FAILS on main under TSan (TSan exitcode non-zero for tests) and passes on the lane, so ctest keeps the teeth after the session. The normal (non-sanitized) build and full ctest must stay green; behaviour parity for triggers, crossfades, beat-snapped triggers (pendingTriggerColumn / processPendingTrigger), routines replay, REST /api/trigger_* and existing probes (probe-crossfade.sh, probe-routines, probe-step3, probe-deck-clock, etc.).
SECOND ATTEMPT — the first planner spent its whole budget researching and ended WITHOUT writing the plan. So: within your first ~10 tool calls WRITE ${RPT}/plan-tsan.md as a skeleton with the 9 PLAN FORMAT headings, then REWRITE it as each section firms up (Bash heredoc to that one path); never hold the plan only in your head. Budget research: the verifier reports already hold the stacks and most facts — verify only the load-bearing claims. A fresh RED baseline exists: ${RPT}/tsan-red-main-655d232.txt (TSan build of main 655d232, 9 launches a/b/c x3: 25 unique, all 5 families; current line numbers, e.g. VideoPlayer.cpp:307-316, MainComponent.cpp:4647/4853/5146/5153/5525) and the parameterized harness ${RPT}/tsan-harness/ (README.md). The previous attempt's transcript noted OSC handler marshalling (MainComponent.cpp ~2196-2240, OscHandler.cpp) and manual-write test APIs (tests/test_manual_write.cpp) as relevant.
${COMMON}
REPORT_FILE: ${RPT}/plan-tsan.md`
  }
const LENSES = {
  tsan: [
    { key: 'memmodel', t: 'CONCURRENCY-CORRECTNESS seat: attack whether the design actually removes EVERY race (families A-E, all 29 unique ids) and the lost-update, under the C++ memory model — orderings, tuple consistency, multiple writers, the copyable wrapper semantics under vector<Layer> copy / move / reallocation, serialization, composition swap / withDeckDetached overlap, undo exactness. Find the race the plan leaves.' },
    { key: 'realtime', t: 'REAL-TIME / LIVE-SHOW seat: attack render-thread cost and waiting, trigger-to-visual latency (a VJ fires columns on the beat), beat-snapped triggers, crossfade timing and retrigger-restart parity, routines replay, MIDI / OSC / REST trigger paths, UI playhead display; what would a performer see go wrong?' },
    { key: 'gates', t: 'GATES / TESTS seat: attack the verification — can each RED test actually fail on main 655d232 (or is it a test that cannot fail)? Is the TSan gate reproducible given races that hit 1/6 launches, are the scenario counts enough, are sanitizer options right (abort_on_error=0), can the TSan unit-test target keep teeth in ctest, are the parity probes named and runnable under the rig rules?' },
  ]
}

const PLAN_S = { type: 'object', properties: { lane: { type: 'string' }, plan_path: { type: 'string' }, goal: { type: 'string' }, fork_choice: { type: 'string' }, items: { type: 'array', items: { type: 'object', properties: { id: { type: 'string' }, title: { type: 'string' }, files: { type: 'string' } }, required: ['id', 'title'] } }, cross_lane_touches: { type: 'string' }, boris_questions: { type: 'array', items: { type: 'string' } }, summary: { type: 'string' } }, required: ['lane', 'plan_path', 'goal', 'items', 'summary'] }
const ATK_S = { type: 'object', properties: { seat: { type: 'string' }, verdict: { type: 'string', enum: ['ADOPT', 'AMEND', 'REJECT'] }, attacks: { type: 'array', items: { type: 'object', properties: { severity: { type: 'string', enum: ['MUST', 'SHOULD', 'NIT'] }, claim: { type: 'string' }, evidence: { type: 'string' }, fix: { type: 'string' } }, required: ['severity', 'claim', 'evidence'] } } }, required: ['seat', 'verdict', 'attacks'] }
const RUL_S = { type: 'object', properties: { lane: { type: 'string' }, ruling_path: { type: 'string' }, accepted: { type: 'array', items: { type: 'string' } }, rejected: { type: 'array', items: { type: 'string' } }, amendments: { type: 'string' }, boris_questions: { type: 'array', items: { type: 'string' } }, ready_to_build: { type: 'boolean' } }, required: ['lane', 'ruling_path', 'accepted', 'rejected', 'amendments', 'ready_to_build'] }
const paper = a => `### SEAT ${a.seat} — VERDICT ${a.verdict}\n` + (a.attacks || []).map((t, i) => `A${i + 1} [${t.severity}] ${t.claim}\n  EVIDENCE: ${t.evidence}\n  FIX: ${t.fix || ''}`).join('\n')

const tsanChain = async () => {
  phase('Plan')
  const plan = await agent(P.prompt, { agentType: 'architect', model: 'opus', effort: 'max', schema: PLAN_S, phase: 'Plan', label: 'plan:tsan#2' })
  if (!plan) { log('tsan plan returned null — check whether plan-tsan.md exists'); return { plan: null } }
  const atks = (await parallel(LENSES.tsan.map(l => () => agent(`BLIND COUNCIL SEAT (attack; you see no other seat). Lane tsan. Your temperament: ${l.t}
Read the plan ${MAIN}/${RPT}/plan-tsan.md IN FULL and verify its load-bearing claims against the source and the reports it cites (cite file:line you read). Attack it: find what is wrong, missing, untestable or unsafe. Each attack: severity MUST (the plan as written ships a defect, misses a goal, or has a test that cannot fail) / SHOULD / NIT, the claim, your evidence, the fix. No praise. Return the paper as your structured output (that is what the ruling receives); also write it to the REPORT_FILE.
REPORT_FILE: ${RPT}/attack-tsan-${l.key}.md`, { agentType: 'authored-council-seat', model: 'sonnet', effort: 'medium', schema: ATK_S, phase: 'Attack', label: `attack:tsan:${l.key}` })))).filter(Boolean)
  const papers = atks.map(paper).join('\n\n')
  const r = await agent(`ARCHITECT RULING on the blind council's attacks, lane tsan. Read your plan ${MAIN}/${RPT}/plan-tsan.md. The seats' papers are INLINE below (they are not on disk). FIRST write them VERBATIM to ${MAIN}/${RPT}/attack-tsan-papers.md (Bash heredoc), then for EVERY attack: ACCEPT (with the exact plan amendment) or REJECT (with evidence: file:line / measurement). Then write the consolidated amendments as a section the builder can execute directly: "## ARCHITECT RULING (s-rta-0930)" — numbered amendments that OVERRIDE the plan body, plus the final gate list with pre-registered bars. Write it to REPORT_FILE (a separate file; do not edit the plan). Harmony decides adoption after reading it.
SEAT PAPERS:
${papers}
REPORT_FILE: ${RPT}/ruling-tsan.md`, { agentType: 'architect', model: 'opus', effort: 'max', schema: RUL_S, phase: 'Rule', label: 'rule:tsan' })
  return { plan, attacks: atks.map(a => ({ seat: a.seat, verdict: a.verdict, musts: (a.attacks || []).filter(t => t.severity === 'MUST').length })), ruling: r }
}

const bt2Chain = () => agent(`ARCHITECT RULING ADDENDUM, lane bt2. Your earlier ruling ${MAIN}/${RPT}/ruling-bt2.md (AM1-AM11, H5) was written while the two blind seats' papers were missing; they are now on disk (recovered verbatim from the workflow journal): ${MAIN}/${RPT}/attack-bt2-coreaudio.md (3 MUST, 3 SHOULD) and ${MAIN}/${RPT}/attack-bt2-gates.md (3 MUST, 4 SHOULD). Read the plan ${MAIN}/${RPT}/plan-bt2.md, your ruling, and both papers. For EVERY seat attack: ACCEPT (exact amendment, reconciled with AM1-AM11 — say where one supersedes another) or REJECT (evidence: file:line / scratch run). Then write "## ARCHITECT RULING ADDENDUM — SEATS (s-rta-0930)": numbered amendments (continue the AM numbering) that OVERRIDE the plan body, the FINAL consolidated gate list with pre-registered bars, and ready_to_build. Write it to REPORT_FILE (do not edit the plan or the earlier ruling).
REPORT_FILE: ${RPT}/ruling-bt2-seats.md`, { agentType: 'architect', model: 'opus', effort: 'max', schema: RUL_S, phase: 'Rule', label: 'rule:bt2-seats' })

const [t, b] = await Promise.all([tsanChain(), bt2Chain()])
return { tsan: t, bt2: b }
