# usage: python3 mk_edits2.py  -- Harmony's own edit blocks after the last three-seat read of the rendered page (page3-final-chair/faith/truth.md).
# Field-level changes are laid over the CURRENT blocks (round 1 + the second ruling's edits), so TOPIC / KIND / FROM are never re-typed; full blocks are written to page3-edits2.md.
import sys, os
here = os.path.dirname(os.path.abspath(__file__)); RS = os.path.join(here, '..'); sys.path.insert(0, here)
from blocks3 import parse, dump
K = {'PAGE-ANSWER': ['ASKED', 'TITLE', 'TEXT', 'ITEM'], 'PAGE-ITEM': ['TOPIC', 'KIND', 'TEXT', 'B', 'C', 'FROM'], 'TRIAGE': ['TO', 'WHY'], 'DROP': ['WHY']}
rd = lambda p: open(os.path.join(RS, p), encoding='utf-8').read()
cur = {}
for f in ('page3-round1.md', 'page3-edits.md'):
    for b in parse(rd(f), K)[0]:
        if b['kind'] == 'DROP':
            k, i = b['id'].split(None, 1); cur.pop((k, i), None)
        else: cur[(b['kind'], b['id'])] = b
CH = {
 ('PAGE-ANSWER', '222'): {'TEXT': 'Master cue is one on / off button. It will sit with the layers\' cue buttons, under the preview monitor, and has no picture of its own: it changes what the preview monitor shows. The name and the button are yours, from 7 October: "add a global effects and actions toggle button called master cue". What it does is my guess. Off: the preview monitor shows the layers you cue, mixed, without the global effects. On: the same mix goes through the global effects, moved by the global actions, so you see it as it would look on the output. As far as I can see without running it, no cue button is built yet; the S button on each layer is solo and changes the output, not a cue.'},
 ('PAGE-ANSWER', '250'): {'TEXT': 'Yes: I meant sliding all the beats, the 1 with them, a little forward or backwards, so a beat falls where you tap; like a nudge, it never makes another beat the 1. The beat has three things: how fast it runs (the BPM), where the beats fall, and which beat is the 1. Tapping always sets how fast. Whether it also moves where the beats fall is open. On 4 October, of the nudge number, you wrote "If I tapped the tempo again, to set the tempo, the time does not change"; on 7 October, of your Resolume, "the beat reacts instantly to the tapping on the second tap", which reads either way. So I ask it below.'},
 ('PAGE-ANSWER', '252'): {'TEXT': 'Yes: they should all run at the same fps: the output monitor and the preview monitor will be drawn together. You are right about smaller and less smooth: I take both back. I expect a layer you cue to be drawn from the same picture the output uses, trails included. By "come first" I mean a rule the build must meet: a preview never changes what the audience sees. If the computer cannot keep up, a preview that needs its own drawing (a clip previewed by its name, or master cue on) freezes on a marked still picture, while the output and the cue of playing layers carry on. Until it freezes, the output may stutter for a moment. None of this is measured: I measure it on your heaviest show before the preview is built.', 'ITEM': 'none'},
 ('PAGE-ANSWER', 'lowres'): {'TEXT': 'Yes: small, like the output monitor inside the app. I take you to mean that one, not the projector: say so if not. I start at a quarter of the show\'s width and height (480 by 270 for full HD) and go larger if that is too small. As you wrote, it is just for reference: it runs next to every show recording by default, without sound, at 30 pictures a second at the most, or at 15 if the test shows that 30 is heavy. Its codec comes out of your test of codecs after the build. A very HD film will come from Render in Studio, not built yet. None of this is measured: if a test shows it makes the live picture stutter, I tell you first.', 'ITEM': 'none'},
 ('PAGE-ANSWER', '246-hold'): {'TEXT': 'My advice: yes, worth doing in a small form: one switch per pad and key, press or hold, set to press. I am medium sure. DJs hold buttons as a fixed habit of some buttons or one setting for all pads: Gate Cue on AlphaTheta (Pioneer), where a hot cue plays only while held, on a paused deck; Momentary on Denon. Big lighting desks (grandMA, ChamSys, Avolites) have a Flash button, on only while held, for hits and strobes. A switch on each pad or clip is what Traktor, Ableton (Gate) and your Resolume (Piano) have. The DJ / producers who described their own visuals let Ableton trigger them; I found none who holds a pad for visuals, which does not prove none does. Nobody has numbers. This is advice, not a rule: your answer of 7 October (no hold setting) stands unless you choose b or c in the item below. Three of the pages I read are linked at the bottom.'},
 ('PAGE-ANSWER', 'general'): {'TEXT': 'Yes, send them as you get them, and do not convert anything yourself. MP3 is on the list of sound files the app opens (read in the program, not run). M4A is not on that list: the file window and drag-and-drop do not offer it, though this Mac probably could read one (not tried). So I make a WAV copy of each M4A myself and your files stay untouched. If the DJ can give you WAV or AIFF just as easily, take those: they are the safest. I take these to be the tracks for measuring how well the app finds the tempo and the 1 on your music. Nothing about automatic mode is promised before that. Say so if you meant them for something else.'},
 ('PAGE-ITEM', 'P1'): {'TEXT': 'I assume in automatic mode the app always tries to find the 1, also after the press that starts the beat (before: "click on play or any clip is the new 1"). After your Resync your 1 holds until the music clearly changes, or you pause or stop.', 'B': 'After your first Resync the 1 is yours for the rest of the night: the app never places it again (your answer b on page 2, read to the letter).'},
 ('PAGE-ITEM', 'P10'): {'TEXT': 'I assume tempo stop and Stop actions stop every action. Layer and global action buttons go off. A clip\'s action buttons stay on, and its actions play again when that clip is next triggered. Is that right? Type yes, b or c: an empty box cannot answer this one.'},
 ('PAGE-ITEM', 'P11'): {'TEXT': 'I assume a layer\'s Clear button (the X) takes the clip off and also stops that layer\'s own actions: their buttons go off. A clip that leaves its layer another way (it ends and leaves by itself, you trigger an empty cell, you delete it) leaves them on.'},
 ('PAGE-ITEM', 'P13'): {'TEXT': 'I assume, as you wrote, the low-resolution show recording is there to catch mistakes in the parameter recording: Studio plays it beside its own picture, at the same moment of the show, also while you scrub.'},
 ('PAGE-ITEM', 'P20'): {'TEXT': 'I assume All Outputs Off lasts through a quit: at the next start no output comes on by itself, until you switch one on or use Restore Last Outputs; after that, shows bring their outputs on again (before: shows remember their outputs).'},
 ('PAGE-ITEM', 'P23'): {'TEXT': 'I assume by "adjust the sink" you mean a Sync slider on a strobe, a pulse and effects like them: it sets how fast they pulse, locked to the beat (every bar, beat, half beat ...).'},
 ('PAGE-ITEM', 'P24'): {'TEXT': 'I assume an envelope you draw for a clip is that clip\'s own: saved and copied with it, used only by that clip\'s sliders and buttons. A preset loaded on another clip sets the slider\'s value only, not the envelope.'},
 ('PAGE-ITEM', 'P27'): {'TEXT': 'I assume a slider away from its knob (after an action, a preset or a deck switch) jumps to it when you turn a knob that sends its position. Your "work smoothly" may mean no jump. An endless knob never jumps.'},
 ('PAGE-ITEM', 'NEW-2'): {'TEXT': 'I assume the tempo stop takes everything off the output, a MilkDrop picture you clicked onto it too.', 'B': 'A MilkDrop picture you clicked stays on the output after a stop.', 'FROM': 'K3-3'},
 ('PAGE-ITEM', 'P8'): {'B': 'With a layer\'s cue button on, a click on a clip\'s name there puts the clip into the cue on the next 1; the output does not change.'},
 ('PAGE-ITEM', 'NEW-1'): {'TEXT': 'I assume in the first build a MilkDrop clip previewed while another one plays shows the playing one\'s picture, marked; the same for sources that cannot run twice at once.'},
 ('PAGE-ITEM', 'P9'): {'B': 'A show saved on this computer never asks: this computer\'s version stays. A show from another computer asks whenever the two versions differ (my recommendation).'},
 ('PAGE-ITEM', 'P15'): {'B': 'Opening Studio switches the action buttons off, as Stop actions does, whichever way you choose for the tempo stop.'},
 ('PAGE-ITEM', 'P18'): {'TEXT': 'I assume a deleted clip leaves its layer at once, also in BPM mode; so does a clip whose column or deck is removed (before: that one played on).'},
 ('PAGE-ITEM', 'P19'): {'TEXT': 'I assume a Snapshot remembers the MilkDrop preset showing and loads it when opened, since you asked for "the output and everything": an exception to keeping MilkDrop as it is.', 'B': 'A Snapshot does not bring back the MilkDrop preset: MilkDrop stays exactly as it is; the Snapshot\'s picture shows how the moment looked.'},
 ('PAGE-ITEM', 'P25'): {'TEXT': 'I assume your newest words hold: blend modes and keying stay, built later. I take the keying slider to stay with the keying (before: you wanted the keying and its slider removed).'},
 ('TRIAGE', 'K3-7'): {'TO': 'NEW-3', 'WHY': 'What a layer on autopilot does after "Stop removes all clips from all layers" (BF271) is in no line of his; it gets a line of its own, apart from the MilkDrop picture (the last read: chair F4, faith F11: two assumptions, one b could not strike only one).'},
 ('TRIAGE', 'A3-2'): {'TO': 'NEW-4', 'WHY': 'One cut on every playing clip in BPM mode is seen on stage. His "71 b" is the rule for a clip out of time, not for the app placing the 1 (the last read: faith F13; topic A\'s ruling had it as a line): one line he can strike.'},
}
NEW = [
 ('PAGE-ITEM', 'NEW-3', {'TOPIC': 'A', 'KIND': 'LINE', 'TEXT': 'I assume after a tempo stop a layer on autopilot stays empty until you trigger a clip there.', 'B': 'Autopilot puts a clip on an empty layer again when the beat runs.', 'C': 'none', 'FROM': 'K3-7'}),
 ('PAGE-ITEM', 'NEW-4', {'TOPIC': 'A', 'KIND': 'LINE', 'TEXT': 'I assume when the app moves the 1 by itself, a clip playing in BPM mode falls into step with one cut, on the next 1; your own Resync cuts it at once.', 'B': 'The clip is cut at once to the new 1, as with a Resync.', 'C': 'none', 'FROM': 'A3-2'}),
]
o = ['# page3-edits2.md -- Harmony\'s edit blocks after the last three-seat read of the rendered page (made by wf/mk_edits2.py; the reasons: page3-final-chair.md, page3-final-faith.md, page3-final-truth.md and the work log)', '']
for key, ch in CH.items():
    assert key in cur, key
    b = cur[key]; f = dict(b['fields']); f.update(ch); o += [dump(dict(b, fields=f), K), '']
for kind, i, f in NEW:
    assert (kind, i) not in cur; o += [dump({'kind': kind, 'id': i, 'fields': f}, K), '']
open(os.path.join(RS, 'page3-edits2.md'), 'w', encoding='utf-8').write('\n'.join(o))
print('page3-edits2.md: %d blocks changed, %d new' % (len(CH), len(NEW)))
