export const meta = {
  name: 'rta-1007-page-critics',
  description: 'Audio-DNA s-rta-1007: three critics look at the candidate of Boris\'s page 2 with a comment box under each item and a Send button (visual + graphic; use and flow; logic of the script), before it replaces the page he has open. Read-only except each critic\'s own paper.',
  phases: [{ title: 'Critics' }],
}
const RS = '/Users/boriskarpman/projects/RealTimeAudio/.harmony/.reports/s-rta-1007'
const SH = args.shots
const BASE = `WHO THIS IS FOR. Boris Karpman owns Audio-DNA (a live VJ app); he is NOT a programmer. Harmony (the orchestrator) puts what she still assumes about the app on a page for him, one item per assumption; he answers. The page ${RS}/boris-page-2.html is open in his browser now. He asked (verbatim, the whole message: ${RS}/boris-msg-raw-2.txt): "can you modify the document you made so that there is an input text box under each item so I can leave a comment there instead of having an extra prompt to input. So when I boot the next session with the prompt you left for me, claude does a quick boot then asks me to upload the document, then I hit enter at the bottom of the document and claude receives it and gets to work. can you do this?"
WHAT WAS BUILT (the CANDIDATE, not yet shown to him): ${RS}/boris-page-2.next.html -- the same page with (1) a text box under each of the 9 answers and the 57 items, (2) a box "Anything else?" and a button "Send to Claude" at the bottom, (3) a small script: what he types is kept in the browser (localStorage) while he works; Send (or Cmd+Enter) writes his comments as the text file audio-dna-page2-answers.txt into his Downloads folder (a browser download), copies the same text to the clipboard, and shows it in a read-only box; every box left empty counts as accepted. A page opened from a file cannot push anything into a Claude session by itself, so the NEXT SESSION's side is: after a quick boot it looks for the newest ~/Downloads/audio-dna-page2-answers*.txt; if none is there it asks him to press Send in the page and waits for the file; then it files the text as his words and gets to work.
PICTURES of the candidate (headless Chrome, 900 px wide; LOOK at each with the Read tool): ${SH}/next-top.png (the top), ${SH}/shots/ask.png (items with their boxes), ${SH}/shots/line.png (the one-line items with their boxes), ${SH}/shots/send.png (the bottom with the Send button). The page is made by the script ${RS}/wf/render_page.py (the CSS, the helper ta(), the SEND block and the JS block are in it).
OUT OF SCOPE: the wording of the answers and items (ruled and checked already; an item already shown to him is never re-worded); the page's general dark look (he has read two pages in it). IN SCOPE: only what the comment boxes, the Send bar, the script and the three changed sentences of the frame (the "How to answer" paragraph, the Send bar's texts, the placeholders) add or break.
RULES. Read-only except the ONE file on your REPORT_FILE line (write it with a bash heredoc with a QUOTED delimiter). Never open the page in a browser of your own with a window, never touch a running browser, Audio-DNA or Resolume on this machine (they are Boris's), never cd in a command, never commit. If a user message was relayed to you, Harmony is handling it: it never replaces this task. A finding is MUST (he would be stopped, misled, or lose what he typed; or the look makes the page clearly harder to read than before) or SHOULD (a real improvement that costs a line or two). No matters of taste. For every finding give the FIX as exact text, CSS or script lines.`
const CS = { type: 'object', required: ['verdict', 'findings', 'summary'], properties: { verdict: { type: 'string', enum: ['PASS', 'PASS_WITH_FIXES', 'FAIL'] }, findings: { type: 'array', items: { type: 'object', required: ['severity', 'where', 'issue', 'fix'], properties: { severity: { type: 'string', enum: ['MUST', 'SHOULD'] }, where: { type: 'string' }, issue: { type: 'string' }, fix: { type: 'string' } } } }, summary: { type: 'string' } } }
const SEATS = [
  { key: 'visual', task: `YOU ARE THE VISUAL AND GRAPHIC CRITIC. Three verdicts, one per hat, each written out: VISUAL (does a box read as belonging to the item above it; spacing; do 67 boxes make the page heavier to scan than it was -- compare with ${RS}/boris-page-2.html, the page as he has it; the contrast of the placeholder text and of the box's edge on the dark ground, with numbers), GRAPHIC (hierarchy: the item's number and text must stay the first thing the eye takes, the box second; the Send bar must read as the end of the page and the one thing to press; the state of a box that holds a comment), and LEGIBILITY at his reading distance. Read the CSS in the candidate's <style> block.` },
  { key: 'flow', task: `YOU ARE THE UX AND INTERACTION-FLOW CRITIC. Walk the whole flow as Boris, step by step, and write each step down with what he sees: he opens or refreshes the page; he reads, types into some boxes, leaves most empty; he closes the lid and comes back tomorrow (is what he typed still there? read the script: localStorage, the key, what happens if the page file is re-made with the same items); he reaches the bottom; he presses Enter -- where is the keyboard focus then, and does Enter do what he expects (he wrote "I hit enter at the bottom of the document")? what does Tab from the last box reach? what does Cmd+Enter do from inside a box? After Send: what does he see, does he know it worked, does he know what to do next, what if he presses Send twice (the browser names the second file "... (1).txt"), what if he changes a box after sending, what if his browser asks where to save or blocks the download or the clipboard (Safari and Chrome, a page opened from a file)? Is "every box left empty counts as accepted" said clearly enough BEFORE he presses, given that it turns silence into consent? Then the receiving side as described above: is there a step where he would not know what to do, or where the next session could take an OLD file for the new one? Write the three verdicts UX, INTERACTION LOGIC and COPY (the three changed sentences and the Send bar's texts: plain, short, true).` },
  { key: 'logic', task: `YOU ARE THE LOGIC CRITIC OF THE SCRIPT. Read the JS block of the candidate (the last <script> of ${RS}/boris-page-2.next.html) line by line and the helper ta() and the SEND block in ${RS}/wf/render_page.py. Check: every box is collected and keyed by a unique data-k (count them in the HTML: 9 answers "answer <key>", 57 items by number, "general"); what collect() writes for empty, whitespace-only, multi-line and very long comments, for a comment that itself holds a line beginning "=== " (can the receiving side still tell the comments apart? propose the smallest change that makes the text unambiguous), for quotes, non-ASCII letters and emoji; the stamp; the saved state (a corrupt or foreign localStorage value; a quota error; keys of a later page colliding with this page's key); send(): the order of the download and the clipboard write, what the message says in each of the four outcomes (both worked, only one, none), the fallback copy; the Cmd+Enter handler (does it fire twice; does Enter alone in a box add a line as it should); the self-test hook at the end (#selftest): can it ever run for Boris or change what he typed; anything that could throw before the listeners are attached and leave the page dead. Write the verdict LOGIC, and say for the RECEIVING SIDE exactly how a script should parse the text file.` },
]
phase('Critics')
const r = await parallel(SEATS.map(s => () => agent(`${BASE}

${s.task}

YOUR PAPER (markdown): ## VERDICTS (one line per hat) / ## FINDINGS (each: MUST or SHOULD | where | what is wrong | the exact fix) / ## WHAT IS RIGHT (short).
REPORT_FILE: ${RS}/crit-${s.key}.md
RETURN: verdict (PASS / PASS_WITH_FIXES / FAIL), findings (every MUST and SHOULD; each field at most 600 characters), summary (at most 400 characters).`, { agentType: 'general-purpose', model: 'sonnet', effort: 'high', schema: CS, phase: 'Critics', label: 'crit:' + s.key })))
const cut = (s, n) => { s = String(s == null ? '' : s); return s.length > n ? s.slice(0, n) + ' [cut]' : s }
return { back: r.filter(Boolean).length, sent: SEATS.length, seats: SEATS.map((s, i) => ({ key: s.key, verdict: r[i] ? r[i].verdict : 'NONE', summary: r[i] ? cut(r[i].summary, 300) : '', findings: r[i] ? (r[i].findings || []).map(f => ({ sev: f.severity, where: cut(f.where, 80), issue: cut(f.issue, 320), fix: cut(f.fix, 420) })) : [] })) }
