export const meta = {
  name: 'rta-1003b-bf2-stops',
  description: 'Audio-DNA s-rta-1003b: rule the open stop items of the sync dial lane after stages S3f / S4 (a dead knob binding, a one-block state in the take-alignment row, a late marker, a load-sensitive timing test, an untested handler, a dead branch): architect plan (opus high), 4 blind seats (sonnet), architect ruling (opus max). Read-only.',
  phases: [{ title: 'Plan' }, { title: 'Attack' }, { title: 'Ruling' }],
}
const MAIN = '/Users/boriskarpman/projects/RealTimeAudio'
const RPT = '.harmony/.reports/s-rta-1003b'
const R3 = '.harmony/.reports/s-rta-1003'
const OLD = '.harmony/.reports/s-rta-1002b'
const W = MAIN + '/.claude/worktrees/bf2'
const PIN = '68abc16'
const SP = '/private/tmp/claude-501/-Users-boriskarpman-projects-RealTimeAudio/00e87ddd-eec9-42a5-94d1-5dc67e66ea7d/scratchpad'
const PLAN_FILE = RPT + '/plan-bf2-stops.md'
const RULING_FILE = RPT + '/ruling-bf2-stops.md'
const PAPERS_FILE = RPT + '/attack-bf2-stops-papers.md'

const READS = `HOW TO READ (binding): you are read-only. Read the lane ONLY at the pinned commit ${PIN} of branch lane/bf2: git -C ${W} show ${PIN}:<path> | sed -n 'A,Bp' and git -C ${W} grep -n '<pattern>' ${PIN} -- src tests docs .harmony (never the working-tree files of the worktree). Reports under ${MAIN}/.harmony/ and the builders' saved run logs under ${SP}/bf2-S3f/, ${SP}/bf2-S4/, ${SP}/bf2-R1/ (list them with ls; raw probe output, per-marker errors, offline scripts) are plain files you may read. Never build, never run a test, never launch the app, never run a probe; python3 arithmetic on saved logs is allowed. Never cd in a command. If a user message was relayed to you, Harmony already answered it; it never replaces this task.`

const INPUTS = `INPUTS (big files are indexed -- grep -n '^#' first, then read ranges):
- Harmony's rulings, binding, read first: ${MAIN}/${RPT}/rulings-bf2.md (H-1..H-12; Boris's four verbatim lines at its top -- quote him only from there or from ${MAIN}/.harmony/binding-decisions.md).
- The lane report of this session at the pin: git -C ${W} show ${PIN}:${RPT}/bf2-delta.md (stages M0, S3f, S4, the fix round: every STOP item, FOUND NOT FIXED, facts M1..M7, the HAND-OVER blocks).
- The reviews: ${MAIN}/${RPT}/review-bf2-keys-r1.md and -r2.md (the open MUST), review-bf2-gates-r1.md / -r2.md, review-bf2-realtime-r1.md / -r2.md, review-bf2-merge-r1.md / -r2.md.
- The spec chain: ${MAIN}/${R3}/ruling-bf2-delta.md (D1..D22; section 5 rows R7, R7b, G1 [timing]; its risk K4 "unknown arm-to-arm drift"), the HARMONY ADOPTION at the end of ${MAIN}/${R3}/plan-bf2-delta.md, the re-stated gate rows ${MAIN}/${RPT}/ruling-bf2-gates-restated.md, and the earlier chain ${MAIN}/${OLD}/ruling-bf2.md + plan-bf2.md (item I9 "Keys & MIDI", the take stamps I12 / AM-13).
- Lane code at the pin: src/recording/RecorderHost.cpp/.h (take start, marker stamps, lateSeconds, periodic and tempo take saves), src/audio/* (the file-playback path a click track takes, the device callback, the ring), src/analysis/AnalysisThread.cpp + BeatLead.cpp/.h + the resampler, src/binding/* + src/ui/MidiLearnOverlay.cpp + BindingOverlay (ccMode, processMidiCC, the learn capture), src/MainComponent.cpp handleBindingAction's SyncNudge case, src/api/ApiServer.cpp (routes that could fire a binding action), .harmony/probe-sync.sh + probe-sync.py (rows R7, R7b; how a take, a marker and the click grid are paired) + probe-sync-selftest.py, tests/test_analysis_sync_thread.cpp ([timing]).
- Project rules: CLAUDE.md (sacred rules; "two rate domains", Pitfall 29; Pitfall 48) and docs/claude/pitfalls.md entries 29, 30, 42, 48, 61, 68 at the pin; docs/claude/recording.md "Takes under the sync dial".`

const ITEMS = `ITEMS. For each: what is VERIFIED at ${PIN} (file:line or a saved log line), the forks, the choice, why the runner-up loses, the change by file / function (no code), RED-first tests and mutants, the gate row.
P1 THE DEAD KNOB (keys MUST, open after the fix round). A MIDI knob or encoder learned onto "Sync -1 ms" / "Sync +1 ms" is bound and does nothing: MIDI learn makes every CC binding Absolute, an Absolute CC on SyncNudge is ignored as ruled, and no screen makes a Relative binding. Lay out every defensible way out -- at least: (a) MIDI learn makes the binding Relative when the target is a Sync nudge; (b) keys and notes only, and MIDI learn does not bind a CC to a Sync target at all (no dead binding can be made), docs say so; (c) a general way to choose a CC binding's mode on screen (which screen, what it costs, is it this lane); (d) an Absolute-CC meaning for a nudge (a CC button that sends 127 on press and 0 on release = one step per press). Say what a relative encoder, a plain knob, a fader and a CC button each send, how the engine's Relative decoding reads it today, and what each option does to each control in Boris's hands. Rule one, name the runner-up, and say what -- if anything -- is a question for Boris (with a default). Harmony constraint: no bound control that silently does nothing; no on-screen text that announces an event or a failure (how does the learn screen show, as a STATE, that nothing was bound?).
P2 R7'S ONE-BLOCK STATE AT DIAL 0. In short development runs, 3 of 7 live zero-dial takes read a median paired marker error of 41.333 ms instead of 30.667 (every marker +512 samples at 48 kHz), changing once inside a launch; the cause is not established. Is it in the PRODUCT (a take's markers or its audio sit one device block late on some takes -- then Boris's takes are sometimes 10.7 ms off, with or without the dial) or in the PROBE (how the click file's playback start is paired with the take's first sample)? Harmony constraint (the project's Definitive-Fix rule): diagnose by INSTRUMENT-AND-RUN, never by reading alone. So: list every hypothesis the code and the saved logs allow, with the evidence for and against; for each, the cheapest experiment that discriminates it from the others (what is logged, where -- a test-server-only witness field or an environment-gated log line, removed afterwards with a strings check; how many takes; which arms; expected reading under each hypothesis); a DECISION TABLE: outcome -> product defect (fixed where, pinned by which unit case, RED first) or instrument artefact (what the row computes instead -- without loosening R7's bar or its validity rule); and what Harmony's 21-arm gate run then needs. Use the saved per-marker errors: does the +512 state start at a take boundary, at an arm boundary, at a dial change?
P3 THE LATE MARKER. In every take seen, exactly one marker is late by about 4,416 - 4,928 samples (about 92 - 103 ms): raw index 70, about 35 s into a 60 s take, and R7's rule drops it. The ruling routes "it is not the take's first marker" to the architect before the merge. Hypotheses (a periodic or tempo take save stalling the thread that stamps markers; an irregularity in the click file itself at that position; a tracker or onset-detector event; a ring or resampler boundary) and the discriminating experiment for each (a 120 s take; another click file; the save interval read at the pin). Product defect or measurement artefact? If product: does it matter to Boris (one gesture or onset stamp per ~30 s late by a tenth of a second)?
P4 [timing] UNDER LOAD. The unit case "[timing] the published lag moves 1 ms per 1 ms step and 150 ms at 150" read 0.65 - 0.82 ms per pair once while a video player sat above 20 % CPU (bar 0.7 .. 1.3) and 0.97 - 1.01 in later runs under the same process. Read the case at the pin: what clock does it read, what would make the slope LOW rather than noisy? Design the discriminating run (N runs idle, N runs under a controlled CPU load from a plain shell loop; the pair lines D8 now always prints) and say which outcome means what. The bar is not changed by this item; rule whether the case stays a gate, becomes a quiet-machine-only gate (it is one today), or needs a different measurement.
P5 THE UNTESTED HANDLER. No test drives MainComponent::handleBindingAction's SyncNudge case (the unit test re-states its body in a lambda; no unit target builds MainComponent; the rig forbids synthetic key and MIDI events). Design a REST-driven live row through the REAL handler: does a route that fires a binding action exist at the pin, or is a test-server-only route needed (which file, what it calls); the row (nudge -> GET /api/sync targetMs moves by the step, clamped at the range ends), its RED arm (a wrong-sign or missing-call mutant), which stage builds it.
P6 THE DEAD BRANCH. Since D5 the BeatLead manual-Resync branch, originX_, lastResyncs_ and Flags::resyncs carry no information (both arms leave originX == barX; real-time review r1). D5 made them dead, so they are this lane's orphan: remove them in this lane (what goes, which tests and call sites change, the T-L family's proof that behaviour is unchanged, the zero-heap lint) or keep them as recorded debt -- rule it.
P7 ORDER. With P1-P6 ruled: the stages still to build are S6 (taps go through the dial, incl. D9 the take start), S5a, S5b. Where do the diagnosis stage, its fix, the keys fix and P5's row go; may S6 be built before P2's diagnosis is known, given that D9 edits the take start; which rows of ${MAIN}/${R3}/ruling-bf2-delta.md section 5 change (exact replacement strings) and which are added; what Harmony runs herself and when (the machine is shared with Boris: a quiet row needs no agent running and no video playing).`

const PS = { type: 'object', properties: { plan_path: { type: 'string' }, status: { type: 'string', enum: ['DONE', 'PARTIAL'] }, summary: { type: 'string' }, forks: { type: 'array', items: { type: 'object', properties: { id: { type: 'string' }, choice: { type: 'string' }, runner_up: { type: 'string' } }, required: ['id', 'choice'] } }, not_verified: { type: 'array', items: { type: 'string' } } }, required: ['plan_path', 'status', 'summary', 'forks'] }
const AS = { type: 'object', properties: { seat: { type: 'string' }, attacks: { type: 'array', items: { type: 'object', properties: { id: { type: 'string' }, target: { type: 'string' }, claim: { type: 'string' }, evidence: { type: 'string' }, severity: { type: 'string', enum: ['MUST', 'SHOULD', 'NIT'] }, proposed_change: { type: 'string' } }, required: ['id', 'target', 'claim', 'evidence', 'severity'] } }, strongest_point: { type: 'string' }, citations_rechecked: { type: 'boolean' } }, required: ['seat', 'attacks', 'strongest_point', 'citations_rechecked'] }
const RS = { type: 'object', properties: { ruling_path: { type: 'string' }, papers_path: { type: 'string' }, status: { type: 'string', enum: ['DONE', 'PARTIAL'] }, verdict: { type: 'string' }, amendments: { type: 'number' }, attacks_ruled: { type: 'number' }, stages: { type: 'array', items: { type: 'object', properties: { key: { type: 'string' }, scope: { type: 'string' } }, required: ['key', 'scope'] } }, boris_questions: { type: 'array', items: { type: 'string' } }, harmony_decisions: { type: 'array', items: { type: 'string' } }, facts_harmony_must_measure: { type: 'array', items: { type: 'string' } }, strongest_counterargument: { type: 'string' } }, required: ['ruling_path', 'status', 'verdict', 'amendments', 'attacks_ruled', 'stages'] }

phase('Plan')
const plan = await agent(`PLAN AUTHORING (architect) -- Audio-DNA, lane bf2 (the sync dial): the STOP ITEMS left open after stages S3f and S4 and their review rounds. You author the position; a blind council attacks it; an architect ruling follows; Harmony decides.
GOAL: no further build stage of this lane starts until these items are ruled. Two of them (P2, P3) are unexplained measurements in the take-alignment gate and must be DIAGNOSED by instrument-and-run before anything is fixed or re-stated; one (P1) is a review MUST that needs a product choice; the rest are small. Produce the plan a builder can execute stage by stage, with the diagnosis experiments designed so that their result decides, and one list of what Harmony runs.
${READS}
${INPUTS}
${ITEMS}
OUTPUT: write the plan to REPORT_FILE (literal path below, relative to ${MAIN}; bash heredoc to exactly that path). Sections: 1 GOAL; 2 ESTABLISHED FACTS (ONLY lines verified at ${PIN} or in a saved log, each with file:line or the log path and line; anything else is labelled INFERRED or ASSUMED where it is used); 3 ITEMS P1-P6; 4 STAGES + ORDER (P7); 5 GATE ROWS that change or are added (exact strings and bars; each with its RED arm); 6 WHAT ONLY BORIS CAN CHECK; 7 QUESTIONS FOR BORIS (plain words, each with a default; only what is genuinely his); 8 RISKS (the strongest counterargument first; the cheapest refuting test for each choice).
RULES OF THE DOCUMENT: Boris is quoted ONLY verbatim; anything Harmony requires is written as "Harmony constraint:". No code blocks longer than a signature. Real-time rules hold (no allocation / lock / syscall on the audio callback; analysis steady state allocation-free; no new mutex). A pre-registered bar is never loosened. Prefer the smallest change that is correct; say what is NOT in this lane.
TURN BUDGET (the architect role stops SILENTLY at 120 turns): write a SKELETON of the plan file with all headings by your turn 8; rewrite it with what you have every ~10 turns; be DONE by turn 90; if short, status PARTIAL with what is missing at the top.
REPORT_FILE: ${PLAN_FILE}
RETURN: plan_path, status, summary <= 1500 characters, forks (id, choice, runner_up), not_verified (what you could not establish by reading).`, { agentType: 'architect', model: 'opus', effort: 'high', schema: PS, phase: 'Plan', label: 'plan:bf2-stops' })
if (!plan) return { failed: 'plan' }
log('plan: ' + plan.status + ' -> ' + plan.plan_path)

phase('Attack')
const SEATS = [
  { key: 'audio-clock', temper: 'You are the AUDIO-CLOCK SKEPTIC: every sample count belongs to a rate domain and a block lattice, and a measurement is only as good as its instrument. Attack P2, P3 and P4: a hypothesis the plan did not list (device block size vs analysis hop, the resampler, the ring, the file-playback start, a rate change, which thread stamps what); an experiment that cannot tell two hypotheses apart; an instrumentation line that itself moves the timing; a decision table with a missing outcome; a "probe artefact" verdict that would hide a real 10.7 ms product error from Boris. Re-derive each claim from the code and the saved per-marker logs.' },
  { key: 'midi-hands', temper: 'You are the MIDI OPERATOR: Boris binds real controllers (pads that send notes, endless encoders, plain knobs, faders, CC buttons) by MIDI learn and performs with them. Attack P1 and P5: what each option does when the WRONG kind of control is learned (a plain knob in relative mode jumping tens of milliseconds; a fader; a CC button); an option that leaves a bound control doing nothing; a learn screen that gives no state he can read; relative decoding that is wrong for common encoders (two-complement, signed-bit, 64-offset); a nudge that auto-repeats while a key is held; a question that is not his or lacks a default.' },
  { key: 'gates', temper: 'You are the GATE PROSECUTOR: a test that cannot fail is not a test. Attack every experiment, test, mutant, bar and gate string in the plan: a diagnosis whose every outcome is read as "artefact"; a RED arm that does not exist; a row re-stated so that the one-block state can no longer fail it (a loosened bar by another name); a live row that passes when the handler is never reached; a [timing] ruling that turns a failing gate into INFO without proof; a pin (case count, EXPECTED rows) left stale by an added case.' },
  { key: 'scope', temper: 'You are the MINIMALIST: three build stages and the merge still wait behind these items, and other lanes behind the merge. Attack scope and order: a diagnosis bigger than the question; a fix planned before the diagnosis can justify it; a new screen for a CC mode when a two-line rule would do; removing dead code where a comment suffices (or the reverse); a stage order that makes S6 wait when it need not, or lets it start when the take start is under suspicion. For each cut, name what is lost -- and name the ONE thing in the plan that must NOT be cut.' },
]
const papers = (await parallel(SEATS.map(s => () => agent(`BLIND COUNCIL SEAT "${s.key}" -- attack ONE plan from ONE temperament. You do not see the other seats.
${s.temper}
THE PLAN UNDER ATTACK: ${MAIN}/${PLAN_FILE} (read it IN FULL first).
${READS}
${INPUTS}
MANDATORY CITATION RE-CHECK: before you return, re-open every file:line or log line you cite and confirm it says what you claim; set citations_rechecked accordingly and drop any attack whose evidence did not survive. An attack without evidence (a file:line at ${PIN}, a saved log line, a quoted plan line, or a quoted line of Boris's verbatim record) is not an attack.
Do NOT write any file. RETURN (StructuredOutput): seat, attacks (id like ${s.key.slice(0, 2).toUpperCase()}-1..; target = the plan item / section; claim; evidence; severity MUST = the plan would ship a defect, hide a product error, contradict Boris's verbatim words, or carry a gate that cannot fail, SHOULD, NIT; proposed_change), strongest_point, citations_rechecked. At most 8 attacks, each field under 900 characters; fewer and sharper is better.`, { agentType: 'authored-council-seat', model: 'sonnet', effort: 'high', schema: AS, phase: 'Attack', label: 'attack:' + s.key })))).filter(Boolean)
const papersJson = JSON.stringify(papers)
log('seats returned: ' + papers.length + ' of ' + SEATS.length + '; attacks: ' + papers.reduce((n, p) => n + (p.attacks || []).length, 0) + '; papers ' + papersJson.length + ' characters (passed WHOLE, no cut)')

phase('Ruling')
const ruling = await agent(`ARCHITECT RULING on a blind council's attacks (you run on opus at max effort because Fable is out of usage -- Boris, verbatim, 2026-10-02: "just so you know, we are out of fable usage so you will need to do all fable work with opus 5.5"). Harmony decides after you; your ruling is her working document.
THE PLAN: ${MAIN}/${PLAN_FILE} (read IN FULL).
THE SEAT PAPERS (${papers.length} of ${SEATS.length} seats returned; verbatim JSON, WHOLE -- ${papersJson.length} characters; if the text below does not end with a closed JSON array, STOP and return status PARTIAL saying so): ${papersJson}
${READS}
${INPUTS}
DO, IN THIS ORDER:
1. FIRST write the seat papers verbatim (pretty-printed, one section per seat) to ${PAPERS_FILE} (literal path, relative to ${MAIN}, bash heredoc).
2. For every attack: re-derive the evidence yourself at the pin or in the saved logs (never trust a seat's citation, never the plan's); verdict ACCEPT / PARTIAL / REJECT with the line that decides it. Reconcile seats that conflict. Where an outcome turns on a fact that only a run can establish, do NOT guess: it is exactly what the diagnosis stage measures -- give the ruling for EACH outcome (the decision table must be complete). Where it turns on what Boris wants and his words do not settle it, it is a BORIS QUESTION with a default.
3. Write the ruling to REPORT_FILE: 0 VERDICT; 1 FACTS RE-DERIVED; 2 ATTACK RULINGS (table: one row per attack id); 3 AMENDMENTS (numbered; each OVERRIDES the plan body); 4 FINAL STAGES + ORDER (one builder context each: the diagnosis stage with its experiments and the decision table; the fix stages conditional on its outcome; the keys fix; where S6, S5a, S5b follow; what each proves); 5 GATE ROWS changed or added (pre-registered; exact strings and bars; each row's RED arm; which rows of ${MAIN}/${R3}/ruling-bf2-delta.md section 5 they replace); 6 WHAT ONLY BORIS CAN CHECK; 7 BORIS QUESTIONS (each with a default); 8 HARMONY'S DECISIONS (each with a default); 9 SIDE FINDINGS; 10 RISKS (the strongest counterargument first).
RULES: Boris quoted only verbatim; Harmony's requirements labelled "Harmony constraint:"; Harmony constraint: no on-screen text that announces an event or a failure, and no bound control that silently does nothing; no code beyond a signature; prefer the smallest correct change; a pre-registered bar is never loosened -- it is met, or reported.
TURN BUDGET (the role stops SILENTLY at 120 turns): papers file by turn 4; a SKELETON ruling with all headings by turn 10; rewrite every ~10 turns; DONE by turn 90; if short, status PARTIAL with what is missing at the top.
REPORT_FILE: ${RULING_FILE}
RETURN: ruling_path, papers_path, status, verdict (<= 1200 characters), amendments (count), attacks_ruled (count), stages (key + one-line scope), boris_questions, harmony_decisions, facts_harmony_must_measure, strongest_counterargument.`, { agentType: 'architect', model: 'opus', effort: 'max', schema: RS, phase: 'Ruling', label: 'ruling:bf2-stops' })
const nAtt = papers.reduce((n, p) => n + (p.attacks || []).length, 0)
return { plan: { path: plan.plan_path, status: plan.status, summary: String(plan.summary || '').slice(0, 1500), forks: (plan.forks || []).map(f => ({ id: f.id, choice: String(f.choice || '').slice(0, 260), runner_up: String(f.runner_up || '').slice(0, 200) })), not_verified: (plan.not_verified || []).map(x => String(x).slice(0, 240)) }, seats: papers.map(p => ({ seat: p.seat, n: (p.attacks || []).length, must: (p.attacks || []).filter(a => a.severity === 'MUST').length, strongest: String(p.strongest_point || '').slice(0, 300) })), attacks_sent: nAtt, papers_chars: papersJson.length, ruling: ruling ? { ruling_path: ruling.ruling_path, status: ruling.status, verdict: String(ruling.verdict || '').slice(0, 1200), amendments: ruling.amendments, attacks_ruled: ruling.attacks_ruled, stages: (ruling.stages || []).map(s => ({ key: s.key, scope: String(s.scope || '').slice(0, 300) })), boris_questions: (ruling.boris_questions || []).map(x => String(x).slice(0, 400)), harmony_decisions: (ruling.harmony_decisions || []).map(x => String(x).slice(0, 300)), facts_harmony_must_measure: (ruling.facts_harmony_must_measure || []).map(x => String(x).slice(0, 300)), strongest_counterargument: String(ruling.strongest_counterargument || '').slice(0, 500) } : { failed: true } }
