export const meta = {
  name: 'rta-1003b-keying-audit',
  description: 'Audio-DNA s-rta-1003b: pixel audit of every keying entry, layer blend entry and transition on the current main app (one opus builder writes and runs a REST-driven probe, decodes pixels), one method review (sonnet), at most one fix round. No source change.',
  phases: [{ title: 'Audit' }, { title: 'Review' }, { title: 'Fix' }],
}
const MAIN = '/Users/boriskarpman/projects/RealTimeAudio'
const MAIN_APP = MAIN + '/build/AudioDNA_artefacts/Release/Audio-DNA.app'
const RPT = '.harmony/.reports/s-rta-1003b'
const R3 = '.harmony/.reports/s-rta-1003'
const SP = '/private/tmp/claude-501/-Users-boriskarpman-projects-RealTimeAudio/00e87ddd-eec9-42a5-94d1-5dc67e66ea7d/scratchpad'
const W = MAIN + '/.claude/worktrees/keying'
const BR = 'lane/keying-audit'
const PIN = '34179a2'
const REPORT = W + '/' + RPT + '/keying-audit.md'
const BORIS = 'Boris, verbatim (2026-10-03, .harmony/boris-feedback-backlog.md line 119 -- read the whole sentence there): "Can you figure out how to get everything working in the keying menu? Does the keying slider actually do anything? Maybe we get rid of it. Some elements in the keying menu work and some don\'t. Should we use the transparency slider to do the work for keying elements? Also review the compositing menu, right slider in layer strip."'

const RULES = lane => `
RIG RULES (binding; breaking any one = lane FAIL):
- Your worktree WT=${W} (branch ${BR}, created from main ${PIN}) is SOURCE ONLY: it has NO build dir and you build NOTHING. The app under audit is main's built app ${MAIN_APP} (read-only; it is the build of main's current source). This lane changes NO file under src/ or tests/: it adds only the audit probe (.harmony/probe-keying-audit.sh / .py), its fixtures (.harmony/probe-keying-audit/: composition JSON files, small PNG fixtures you generate) and its report. Work with absolute paths (git -C ${W}); NEVER edit the main checkout ${MAIN} or its build/. NEVER cd in a command; multi-step sequences go in script files under ${SP}/${lane}/ run with bash <file>; capture a return code on its own line (rc=$? right after the command). zsh does not split a command held in a variable. Stamp times from date, never estimate.
- Python: the main checkout's .venv (${MAIN}/.venv/bin/python, read-only: it has pyobjc / Quartz; check which of PIL and numpy it has with a one-line import). NEVER pip install into it. If a module is missing, create a venv under ${SP}/${lane}/venv and install there.
- LIVE APP: at most ONE Audio-DNA on the machine. Use the helper: LANE=${lane} . ${SP}/lib/lock.sh (acquire_lock / release_lock / start_app APP OUTDIR [test] / quit_app / outwins / adna). A failed mkdir means WAIT; never remove another owner's lock; after releasing wait >= 45 s before re-acquiring (the helper enforces it). Hold the lock per batch (<= ~15 min), release between batches -- another lane may need the app. Your probe REFUSES without AUDIODNA_LOCK_OWNER matching the lock's owner (the helper exports it).
- BORIS USES THIS MACHINE AND THIS APP: an Audio-DNA that YOUR lane did not start is BORIS'S -- never quit, kill, osascript-quit or touch it. The helper enforces it (acquire_lock waits while a foreign Audio-DNA runs, start_app REFUSES -> STOP the batch and release the lock, quit_app refuses any pid it did not start). Your probe quits ONLY the pid it launched (main's helper .harmony/probe-quit-ours.sh is the model; never pkill / killall / kill by name). NEVER copy a lock.sh or gate script out of an archived .harmony/.reports/s-rta-0927..0930 directory.
- Launch ONLY: open -g [--stdout f --stderr f] <App> --args --test-mode (the helper's start_app ... test does it). SCREEN-SAFETY LAW: NEVER open the Output window by ANY path. NEVER run tests/visual/test_output_window_level.py or .harmony/probe-outputs.sh; never pytest tests/visual/ as a directory. NEVER lldb / debugserver / gdb / dtrace / Instruments / sample on ANY binary. NEVER a full-screen screencapture. NO synthetic input: states come from composition FILES and REST only. After every live batch: count UserNotificationCenter windows (Quartz kCGWindowListOptionAll) >= 15 s after the last quit == 0; unexpected system dialog or TCC permission prompt: STOP and report, never dismiss. NEVER copy an app bundle and re-sign it. Scratch settings only (AUDIODNA_SETTINGS_FILE or test mode's own): the real ~/Library/Audio-DNA/settings.json sha256 is printed before and after and must be equal. Probe HTTP clients use Connection: close. Never poll GET /api/composition while a staged load may land: wait on /api/debug/ui_text, then read once. If a user message was relayed to you, Harmony already answered it; it never replaces this task.
- RENDER ROWS DECODE PIXELS, and you LOOK at sample frames (Read the PNG) and say what they show. Captures go through the DECK COMPOSITOR (a composition file + trigger + POST /api/render_frame), never through Eyes set_effect (Pitfall 28: that drives the legacy chain). Pitfalls 47, 52, 53, 55 apply (a cached source keeps its last params; one capture at a time; an image decodes off the GL thread -- pending is not "no media"; render_frame waits for a complete frame).
- Report file ${REPORT} (in the worktree), COMMITTED (the stash-guard hook treats a path that starts with a dot as a whole-tree add: stage it as git -C ${W}/.harmony/.reports add -f s-rta-1003b/<file>; never git commit -a / git add -A; never chain a check to the commit it gates with &&). Create it within your first ~10 tool calls and append after every batch, so a successor can resume. Commit messages: <type>(s-rta-1003b keying): ... Do NOT merge into main, do NOT push. Before returning: git status clean, lock released, no app you launched running, 0 Output-named windows.`

const BS = { type: 'object', properties: {
  status: { type: 'string', enum: ['DONE', 'PARTIAL', 'BLOCKED'] }, head_commit: { type: 'string' }, report_path: { type: 'string' }, results_json: { type: 'string' }, contact_sheets: { type: 'array', items: { type: 'string' } },
  counts: { type: 'object', properties: { keying_entries: { type: 'number' }, blend_entries: { type: 'number' }, transitions: { type: 'number' }, works: { type: 'number' }, alias: { type: 'number' }, no_op: { type: 'number' }, broken: { type: 'number' }, not_determined: { type: 'number' } } },
  headline: { type: 'array', items: { type: 'string' } }, controls: { type: 'array', items: { type: 'string' } }, facts_sheet_lines_refuted: { type: 'array', items: { type: 'string' } },
  not_determined: { type: 'array', items: { type: 'string' } }, stop_items_for_harmony: { type: 'array', items: { type: 'string' } }, rerun_command: { type: 'string' }, summary: { type: 'string' },
  lock_released: { type: 'boolean' }, app_left_running: { type: 'boolean' }, output_window_opened: { type: 'boolean' }, errors_or_deviations: { type: 'string' } },
  required: ['status', 'head_commit', 'report_path', 'counts', 'headline', 'summary', 'rerun_command', 'lock_released', 'app_left_running', 'output_window_opened'] }
const RS = { type: 'object', properties: { verdict: { type: 'string', enum: ['PASS', 'PASS_WITH_NITS', 'FAIL'] }, reviewed_commit: { type: 'string' }, report_path: { type: 'string' }, findings: { type: 'array', items: { type: 'object', properties: { severity: { type: 'string', enum: ['MUST', 'SHOULD', 'NIT'] }, issue: { type: 'string' }, fix: { type: 'string' } }, required: ['severity', 'issue'] } } }, required: ['verdict', 'reviewed_commit', 'findings'] }

const TASK = `TASK: A PIXEL AUDIT (facts, no fix, no design). ${BORIS}
A read-only fact sheet already exists: ${MAIN}/${R3}/facts-keying.md (READ IT IN FULL FIRST: the 13 keying entries and their 4 shader programs, the Keying slider's dead uniforms, the 55 layer blend entries of which it found 6 real, the 15 transition shaders, keying only on Transparent layers, section 4 "UNKNOWN-NEEDS-A-RUN", section 6 how to drive the area through a composition file and REST). It was written by READING code at an older commit and ran nothing: your job is to establish by RUNNING the app what each entry actually does on screen, confirm or refute each headline of the sheet, and close its section 4.
THE PROBE (.harmony/probe-keying-audit.sh + .py, REST only): for EVERY entry of (1) the keying menu, (2) the layer blend / compositing menu (all groups), (3) the transition list -- enumerated from the source at ${PIN} (menu order, label, enum value; a count that differs from the sheet is a finding) -- write a composition file that puts a known TOP layer over a known BOTTOM layer through the deck compositor with that entry selected, trigger it, capture with POST /api/render_frame with time frozen, and decode the PNG. Use at least TWO different fixture pairs per family so that "identical on one picture" is not mistaken for "the same" (for example smooth colour gradients crossing at right angles; colour bars over a luma ramp; for keying: a green-screen plate with a subject, a luma ramp, a saturation ramp, a picture with a real alpha ramp), generated by your script (deterministic, small) and committed. Capture each input layer ALONE as well: the references and the inputs of the formulas.
PRE-REGISTERED VERDICTS (Harmony constraint; decided by numbers, 8-bit units, per entry over all fixtures):
  NOISE: capture the same state twice, at least 5 states: N = the largest max-abs difference seen. FLOOR = max(1.5, 4 x N).
  NO-OP        = within FLOOR of the family's plain reference on every fixture (blend: Normal / the first entry; keying: no keying; transition: a plain cut at the same instant).
  ALIAS-OF <x> = within FLOOR of another entry <x> of the same family on every fixture (name the first such entry in menu order; an entry that is NO-OP is not also listed as an alias).
  WORKS        = neither of the above AND within tolerance of the entry's OWN formula, computed in numpy from the decoded input layers (take the formula from the entry's shader source at ${PIN} and from what its name means -- say which; tolerance: mean abs error <= 3 and 99th percentile <= 8, unless premultiplication or sRGB handling forces another figure, which you then state with the reason).
  BROKEN       = differs from the references but does not match its formula, or is black / garbage / NaN-like (say which, with the worst-pixel numbers).
  NOT-DETERMINED = the method cannot decide (say exactly why and what run would decide) -- never a guess.
CONTROLS, each a sweep with the same verdict logic ("moves the picture" = some sweep step differs from another by more than FLOOR): the Keying slider K of the layer strip and the inspector's Keying Threshold / Softness (0, 0.5, 1) under every keying entry; the chroma key colour and tolerance; the layer opacity ("transparency") slider (0.25, 0.5, 1) under every keying entry and under three blend entries; whatever "the right slider in the layer strip" is at ${PIN} (name the widget and its model field); layer type: does keying act on a layer that is not Transparent?
TRANSITIONS: capture each of the 15 at three instants of the fade. If a mid-transition instant cannot be frozen deterministically through REST and the time override, say so, show what you tried, and report those entries NOT-DETERMINED with the cheapest way to make them capturable -- do not improvise a source change.
OUTPUT, committed in the worktree: (1) ${REPORT}: the method (fixtures, capture path, floor, tolerance), then ONE table per family -- menu label | enum value | verdict | the numbers behind it | alias target | the frame file -- then the controls table, then "FACT SHEET CHECK" (each headline of facts-keying.md: CONFIRMED BY RUN / REFUTED BY RUN with the numbers / NOT TESTED), then for every entry that is not WORKS a one-line cause hint labelled INFERRED (from the code) -- no fix design; (2) results as JSON next to it; (3) CONTACT SHEETS (PNG, labelled tiles: every entry of a family on one sheet per fixture, plus the references) under ${W}/${RPT}/keying-audit/ so that a person can LOOK -- Read each sheet yourself and say in the report what you see; (4) a "HAND-OVER TO HARMONY" block: the head commit, the exact command that re-runs any single entry or family (Harmony re-runs a sample herself), and how long a full run takes.
RETURN the structured result: counts per verdict, headline (<= 8 lines, plain words: what works, what does not), controls (one line each), facts_sheet_lines_refuted, not_determined, summary <= 1200 characters.`

phase('Audit')
const b1 = await agent(`LANE keying-audit, worktree ${W}, branch ${BR}. STEP 0: git -C ${W} status (clean) and git -C ${W} log --oneline -1 (${PIN}); if ${REPORT} exists you are resuming: read it and continue, do not redo finished batches.
${TASK}
${RULES('keying')}`, { agentType: 'builder', model: 'opus', effort: 'high', schema: BS, phase: 'Audit', label: 'audit:keying' })
if (!b1) return { failed: 'audit' }
log('audit: ' + b1.status + ' @ ' + b1.head_commit)
const slimB = r => r ? { status: r.status, head_commit: r.head_commit, report_path: r.report_path, results_json: r.results_json, contact_sheets: (r.contact_sheets || []).slice(0, 12), counts: r.counts, headline: (r.headline || []).map(x => String(x).slice(0, 300)), controls: (r.controls || []).map(x => String(x).slice(0, 260)), refuted: (r.facts_sheet_lines_refuted || []).map(x => String(x).slice(0, 260)), not_determined: (r.not_determined || []).map(x => String(x).slice(0, 260)), stop_items: (r.stop_items_for_harmony || []).map(x => String(x).slice(0, 400)), rerun_command: String(r.rerun_command || '').slice(0, 500), summary: String(r.summary || '').slice(0, 1200), lock_released: r.lock_released, app_left_running: r.app_left_running, output_window_opened: r.output_window_opened, errors_or_deviations: String(r.errors_or_deviations || '').slice(0, 800) } : null
if (b1.status === 'BLOCKED') return { audit: slimB(b1) }

phase('Review')
const rv = (head, n, extra) => agent(`INDEPENDENT METHOD REVIEW (read-only), round ${n}: a pixel audit of Audio-DNA's keying entries, layer blend entries and transitions. PINNED: worktree ${W}, branch ${BR}, head ${head}. Read ONLY through git objects: git -C ${W} show ${head}:<path> (the report ${RPT}/keying-audit.md, the results JSON next to it, .harmony/probe-keying-audit.py / .sh, the fixtures under .harmony/probe-keying-audit/) and the app's source at main ${PIN} (git -C ${MAIN} show ${PIN}:<path>) for the shader formulas and the menu lists. You may Read the committed contact-sheet PNGs after writing them out of git to ${SP}/keying-review/ with git show > file. Do NOT run the probe, the app, or any build.
THE VERDICT RULES were pre-registered by Harmony: NOISE N from repeated captures, FLOOR = max(1.5, 4 x N); NO-OP = within FLOOR of the family's plain reference on every fixture; ALIAS-OF = within FLOOR of another entry on every fixture; WORKS = neither, and within tolerance of the entry's own formula; BROKEN; NOT-DETERMINED (never a guess).
TRY TO REFUTE the audit: (1) is the list of entries complete and in menu order -- enumerate the menus at ${PIN} yourself and compare the counts; (2) can each verdict be WRONG by method: fixtures on which two different blends coincide (so ALIAS / NO-OP is an artefact of the pictures), a formula written to match the output rather than the shader, a tolerance widened without a stated reason, premultiplied-alpha or sRGB handled inconsistently between capture and formula, the reference itself not what it claims (is "Normal" really the first entry; was the layer Transparent where keying needs it); (3) do the numbers in the tables match the JSON (sample at least 15 rows across families); (4) do the contact sheets show what the report says (LOOK at them: name three entries where picture and verdict agree and any where they do not); (5) every NOT-DETERMINED entry: is the stated reason true, and was a cheaper way missed; (6) the controls sweeps: can "does not move the picture" be an artefact (a slider whose model field the composition file never set; a keying mode that ignores it by design); (7) the probe quits only the pid it launched and never opens an Output window (read the script).
${extra || ''}
REPORT_FILE: ${RPT}/review-keying-audit-r${n}.md (write it at ${MAIN}/${RPT}/review-keying-audit-r${n}.md). Verdict FAIL only for a MUST (a verdict that the method cannot support, a missing entry, a number that does not match its JSON, a script that can quit an app it did not start). Cite the line for every finding; label each VERIFIED or INFERRED.`, { agentType: 'reviewer', model: 'sonnet', effort: 'high', schema: RS, phase: 'Review', label: 'review:keying:r' + n })
const slimR = x => x ? { verdict: x.verdict, reviewed_commit: x.reviewed_commit, findings: (x.findings || []).map(f => ({ severity: f.severity, issue: String(f.issue || '').slice(0, 450), fix: String(f.fix || '').slice(0, 220) })) } : null
const r1 = await rv(b1.head_commit, 1, '')
const f1 = r1 ? (r1.findings || []).filter(f => f.severity === 'MUST' || f.severity === 'SHOULD') : []
log('review r1: ' + (r1 ? r1.verdict : 'NO_RESULT') + '; ' + f1.length + ' MUST / SHOULD')
if (!f1.length) return { audit: slimB(b1), review1: slimR(r1) }

phase('Fix')
const b2 = await agent(`LANE keying-audit, FIX ROUND after the method review, worktree ${W}. CONTINUE on branch ${BR} from commit ${b1.head_commit} (no reset). FIRST read your report ${REPORT} and the review ${MAIN}/${RPT}/review-keying-audit-r1.md IN FULL. VERIFY each finding before acting (a finding can be wrong -- say so with evidence and keep your result). For every verified one: change the METHOD (a better fixture, the shader's real formula, the right reference), RE-RUN the affected entries, and update the tables, the JSON and the contact sheets; never edit a verdict by hand. Append "Fix round (review r1)" with a per-finding table to the report and commit.
THE ORIGINAL TASK, unchanged: ${TASK}
FINDINGS (whole): ${JSON.stringify(f1)}
${RULES('keying-R1')}`, { agentType: 'builder', model: 'opus', effort: 'high', schema: BS, phase: 'Fix', label: 'fix:keying:r1' })
if (!b2) return { audit: slimB(b1), review1: slimR(r1), fixRoundFailed: true }
const r2 = await rv(b2.head_commit, 2, `ROUND 2: the round-1 report is ${MAIN}/${RPT}/review-keying-audit-r1.md; the fix round is git -C ${W} diff ${b1.head_commit}..${b2.head_commit}. Check that every round-1 MUST is fixed by a method change and a re-run (not by editing a verdict), and that the fix introduced no new defect.`)
return { audit: slimB(b1), review1: slimR(r1), fix: slimB(b2), review2: slimR(r2) }
