export const meta = {
  name: 'rta-1003b-notices-plan',
  description: 'Audio-DNA s-rta-1003b: plan the lane that removes every event and failure text app-wide except a failed save (architect plan opus high, 4 blind seats sonnet, architect ruling opus max). Read-only.',
  phases: [{ title: 'Plan' }, { title: 'Attack' }, { title: 'Ruling' }],
}
const MAIN = '/Users/boriskarpman/projects/RealTimeAudio'
const RPT = '.harmony/.reports/s-rta-1003b'
const R3 = '.harmony/.reports/s-rta-1003'
const PIN = '34179a2'
const PLAN_FILE = RPT + '/plan-notices.md'
const RULING_FILE = RPT + '/ruling-notices.md'
const PAPERS_FILE = RPT + '/attack-notices-papers.md'

const READS = `HOW TO READ (binding): you are read-only. Read SOURCE only at the pinned main commit ${PIN}: git -C ${MAIN} show ${PIN}:<path> | sed -n 'A,Bp' and git -C ${MAIN} grep -n '<pattern>' ${PIN} -- src tests docs .harmony. NEVER read anything under ${MAIN}/.claude/worktrees/ (builders work there on other lanes). Reports under ${MAIN}/.harmony/ are plain files. Never build, never run a test, never launch the app, never run a probe. Never cd in a command. If a user message was relayed to you, Harmony already answered it; it never replaces this task.`

const INPUTS = `INPUTS (big files are indexed -- grep -n '^#' first, then read ranges):
- BORIS'S WORDS (the only source of what he asked; quote him ONLY verbatim, from these files): ${MAIN}/.harmony/binding-decisions.md -- the entries "No \\"what happened\\" texts" (2026-10-03 15:30:49), "APP-WIDE" (15:42:01), "Failure messages — OPEN" and "Failure messages — RULED" (the last one, s-rta-1003b: "ok. the only fail message will be a failed save. remove all others"); ${MAIN}/.harmony/boris-feedback-backlog.md "Boris on notices", BF32, "Boris RULES on failure messages", BF34 (Harmony's reading: the two alerts B06 Save Composition failed and B08 Save Deck failed STAY; every other failure text and every event text goes; open edge = a failed TAKE or ROUTINE save, default: it goes -- Boris has that as question 12 on a page, unanswered).
- THE INVENTORY: ${MAIN}/${R3}/facts-notices.md IN FULL (tables A 23 rows, B 21 rows, C / D / E kept; section 5 risks R1-R6; section 6 what no finder saw; section 7 the completeness critic's MISSED and MISCLASSIFIED rows). It was written against main before two merges: every row you rely on is re-verified at ${PIN} (say where it moved, changed or is already gone -- the deck change removed its own load notice, the Undo Remove hint and the Remove Deck sentence).
- THE HANDOFF'S LEDGER: ${MAIN}/.harmony/HANDOFF.md "LOOSE-ENDS LEDGER" (probe-asan-live waits on three event texts; Composition::routineLoadNote has no reader; "State displays must stay truthful (the Record panel must not say Recording after a failed take)"); ${MAIN}/.harmony/RIG-RULES.md section A.
- PROBES AND TESTS that read on-screen texts at ${PIN}: git grep for ui_text, file_label, noticeLabel, warningText, routineNotice, "Loaded", "Saved" over .harmony/*.sh .harmony/*.py tests/.
- PROJECT RULES: CLAUDE.md at ${PIN} (UI patterns; Pitfalls 41, 57, 59 on model-driven widgets and timed repaints), docs/claude/recording.md "Surfaces", docs/claude/integration.md.
- THE LANES AHEAD OF THIS ONE on main: the sync dial (bf2: TopBar, ApiServer, MainComponent providers; it adds no event text) and the transport + undo-live lane (${MAIN}/${RPT}/ruling-transport.md: MainComponent trigger handlers, UndoService, ClipInspector, LayerStrip; it adds no event text).`

const ITEMS = `ITEMS TO PLAN. For each: what is on screen TODAY at ${PIN} (file:line), Boris's words, the forks, the choice, why the runner-up loses, the change by file / function (no code), tests RED-first + mutants, the gate row.
N1 THE LIST, RE-VERIFIED. Every row of tables A and B (and the critic's MISSED rows) at ${PIN}: still there / moved / already gone; its widget chain and every writer; whether a REST field, a test or a probe reads it. The two rows that STAY (B06, B08) are stated exactly (title, text, when shown, test-mode behaviour) so that nothing else hides behind "a failed save".
N2 THE EDGE ROWS. Rows the inventory marks EDGE or that read like a state: B14 ("No audio device found ..." / "No wired mic found ..."), B19's third line ("Replaying with the take's audio ..."), B21 (the red "!" on a routine pad and its tooltip prefix), A-rows that show a mode rather than an event, the progress texts. For each: is it an event / failure text (goes) or a state display (stays -- perhaps in a proper state widget)? Decide by Boris's words; where they do not settle it, it is a question for him WITH a default.
N3 STATE DISPLAYS STAY TRUTHFUL. After the removal, which state display would LIE or go blank: the Record panel's status line after a take that failed to start or broke mid-take (inventory R2: it keeps reading "Recording"), the file label after a failed load, the audio source line with no device, a routine pad after an incomplete run. For each: the truthful state it must show (a state, never an announcement) and the model fact it reads. Harmony constraint: a state display shows what IS; it never says what just happened.
N4 SAVES OTHER THAN A SHOW OR A DECK. A take (B17, B18), a routine (B20), the settings / venue list: under the default they show nothing. Say what he then sees when one fails, and specify the small delta that keeps a message for them should Boris answer the other way (so the build does not have to be redone).
N5 CLEANLY AND COMPLETELY. For every removed text: the widget, members, timers, layout slots, setters, call sites, strings, the tests that assert it (retired BY NAME; no other test disappears), docs lines, ui_text / REST fields that carried it. What stays: the behaviour behind each text, the app-log lines (logLine / std::cerr twins), REST lastError fields, decision dialogs, tooltips, state displays. What the freed space becomes (the Record tab's notice lines, the yellow line): this is a VISUAL change.
N6 PROBES AND TESTS THAT WAIT ON A TEXT. Every probe row and test that reads or waits on a removed text, BY NAME (probe-asan-live's three waits, probe-btguard's rows, probe-boxes rows, probe-ui-files-rename, the recorder tests that assert notices ...): the model fact or REST field each moves to, done FIRST (a stage before any text is removed), with RED / GREEN on the frozen pre-lane app so a moved row still fails for its remaining clauses.
N7 KEEPING THEM OUT. Is a lint possible that can fail when a new event or failure text is added -- e.g. an allowlist of setFileLabel writers, of showMessageBoxAsync / alert call sites (decision dialogs + the two save-failed alerts), of Label members fed by a notify lambda? State exactly what it catches and what it cannot (a lint that pins names while a new name walks past is not a gate).
N8 HARMONY'S GATE LIST (pre-registered; exact strings and bars; each row with its RED arm = the frozen pre-lane app): unit suites, the lint(s), live rows through REST (every removed text absent from GET /api/debug/ui_text AND from a dump of every text widget, in the situations that used to raise it: a load, a save, a failed load, a refused record, a device drop where it can be driven without hardware; the two save-failed alerts still raised by a save into an unwritable path -- in production mode, since test mode suppresses them: say how that is driven safely with scratch files and without leaving a modal box on Boris's screen), and the VISUAL WORK GATE for the Record tab and the top rows: states, measurable bars from a dump, questions for five critic seats (visual-design, UX, graphic-design, logic, interaction-logic).
N9 STAGES + ORDER. One builder context each. This lane edits MainComponent, RecordPanel, TopBar-adjacent rows -- files the sync dial and the transport lane also edit. Should it build before the transport lane (it is removal-only) or after it; what a re-base stage re-reads. Give the order you recommend and the strongest case for the other.
N10 DOCS, WHAT ONLY BORIS CAN CHECK (do -> expect -> what wrong looks like), QUESTIONS FOR BORIS (plain words; each with a default; only what is genuinely his).`

const PS = { type: 'object', properties: { plan_path: { type: 'string' }, status: { type: 'string', enum: ['DONE', 'PARTIAL'] }, summary: { type: 'string' }, rows_changed_since_inventory: { type: 'array', items: { type: 'string' } }, forks: { type: 'array', items: { type: 'object', properties: { id: { type: 'string' }, choice: { type: 'string' }, runner_up: { type: 'string' } }, required: ['id', 'choice'] } } }, required: ['plan_path', 'status', 'summary', 'forks'] }
const AS = { type: 'object', properties: { seat: { type: 'string' }, attacks: { type: 'array', items: { type: 'object', properties: { id: { type: 'string' }, target: { type: 'string' }, claim: { type: 'string' }, evidence: { type: 'string' }, severity: { type: 'string', enum: ['MUST', 'SHOULD', 'NIT'] }, proposed_change: { type: 'string' } }, required: ['id', 'target', 'claim', 'evidence', 'severity'] } }, strongest_point: { type: 'string' }, citations_rechecked: { type: 'boolean' } }, required: ['seat', 'attacks', 'strongest_point', 'citations_rechecked'] }
const RS = { type: 'object', properties: { ruling_path: { type: 'string' }, papers_path: { type: 'string' }, status: { type: 'string', enum: ['DONE', 'PARTIAL'] }, verdict: { type: 'string' }, amendments: { type: 'number' }, attacks_ruled: { type: 'number' }, stages: { type: 'array', items: { type: 'object', properties: { key: { type: 'string' }, scope: { type: 'string' } }, required: ['key', 'scope'] } }, boris_questions: { type: 'array', items: { type: 'string' } }, harmony_decisions: { type: 'array', items: { type: 'string' } }, facts_harmony_must_measure: { type: 'array', items: { type: 'string' } }, strongest_counterargument: { type: 'string' } }, required: ['ruling_path', 'status', 'verdict', 'amendments', 'attacks_ruled', 'stages'] }

phase('Plan')
const plan = await agent(`PLAN AUTHORING (architect) -- Audio-DNA, the NOTICES lane: remove every on-screen text that announces an event or reports a failure, app-wide, except a failed save. You author the position; a blind council attacks it; an architect ruling follows; Harmony decides.
GOAL: Boris ruled it in his own words (read them in the files named below). The app must show what IS, never what just happened; the only failure message left is a failed save. Plan the removal so that it is clean and complete, no state display lies afterwards, every probe and test that leaned on a removed text stands on a model fact first, and one gate list proves it.
${READS}
${INPUTS}
${ITEMS}
OUTPUT: write the plan to REPORT_FILE (literal path below, relative to ${MAIN}; bash heredoc to exactly that path). Sections: 1 GOAL; 2 ESTABLISHED FACTS (ONLY lines verified at ${PIN}, each with file:line; anything else labelled INFERRED or ASSUMED where used); 3 ITEMS N1-N7; 4 STAGES + ORDER (N9); 5 HARMONY'S GATE LIST (N8); 6 DOCS; 7 WHAT ONLY BORIS CAN CHECK; 8 QUESTIONS FOR BORIS; 9 RISKS (the strongest counterargument first; the cheapest refuting test for each choice).
RULES OF THE DOCUMENT: Boris is quoted ONLY verbatim; anything Harmony requires is written as "Harmony constraint:". No code blocks longer than a signature. UI rules of the project hold (model-driven widgets, no timer repaint of the whole window, ResettableSlider, menus async). Prefer the smallest change that is correct; say what is NOT in this lane (an "unsaved changes" mark, new state widgets nobody asked for).
TURN BUDGET (the architect role stops SILENTLY at 120 turns): a SKELETON of the plan file with all headings by your turn 8; rewrite it with what you have every ~10 turns; DONE by turn 90; if short, status PARTIAL with what is missing at the top.
REPORT_FILE: ${PLAN_FILE}
RETURN: plan_path, status, summary <= 1500 characters, rows_changed_since_inventory, forks (id, choice, runner_up).`, { agentType: 'architect', model: 'opus', effort: 'high', schema: PS, phase: 'Plan', label: 'plan:notices' })
if (!plan) return { failed: 'plan' }
log('plan: ' + plan.status + ' -> ' + plan.plan_path)

phase('Attack')
const SEATS = [
  { key: 'stage-operator', temper: 'You are the STAGE OPERATOR: Boris performs live with this app. Attack what he loses and what he keeps: a removed text whose absence leaves him blind at a moment that costs him the show (a take that is not recording, a file that did not load, a dead input) with no state display covering it; a text that stays although his words remove it; a "state display" that is an announcement in disguise; a save-failed alert that would no longer appear in a case he would call a failed save; a Boris check he cannot perform; a question that is not his or lacks a default.' },
  { key: 'state-truth', temper: 'You are the STATE-TRUTH SKEPTIC: once the announcements are gone the remaining displays must be true at every moment. Attack N2, N3, N4: a display that keeps showing the old state after a failure (the Record status line, the file label, a routine pad, the source line); a state the plan derives from a field that is not updated on the failure path (read the writers at the pin); a model-driven widget that would need a timer repaint of the whole window; an edge row classified by convenience rather than by what it shows.' },
  { key: 'gates', temper: 'You are the GATE PROSECUTOR: a test that cannot fail is not a test. Attack every test, lint, bar and gate string: a "text absent" row that passes because the situation that raised the text was never produced; a row that reads five strings while the app has many text widgets; a lint that pins identifiers while a new name walks past; a moved probe wait that is already true before the action; a save-failed row that cannot be driven without leaving a modal box on screen; a retired test not listed by name; a RED arm that does not exist on the frozen app.' },
  { key: 'completeness', temper: 'You are the COMPLETENESS AUDITOR: Boris said "cleanly and completely". Attack what is left behind and what is over-removed: a writer of a removed text the plan did not list (grep the pin: setFileLabel, notify lambdas, showMessageBoxAsync, AlertWindow, Label::setText with a literal, tooltips that report an event); a dead member, timer, layout slot or string left in place; a REST field or app-log line removed although it is not on screen; a decision dialog or tooltip removed although his words keep it; work that belongs to another lane; a stage order that leaves the tree not building.' },
]
const papers = (await parallel(SEATS.map(s => () => agent(`BLIND COUNCIL SEAT "${s.key}" -- attack ONE plan from ONE temperament. You do not see the other seats.
${s.temper}
THE PLAN UNDER ATTACK: ${MAIN}/${PLAN_FILE} (read it IN FULL first).
${READS}
${INPUTS}
MANDATORY CITATION RE-CHECK: before you return, re-open every file:line you cite at the pin and confirm it says what you claim; set citations_rechecked accordingly and drop any attack whose evidence did not survive. An attack without evidence (a file:line at ${PIN}, a quoted plan line, or a quoted line of Boris's verbatim record) is not an attack.
Do NOT write any file. RETURN (StructuredOutput): seat, attacks (id like ${s.key.slice(0, 2).toUpperCase()}-1..; target = the plan item / section; claim; evidence; severity MUST = the plan would ship a defect, leave Boris blind where a state display must speak, contradict his verbatim words, or carry a gate that cannot fail, SHOULD, NIT; proposed_change), strongest_point, citations_rechecked. At most 8 attacks, each field under 900 characters; fewer and sharper is better.`, { agentType: 'authored-council-seat', model: 'sonnet', effort: 'high', schema: AS, phase: 'Attack', label: 'attack:' + s.key })))).filter(Boolean)
const papersJson = JSON.stringify(papers)
log('seats returned: ' + papers.length + ' of ' + SEATS.length + '; attacks: ' + papers.reduce((n, p) => n + (p.attacks || []).length, 0) + '; papers ' + papersJson.length + ' characters (passed WHOLE, no cut)')

phase('Ruling')
const ruling = await agent(`ARCHITECT RULING on a blind council's attacks (you run on opus at max effort because Fable is out of usage -- Boris, verbatim, 2026-10-02: "just so you know, we are out of fable usage so you will need to do all fable work with opus 5.5"). Harmony decides after you; your ruling is her working document.
THE PLAN: ${MAIN}/${PLAN_FILE} (read IN FULL).
THE SEAT PAPERS (${papers.length} of ${SEATS.length} seats returned; verbatim JSON, WHOLE -- ${papersJson.length} characters; if the text below does not end with a closed JSON array, STOP and return status PARTIAL saying so): ${papersJson}
${READS}
${INPUTS}
DO, IN THIS ORDER:
1. FIRST write the seat papers verbatim (pretty-printed, one section per seat) to ${PAPERS_FILE} (literal path, relative to ${MAIN}, bash heredoc).
2. For every attack: re-derive the evidence yourself at the pin (never trust a seat's citation, never the plan's); verdict ACCEPT / PARTIAL / REJECT with the line that decides it. Reconcile seats that conflict (the stage operator wants a signal kept; the completeness auditor wants it gone: Boris's verbatim words decide, and where they do not, it is a question for him WITH a default). Where an outcome turns on a fact only a run can establish, list it in facts_harmony_must_measure with the cheapest discriminating test and give the ruling for each outcome.
3. Write the ruling to REPORT_FILE: 0 VERDICT; 1 FACTS RE-DERIVED; 2 ATTACK RULINGS (table: one row per attack id); 3 AMENDMENTS (numbered; each OVERRIDES the plan body); 4 FINAL BUILD STAGES + ORDER; 5 FINAL CONSOLIDATED GATE LIST (pre-registered; the full list, not a diff; each row's RED arm), incl. the VISUAL WORK GATE's states, measurable bars and the five critic seats' questions; 6 THE FINAL TABLE: every on-screen text of classes A and B at ${PIN}, one line each: GOES / STAYS (and why) / BECOMES A STATE DISPLAY (which, reading what); 7 WHAT ONLY BORIS CAN CHECK; 8 BORIS QUESTIONS (each with a default); 9 HARMONY'S DECISIONS (each with a default); 10 SIDE FINDINGS; 11 RISKS (the strongest counterargument first); 12 HOW A BUILDER READS THE PLAN (what is built from the plan body, what from the ruling).
RULES: Boris quoted only verbatim; Harmony's requirements labelled "Harmony constraint:"; Harmony constraint: a state display shows what IS and never what just happened; no code beyond a signature; prefer the smallest correct change; a pre-registered bar is never loosened -- it is met, or reported.
TURN BUDGET (the role stops SILENTLY at 120 turns): papers file by turn 4; a SKELETON ruling with all headings by turn 10; rewrite every ~10 turns; DONE by turn 90; if short, status PARTIAL with what is missing at the top.
REPORT_FILE: ${RULING_FILE}
RETURN: ruling_path, papers_path, status, verdict (<= 1200 characters), amendments (count), attacks_ruled (count), stages (key + one-line scope), boris_questions, harmony_decisions, facts_harmony_must_measure, strongest_counterargument.`, { agentType: 'architect', model: 'opus', effort: 'max', schema: RS, phase: 'Ruling', label: 'ruling:notices' })
const nAtt = papers.reduce((n, p) => n + (p.attacks || []).length, 0)
return { plan: { path: plan.plan_path, status: plan.status, summary: String(plan.summary || '').slice(0, 1500), rows_changed: (plan.rows_changed_since_inventory || []).map(x => String(x).slice(0, 220)), forks: (plan.forks || []).map(f => ({ id: f.id, choice: String(f.choice || '').slice(0, 260), runner_up: String(f.runner_up || '').slice(0, 200) })) }, seats: papers.map(p => ({ seat: p.seat, n: (p.attacks || []).length, must: (p.attacks || []).filter(a => a.severity === 'MUST').length, strongest: String(p.strongest_point || '').slice(0, 300) })), attacks_sent: nAtt, papers_chars: papersJson.length, ruling: ruling ? { ruling_path: ruling.ruling_path, status: ruling.status, verdict: String(ruling.verdict || '').slice(0, 1200), amendments: ruling.amendments, attacks_ruled: ruling.attacks_ruled, stages: (ruling.stages || []).map(s => ({ key: s.key, scope: String(s.scope || '').slice(0, 300) })), boris_questions: (ruling.boris_questions || []).map(x => String(x).slice(0, 400)), harmony_decisions: (ruling.harmony_decisions || []).map(x => String(x).slice(0, 300)), facts_harmony_must_measure: (ruling.facts_harmony_must_measure || []).map(x => String(x).slice(0, 300)), strongest_counterargument: String(ruling.strongest_counterargument || '').slice(0, 500) } : { failed: true } }
