export const meta = {
  name: 'rta-1003b-transport-plan',
  description: 'Audio-DNA s-rta-1003b: plan the transport + undo-live lane (every fire restarts, column re-fire, playhead drag, BPM and beats boxes, Undo never changes what is live): architect plan (opus high), 5 blind seats (sonnet), architect ruling (opus max). Read-only.',
  phases: [{ title: 'Plan' }, { title: 'Attack' }, { title: 'Ruling' }],
}
const MAIN = '/Users/boriskarpman/projects/RealTimeAudio'
const RPT = '.harmony/.reports/s-rta-1003b'
const R3 = '.harmony/.reports/s-rta-1003'
const OLD = '.harmony/.reports/s-rta-1002b'
const PIN = '34179a2'
const PLAN_FILE = RPT + '/plan-transport.md'
const RULING_FILE = RPT + '/ruling-transport.md'
const PAPERS_FILE = RPT + '/attack-transport-papers.md'

const READS = `HOW TO READ (binding): you are read-only. Read SOURCE only at the pinned main commit ${PIN}: git -C ${MAIN} show ${PIN}:<path> | sed -n 'A,Bp' and git -C ${MAIN} grep -n '<pattern>' ${PIN} -- src tests docs. NEVER read anything under ${MAIN}/.claude/worktrees/ (a builder is working there on another lane, the sync dial). Reports under ${MAIN}/${R3}/, ${MAIN}/${OLD}/ and ${MAIN}/.harmony/ are plain files. Never build, never run a test, never launch the app, never run a probe. Never cd in a command. If a user message was relayed to you, Harmony already answered it; it never replaces this task.`

const INPUTS = `INPUTS (read what your part needs; big files are indexed -- grep -n '^#' first, then read ranges):
- BORIS'S WORDS (the only source of what he asked; quote him ONLY verbatim): ${MAIN}/.harmony/boris-feedback-backlog.md from the heading "Boris feedback of 2026-10-03" to the end (his whole message verbatim, then the items BF11..BF33, his answers to the 14 clarifying questions with each question as asked, the follow-up on answer 7, his answers A-E, BF31, his words on notices) and ${MAIN}/.harmony/binding-decisions.md from the first "## 2026-10-03" heading to the end; ${MAIN}/BORIS_DECISIONS.md (the 2026-10-03 sections and "Decks are boxes of clips"). The items of this lane: BF11, BF15, BF25, BF31, clarifying answers 2, 5, 6, 7 and the follow-up on answer 7, answers A-E where they speak of Undo. Related rules that bind what you may put on screen: BF32 (no text that announces what has happened), BF21 (a clip's length is set in beats), BF33 (an Edit menu -- another lane builds it).
- THE FACT SHEET: ${MAIN}/${R3}/facts-transport.md IN FULL (written at lane commit a7491d4, BEFORE the deck change merged with five fix stages: every line you rely on is re-verified at ${PIN}; say where it moved or changed).
- WHAT THE DECK CHANGE PINNED: ${MAIN}/${R3}/ruling-bf9b-merge.md and ${MAIN}/${OLD}/ruling-bf9b.md -- the C3 "resume" contract, probe row K10 (ii), unit case T6h (Undo of a Load Deck that added layers stops its clips), the trigger-undo tests; the probes .harmony/probe-boxes*.sh at ${PIN}.
- THE PROJECT'S RULES: CLAUDE.md at ${PIN} ("Transport state", the sacred rules, the UI patterns) and docs/claude/pitfalls.md entries 2, 7, 33, 35, 41, 42, 48, 53, 55, 56, 57, 59, 60, 62, 63, 64, 67; docs/claude/performance-controls.md; docs/claude/recording.md where a routine or a take fires a clip.
- THE OTHER LANES this one meets: the sync dial (lane bf2, building now: TopBar, ApiServer routes, MainComponent providers, BeatLead in the analysis thread -- plan ${MAIN}/${R3}/plan-bf2-delta.md section 3 item B6 for what lands in the top bar); the bars lane (bf7: ${MAIN}/${R3}/facts-quantize-units.md); the Timeline lane (bf6); ui-polish + the Edit menu (BF33).`

const ITEMS = `ITEMS TO PLAN. For each: what the app does TODAY at ${PIN} (verified, file:line); what Boris asked (verbatim); every defensible reading where his words leave a fork, the choice, why the runner-up loses; the change by file / function (no code); RED-first tests and mutants; the pre-registered gate row.
T1 EVERY FIRE RESTARTS A VIDEO. A clip fired again -- after it was replaced on its layer, or while it is the layer's playing clip -- starts from its beginning. Enumerate EVERY path that fires a clip (cell click, column fire, keyboard / MIDI / OSC / REST bindings in each of the 3 targeting modes, piano / momentary mode and its release, a routine's replay, the take recorder's replay, Autopilot / structural scene triggering, beat-snapped (quantized) release, a deck switch -- which fires nothing) and say for each what "restart" means and what stays untouched (a paused clip? an image sequence? a procedural or MilkDrop source that has no start? a clip that is crossfading in?). Which state decides resume today (hasBeenTriggered, the C3 contract) and what becomes of it.
T2 A COLUMN RE-FIRE RESTARTS ITS VIDEOS (BF11): firing the column that already plays. One rule with T1 or its own? What happens to layers whose clip in that column is empty.
T3 THE PLAYHEAD DRAG (BF25): after the drop the clip plays on from the drop point at the same speed and does not jump. Find the cause of today's jump at ${PIN} (the decode ring pick, the clock re-base, the direction / reverse cache, the run seek -- Pitfalls 56, 62, 64), in every transport mode the fact sheet lists (free-running, BPM-synced, reverse, ping-pong, one-shot), and what the drag does WHILE the mouse is down.
T4 A BPM-SYNCED CLIP (BF15, answers 5, 6, 7 and the follow-up): a BPM box and a beats box with x2 and /2; every clip's BPM box starts at 120. The model (which fields exist today, which are new, how they serialize, what an OLD show loads as), the maths that turns (file length, BPM box, beats box, the show's current BPM) into a playback speed, what follows the tempo and when (Pitfalls 42, 48: a beat clock integrates totalBeatCount + beatPhase), what the "automatic length" is, how x2 and /2 behave at the limits, and the widgets (ResettableSlider / number-box rules, right-click reset, the model-driven refresh of Pitfalls 41 / 59, no timer repaint of the whole window). This part is a VISUAL deliverable.
T5 UNDO NEVER CHANGES WHAT IS LIVE (BF31): Cmd+Z changes nothing that is live in the layer strip; it undoes everything else. Enumerate every Undo command at ${PIN} (UndoService, DeckCommands and the rest) and classify: (a) today it changes what plays (a fired clip recorded as an Undo step; Undo of a Load Deck that added layers; Undo of Remove Layer / Add Layer / Clear Clips / Remove Column / a clip replace on a playing cell ...), (b) it never does. For each (a): what Undo does after this lane, what Redo does, and what "live" means precisely (the playing clip of each layer? its transport position? its opacity / effects?). Where "keep it playing" and "undo the structure" collide (the layer the clip plays on is the thing being un-added), give the rule and its runner-up.
T6 EXPECTATION CHANGES: every existing test, lint and probe row that pins today's behaviour (K10 (ii), T6h, the trigger-undo tests, the C3 rows, any [transport] case), BY NAME, with its new expectation and Boris's verbatim words beside it. No other expectation changes.
T7 HARMONY'S GATE LIST for this lane (pre-registered; exact strings and bars; each row with its RED arm): unit suites, TSan / ASan unit gates that apply, live probe rows (REST-driven, --test-mode, open -g, never an Output window, no synthetic input, decoded pixels for render rows, own-pid quit), and the VISUAL WORK GATE for T4's widgets -- the states, the measurable bars read from a dump, and the questions for five critic seats (visual-design, UX, graphic-design, logic, interaction-logic). Harmony constraint: RED arm = a frozen copy of the pre-merge main app; a bar whose teeth equal the noise is INFO, not a gate; a flake verdict needs >= 5 runs per arm.
T8 BUILD STAGES: one builder context each, dependency order, what each proves before the next starts; ONE lane or two (transport / undo-live) and why; which files collide with the sync-dial lane and what must be re-read once it has merged; what the bars lane and the Timeline lane will need from this one.
T9 DOCS: which docs/claude/*.md lines change; CLAUDE.md's "Transport state" paragraph will be false -- say what replaces it (CLAUDE.md is being cut to <= 8 KB by another task: prefer docs/claude/*.md); pitfall entries that change or are added (write "Pitfall NN"; Harmony assigns numbers).`

const PS = { type: 'object', properties: { plan_path: { type: 'string' }, status: { type: 'string', enum: ['DONE', 'PARTIAL'] }, summary: { type: 'string' }, facts_changed_since_sheet: { type: 'array', items: { type: 'string' } }, forks: { type: 'array', items: { type: 'object', properties: { id: { type: 'string' }, choice: { type: 'string' }, runner_up: { type: 'string' } }, required: ['id', 'choice'] } } }, required: ['plan_path', 'status', 'summary', 'forks'] }
const AS = { type: 'object', properties: { seat: { type: 'string' }, attacks: { type: 'array', items: { type: 'object', properties: { id: { type: 'string' }, target: { type: 'string' }, claim: { type: 'string' }, evidence: { type: 'string' }, severity: { type: 'string', enum: ['MUST', 'SHOULD', 'NIT'] }, proposed_change: { type: 'string' } }, required: ['id', 'target', 'claim', 'evidence', 'severity'] } }, strongest_point: { type: 'string' }, citations_rechecked: { type: 'boolean' } }, required: ['seat', 'attacks', 'strongest_point', 'citations_rechecked'] }
const RS = { type: 'object', properties: { ruling_path: { type: 'string' }, papers_path: { type: 'string' }, status: { type: 'string', enum: ['DONE', 'PARTIAL'] }, verdict: { type: 'string' }, amendments: { type: 'number' }, stages: { type: 'array', items: { type: 'object', properties: { key: { type: 'string' }, scope: { type: 'string' } }, required: ['key', 'scope'] } }, boris_questions: { type: 'array', items: { type: 'string' } }, facts_harmony_must_measure: { type: 'array', items: { type: 'string' } }, strongest_counterargument: { type: 'string' } }, required: ['ruling_path', 'status', 'verdict', 'amendments', 'stages'] }

phase('Plan')
const plan = await agent(`PLAN AUTHORING (architect) -- Audio-DNA, the TRANSPORT + UNDO-LIVE lane. You author the position; a blind council attacks it; an architect ruling follows; Harmony decides.
GOAL: Boris performs live with this app and on 2026-10-03 ruled how firing a clip, dragging its playhead, a BPM-synced clip and Cmd+Z must behave. Plan ONE coherent change (the two halves share the trigger paths and the Undo stack, which is why they are planned together) that a builder can build stage by stage on main after the sync-dial lane has merged, with tests that can fail and one gate list Harmony runs herself.
${READS}
${INPUTS}
${ITEMS}
OUTPUT: write the plan to REPORT_FILE (literal path below, relative to ${MAIN}; write it with a bash heredoc to exactly that path). Sections: 1 GOAL; 2 ESTABLISHED FACTS (ONLY lines you verified at ${PIN}, each with file:line or the command you ran; anything else is labelled INFERRED or ASSUMED where it is used); 3 ITEMS T1-T6 (today / Boris verbatim / forks, the choice, why the runner-up loses / the change / tests RED-first + mutants / gate); 4 BUILD STAGES (T8); 5 HARMONY'S GATE LIST (T7; exact strings and bars); 6 DOCS (T9); 7 WHAT ONLY BORIS CAN CHECK (plain words; do -> expect -> what wrong looks like); 8 QUESTIONS FOR BORIS (plain words, each with a default so the build never waits; only questions that are genuinely his: taste, behaviour he would notice on stage); 9 RISKS (the strongest counterargument to this plan first, and the cheapest test that would refute each choice).
RULES OF THE DOCUMENT: Boris is quoted ONLY verbatim; anything Harmony requires is written as "Harmony constraint:". Harmony constraint: this lane adds NO on-screen text that announces an event. No code blocks longer than a signature. Real-time rules of the project hold (no allocation / lock / syscall on the audio callback; no new mutex; the render thread never waits and never decodes; shared model fields are Relaxed<T>, Pitfall 63). Prefer the smallest change that is correct; say explicitly what is NOT in this lane.
TURN BUDGET (the architect role stops SILENTLY at 120 turns): write a SKELETON of the plan file with all section headings by your turn 8; rewrite the file with what you have every ~10 turns; be DONE by turn 90. If you run short, write status PARTIAL and list what is missing at the top of the file.
REPORT_FILE: ${PLAN_FILE}
RETURN: plan_path, status, a summary <= 1500 characters, facts_changed_since_sheet (fact-sheet lines that are no longer true at ${PIN}), forks (id, choice, runner_up).`, { agentType: 'architect', model: 'opus', effort: 'high', schema: PS, phase: 'Plan', label: 'plan:transport' })
if (!plan) return { failed: 'plan' }
log('plan: ' + plan.status + ' -> ' + plan.plan_path)

phase('Attack')
const SEATS = [
  { key: 'stage-operator', temper: 'You are the STAGE OPERATOR: Boris performs live with this app; nothing may jump, flash, restart or stop that he did not ask for, and everything he asked for must happen on every path he can reach with his hands. Attack T1, T2, T3 and sections 7-8: a fire path the plan did not enumerate (a binding mode, piano / momentary release, a routine replay, a quantized release, Autopilot); a "restart" that also resets something he did not name; a drag that still jumps in one transport mode; a Boris check he cannot actually perform; a question that is not his to answer or that lacks a default; a reading of his words that the verbatim text does not support.' },
  { key: 'undo-model', temper: 'You are the UNDO-MODEL SKEPTIC: an Undo stack is a contract -- every command must be exactly reversible or exactly excluded. Attack T5 and T6: a command the plan did not classify; an Undo / Redo / Undo sequence that leaves the model and the screen disagreeing, resurrects or loses a deck, layer or clip, or changes what plays after all; a "live" definition that is vague at an edge (the playing clip sits on the layer being un-added; a crossfade in progress; a routine holding a grip); a fired clip silently dropped from the stack while a later command depends on it. Re-derive each claim from the code at the pin.' },
  { key: 'real-time', temper: 'You are the REAL-TIME AND THREADS SKEPTIC: the render thread never waits and never decodes, the audio callback is sacred, shared model fields are Relaxed<T>. Attack T1-T4: a restart or a drag that makes the render thread wait for a seek or shows a stale or black frame; a race between the message thread writing a restart and the decode thread or the render-side transport write-back (Pitfalls 2, 7, 56, 62, 63, 64); a tempo-following speed computed from a beatPhase wrap instead of an integrated beat clock (Pitfalls 42, 48); a new field read on two threads without the house type; a model-driven widget that repaints the whole window on a timer (Pitfalls 41, 57, 59).' },
  { key: 'gates', temper: 'You are the GATE PROSECUTOR: a test that cannot fail is not a test. Attack every test, mutant, bar and gate string in the plan (sections 3, 5): no RED arm; a bar whose teeth equal the noise; a lint that pins text while behaviour is free to break; a live row that would pass with the bug present (a restart measured on a clip already at frame 0; a drag row that never moves the playhead far enough to show a jump); an expectation change (T6) not backed by a verbatim Boris line; a visual-gate bar that no dump can measure; a row with no pre-registered string.' },
  { key: 'scope', temper: 'You are the MINIMALIST: other lanes queue behind this one (bars, envelopes, record to clip, the Timeline, the Edit menu). Attack scope and risk: a change wider than what Boris said; work that belongs in the bars lane or the Timeline lane; a stage order that leaves the tree not building; a new model field or serialization change that an old show cannot load; a gate that costs an hour and proves what a cheaper one already proves. For each cut you propose, name what is lost and why that is acceptable -- and also name the ONE thing in the plan that must NOT be cut.' },
]
const papers = (await parallel(SEATS.map(s => () => agent(`BLIND COUNCIL SEAT "${s.key}" -- attack ONE plan from ONE temperament. You do not see the other seats.
${s.temper}
THE PLAN UNDER ATTACK: ${MAIN}/${PLAN_FILE} (read it IN FULL first).
${READS}
${INPUTS}
MANDATORY CITATION RE-CHECK: before you return, re-open every file:line you cite at the pin and confirm it says what you claim; set citations_rechecked accordingly and drop any attack whose evidence did not survive. An attack without evidence (a file:line at ${PIN}, a quoted plan line, or a quoted line of Boris's verbatim record) is not an attack.
Do NOT write any file. RETURN (StructuredOutput): seat, attacks (id like ${s.key.slice(0, 2).toUpperCase()}-1..; target = the plan item / section; claim; evidence; severity MUST = the plan would ship a defect, contradict Boris's verbatim words, or carry a gate that cannot fail, SHOULD, NIT; proposed_change), strongest_point (the one attack you would stake the seat on), citations_rechecked. At most 10 attacks; fewer and sharper is better.`, { agentType: 'authored-council-seat', model: 'sonnet', effort: 'high', schema: AS, phase: 'Attack', label: 'attack:' + s.key })))).filter(Boolean)
log('seats returned: ' + papers.length + ' of ' + SEATS.length + '; attacks: ' + papers.reduce((n, p) => n + (p.attacks || []).length, 0))

phase('Ruling')
const ruling = await agent(`ARCHITECT RULING on a blind council's attacks (you run on opus at max effort because Fable is out of usage -- Boris, verbatim, 2026-10-02: "just so you know, we are out of fable usage so you will need to do all fable work with opus 5.5"). Harmony decides after you; your ruling is her working document.
THE PLAN: ${MAIN}/${PLAN_FILE} (read IN FULL).
THE SEAT PAPERS (${papers.length} of ${SEATS.length} seats returned; verbatim JSON): ${JSON.stringify(papers).slice(0, 70000)}
${READS}
${INPUTS}
DO, IN THIS ORDER:
1. FIRST write the seat papers verbatim (pretty-printed, one section per seat) to ${PAPERS_FILE} (literal path, relative to ${MAIN}, bash heredoc).
2. For every attack: re-derive the evidence yourself at the pin (never trust a seat's citation, never trust the plan's); verdict ACCEPT / PARTIAL / REJECT with the line that decides it. Where two seats conflict, RECONCILE them (do not relay both). Where the outcome turns on ONE fact nobody can establish by reading (it needs a build, a run or a measurement), do NOT guess: list it in facts_harmony_must_measure with the cheapest discriminating test, and give the ruling for each outcome. Where the outcome turns on what Boris meant and his verbatim words do not settle it, it is a BORIS QUESTION with a default -- never a guess presented as his wish.
3. Write the ruling to REPORT_FILE: 0 VERDICT; 1 FACTS RE-DERIVED; 2 ATTACK RULINGS (table); 3 AMENDMENTS (numbered; each OVERRIDES the plan body where they differ); 4 FINAL BUILD STAGES (one builder context each; what each must prove; the order; what is re-read after the sync-dial lane merges); 5 FINAL CONSOLIDATED GATE LIST (pre-registered; Harmony copies gate strings ONLY from here: the full list, not a diff), incl. the VISUAL WORK GATE's states, measurable bars and the five critic seats' questions; 6 WHAT ONLY BORIS CAN CHECK (plain words; do -> expect -> what wrong looks like); 7 BORIS QUESTIONS (plain words, each with a default); 8 SIDE FINDINGS (outside this lane); 9 RISKS OF THIS RULING (the strongest counterargument first).
RULES: Boris quoted only verbatim; Harmony's requirements labelled "Harmony constraint:"; Harmony constraint: no on-screen text that announces an event; no code beyond a signature; prefer the smallest correct change; a pre-registered bar is never loosened -- it is met, or reported.
TURN BUDGET (the role stops SILENTLY at 120 turns): papers file by turn 4; a SKELETON ruling with all headings by turn 10; rewrite every ~10 turns; DONE by turn 90; if short, status PARTIAL with what is missing at the top.
REPORT_FILE: ${RULING_FILE}
RETURN: ruling_path, papers_path, status, verdict (<= 1200 characters), amendments (count), stages (key + one-line scope), boris_questions, facts_harmony_must_measure, strongest_counterargument.`, { agentType: 'architect', model: 'opus', effort: 'max', schema: RS, phase: 'Ruling', label: 'ruling:transport' })
return { plan: { path: plan.plan_path, status: plan.status, summary: String(plan.summary || '').slice(0, 1500), facts_changed: (plan.facts_changed_since_sheet || []).map(x => String(x).slice(0, 240)), forks: (plan.forks || []).map(f => ({ id: f.id, choice: String(f.choice || '').slice(0, 260), runner_up: String(f.runner_up || '').slice(0, 200) })) }, seats: papers.map(p => ({ seat: p.seat, n: (p.attacks || []).length, must: (p.attacks || []).filter(a => a.severity === 'MUST').length, strongest: String(p.strongest_point || '').slice(0, 300) })), ruling: ruling ? { ruling_path: ruling.ruling_path, status: ruling.status, verdict: String(ruling.verdict || '').slice(0, 1200), amendments: ruling.amendments, stages: (ruling.stages || []).map(s => ({ key: s.key, scope: String(s.scope || '').slice(0, 260) })), boris_questions: (ruling.boris_questions || []).map(x => String(x).slice(0, 400)), facts_harmony_must_measure: (ruling.facts_harmony_must_measure || []).map(x => String(x).slice(0, 300)), strongest_counterargument: String(ruling.strongest_counterargument || '').slice(0, 500) } : { failed: true } }
