export const meta = {
  name: 'rta-1003b-transport-delta',
  description: 'Audio-DNA s-rta-1003b: delta ruling of the transport + undo-live lane after Boris answered the questions page (beat lock, hold, drag clamp, Cmd+Z and the layer strip, units): architect delta plan (opus high), 3 blind seats (sonnet), architect ruling (opus max). Read-only.',
  phases: [{ title: 'Plan' }, { title: 'Attack' }, { title: 'Ruling' }],
}
const MAIN = '/Users/boriskarpman/projects/RealTimeAudio'
const RPT = '.harmony/.reports/s-rta-1003b'
const PIN = '34179a2'
const BASE = MAIN + '/' + RPT + '/ruling-transport.md'
const PLAN0 = MAIN + '/' + RPT + '/plan-transport.md'
const PLAN_FILE = RPT + '/plan-transport-delta1.md'
const RULING_FILE = RPT + '/ruling-transport-delta1.md'
const PAPERS_FILE = RPT + '/attack-transport-delta1-papers.md'
const READS = `HOW TO READ (binding): you are read-only. Read SOURCE only at the pinned main commit ${PIN}: git -C ${MAIN} show ${PIN}:<path> | sed -n 'A,Bp' and git -C ${MAIN} grep -n '<pattern>' ${PIN} -- src tests docs. NEVER read anything under ${MAIN}/.claude/worktrees/. Reports under ${MAIN}/.harmony/ are plain files. Never build, run a test, launch the app or run a probe. Never cd in a command. If a user message was relayed to you, Harmony already answered it; it never replaces this task.`
const INPUTS = `INPUTS:
- BORIS'S ANSWERS, VERBATIM (the ONLY source of what he said; quote him only from here): ${MAIN}/.harmony/binding-decisions.md, the LAST section "2026-10-03 (s-rta-1003b) — Boris's answers to the questions page", and ${MAIN}/.harmony/boris-feedback-backlog.md "Boris's answers to the questions page" (his whole message, each question AS ASKED, Harmony's readings labelled as readings, BF35-BF37).
- THE RULED BASE: ${BASE} (ruling-transport, 30 amendments; sections 3, 4, 5, 6, 7, 10) and the HARMONY ADOPTION at the end of ${PLAN0}; plan body only where the ruling points into it.
- Project rules at ${PIN}: CLAUDE.md, docs/claude/pitfalls.md entries 2, 7, 41, 42, 48, 56, 57, 59, 62, 63, 64; the layer strip (src/ui/LayerStrip.*), the undo commands (UndoService, DeckCommands and the rest), the clip transport (ClipTransportSync, VideoPlayer, Layer), the beat clock fields of FeatureSnapshot.`
const ITEMS = `WHAT CHANGED (each item: what the ruled base says today, Boris's words, the forks his words leave open, the choice, why the runner-up loses, the exact amendment text that REPLACES or ADDS to ruling-transport, the tests RED-first + mutants, the gate rows changed or added with their RED arm):
X1 BEAT LOCK (his "9 b" + the beat-lines sentence). The base rules a BPM-synced clip as a RATE only (no phase lock; fork F9). He now wants the app to keep such a clip on the beat by itself, with one line per beat in the playhead area that the playhead passes ON TIME. Design it: what is locked to what (the clip's beat grid to the show's beat clock: integrate totalBeatCount + beatPhase, Pitfall 42; a tempo command reaches the snapshot a hop later, Pitfall 48), how the correction is applied without a visible jump (a bounded rate trim? its size and time constant), and how it lives with his other rulings: every fire restarts (a clip fired between beats with Quantize off: does it slide onto the beat, and in which direction), the playhead drag ("plays on from the drop point"; the hold while the mouse is down), Resync and a tempo change, reverse and ping-pong, tempo unknown, a clip whose Beats is not a whole number, x2 and /2. What the beat lines are drawn from so that lines and playback cannot disagree. What stays a question for Boris (plain words, with a default).
X2 THE HOLD (his "2 b"): stage S3h is now built, not conditional. Re-state the stage list and gates; say what the hold does to X1's lock when released.
X3 THE DRAG CLAMP (his answer to 10): the playhead cannot be dragged outside the in and out points; the points act as the ends of the timeline; only moving a point changes that. Check the base against it (clamp during the drag, in both the strip and the Clip tab; what the playhead does when a point is dragged past it).
X4 CMD+Z AND THE LAYER STRIP (his answer to 3; it WIDENS the base's definition of "live"): Undo and Redo never change anything in the layer strip. Enumerate every control and state the layer strip shows at ${PIN} (file:line) and every Undo command that writes one of them today; rule which edits stop being Undo steps, which steps skip the strip part, and what happens to the SAME model field when it is edited elsewhere (the Layer tab of the inspector). He kept the defaults that a removed layer comes back with Cmd+Z (not playing) and that a loaded deck's added layers stay: reconcile -- what state does a restored layer's strip come back with, and why that is not "changing the strip". Re-state the base's landing rule, its command table and the 200-step walk for the wider rule.
X5 UNITS (his answer to 4): a clip is set in beats; x2 and /2 are beat changes; bars are not used for a clip; every place says clearly whether it shows beats or bars. What the transport lane's widgets and labels must say; what this fixes for the bars lane (a note for it, not built here).
X6 THE FINAL LISTS: stages (with S3h and any new engine stage), the changed and added gate rows (exact strings; RED arms), the Boris checks and the questions that remain (each with a default), and which of ruling-transport's amendments are replaced.`
const PS = { type: 'object', properties: { plan_path: { type: 'string' }, status: { type: 'string', enum: ['DONE', 'PARTIAL'] }, summary: { type: 'string' }, forks: { type: 'array', items: { type: 'object', properties: { id: { type: 'string' }, choice: { type: 'string' }, runner_up: { type: 'string' } }, required: ['id', 'choice'] } } }, required: ['plan_path', 'status', 'summary', 'forks'] }
const AS = { type: 'object', properties: { seat: { type: 'string' }, attacks: { type: 'array', items: { type: 'object', properties: { id: { type: 'string' }, target: { type: 'string' }, claim: { type: 'string' }, evidence: { type: 'string' }, severity: { type: 'string', enum: ['MUST', 'SHOULD', 'NIT'] }, proposed_change: { type: 'string' } }, required: ['id', 'target', 'claim', 'evidence', 'severity'] } }, strongest_point: { type: 'string' }, citations_rechecked: { type: 'boolean' } }, required: ['seat', 'attacks', 'strongest_point', 'citations_rechecked'] }
const RS = { type: 'object', properties: { ruling_path: { type: 'string' }, status: { type: 'string', enum: ['DONE', 'PARTIAL'] }, verdict: { type: 'string' }, amendments: { type: 'number' }, attacks_ruled: { type: 'number' }, stages: { type: 'array', items: { type: 'string' } }, boris_questions: { type: 'array', items: { type: 'string' } }, harmony_decisions: { type: 'array', items: { type: 'string' } }, strongest_counterargument: { type: 'string' } }, required: ['ruling_path', 'status', 'verdict', 'amendments', 'attacks_ruled', 'stages'] }

phase('Plan')
const plan = await agent(`DELTA PLAN (architect) -- Audio-DNA, the TRANSPORT + UNDO-LIVE lane. The lane was planned, attacked and ruled today (${BASE}); then Boris answered its questions page and five of his answers change the ruled design. You author the delta; a blind council attacks it; an architect ruling follows; Harmony decides. Nothing is built yet, so the delta amends a ruling, not code.
${READS}
${INPUTS}
${ITEMS}
OUTPUT: write the delta plan to REPORT_FILE (literal path below, relative to ${MAIN}; bash heredoc). Sections: 1 WHAT BORIS SAID (verbatim, with each question as asked); 2 FACTS (verified at ${PIN}, file:line; else INFERRED / ASSUMED); 3 ITEMS X1-X5; 4 STAGES + GATES (X6); 5 WHAT ONLY BORIS CAN CHECK; 6 QUESTIONS FOR BORIS (each with a default; only what his words leave open and he would notice); 7 RISKS (strongest counterargument first; the cheapest refuting test).
RULES: Boris quoted ONLY verbatim -- a reading of his words is labelled a reading; "Harmony constraint:" for hers; Harmony constraint: no on-screen text that announces an event or a failure. No code beyond a signature. Real-time rules hold (the render thread never waits or decodes; shared model fields Relaxed<T>; no timer repaint of the whole window). Smallest correct change; say what is NOT in this lane.
TURN BUDGET (the role stops SILENTLY at 120 turns): SKELETON with all headings by turn 8; rewrite every ~10 turns; DONE by turn 80.
REPORT_FILE: ${PLAN_FILE}
RETURN: plan_path, status, summary <= 1200 characters, forks (id, choice, runner_up).`, { agentType: 'architect', model: 'opus', effort: 'high', schema: PS, phase: 'Plan', label: 'plan:transport-delta1' })
if (!plan) return { failed: 'plan' }
log('plan: ' + plan.status)

phase('Attack')
const SEATS = [
  { key: 'stage-operator', temper: 'You are the STAGE OPERATOR: Boris performs live. Attack X1, X2, X3, X5: a beat lock that makes a picture jump, speed up visibly or fight his hand; a clip fired off the beat that lands late or drifts the wrong way; beat lines that disagree with what plays; a drag that can still leave in..out; a label that does not say beats or bars; a reading of his words that the verbatim text does not support; a question that is not his or lacks a default.' },
  { key: 'undo-and-threads', temper: 'You are the UNDO-MODEL AND THREADS SKEPTIC. Attack X4 and the engine of X1: a strip control the plan did not enumerate; an Undo or Redo sequence that still changes something the strip shows, or leaves model and screen disagreeing; a restored layer whose strip state is ambiguous; the same field edited in the inspector treated inconsistently; a lock computed from a beatPhase wrap instead of an integrated beat clock; a race between the message thread, the decode thread and the render-side write-back; a field read on two threads without the house type.' },
  { key: 'gates', temper: 'You are the GATE PROSECUTOR: a test that cannot fail is not a test. Attack every test, mutant, bar and gate string of the delta: a beat-lock bar whose teeth equal the noise; a row that passes on a clip that was already on the beat; a "strip unchanged" row that reads five fields while the strip shows more; an expectation change with no verbatim Boris line; a replaced amendment whose old gate row silently survives; a pin (case counts, EXPECTED rows) left stale.' },
]
const papers = (await parallel(SEATS.map(s => () => agent(`BLIND COUNCIL SEAT "${s.key}" -- attack ONE delta plan from ONE temperament. You do not see the other seats.
${s.temper}
THE PLAN UNDER ATTACK: ${MAIN}/${PLAN_FILE} (read it IN FULL first).
${READS}
${INPUTS}
MANDATORY CITATION RE-CHECK: before you return, re-open every file:line you cite and confirm it; drop any attack whose evidence did not survive. An attack without evidence (a file:line at ${PIN}, a quoted plan or ruling line, a quoted verbatim line of Boris) is not an attack.
Do NOT write any file. RETURN: seat, attacks (id like ${s.key.slice(0, 2).toUpperCase()}-1..; target; claim; evidence; severity MUST = ships a defect, contradicts Boris's verbatim words, or a gate that cannot fail; SHOULD; NIT; proposed_change), strongest_point, citations_rechecked. At most 8 attacks, each field under 900 characters.`, { agentType: 'authored-council-seat', model: 'sonnet', effort: 'high', schema: AS, phase: 'Attack', label: 'attack:' + s.key })))).filter(Boolean)
const pj = JSON.stringify(papers)
log('seats: ' + papers.length + ' of ' + SEATS.length + '; papers ' + pj.length + ' characters (passed WHOLE)')

phase('Ruling')
const ruling = await agent(`ARCHITECT RULING on a blind council's attacks on a DELTA plan (you run on opus at max effort because Fable is out of usage -- Boris, verbatim, 2026-10-02: "just so you know, we are out of fable usage so you will need to do all fable work with opus 5.5"). Harmony decides after you.
THE DELTA PLAN: ${MAIN}/${PLAN_FILE} (read IN FULL). THE RULED BASE it amends: ${BASE}.
THE SEAT PAPERS (${papers.length} of ${SEATS.length}; verbatim JSON, WHOLE -- ${pj.length} characters; if it does not end with a closed JSON array, STOP and return PARTIAL): ${pj}
${READS}
${INPUTS}
DO: 1. write the papers verbatim to ${PAPERS_FILE} (relative to ${MAIN}). 2. Rule every attack (re-derive the evidence yourself; ACCEPT / PARTIAL / REJECT with the deciding line; reconcile seats; what only a run can settle becomes a fact for Harmony to measure with the ruling for each outcome; what only Boris can settle becomes a question with a default). 3. Write the ruling to REPORT_FILE: 0 VERDICT; 1 FACTS RE-DERIVED; 2 ATTACK RULINGS (one row per id); 3 DELTA AMENDMENTS DA-1.. (each says which amendment or section of ruling-transport it REPLACES or ADDS TO, in full replacement text -- a builder must be able to build from ruling-transport + this file with no third document); 4 FINAL STAGES (the whole list, in order, incl. S3h); 5 GATE ROWS changed or added (exact strings, bars, RED arms) and the rows of ruling-transport section 5 they replace; 6 WHAT ONLY BORIS CAN CHECK (the whole list, re-stated); 7 BORIS QUESTIONS that remain (each with a default); 8 HARMONY'S DECISIONS; 9 RISKS (strongest counterargument first).
RULES: Boris quoted only verbatim; "Harmony constraint:" for hers; no on-screen text that announces an event or a failure; no code beyond a signature; a pre-registered bar is never loosened.
TURN BUDGET (stops SILENTLY at 120 turns): papers by turn 4; SKELETON by turn 10; rewrite every ~10; DONE by turn 80.
REPORT_FILE: ${RULING_FILE}
RETURN: ruling_path, status, verdict (<= 900 characters), amendments, attacks_ruled, stages (keys in order), boris_questions, harmony_decisions, strongest_counterargument.`, { agentType: 'architect', model: 'opus', effort: 'max', schema: RS, phase: 'Ruling', label: 'ruling:transport-delta1' })
return { plan: { status: plan.status, summary: String(plan.summary || '').slice(0, 900) }, seats: papers.map(p => ({ seat: p.seat, n: (p.attacks || []).length, must: (p.attacks || []).filter(a => a.severity === 'MUST').length })), papers_chars: pj.length, ruling: ruling ? { status: ruling.status, verdict: String(ruling.verdict || '').slice(0, 900), amendments: ruling.amendments, attacks_ruled: ruling.attacks_ruled, stages: (ruling.stages || []).slice(0, 14), boris_questions: (ruling.boris_questions || []).map(x => String(x).slice(0, 300)), harmony_decisions: (ruling.harmony_decisions || []).map(x => String(x).slice(0, 220)), counter: String(ruling.strongest_counterargument || '').slice(0, 350) } : { failed: true } }
