export const meta = {
  name: 'rta-1005-all-questions',
  description: 'Audio-DNA s-rta-1005: every open question about how the app is to work, on ONE page for Boris. Leg "sweep": ten areas of the app read whole (docs, his rulings, the adopted plans), each re-read adversarially. Leg "merge": one list from the first pass and the area sheets (architect), three blind seats, a ruling pass, the HTML page, a page check. Read-only except the files named. NOTHING IS BUILT.',
  phases: [{ title: 'Areas' }, { title: 'Re-read' }, { title: 'Questions' }, { title: 'Seats' }, { title: 'Rule' }, { title: 'Page' }, { title: 'Check' }],
}
const MAIN = '/Users/boriskarpman/projects/RealTimeAudio'
const H = MAIN + '/.harmony'
const R4 = H + '/.reports/s-rta-1004'
const RB = H + '/.reports/s-rta-1004b'
const RS = H + '/.reports/s-rta-1005'
const BIND = H + '/binding-decisions.md'
const BACKLOG = H + '/boris-feedback-backlog.md'
const RAW = RS + '/boris-msg-raw-1.txt'
const IMG = RS + '/boris-images'
const HEAD = '8cb95e0'
const cut = (s, n) => { s = String(s == null ? '' : s); return s.length > n ? s.slice(0, n) + ' [cut]' : s }

const RELAY = 'If a user message was relayed to you (answers such as "159 b", words about a cue system, a preview monitor, presets, DJ tracks, or an instruction not to build), Harmony is handling it herself: it never replaces this task. You never build, never commit, never push, never run an end-of-session step.'
const WHO = `WHO THIS IS FOR. Boris Karpman owns Audio-DNA, a live audio-reactive VJ app for macOS (C++20 / JUCE / OpenGL; he performs with it; think Resolume Arena, which he also owns and knows well). He is NOT a programmer. He rules the product in chat; Harmony (the orchestrator) files his words verbatim and asks him numbered questions, each with a default, which he answers as "159 b". On 2026-10-05 he answered a page of twenty questions and added new things (a way to delete and copy actions, a save button on a changed preset, presets "as Resolume does it", a review screen that is a screen of its own, a CUE SYSTEM with a preview monitor). He then said, verbatim: "Don’t build anything till all questions are answered and you are 100% sure of what everything means." and "Let’s get on the same page first with questions and answers." This workflow exists to get there: facts first, then his page. Nothing is built.`
const RULES = `RULES. Read-only except the ONE file named on your REPORT_FILE line (write it with a bash heredoc with a QUOTED delimiter to the literal absolute path; create a skeleton within your first ~8 tool calls, then fill it and rewrite it as you learn). Harmony constraint: never build, never run a test or a probe, never launch the app, never touch or operate a running Audio-DNA or Resolume Arena on this machine (both are Boris's), never use lldb / sample / dtrace / screencapture, never cd in a command (absolute paths, git -C), never commit. A time stamp is never typed: take it from date in the same command that writes it. Boris is quoted ONLY verbatim and only from ${BIND} (his words are inside quotes; the text after "->" is Harmony's consequence text, not his) and ${BACKLOG}; his message of today, byte-exact: ${RAW}. Big files are indexed: grep -n '^#' first, then read ranges. Label every line of your output VERIFIED (you read it: file:line, or URL + the quoted words) or INFERRED (say from what) or UNKNOWN (say the cheapest way to find out). An honest UNKNOWN costs one question; a confident wrong line costs a build stage. ${RELAY}`
const CODE = `READING THE APP. Read the repository's main working tree at ${MAIN} (HEAD ${HEAD}; no builder is editing it: the build is on hold). Do NOT read the lane worktrees under ${MAIN}/.claude/worktrees (they hold unmerged code) unless your topic names one. Project docs that index the code: ${MAIN}/CLAUDE.md (the pitfall index), ${MAIN}/docs/claude/*.md, ${H}/APP-INVENTORY.md. Fact sheets of 2026-10-04 that you may cite instead of re-deriving (but re-check at least five load-bearing lines of any sheet you lean on): ${RB}/facts-actions-today.md, ${RB}/facts-quantize.md. Use the app's on-screen words when you name a control (read the string in the source), and give the class and file:line beside it.`
const HIS = `HIS WORDS OF TODAY, where to read them: ${BIND} -- the LAST section, headed "2026-10-05 (s-rta-1005)" (one bullet per topic: his words in quotes, then "->" and Harmony's consequence); ${BACKLOG} -- the LAST section (whole message verbatim, his four pictures described, Harmony's readings R127-R147, items BF126-BF149). The page he answered, with each question as asked and its ANSWERS block: ${RB}/boris-clarify-150-plus.md. His pictures (LOOK at them with the Read tool): ${IMG}/resolume-monitors-menu.jpg, ${IMG}/resolume-monitors.jpg (Resolume's Composition Monitor above its Clip Monitor, and the monitor's menu), ${IMG}/resolume-effects-tab-presets.png (an effect with its presets listed under it in the effects tab), ${IMG}/resolume-effect-panel-presets-menu.png (the effect's panel with the presets menu open: Default, Blue, Green, Red, Manage..., Save); from 2026-10-04: ${RB}/boris-images/review-screen-reference.png, resolume-tempo-bar.png, resolume-bpm-sync-panel.png.`

const FS = { type: 'object', required: ['status', 'report_path', 'lines_verified', 'unknowns', 'summary'], properties: { status: { type: 'string', enum: ['DONE', 'PARTIAL', 'BLOCKED'] }, report_path: { type: 'string' }, lines_verified: { type: 'number' }, lines_inferred: { type: 'number' }, unknowns: { type: 'array', items: { type: 'string' } }, surprises: { type: 'array', items: { type: 'string' } }, summary: { type: 'string' } } }
const VS = { type: 'object', required: ['verdict', 'checked', 'wrong', 'corrections', 'summary'], properties: { verdict: { type: 'string', enum: ['SOUND', 'SOUND_WITH_CORRECTIONS', 'UNRELIABLE'] }, checked: { type: 'number' }, wrong: { type: 'number' }, corrections: { type: 'array', items: { type: 'string' } }, summary: { type: 'string' } } }

const CHAT = `WHAT HARMONY ALREADY TOLD HIM IN CHAT on 2026-10-05 (he asked for these four; the page repeats them in a short block and does not ask them again):
R114 -- it is about the live show's tempo row, not about actions. The row's pause and stop are for the whole show; each clip also has its own pause button; the row never flips a clip's own pause. A clip he paused himself is still paused after a row stop and a re-fire; a clip that was playing plays when re-fired. A clip's own pause IS saved with the show (already ruled); what is not saved is the ROW's state (a beat that was paused or stopped).
R116 -- two things about old files only: (1) an old show's Quantize setting is ignored and dropped at the next save; (2) an old recording made with Quantize on wrote down his press, not the bar line the clip was held to, so replayed now the clip changes at his press. Both fall away by his words on R117 (nothing saved is in use).
R120 -- in the keyboard and MIDI mapping (HIS name for the list where functions are put on keys and MIDI pads), two old entries, "Stop" (stops routines) and "Play / Pause" (plays / pauses the audio file), get longer names ("Stop actions", "Audio play / pause") so that they are not taken for the new "Beat stop" / "Beat play". Names only.
R121 -- where presets stand: nothing built; ruled twice on paper; re-planned on his Resolume pictures. Stays: the name stays after a change, no mark. Changes: the effect shows its own name; a preset button with a drop-down above its sliders (Default, his presets, "Manage...", "Save"); a small Save button appears when a slider leaves the preset (a small window, a name, Save); the effects tab lists each effect's presets under it; Rename and Delete move into "Manage...". Rename -> every effect of the open show that carries the preset reads the new name; Delete -> those effects read "Default" and keep their settings.`
const NEWMSG = `A SECOND MESSAGE OF HIS, 2026-10-05 14:16 (it arrived after this workflow's fact sheets were written; byte-exact ${RS}/boris-msg-raw-2.txt; filed as the last two bullets of today's section of ${BIND} and as an "ADDED" block at the end of the last section of ${BACKLOG}), verbatim, two lines: "r120 we call it keyboard and midi 'mapping' lets use this term" and "ask me questions about anything that is unclear when you are ready". CONSEQUENCE, binding for every text he reads: the list where functions are put on keys and MIDI pads is called "keyboard and MIDI mapping" -- never "the key / pad list", "the key and pad list", "bindings" or "the overlay". ONE new reading (numbered like any new reading) says so: look up what that list or window is titled on screen today (the string in the source, file:line as its source) and say what it reads today and that it is called "keyboard and MIDI mapping" from now on. His second line is the invitation this page answers: the intro says so in one short line, quoting it.`
const SEEDS = `HARMONY'S SEED LIST (what she saw open in his answers; not exhaustive; a seed a fact sheet settles is dropped with the fact named; each seed that survives becomes a question, a reading, a "decided, not asked" line or a design-page item):
 1 [154] Between his press and the next "1" for a BPM-mode clip: what the layer shows (the old clip plays on until the "1" / the new clip shows at once, held on its first frame / the case of an empty layer).
 2 [R111] Does ANY fired clip start a stopped beat or only a BPM-mode clip; is his press the "1"; is a column click the same; while PAUSED, a clip that is NOT in BPM mode: does it play at once (his earlier words: pause holds the beat and the BPM-synced clips).
 3 [cue] What the preview shows for a cued layer: the layer before its fader (so he can see it with the fader down, as a DJ hears a track that is not in the mix yet)? with the layer's effects? with or without the global effects? several cued layers mixed with their blend modes?
 4 [cue] A clip previewed by a click on its name: moving or a still; with its own effects; alone or over the cued layers; how the preview returns to the layers; does that click still select the clip for the Clip tab; what a click on the thumbnail does.
 5 [cue] The preview monitor: always shown or foldable; on a second screen or not.
 6 [150] The save window: the name it starts with; saving under a name that exists; does the small Save button also appear on an effect that still reads "Default". Where he said emulate Resolume, Resolume's facts answer.
 7 [169, presets] Dragging a preset from the effects tab; what "Manage..." is. Resolume's facts answer.
 8 [169, review] "a row in the recording for every parameter and button that can be adjusted": rows of controls that never moved in the take -- always shown, or folded under their effect's name.
 9 [170] Where the review screen's picture comes from: re-made from the recorded moves (then a mended curve changes the picture) or a film of the night -- technical, but its consequence is his. While the review screen is open, does the live output go on? Is there still a way to play a whole take back through the live output?
10 [BF127] Paste: onto what can a copied action be pasted; onto a clip that lacks the effect the action moves; what cut means.
11 [BF128] "save an option with the ignore action items not in it": is "option" an action; saved as a NEW action or over the old one.
12 [159 B] "where they were before the action started": after he moved the slider by hand during the action; with two actions on one slider (160 A); with a global action over a layer's (156 A).
13 [160] The light on "the first one that is conflicted": on that action's button; what it says in one sentence.
14 [164] Where the 8 / 8 / 16 buttons and their "+" sit (today eight routine pads sit above the column numbers; a clip cell is narrow).
15 [R117] No carrying-over of old routines, recordings or shows is built; the show-file protection stays.
16 [157 A + 154 + R123] An action on a BPM-mode clip starts with the clip on the "1" and follows the tempo: say it once, as one reading.
17 [R114] The state of the beat when a show is opened.
18 [161] A lamp beside EVERY slider and button costs room on every row (the layer strip is almost full).`
const ITEMS1 = RS + '/boris-open2-items.json'
const ITEMS = RS + '/boris-all-items.json'
const CLAR1 = RS + '/boris-clarify-172-plus.md'
const CLAR = RS + '/boris-clarify-all.md'
const QRULES = `WHAT MAKES A GOOD QUESTION FOR HIM. (a) Only what is HIS: what he sees, hears or does on stage, taste, product behaviour, anything costly to undo. NEVER a technical question (which file, which thread, how it is stored): those are decided by the architects and listed under "decided, not asked" in one plain line each with the consequence he would notice. (b) Where he said "emulate" Resolume, a Resolume FACT is the answer: write it as a reading that begins "As in Resolume:" -- ask only where the fact sheet says UNKNOWN or where the app cannot do what Resolume does. (c) A question he has already answered is never asked again; a question already shown to him (numbers up to 171) is never re-worded or re-lettered: a narrower follow-up gets a NEW number and names the old one. (d) Each question is a concrete moment in his show in the second person ("You fire a BPM-mode clip half-way through a bar while another clip plays on that layer."), then two or three options, each at most 45 words, A = the default with the reason it is the default (closest to his words, or what Resolume does, or least surprise), then one "why it matters" line. No code names, no file names, no stage ids, no "quantize-out", no "delta"; his vocabulary: clip, layer, deck, column, the tempo row, the "1", BPM mode, action, preset, the review screen, the preview monitor, cue. (e) As FEW questions as are truly needed: a point with one sensible answer is a READING he corrects only if wrong. Order: the ones that hold up the most building first. Group by topic: A firing clips and the tempo row; B the cue system; C presets; D actions in a show; E the review screen and recordings; F the show file, decks and saving; G output screens; H how a clip plays; I effects, signals and what moves a slider by itself; J the keyboard and MIDI mapping, menus and messages; K sources and the automatic features. (f) Where two of his OWN statements disagree, quote both and ask which wins -- unless the later one plainly replaces the earlier, then it is a reading that says so. (g) Things that need a PICTURE to be judged (where buttons sit, sizes, colours, how the review screen is laid out) are NOT questions: they go on the list "comes next as pictures" for the design page, each with the two or three variants worth drawing.`
const ITEMSHAPE = `THE ITEMS FILE is ONE JSON object (valid JSON, UTF-8, written with a bash heredoc with a quoted delimiter; verify it with python3 -c "import json;json.load(open(...))"):
{ "session": "s-rta-1005", "topics": {"A": "Firing clips and the tempo row", "B": "The cue system", "C": "Presets", "D": "Actions in a show", "E": "The review screen and recordings", "F": "The show file, decks and saving", "G": "Output screens", "H": "How a clip plays", "I": "Effects, signals and what moves a slider by itself", "J": "The keyboard and MIDI mapping, menus and messages", "K": "Sources and the automatic features"}, "parts": [{"part": 1, "title": "What the first builds stand on", "topics": ["A", "B", "C", "D", "E"]}, {"part": 2, "title": "The rest of what is being changed", "topics": ["F", "G", "H", "I", "J"]}, {"part": 3, "title": "What exists today and stays unless you say otherwise", "topics": ["K"]}], "first_question": 172, "last_question": N, "last_reading": N,
  "intro": [short lines for the top of his page: what this page is; how to answer ("172 a"); that nothing is being built, in his own words quoted verbatim],
  "told_in_chat": [{"r": "R114", "text": "..."}, ...],
  "readings": [{"r": "R127", "topic": "A..K", "about": "150", "text": "...", "state": "as filed | revised | new", "why_revised": "", "label": "his words | As in Resolume (VERIFIED) | INFERRED", "source": "file:line or BD line", "picture": "" }],
  "questions": [{"n": 172, "topic": "A", "about": "154", "situation": "...", "options": [{"k": "A", "text": "...", "default": true, "why_default": "..."}, {"k": "B", "text": "..."}], "why": "...", "his_words": ["verbatim quote", ...], "source": "...", "picture": "" }],
  "conflicts": [{"a": "verbatim quote", "a_where": "BD:line", "b": "verbatim quote", "b_where": "BD:line", "handled_as": "question 17x | reading R1xx"}],
  "decided_not_asked": [{"text": "plain line with the consequence he would notice", "by": "the fact or ruling that settles it"}],
  "design_page": [{"what": "...", "variants": ["...", "..."]}],
  "defaults_taken": "the line listing 151 A, 155 A, ... as he accepted them",
  "seeds": [{"seed": 1, "became": "question 172 | reading R150 | decided | design | dropped: <fact>"}] }
"picture" is a file name under ${IMG}/ or "" (resolume-monitors-menu.jpg, resolume-monitors.jpg, resolume-effects-tab-presets.png, resolume-effect-panel-presets-menu.png) or "../s-rta-1004b/boris-images/review-screen-reference.png". Readings R127-R147 KEEP their numbers (their filed text is in the last section of ${BACKLOG}); where a fact sheet shows a filed reading to be wrong or incomplete, correct its text and set state "revised" with why. Carried items keep their numbers; NEW readings and NEW questions continue from the first pass's last numbers, without gaps (a first pass with no items: readings from R148, questions from 172).`
const SS = { type: 'object', required: ['status', 'items_path', 'clarify_path', 'questions', 'last_question', 'last_reading', 'summary'], properties: { status: { type: 'string', enum: ['DONE', 'PARTIAL', 'BLOCKED'] }, items_path: { type: 'string' }, clarify_path: { type: 'string' }, questions: { type: 'number' }, first_question: { type: 'number' }, last_question: { type: 'number' }, readings: { type: 'number' }, readings_revised: { type: 'array', items: { type: 'string' } }, last_reading: { type: 'number' }, decided_not_asked: { type: 'number' }, design_page_items: { type: 'number' }, conflicts: { type: 'array', items: { type: 'string' } }, summary: { type: 'string' } } }

const LEG = args && args.leg
const NEWMSG3 = `A THIRD MESSAGE OF HIS, 2026-10-05 14:44 (byte-exact ${RS}/boris-msg-raw-3.txt; filed as the last bullet of today's section of ${BIND}), verbatim: "take your time to go through all the documentation and notes about app function, then I want you to output a html page with all questions and then run eos. I will start next session with my answers and we will work this way till you have a clear idea about everything. After all is clear, then the following session you will start building the app and not before that. so take your time and we will build when all the functionality details are fully understood." CONSEQUENCE: his page is no longer only about his answers of today -- it carries EVERY open question about how the app is to work, across the whole app. Nothing is built until he has said that all is clear, so there is no hurry and no reason to guess; question-and-answer sessions repeat until then.`
const DOCS = MAIN + '/docs/claude'
const R3 = H + '/.reports/s-rta-1003'
const R3B = H + '/.reports/s-rta-1003b'
const AREAS = [
  { key: 'show-decks', title: 'the show file and saving (Save, Save As, Save Deck, Load Deck, Import, the quit window, backups, the keys and layout blocks, Collect Media), decks, deck tabs, columns and the clip grid, deck names',
    docs: `${DOCS}/performance-controls.md, ${DOCS}/architecture.md (the Clip / Deck / Composition parts), ${R4}/facts-saves.md, ${R4}/facts-one-save.md, ${R3}/facts-deck-names.md`,
    plans: `${R4}/ruling-one-save.md (sections 0, 4, 6, 7, 8) with the adoption blocks at the END of ${R4}/plan-one-save.md and ${RB}/rulings-one-save.md; ${R3}/ruling-bf9b-merge.md (decks are boxes)`,
    grep: 'save|deck|backup|import|quit|column|show file|collect' },
  { key: 'outputs', title: 'output screens and their settings (Device, Delay, Opacity, Brightness, Contrast, Red, Green, Blue), Syphon as an output, the Output menu and the Outputs button, Restore Last Outputs, the Preview / Output panel, the canvas and its resolution, the composition transform',
    docs: `${DOCS}/integration.md ("Output windows", Syphon), ${DOCS}/rendering.md (the canvas, the composition transform), ${R4}/facts-outputs.md, ${R4}/facts-resolume-screen-delay.md`,
    plans: `${R4}/ruling-outputs.md (sections 0, 4, 6, 7, 8) with the adoption blocks at the END of ${R4}/plan-outputs.md and ${RB}/rulings-outputs.md`,
    grep: 'output|screen|delay|syphon|monitor|resolution|display|brightness' },
  { key: 'tempo', title: 'the tempo row (beat circle, play, pause, stop, BPM, minus, plus, nudge, /2, x2, Tap, Resync), the beat nudge, Auto and Manual BPM, Ableton Link, Quantize leaving live use, bars as the unit (the bars plan, MilkDrop labels in bars)',
    docs: `${DOCS}/performance-controls.md (Ableton Link, beat snap), ${DOCS}/effects.md (Manual BPM Mode), ${DOCS}/analysis.md, ${R4}/facts-beat-controls.md, ${RB}/facts-quantize.md, ${R3}/facts-quantize-units.md, ${R3}/facts-topbar-sync.md`,
    plans: `${RB}/ruling-nudge-row2.md (sections 0, 4, 6, 7, 8), ${R4}/ruling-nudge-row.md and ${R4}/ruling-nudge.md (sections 0, 6, 7) with the adoption blocks at the END of ${R4}/plan-nudge.md, ${R4}/plan-nudge-row.md, ${RB}/plan-nudge-row2.md and ${RB}/rulings-nudge.md`,
    grep: 'tempo|bpm|nudge|tap|resync|quantiz|snap|beat|bar |bars|link|stop|pause' },
  { key: 'clip-transport', title: 'how a clip plays: BPM mode (BPM Sync) and Timeline mode, speed, beats, loop modes, Random, Beat Repeat, a clip\'s own pause, every fire restarts a video, dragging the playhead, image sequences and slideshows; Undo and what is live (Cmd+Z never changes what is live in the layer strip); the three audio tracks he will bring',
    docs: `${DOCS}/rendering.md, ${DOCS}/performance-controls.md, ${R3}/facts-transport.md, ${R4}/facts-resolume-transport.md`,
    plans: `${R4}/ruling-transport-answers.md and ${R4}/ruling-transport-delta2.md (sections 0, 4, 6, 7, 8) with the adoption blocks at the END of ${R4}/plan-transport-delta2.md and ${R4}/plan-transport-answers.md; ${R3B}/ruling-transport.md and ${R3B}/ruling-transport-delta1.md (verdict and questions only)`,
    grep: 'clip|transport|bpm sync|bpm mode|timeline|speed|loop|random|beat repeat|beatloopr|playhead|undo|control z|ctrl-z|fire|trigger|tracks' },
  { key: 'effects-signals', title: 'effects and the effect stack, the effects tab, presets (were "looks"), signals plugged into sliders (the mapping of audio to sliders, the Signal tab, macros, the master signal), envelopes, the Timeline that follows the clip, the per-type autopilot',
    docs: `${DOCS}/effects.md, ${DOCS}/rendering.md (the mapping system, the audio uniform system), ${R4}/facts-effect-looks.md, ${R3}/facts-envelope.md`,
    plans: `${RB}/ruling-looks-answers2.md (sections 0, 6, 7, 8; NOT adopted), ${R4}/ruling-looks-answers.md, ${R4}/ruling-effect-looks.md (sections 0, 6, 7) with the adoption blocks at the END of ${R4}/plan-effect-looks.md, ${R4}/plan-looks-answers.md, ${RB}/plan-looks-answers2.md; board rows 6 (envelopes) and 8 (Timeline)`,
    grep: 'effect|preset|look|signal|envelope|macro|autopilot|slider|timeline|mapping' },
  { key: 'actions', title: 'actions (which replace routines): what one is, who owns it (clip, layer, global), how it is made, switched, copied, deleted, ignored, how it follows the tempo; and what routines, the routine pads, the bank of 8 and the bands are today',
    docs: `${DOCS}/recording.md ("Surfaces", routines), ${RB}/facts-actions-today.md, ${RS}/facts-actions-open.md (today's sheet: build on it, do not repeat it -- add what it missed)`,
    plans: `${RB}/open-sweep-actions.md; nothing is planned or ruled for actions: only his words`,
    grep: 'action|routine|ignore|pad|global|layer action|clip action' },
  { key: 'recording', title: 'recording: a take (the performance recorder), the review screen, recording to a clip, video recording and snapshots, the Audio Store; and the messages the app shows (his rule: only a failed save and a recording that could not be saved or has no disk space)',
    docs: `${DOCS}/recording.md, ${DOCS}/integration.md (video recording), ${R3}/facts-record-codec.md, ${R3}/facts-notices.md, ${RS}/facts-takes-bpm-fire.md`,
    plans: `${R3B}/ruling-notices.md (verdict, questions); board rows 3c (notices), 7 (record to clip), 2g (the review screen); the handoff's "NOT PLANNED" list (the messages lane re-stated; recording: three boxes)`,
    grep: 'record|take|review|replay|notice|message|codec|rec |snapshot|audio store' },
  { key: 'cue-layers', title: 'the cue system (a preview monitor, a cue button per layer, a click on a clip\'s name), the layer strip (faders, B, S, X, the transport buttons), blend modes, keying and transitions, crossfades, the layer router, feedback',
    docs: `${DOCS}/rendering.md, ${DOCS}/performance-controls.md (the Layer Router), ${R3}/facts-keying.md, ${R3B}/rulings-keying.md, ${RS}/facts-app-cue-today.md (today's sheet: build on it)`,
    plans: `board row 4 (keying audit) and the new row 2i (the cue system): nothing is planned`,
    grep: 'cue|preview|monitor|layer strip|blend|keying|transition|crossfade|fader|solo|bypass|opacity' },
  { key: 'controls', title: 'the keyboard and MIDI mapping (what can be put on a key or a pad, piano and momentary modes, velocity, endless encoders, the three targeting modes), MIDI feedback to pads, OSC, the remote control port, the menus (an Edit menu with Undo and Redo), tooltips, the manual',
    docs: `${DOCS}/performance-controls.md (Live Performance Controls, bindings), ${DOCS}/integration.md (REST, OSC, MIDI output), ${DOCS}/effects.md (the Tooltip System)`,
    plans: `board rows 9 (ui-polish, the Edit menu), 11 (bug X1); the adoption blocks named under the tempo and transport areas where they add key or pad entries`,
    grep: 'key|midi|pad|mapping|binding|osc|menu|edit menu|tooltip|manual|shortcut' },
  { key: 'sources-auto', title: 'what a clip can hold (images, folders, video, camera, the 108 generated sources, MilkDrop, imported ISF shaders) and the automatic features (genre detection, the energy-aware autopilot, scene triggering from the music\'s structure, beat-synced randomization, instant preset recall, audio input choices, the audio readouts) -- mostly things that exist today and that his new model never mentions',
    docs: `${DOCS}/fractals.md, ${DOCS}/analysis.md, ${DOCS}/integration.md (genre detection, ISF, BPM recovery), ${DOCS}/effects.md (the Autopilot System), ${H}/FEATURE_MAP.md`,
    plans: `none: the question for each is whether it stays as it is under the new model (actions, the tempo row, presets, the cue system)`,
    grep: 'source|milkdrop|camera|video|image|genre|autopilot|random|isf|audio input|microphone|slideshow' },
]
const SHEETS5 = [['resolume', 'facts-resolume-emulate.md'], ['cue-today', 'facts-app-cue-today.md'], ['presets-delta', 'facts-presets-delta.md'], ['takes-bpm-fire', 'facts-takes-bpm-fire.md'], ['actions-open', 'facts-actions-open.md']].map(x => ({ key: x[0], file: RS + '/' + x[1] }))
const AFS = { type: 'object', required: ['status', 'report_path', 'unclear_his', 'unclear_technical', 'overtaken', 'summary'], properties: { status: { type: 'string', enum: ['DONE', 'PARTIAL', 'BLOCKED'] }, report_path: { type: 'string' }, unclear_his: { type: 'number' }, unclear_technical: { type: 'number' }, overtaken: { type: 'number' }, already_open: { type: 'array', items: { type: 'string' } }, top_unclear: { type: 'array', items: { type: 'string' } }, summary: { type: 'string' } } }

if (LEG === 'sweep') {
  phase('Areas')
  log('s-rta-1005 all-questions, leg 1: ' + AREAS.length + ' areas of the app read whole, each re-read. Nothing is built.')
  const areaOf = A => agent(`${WHO}
${NEWMSG3}
YOUR AREA: ${A.title}.
WHY THIS SHEET EXISTS. Before anything is built, Harmony must have "a clear idea about everything". You read EVERYTHING written about your area -- how the app works today, what Boris has ruled, what is planned -- and list what is still UNCLEAR. You do not design and you do not decide.
READ (indexed: grep -n '^#' first, then ranges; cite file:line for everything):
 (a) HOW IT WORKS TODAY: ${A.docs}; ${H}/APP-INVENTORY.md (the rows of your area); the pitfall index in ${MAIN}/CLAUDE.md and the pitfalls it names for your area in ${DOCS}/pitfalls.md. Where a doc is thin, or two docs disagree, read the source and say which is right.
 (b) HIS WORDS: ${BIND} and ${BACKLOG} -- run grep -n -i -E "${A.grep}" on both and read every hit's whole bullet or item. A LATER line of his wins over an earlier one; the sections dated "2026-10-04 (s-rta-1004b)" and "2026-10-05 (s-rta-1005)" are the newest. The questions already put to him, each with an ANSWERS block: ${R4}/boris-clarify-*.md, ${RB}/boris-clarify-*.md.
 (c) WHAT IS PLANNED OR RULED: ${A.plans}; the lane board ${R3}/board.md (the table AND both "LIVE STATE" lists below it); the "LOOSE-ENDS LEDGER" in ${H}/HANDOFF.md.
 (d) TODAY'S FACT SHEETS, already re-read -- cite them, do not redo them (each ends with a "## CORRECTIONS" block that wins over the line it corrects): ${SHEETS5.map(s => s.file).join(', ')}.
WRITE the sheet with exactly these parts:
 1 TODAY -- what the app does in your area now: plain sentences, the on-screen words, one fact per line (20 to 50 lines).
 2 RULED -- what Boris has decided will change, newest first: his words quoted verbatim with their binding-decisions.md line, then what an adopted ruling adds. Mark each line BUILT AND MERGED / BUILT, NOT MERGED / ON PAPER / ONLY HIS WORDS.
 3 OVERTAKEN -- every earlier answer of his, reading, ruling or plan in your area that a LATER word of his replaces or sits against (quote both, with lines). These are what a builder would wrongly follow.
 4 UNCLEAR -- the heart of the sheet: every point where someone building or drawing your area would have to GUESS. For each: (i) what is unclear, one sentence; (ii) why it cannot be settled from what is written -- name what you searched; (iii) whose it is: HIS (he would see or hear the difference, or it is taste or product) or TECHNICAL (the architects decide); (iv) for HIS: the two or three ways it could go, as he would see them on stage, and which way his words lean. Look in particular for: a thing that exists today and that none of his words mention, where his new model (actions, the tempo row, presets, the cue system, the review screen) might change it or make it pointless; two controls that would now do the same thing; a name on screen that changed (look -> preset, routine -> action, BeatLoopr -> Beat Repeat, "keyboard and MIDI mapping") and is not settled everywhere; a rule of his that says what happens in the normal case and not at the edges (an empty layer, the beat stopped, a second press, two things at once, a saved show re-opened).
 5 ALREADY ASKED AND STILL OPEN -- questions put to him that have no answer yet, with their numbers.
 6 NOT UNCLEAR, FOR THE RECORD -- up to 10 things that look open but ARE settled, each with the line that settles it (so that nobody asks him twice).
${CODE}
${RULES}
REPORT_FILE: ${RS}/area-${A.key}.md
RETURN: status, report_path, unclear_his (count), unclear_technical (count), overtaken (count), already_open (question numbers), top_unclear (the <= 8 most important HIS points, each <= 200 characters), summary <= 500 characters.`, { agentType: 'general-purpose', model: 'sonnet', effort: 'high', schema: AFS, phase: 'Areas', label: 'area:' + A.key })
  const rereadArea = (f, A) => agent(`ADVERSARIAL RE-READ of an area sheet (read-only except the sheet itself). The sheet: ${RS}/area-${A.key}.md -- read it whole. Area: ${A.title}. Questions for the app's owner will be written from its part 4, so: (1) every quotation of Boris in parts 2 and 3: open the cited line; not verbatim = WRONG. (2) every point of part 4 marked HIS: search ${BIND} (grep the point's key words) and the ANSWERS blocks of ${R4}/boris-clarify-*.md and ${RB}/boris-clarify-*.md for a line that ALREADY settles it -- a settled point listed as unclear is WRONG (name the line). (3) every claim of part 1 that a part-4 point rests on: open its file:line. (4) then look for what the sheet MISSED: read ${A.docs} for a behaviour in this area that has an edge his rules do not cover, and add up to 8 missed points in the form of part 4.
${WHO}
${NEWMSG3}
${CODE}
${RULES}
WRITE: append to the END of the sheet (bash heredoc with >> ; never rewrite its lines) a block headed "## CORRECTIONS (adversarial re-read)": one line per wrong line (as written -> what is true -> your source), then "MISSED:" and the points you add. If nothing is wrong the block says so and lists what you checked.
REPORT_FILE: ${RS}/area-${A.key}.md
The author's summary: ${cut(f && f.summary, 500)}
RETURN: verdict, checked, wrong, corrections (<= 12, each <= 240 characters; include the missed points you added), summary <= 400 characters.`, { agentType: 'general-purpose', model: 'sonnet', effort: 'high', schema: VS, phase: 'Re-read', label: 'reread:' + A.key })
  // FIXED CALL ORDER (a resume's cache key depends on it): two barriers over literal lists, never a pipeline.
  const ares = await parallel(AREAS.map(A => () => areaOf(A)))
  log('area sheets back: ' + AREAS.map((A, i) => A.key + '=' + (ares[i] ? ares[i].status + ' (' + ares[i].unclear_his + ' his)' : 'none')).join(', '))
  const rres = await parallel(AREAS.map((A, i) => () => rereadArea(ares[i], A)))
  return { leg: 'sweep', areas: AREAS.map((A, i) => ({ key: A.key, file: RS + '/area-' + A.key + '.md', status: ares[i] ? ares[i].status : 'NO_RESULT', his: ares[i] && ares[i].unclear_his, technical: ares[i] && ares[i].unclear_technical, overtaken: ares[i] && ares[i].overtaken, open: ((ares[i] && ares[i].already_open) || []).slice(0, 10), top: ((ares[i] && ares[i].top_unclear) || []).slice(0, 4).map(x => cut(x, 160)), reread: rres[i] ? rres[i].verdict : 'NO_RESULT', wrong: rres[i] && rres[i].wrong, checked: rres[i] && rres[i].checked })) }
}

// ---- leg 2: merge -> ONE list, ONE page ----
const TOPICS = AREAS.map(A => ({ key: A.key, file: RS + '/area-' + A.key + '.md' })).concat(SHEETS5)
const sheets = []
phase('Questions')
log('s-rta-1005 all-questions, leg 2: one list from the first pass (' + ITEMS1 + ') and ' + AREAS.length + ' area sheets; then seats -> ruling -> page -> check.')
const syn = await agent(`${WHO}
${NEWMSG}
${NEWMSG3}
YOUR TASK (architect, read-only except your two files). Make the ONE list that goes on Boris's page: every open question about how the app is to work, and every reading he should confirm. TWO inputs.
INPUT 1 -- THE FIRST PASS, FINAL: ${ITEMS1} with its filing record ${CLAR1}. It was drafted from his answers of today, attacked by three blind seats and ruled on. CARRY EVERY ITEM OF IT OVER UNCHANGED -- same numbers, same words (questions from 172, readings R127 onward, the decided lines, the design-page items, the chat blocks, the intro, the defaults line). You may change a carried item ONLY where an area sheet proves it wrong; then say so in "why_revised" (readings) or in the summary (questions), and never re-number.
INPUT 2 -- TEN AREA SHEETS, each re-read (their "## CORRECTIONS" block wins and its "MISSED:" points count): ${AREAS.map(A => RS + '/area-' + A.key + '.md').join(', ')}. Read of each: part 3 (OVERTAKEN), part 4 (UNCLEAR), part 5 (ALREADY ASKED AND STILL OPEN), part 6 (NOT UNCLEAR) and the CORRECTIONS block -- parts 1 and 2 only where a point needs them (the sheets are long; your window is not). The five fact sheets of the first pass are already distilled into input 1; consult one only for a specific point: ${SHEETS5.map(s => s.file).join(', ')}.
WHAT YOU ADD. For every part-4 point marked HIS, and every part-5 question still open, in every area: is it already covered by an item of input 1? If yes: nothing (note the item). If no: it becomes a NEW question (numbered on from input 1's last question), a NEW reading (numbered on from input 1's last reading) when it has one sensible answer, a "decided, not asked" line when it is really technical, or a design-page item when it needs a picture. Points that several areas raise become ONE item. A point of part 3 (OVERTAKEN) that he was never told becomes a reading: "X, which you said on <date>, is replaced by Y, which you said later".
THE BAR, his: "we will build when all the functionality details are fully understood". Nothing is built until he says all is clear, and he will answer over several sessions -- so the list may be long, but it must be ORDERED so that the first sitting settles the most: put in "parts" (see the shape) Part 1 = what the first builds stand on (firing clips and the tempo row; presets; the cue system; actions; the review screen), Part 2 = the rest of what is being changed (the show file and decks, output screens, clip playback, recording and messages, the keyboard and MIDI mapping and menus), Part 3 = what exists today and stays unless he says otherwise (sources, the automatic features) -- Part 3 is almost all READINGS ("stays as it is"), a question only where his new model collides with it.
TURN BUDGET: you stop silently at 120 turns. Skeleton of BOTH files by your 8th tool call (start by copying input 1's items into the new file with a python one-liner, then add); rewrite about every 10 calls; done by 95.
${HIS}
${CHAT}
${QRULES}
${ITEMSHAPE}
ALSO WRITE the filing record ${CLAR}: plain text in the form of ${RB}/boris-clarify-150-plus.md: a first line saying that it is the list put to him on the page at the close of session s-rta-1005 and that it SUPERSEDES ${CLAR1} as the list of questions as asked (that file stays as the record of the first pass and its ruling); then every question as asked, the readings, the decided lines, the design-page list, and a last heading "## ANSWERS" followed by "(none yet)".
${RULES}
REPORT_FILE: ${ITEMS}
(Second file you may write: ${CLAR}.)
RETURN: status, items_path, clarify_path, questions (count, all), first_question, last_question, readings (count, all), readings_revised (carried readings you changed and why), last_reading, decided_not_asked (count), design_page_items (count), conflicts (<= 8, each <= 220 characters), summary <= 700 characters (say how many questions and readings are carried and how many are new, per part).`, { agentType: 'architect', model: 'opus', effort: 'high', schema: SS, phase: 'Questions', label: 'questions:merge' })
if (!syn || syn.status === 'BLOCKED') { log('the merge did not return a usable result; the first pass (' + ITEMS1 + ') is on disk and stands'); return { leg: 'merge', synthesis: syn || { status: 'NO_RESULT' } } }
log('merge: ' + syn.questions + ' questions (' + syn.first_question + '..' + syn.last_question + '), ' + syn.readings + ' readings to R' + syn.last_reading)
const FIND = { type: 'object', required: ['severity', 'item', 'issue', 'fix'], properties: { severity: { type: 'string', enum: ['MUST', 'SHOULD', 'NIT'] }, item: { type: 'string' }, issue: { type: 'string' }, fix: { type: 'string' } } }
const AS = { type: 'object', required: ['verdict', 'findings', 'summary'], properties: { verdict: { type: 'string', enum: ['PASS', 'PASS_WITH_NITS', 'FAIL'] }, findings: { type: 'array', items: FIND }, missing: { type: 'array', items: { type: 'string' } }, summary: { type: 'string' } } }
const SEATS = [
  { key: 'his-eyes', read: `ONLY the items file ${ITEMS} and his four pictures under ${IMG}/ -- do NOT read the fact sheets, the rulings or the source: you read as HE will.`,
    job: `You are a working VJ who knows Resolume well and is not a programmer. Read every reading, every question, every decided line and every design-page item as he will, on a page. For each: is there a word you would not use on stage; a situation you cannot picture; an option you cannot tell from another; a default that pushes you; two questions that are really one; a question you would have to ask a programmer to answer; a reading that says two things so that "correct only what is wrong" is hard; anything longer than it needs to be. Also: reading the whole list top to bottom, is the ORDER the order in which the answers matter, and would you get through it in one sitting (say how many minutes).` },
  { key: 'nothing-missed', read: `his message ${RAW} sentence by sentence; the last section of ${BIND}; ${RB}/boris-clarify-150-plus.md; the items file ${ITEMS}; the ten area sheets (of each: part 4 UNCLEAR, part 5 and the CORRECTIONS block with its MISSED points) and the five fact sheets: ${TOPICS.map(T => T.file).join(', ')}.`,
    job: `The bar is his: "100% sure of what everything means". (1) Map EVERY sentence of his message to a reading, a question, a decided line or a design-page item: a sentence with no home is a MUST. (2) Every point where a builder would have to guess -- including the pairs of his own statements the sheet facts-actions-open.md lists, every UNKNOWN of the sheets, and all 18 seeds -- must be a question, a reading, a decided line or a design item: a gap is a MUST. (3) A question that a Resolume fact already answers where he said "emulate", or that an earlier answer of his already settles (search binding-decisions.md), is a MUST (it should be a reading). (4) A "decided, not asked" line that is really his to decide (he would see or hear the difference and might want the other way) is a MUST. (5) The defaults he accepted (151 A, 155 A, 156 A, 157 A, 158 A, 165 A, 166 A, 167 A, 171 A) against his new words: any that his new words quietly overturn must be said. (6) THE WHOLE APP: every part-4 point marked HIS and every MISSED point of the ten area sheets must be covered by an item (a question, a reading, a decided line or a design item); list each uncovered one under missing. (7) THE FIRST PASS: every item of ${ITEMS1} is in ${ITEMS} with the same number and the same words; a dropped or re-numbered one is a MUST.` },
  { key: 'facts-and-words', read: `the items file ${ITEMS}; ${CLAR}; the fact sheets with their CORRECTIONS blocks: ${TOPICS.map(T => T.file).join(', ')}; ${BIND}; ${BACKLOG}; the earlier filing records ${R4}/boris-clarify-*.md and ${RB}/boris-clarify-*.md.`,
    job: `(1) Every statement in the items about what the app does TODAY or what Resolume does must rest on a sheet line that survived its re-read: a statement that rests on a corrected or INFERRED line and is worded as a fact is a MUST. (2) Every phrase attributed to Boris ("his_words", the conflicts, any quotation inside a text) must be verbatim in binding-decisions.md or the backlog: grep each; one changed character is a MUST. (3) NUMBERS: no question number from 172 on exists in any earlier filing record; readings R127-R147 carry the topics they were filed with (compare with the last section of the backlog); new readings start at R148; no gaps, no repeats. (4) A question that was already shown to him under a number up to 171 and is asked again or re-worded is a MUST. (5) The filing record ${CLAR} says the same as the items file, item for item. (6) The JSON is valid and has every key of its shape.` },
]
phase('Seats')
const papers = (await parallel(SEATS.map(S => () => agent(`${WHO}
BLIND SEAT "${S.key}" on the list of readings and questions that will be put to Boris. You do not know what the other seats say. Read-only: you write NO file; your paper is your return value.
READ: ${S.read}
YOUR JOB. ${S.job}
SEVERITY: MUST = he would be misled, could not answer, or something he said is lost; SHOULD = it would cost him time or a second round; NIT = wording. For each finding name the item ("Q174", "R131", "decided 3", "design 2", "intro"), say what is wrong in one or two sentences, and give the fix as the exact new wording or the exact thing to add.
${NEWMSG}
${NEWMSG3}
${QRULES}
${RULES.replace('except the ONE file named on your REPORT_FILE line (write it with a bash heredoc with a QUOTED delimiter to the literal absolute path; create a skeleton within your first ~8 tool calls, then fill it and rewrite it as you learn)', '(you write no file at all)')}
RETURN: verdict, findings (every one you have; no cap), missing (things that should be on the list and are not; each <= 300 characters), summary <= 500 characters.`, { agentType: 'authored-council-seat', model: 'sonnet', effort: 'high', schema: AS, phase: 'Seats', label: 'seat:' + S.key }).then(p => p ? { seat: S.key, verdict: p.verdict, findings: p.findings || [], missing: p.missing || [], summary: p.summary } : null)))).filter(Boolean)
const PAPERS = JSON.stringify(papers, null, 1)
log('seat papers WHOLE to the ruling: ' + PAPERS.length + ' characters; ' + papers.map(p => p.seat + '=' + p.verdict + ' (' + p.findings.length + ' findings, ' + p.findings.filter(f => f.severity === 'MUST').length + ' MUST, ' + p.missing.length + ' missing)').join('; '))

const US = { type: 'object', required: ['status', 'accepted', 'rejected', 'questions', 'last_question', 'last_reading', 'summary'], properties: { status: { type: 'string', enum: ['DONE', 'PARTIAL', 'BLOCKED'] }, accepted: { type: 'number' }, partial: { type: 'number' }, rejected: { type: 'number' }, rejected_notes: { type: 'array', items: { type: 'string' } }, questions: { type: 'number' }, first_question: { type: 'number' }, last_question: { type: 'number' }, readings: { type: 'number' }, last_reading: { type: 'number' }, decided_not_asked: { type: 'number' }, design_page_items: { type: 'number' }, question_titles: { type: 'array', items: { type: 'string' } }, still_unsure: { type: 'array', items: { type: 'string' } }, summary: { type: 'string' } } }
phase('Rule')
const rule = await agent(`${WHO}
YOUR TASK (architect; a RULING on three blind papers, then the final list). An architect drafted the readings and questions that go to Boris: ${ITEMS} and its filing record ${CLAR}. Three blind seats attacked the draft; their papers are below, WHOLE. Rule on EVERY finding and every "missing" line: ACCEPT (do it), PARTIAL (do part, say which), REJECT (say why in one line -- a rejection needs a fact or a word of his, not a preference). Then REWRITE both files in place so that they are final. You are bound by the same rules as the draft's author (below). Where two seats pull opposite ways (the "his-eyes" seat wants fewer and shorter, the "nothing-missed" seat wants more), the rule is: nothing he said may be lost and no builder may be left guessing -- but a point with one sensible answer is a READING, not a question, and a point that needs a picture goes to the design page.
TURN BUDGET: you stop silently at 120 turns. Read the two files and the papers first; write your rulings table to the end of ${CLAR} under "## RULING ON THE SEATS' PAPERS" (one line per finding: seat, item, ACCEPT / PARTIAL / REJECT, what changed) BEFORE the "## ANSWERS" heading, which stays last with "(none yet)"; rewrite the items file by your 40th call; be done by 90. Verify the JSON loads.
THE SOURCES, should a finding need them: his message ${RAW}; ${BIND} (last section); ${BACKLOG} (last section); ${RB}/boris-clarify-150-plus.md; the fact sheets with their CORRECTIONS blocks: ${TOPICS.map(T => T.file).join(', ')}.
${HIS}
${CHAT}
${NEWMSG}
${NEWMSG3}
${QRULES}
${ITEMSHAPE}
CARRIED ITEMS: every item of the first pass (${ITEMS1}) stays in the list with its number and its words unless a finding proves it wrong.
LAST CHECK before you return: read your final list once as Boris would. For each question ask: could he answer this in ten seconds from his own experience on stage? For the whole list: is there any sentence of his message whose meaning Harmony would still have to guess after he answers? List those under still_unsure.
${RULES}
REPORT_FILE: ${ITEMS}
(Second file you may write: ${CLAR}.)
THE THREE PAPERS, WHOLE (${PAPERS.length} characters):
${PAPERS}
RETURN: status, accepted, partial, rejected, rejected_notes (each <= 220 characters), questions (count), first_question, last_question, readings (count), last_reading, decided_not_asked (count), design_page_items (count), question_titles (one per question: "172 [topic] <= 12 words"), still_unsure (each <= 240 characters), summary <= 700 characters.`, { agentType: 'architect', model: 'opus', effort: 'max', schema: US, phase: 'Rule', label: 'rule:final-list' })
if (!rule || rule.status === 'BLOCKED') { log('the ruling pass did not return a usable result; the DRAFT list is on disk, unruled'); return { sheets: sheets.map(s => ({ key: s.key, status: s.facts && s.facts.status, reread: s.reread && s.reread.verdict })), synthesis: syn, seats: papers.map(p => ({ seat: p.seat, verdict: p.verdict, findings: p.findings.length })), rule: rule || { status: 'NO_RESULT' } } }

const PAGE = RS + '/boris-all-questions.html'
const PS = { type: 'object', required: ['status', 'page_path', 'bytes', 'questions_on_page', 'readings_on_page', 'summary'], properties: { status: { type: 'string', enum: ['DONE', 'PARTIAL', 'BLOCKED'] }, page_path: { type: 'string' }, bytes: { type: 'number' }, questions_on_page: { type: 'number' }, readings_on_page: { type: 'number' }, pictures_on_page: { type: 'number' }, summary: { type: 'string' } } }
phase('Page')
const page = await agent(`${WHO}
YOUR TASK. Write Boris's page: ONE self-contained HTML file (inline CSS, no script that fetches anything, no external font or link) from the items file ${ITEMS} (final; read it whole). He reads it in his browser and answers in chat ("172 a"). "As usual" means: it looks and reads like his last page -- open ${RB}/boris-open.html and reuse its look (colours, type, the card for a question, how a default is marked, how readings are listed) so that he recognises it.
ORDER ON THE PAGE: (1) a short top: what this page is; how to answer ("172 a"; for a reading "R150 no: ..."); that nothing is built until he says all is clear, with his own words quoted exactly as the items file's intro gives them; how many questions and readings there are, in how many parts, and that he need not do it in one sitting. (2) an INDEX: the parts and their topics as links, with the number of questions in each. (3) then PART BY PART in the order of the items file's "parts", and inside a part TOPIC BY TOPIC (the "topics" names as headings): first that topic's readings under "What I understood -- correct only what is wrong" (a revised reading shows one small line saying what changed; his picture beside the readings it belongs to, small, a click opens it full size), then that topic's questions in number order: the number large, the situation, the options with the default marked and its reason, the "why it matters" line, his own words where the item quotes them. (4) "Decided without asking you -- say so if one is wrong". (5) "Comes next as pictures" (the design page list). (6) "What I told you in chat" (the short blocks). (7) the line of defaults he accepted. Every text comes from the items file CHARACTER FOR CHARACTER (escape & < > only); you add no question, no reading, no opinion and no technical word of your own; headings and the few linking words are yours.
PICTURES: the page lives in ${RS}/ ; reference pictures by RELATIVE path ("boris-images/resolume-monitors.jpg", "../s-rta-1004b/boris-images/review-screen-reference.png"); check that each file exists (ls) before you reference it.
CHECK YOUR OWN PAGE before returning: parse it with python3 html.parser (no unclosed tag), count the question cards and the readings and compare with the items file, and grep the page for "undefined", "null", "[object".
${RULES}
REPORT_FILE: ${PAGE}
RETURN: status, page_path, bytes, questions_on_page, readings_on_page, pictures_on_page, summary <= 400 characters.`, { agentType: 'general-purpose', model: 'sonnet', effort: 'high', schema: PS, phase: 'Page', label: 'page:boris-open2' })

const CS = { type: 'object', required: ['verdict', 'questions_on_page', 'readings_on_page', 'mismatches_found', 'problems_left', 'summary'], properties: { verdict: { type: 'string', enum: ['SOUND', 'FIXED', 'UNRELIABLE'] }, questions_on_page: { type: 'number' }, readings_on_page: { type: 'number' }, mismatches_found: { type: 'number' }, fixed: { type: 'array', items: { type: 'string' } }, problems_left: { type: 'array', items: { type: 'string' } }, summary: { type: 'string' } } }
phase('Check')
const chk = page && page.status !== 'BLOCKED' ? await agent(`${WHO}
CHECK Boris's page against its sources before he sees it (you did not write it). The page: ${PAGE}. Its only source of text: ${ITEMS}. The filing record: ${CLAR}.
(1) ITEM FOR ITEM: every question, option, default mark, "why" line, reading, decided line, design-page item, chat block and the defaults line of the items file is on the page, character for character (after HTML un-escaping), in the right place; nothing is on the page that is not in the items file except headings and linking words. Do it with a script (python3: load the JSON, strip the page's tags, un-escape, and test each text as a substring), not by eye; report the count tested and each miss.
(2) HIS WORDS: every phrase the page attributes to Boris is verbatim in ${BIND} or ${BACKLOG} (grep each).
(3) NUMBERS: questions run from the items file's first_question to last_question without a gap; no question number exists in an earlier filing record (${R4}/boris-clarify-*.md, ${RB}/boris-clarify-*.md) as a different question; readings: none repeats a number below R127 with a different text.
(4) PICTURES: every img src resolves to an existing file relative to ${RS}/ .
(5) PLAIN WORDS: flag any code name, file name, stage id, or the words "delta", "ruling", "lane", "quantize-out", "packet" in a text he reads; and any name for the keyboard and MIDI mapping other than that one ("the key / pad list", "bindings": his words of 2026-10-05 14:16, the last bullets of today's section of binding-decisions.md).
(6) THE HTML parses (python3 html.parser), has no script that loads anything, no external link.
You MAY FIX the page yourself for a mechanical defect of (1), (2), (4) or (6) (a dropped character, a wrong escape, a broken path) -- say exactly what you changed; anything else you report and do not edit. You may NOT edit the items file or the filing record.
${RULES}
REPORT_FILE: ${RS}/boris-all-check.md (your findings; the page is the only other file you may touch, and only for the fixes named above)
RETURN: verdict (SOUND = nothing wrong; FIXED = only mechanical defects, all fixed by you; UNRELIABLE = a defect is left), questions_on_page, readings_on_page, mismatches_found, fixed (each <= 200 characters), problems_left (<= 8, each <= 240 characters), summary <= 400 characters.`, { agentType: 'general-purpose', model: 'sonnet', effort: 'high', schema: CS, phase: 'Check', label: 'check:boris-open2' }) : null

return {
  sheets: sheets.map(s => ({ key: s.key, file: s.file, status: s.facts ? s.facts.status : 'NO_RESULT', verified: s.facts && s.facts.lines_verified, unknowns: ((s.facts && s.facts.unknowns) || []).slice(0, 6).map(x => cut(x, 200)), surprises: ((s.facts && s.facts.surprises) || []).slice(0, 5).map(x => cut(x, 200)), reread: s.reread ? s.reread.verdict : 'NO_RESULT', wrong: s.reread && s.reread.wrong, checked: s.reread && s.reread.checked })),
  synthesis: { status: syn.status, questions: syn.questions, readings: syn.readings, conflicts: (syn.conflicts || []).slice(0, 8).map(x => cut(x, 220)) },
  seats: papers.map(p => ({ seat: p.seat, verdict: p.verdict, findings: p.findings.length, must: p.findings.filter(f => f.severity === 'MUST').length, missing: p.missing.length })),
  rule: { status: rule.status, accepted: rule.accepted, partial: rule.partial, rejected: rule.rejected, rejected_notes: (rule.rejected_notes || []).slice(0, 8).map(x => cut(x, 220)), questions: rule.questions, first_question: rule.first_question, last_question: rule.last_question, readings: rule.readings, last_reading: rule.last_reading, decided_not_asked: rule.decided_not_asked, design_page_items: rule.design_page_items, question_titles: (rule.question_titles || []).map(x => cut(x, 120)), still_unsure: (rule.still_unsure || []).slice(0, 8).map(x => cut(x, 240)), summary: cut(rule.summary, 700), items_path: ITEMS, clarify_path: CLAR },
  page: page ? { path: page.page_path, status: page.status, bytes: page.bytes, questions: page.questions_on_page, readings: page.readings_on_page, pictures: page.pictures_on_page } : { status: 'NO_RESULT' },
  check: chk ? { verdict: chk.verdict, questions_on_page: chk.questions_on_page, readings_on_page: chk.readings_on_page, mismatches_found: chk.mismatches_found, fixed: (chk.fixed || []).slice(0, 6).map(x => cut(x, 200)), problems_left: (chk.problems_left || []).slice(0, 8).map(x => cut(x, 240)), summary: cut(chk.summary, 400) } : { verdict: 'NO_RESULT' },
}
