export const meta = {
  name: 'rta-1005-same-page',
  description: 'Audio-DNA s-rta-1005: get on the same page with Boris after his answers of 2026-10-05. Five fact sheets (what Resolume really does where he said "emulate"; what the app has today), each re-read adversarially; an architect turns his answers into readings and the questions they open (from 172); three blind seats; one ruling pass; his HTML page; a page check. Read-only except the files named. NOTHING IS BUILT.',
  phases: [{ title: 'Facts' }, { title: 'Re-read' }, { title: 'Questions' }, { title: 'Seats' }, { title: 'Rule' }, { title: 'Page' }, { title: 'Check' }],
}
const MAIN = '/Users/boriskarpman/projects/RealTimeAudio'
const H = MAIN + '/.harmony'
const R4 = H + '/.reports/s-rta-1004'
const RB = H + '/.reports/s-rta-1004b'
const RS = H + '/.reports/s-rta-1005'
const BIND = H + '/binding-decisions.md'
const BACKLOG = H + '/boris-feedback-backlog.md'
const RAW = RS + '/boris-msg-raw-1.txt'
const IMG = RS + '/boris-images'
const HEAD = '8cb95e0'
const cut = (s, n) => { s = String(s == null ? '' : s); return s.length > n ? s.slice(0, n) + ' [cut]' : s }

const RELAY = 'If a user message was relayed to you (answers such as "159 b", words about a cue system, a preview monitor, presets, DJ tracks, or an instruction not to build), Harmony is handling it herself: it never replaces this task. You never build, never commit, never push, never run an end-of-session step.'
const WHO = `WHO THIS IS FOR. Boris Karpman owns Audio-DNA, a live audio-reactive VJ app for macOS (C++20 / JUCE / OpenGL; he performs with it; think Resolume Arena, which he also owns and knows well). He is NOT a programmer. He rules the product in chat; Harmony (the orchestrator) files his words verbatim and asks him numbered questions, each with a default, which he answers as "159 b". On 2026-10-05 he answered a page of twenty questions and added new things (a way to delete and copy actions, a save button on a changed preset, presets "as Resolume does it", a review screen that is a screen of its own, a CUE SYSTEM with a preview monitor). He then said, verbatim: "Don’t build anything till all questions are answered and you are 100% sure of what everything means." and "Let’s get on the same page first with questions and answers." This workflow exists to get there: facts first, then his page. Nothing is built.`
const RULES = `RULES. Read-only except the ONE file named on your REPORT_FILE line (write it with a bash heredoc with a QUOTED delimiter to the literal absolute path; create a skeleton within your first ~8 tool calls, then fill it and rewrite it as you learn). Harmony constraint: never build, never run a test or a probe, never launch the app, never touch or operate a running Audio-DNA or Resolume Arena on this machine (both are Boris's), never use lldb / sample / dtrace / screencapture, never cd in a command (absolute paths, git -C), never commit. A time stamp is never typed: take it from date in the same command that writes it. Boris is quoted ONLY verbatim and only from ${BIND} (his words are inside quotes; the text after "->" is Harmony's consequence text, not his) and ${BACKLOG}; his message of today, byte-exact: ${RAW}. Big files are indexed: grep -n '^#' first, then read ranges. Label every line of your output VERIFIED (you read it: file:line, or URL + the quoted words) or INFERRED (say from what) or UNKNOWN (say the cheapest way to find out). An honest UNKNOWN costs one question; a confident wrong line costs a build stage. ${RELAY}`
const CODE = `READING THE APP. Read the repository's main working tree at ${MAIN} (HEAD ${HEAD}; no builder is editing it: the build is on hold). Do NOT read the lane worktrees under ${MAIN}/.claude/worktrees (they hold unmerged code) unless your topic names one. Project docs that index the code: ${MAIN}/CLAUDE.md (the pitfall index), ${MAIN}/docs/claude/*.md, ${H}/APP-INVENTORY.md. Fact sheets of 2026-10-04 that you may cite instead of re-deriving (but re-check at least five load-bearing lines of any sheet you lean on): ${RB}/facts-actions-today.md, ${RB}/facts-quantize.md. Use the app's on-screen words when you name a control (read the string in the source), and give the class and file:line beside it.`
const HIS = `HIS WORDS OF TODAY, where to read them: ${BIND} -- the LAST section, headed "2026-10-05 (s-rta-1005)" (one bullet per topic: his words in quotes, then "->" and Harmony's consequence); ${BACKLOG} -- the LAST section (whole message verbatim, his four pictures described, Harmony's readings R127-R147, items BF126-BF149). The page he answered, with each question as asked and its ANSWERS block: ${RB}/boris-clarify-150-plus.md. His pictures (LOOK at them with the Read tool): ${IMG}/resolume-monitors-menu.jpg, ${IMG}/resolume-monitors.jpg (Resolume's Composition Monitor above its Clip Monitor, and the monitor's menu), ${IMG}/resolume-effects-tab-presets.png (an effect with its presets listed under it in the effects tab), ${IMG}/resolume-effect-panel-presets-menu.png (the effect's panel with the presets menu open: Default, Blue, Green, Red, Manage..., Save); from 2026-10-04: ${RB}/boris-images/review-screen-reference.png, resolume-tempo-bar.png, resolume-bpm-sync-panel.png.`

const FS = { type: 'object', required: ['status', 'report_path', 'lines_verified', 'unknowns', 'summary'], properties: { status: { type: 'string', enum: ['DONE', 'PARTIAL', 'BLOCKED'] }, report_path: { type: 'string' }, lines_verified: { type: 'number' }, lines_inferred: { type: 'number' }, unknowns: { type: 'array', items: { type: 'string' } }, surprises: { type: 'array', items: { type: 'string' } }, summary: { type: 'string' } } }
const VS = { type: 'object', required: ['verdict', 'checked', 'wrong', 'corrections', 'summary'], properties: { verdict: { type: 'string', enum: ['SOUND', 'SOUND_WITH_CORRECTIONS', 'UNRELIABLE'] }, checked: { type: 'number' }, wrong: { type: 'number' }, corrections: { type: 'array', items: { type: 'string' } }, summary: { type: 'string' } } }

const TOPICS = [
  { key: 'resolume', type: 'researcher', file: RS + '/facts-resolume-emulate.md', code: false,
    why: 'Where Boris said "Please emulate this" or "look at how resolume does it", the answer to "how exactly?" is a FACT about Resolume Arena / Avenue 7, not a question for him. Establish those facts from Resolume\'s own manual (resolume.com/support), its forum (staff answers) and its own tutorial videos; a third-party page or your own reasoning is INFERRED. Say which version a statement is for (his pictures say "Arena Presets": Arena 7.x).',
    ask: `A. EFFECT PRESETS. (A1) Where the preset control sits on an effect in a clip / layer / composition panel and what its menu holds (his picture: Default, the presets, "Manage...", "Save"); what the second small "P" in the effect's Blend Mode row is. (A2) What "Save" does exactly: is there a name window, what text does it start with, does saving under an existing name replace that preset, is there a "Save As". (A3) What "Manage..." opens and how a preset is renamed or deleted. (A4) Does the panel show WHICH preset is loaded (a name, a tick in the menu), and what happens to that after a parameter is changed (any "changed" mark?). (A5) The Effects tab: presets listed under each effect -- how it folds; what dragging a PRESET onto a clip, a layer or the composition does (the effect arrives with that preset?); what dragging the effect itself gives. (A6) Where presets live on disk; whether a preset holds only parameter values or also animation / BPM / audio (FFT) links and dashboard links.
B. MONITORS AND PREVIEW. (B1) The output (Composition) monitor and the Preview monitor: what each shows; every entry of the monitor's menu in his picture (Composition, Preview, Selected Clip; Layers: Selected Layer, Layer N; Crossfader: Result, Bus A, Bus B; Snapshot; Copy Image; Transform Widget) -- what each does. (B2) A click on a clip's NAME against a click on its THUMBNAIL: which selects / previews and which triggers; what the Preview monitor then shows: does the previewed clip PLAY or show a still, with its own effects or without, does it have its own transport, does previewing touch the output in any way. (B3) A LAYER shown in a monitor: is it shown before its fader (visible at full strength even with the layer's opacity at 0 or the layer bypassed), with the layer's effects, with or without the composition's effects; can MORE THAN ONE layer be shown mixed in a monitor (Boris wants several at once: is there anything like it, e.g. groups). (B4) Can the preview be sent to a second screen. (B5) Any stated cost or limit of previewing.
C. BPM SYNC AND WHEN A CLIP STARTS. (C1) A clip whose transport is BPM Sync, triggered in the middle of a bar: with Beat Snap off, and with Beat Snap on -- where Beat Snap is set (composition, layer, clip), its values, and what exactly happens between the click and the snap point (does the previous clip keep playing, does the new clip show, is there a waiting indicator on the clip). (C2) Is any snap IMPLIED for a BPM Sync clip when Beat Snap is off? What BPM Sync alone does to where the clip starts (from its beginning at the click, or jumped to the position that is in time with the bar). (C3) The tempo bar: what its pause and its stop (if any) do, what Resync and Tap do, what BPM Sync clips do while the tempo is paused, whether triggering a clip while the tempo is paused or stopped starts anything. (C4) Triggering a whole column: how, and what Beat Snap does to it.
D. BRIEF CONTEXT (at most 12 lines): does Resolume have anything like a recorded performance shown as one row per parameter on a timeline (its per-parameter envelope / animation editor; "Record"); what a parameter's "ignore" or "bypass" of automation looks like there, if anything.` },
  { key: 'cue-today', type: 'general-purpose', file: RS + '/facts-app-cue-today.md', code: true,
    why: 'Boris asked for a CUE SYSTEM: a preview monitor below the output monitor, a cue button per layer under it (every cued layer is shown in the preview, mixed, as a DJ cues tracks before mixing them in), and a click on a clip\'s name shows that clip in the preview without firing it. Before anyone asks him a question or draws it, Harmony needs to know what the app has TODAY. Facts only: no design, no proposal.',
    ask: `(1) THE MONITOR TODAY: the Preview / Output panel in the main window -- its class, where it sits, its size rules, what it draws (the composition canvas, letter-boxed) and from what texture or surface, its Resolution drop-down; whether any second monitor, preview or thumbnail-of-the-output exists anywhere. (2) A CLIP CELL in the deck grid: its parts (thumbnail, a name strip at the bottom?) and what TODAY a click on each part does (fire? select?), a double-click, a right-click, a drag; what "selected clip" means in the app and what the Clip tab follows; how the keyboard launcher fires. (3) THE COLUMN NUMBERS: what a click on a column number does; the eight routine pads above them (where exactly, their size). (4) THE LAYER STRIP: each per-layer control (fader, B, S, X, the transport buttons the ledger says do nothing) and what Bypass and Solo do in the compositor; what a layer at fader 0 costs and shows. (5) WHAT A SECOND PICTURE WOULD COLLIDE WITH (facts with file:line, no design): can the renderer today draw a SUBSET of layers to a second target; can it draw a clip that is on no layer (how ClipThumbnails makes its pictures: one decoded frame? with effects or raw?); which per-layer state is single-instance (temporal / feedback history keyed by the layer: Pitfalls 13, 14, 35; video decode rings: Pitfalls 53-56, 60; the canvas rule: Pitfall 37; the 8 ms frame budget) so that drawing the same layer twice in one frame would disturb the output. (6) THE BEAT AT LAUNCH: when the app starts, and when a show is opened, is the beat clock running, and at what tempo (the tracker, Manual BPM)? Is anything about a paused or stopped beat stored in a show today?` },
  { key: 'presets-delta', type: 'general-purpose', file: RS + '/facts-presets-delta.md', code: true,
    why: 'The per-effect PRESETS lane is planned and ruled twice on paper and NOT built; its second ruling is NOT adopted. Today Boris said presets must look and work as in his two Resolume pictures, and added a small save button that appears when a preset is changed. Harmony needs the exact difference between what is ruled on paper and his new words, so that she adopts no dead decision and asks him nothing the paper already answers.',
    ask: `(1) THE APP TODAY: the effects tab / browser (class, its categories, what an item is, fold arrows, what can be dragged from it and onto what); the header of an effect in the inspectors' effect stack (EffectStackView: what it reads, its buttons); the old look buttons that stage S7 of the one-save lane removes (the small Save, Load, FX Save, the ten numbered slots). (2) THE RULED DESIGN ON PAPER -- read ${RB}/ruling-looks-answers2.md (sections 0, 3, 6, 7, 8), ${R4}/ruling-looks-answers.md and ${R4}/ruling-effect-looks.md (their verdict, amendments and "what only Boris can check" sections), and the adoption blocks at the END of ${R4}/plan-effect-looks.md and ${R4}/plan-looks-answers.md and the "ADOPTION OWED" block at the end of ${RB}/plan-looks-answers2.md: what the "small button" on an effect is, where it sits, what it reads in each state, every entry of its menu, the New Preset / Save over / Rename / Delete flows, where presets are stored, whether presets appear in the effects tab at all, whether a preset can be dragged, how the preset's name is kept with the show, identity by name against an id (HD-24). (3) A TABLE, one row per element: his NEW words (the bullets on 150 and 169 in the last section of binding-decisions.md; BF129, BF138; his two pictures) against the ruled design: STAYS / CHANGES (from what, to what) / NEW (in no ruling) / CONFLICT WITH AN EARLIER ANSWER OF HIS (quote both with their binding-decisions.md line numbers: search his answers 131-134, 138, 150 and the words "the name stays"). (4) Decisions HD-23..HD-31 of ruling-looks-answers2.md section 8: for each, one line -- still meaningful after his new words, or overtaken (by which words). (5) Reading R121 as shown to him (${RB}/boris-clarify-150-plus.md): what of it still holds if Rename and Delete live in a "Manage..." entry.` },
  { key: 'takes-bpm-fire', type: 'general-purpose', file: RS + '/facts-takes-bpm-fire.md', code: true,
    why: 'Three of Boris\'s answers of today touch machinery that is ruled or built: (a) "the replay window looks different than live window ... a screen at the top with the video and the timeline for each parameter below it ... If the user clicks in any track the video will jump to that frame"; (b) "a clip that has BPM mode enabled will start playing on the next 1 if it is triggered in the middle of a bar. This is automatic quantization that is implied when the clip has BPM mode."; (c) "if I fire a clip while the beat is stopped, it starts playing the beat. When paused, it will not play but will still display." Harmony needs the facts under each before she asks him anything.',
    ask: `(1) A TAKE TODAY: what a recorded take stores (which kinds of events, the audio, a checkpoint of the show); that no video is stored (verify); how a replay works today (through the LIVE layers and outputs? restore-then-replay?); whether the app can today show the take's picture at an ARBITRARY moment without playing from the start (what a jump would cost: re-applying events from the checkpoint?); what the Record tab shows. Cite ${RB}/facts-actions-today.md where it already answers and re-check five of its load-bearing lines. (2) WHAT A TAKE CAPTURES of a slider moved with the mouse, the layer strip's buttons, a preset load (reading R124 says: not today). (3) A BPM-MODE CLIP TODAY: what the mode is called on screen; what happens today when such a clip is fired in the middle of a bar with Quantize off and with Quantize = 1 bar (Layer::triggerClip, the pending trigger, the drain): what the layer SHOWS between the press and the line (the old clip plays on? nothing?). (4) WHAT IS RULED (not built) -- quote the ruled behaviour and name the amendment and the stage: ${RB}/ruling-nudge-row2.md (section 0 part 3 "WHERE LIVE QUANTIZE GOES", the amendments on the lane quantize-out, the stop / pause / play / Resync rules, readings R103-R114 in its section 7) and the transport lane's rulings ${R4}/ruling-transport-delta2.md and ${R4}/ruling-transport-answers.md (the BPM Sync "bar lock", his "121 a", what a BPM Sync clip does when fired while the beat is held) with the adoption blocks at the END of ${R4}/plan-transport-delta2.md, ${R4}/plan-transport-answers.md, ${R4}/plan-nudge-row.md and ${RB}/plan-nudge-row2.md. (5) THE DIFFERENCE: his words (b) and (c) against those rulings -- which ruled rule, amendment, stage and test row each of his sentences changes; and every EARLIER answer of his that his new words sit against (quote both with binding-decisions.md line numbers; e.g. his words on 126 / 127, 128, 135, 136 and "This is not for live usage."). (6) Does anything in the ruled lane quantize-out REMOVE what (b) needs (a fire that waits for a line)? Name the pieces.` },
  { key: 'actions-open', type: 'general-purpose', file: RS + '/facts-actions-open.md', code: false,
    why: `ACTIONS (which replace routines) and the recording REVIEW SCREEN exist only as Boris's words. On 2026-10-04 a sweep ranked 16 undecided points (${RB}/open-sweep-actions.md); today he answered questions 155-171 and added rules. Harmony needs to know what is now settled, what is still open, and where two of his OWN statements, once combined, disagree or leave a gap. No design: a list.`,
    ask: `Read every word of his on actions and the review screen: binding-decisions.md -- grep -n -i -E "action|review screen|routine|ignore" and read each hit's bullet (the sections of 2026-10-04 (s-rta-1004), (s-rta-1004b) and 2026-10-05 (s-rta-1005)); the backlog items BF96-BF120 and BF126-BF149; the readings R89-R108, R122-R147; the questions as asked in ${RB}/boris-clarify-135-143.md and ${RB}/boris-clarify-150-plus.md with their ANSWERS blocks (note: "All defaults good except for these." -- every question of 150-171 he did not name is at its default A). Then: (1) THE RULES AS THEY STAND, one line each, his words quoted, grouped: what an action is and who owns it; how it is made; how it starts, loops and follows the tempo; on / off, two at once, global over layer; the hand on a slider; ignore; copy / delete / paste; how many buttons; the review screen (rows, grid, In / Out, the picture, stop and scrub); what a recording keeps. (2) The 16 points of open-sweep-actions.md: for each -- SETTLED (by which words) / STILL OPEN / CHANGED. (3) PAIRS OF HIS OWN STATEMENTS that disagree or leave a gap once combined -- quote both. Look at least at: "159 b" (sliders go back to where they were before the action started) together with 160 A (two actions on one slider), 156 A (a layer's actions come back after a global one), 158 A (the hand on a slider) and a slider he moved by hand while the action was on; 157 A (an action waits for the next "1") together with his words of today on BPM-mode clips and on R123; "162 b" (an ignore is saved) together with "user can save an option with the ignore action items not in it"; "164" (8 for clips, 8 for layer, 16 for global) together with where today's eight routine pads sit and how wide a clip cell is; 165 A (a copied clip keeps its actions) together with copy / paste of an action onto a clip that lacks the effect the action moves; "169" (a row for every parameter and button that can be adjusted) -- estimate how many rows that is for a typical show from the facts in ${RB}/facts-actions-today.md; "170" (the review screen has its own picture, a click jumps to that frame) together with R110 (a replayed recording) and 167 A (he can draw and mend a curve there); R109 (stop also stops routines) once routines are actions. (4) WHAT NO WORD OF HIS COVERS YET and a builder would have to guess.` },
]

phase('Facts')
log('s-rta-1005 same-page: ' + TOPICS.length + ' fact sheets, each re-read; then questions -> seats -> ruling -> page -> check. Nothing is built.')
const factsOf = T => agent(`${WHO}
WHY THIS SHEET EXISTS. ${T.why}
ESTABLISH (answer every lettered or numbered point; a point you cannot settle is listed as UNKNOWN with the cheapest way to settle it -- "Boris has Arena on this machine: one click of his answers it" is a valid way; operating Arena yourself is not):
${T.ask}
${T.code ? CODE : ''}
${HIS}
${RULES}
OUTPUT. The sheet, in plain sentences a planner can build on: one fact per line, each with its label and its source; a short "SURPRISES" list (anything that contradicts what the questions above assume); a closing "WHAT I COULD NOT ESTABLISH" list. No design, no recommendation, no question for Boris.
REPORT_FILE: ${T.file}
RETURN: status, report_path, lines_verified, lines_inferred, unknowns (<= 12, each <= 220 characters), surprises (<= 8, each <= 220 characters), summary <= 500 characters.`, { agentType: T.type, model: 'sonnet', effort: 'high', schema: FS, phase: 'Facts', label: 'facts:' + T.key })
const rereadOf = (f, T) => agent(`ADVERSARIAL RE-READ of a fact sheet (read-only except the sheet itself). The sheet: ${T.file} -- read it whole. Harmony will put questions to the app's owner and architects will plan on it: your job is to find the lines that are WRONG before they do. ${T.code ? 'Re-open the cited file:line of EVERY line labelled VERIFIED that names source code or a ruling, and of at least fifteen load-bearing lines in all; a citation that does not say what the line claims is WRONG.' : (T.type === 'researcher' ? 'Re-fetch the cited page of the fifteen most load-bearing lines (the ones on what "Save" and "Manage..." do, on name against thumbnail clicks, on what a layer in a monitor shows, on Beat Snap and BPM Sync, on the tempo bar): a line whose source does not say it is WRONG; a line labelled VERIFIED whose source is not Resolume\'s own manual, staff or video is re-labelled INFERRED.' : 'Re-open the cited line of EVERY quotation of Boris (binding-decisions.md, boris-feedback-backlog.md): a quotation that is not verbatim is WRONG; a pair listed as disagreeing that does not disagree is WRONG; then look for a disagreeing pair or an uncovered point the sheet MISSED.')} Also check that nothing in the sheet is a design, a recommendation or a question for the owner (flag it).
${WHO}
${T.code ? CODE : ''}
${HIS}
${RULES}
WRITE: append to the END of the sheet a block headed "## CORRECTIONS (adversarial re-read)" with one line per wrong or re-labelled line: the sheet's line as written -> what is true -> your source. Append it with a bash heredoc using >> ; never rewrite the sheet's own lines. If nothing is wrong the block says so and lists what you checked.
REPORT_FILE: ${T.file}
The author's own summary of the sheet: ${cut(f && f.summary, 600)} Unknowns he listed: ${JSON.stringify((f && f.unknowns) || [])}
RETURN: verdict (SOUND = nothing wrong; SOUND_WITH_CORRECTIONS = wrong lines found and all are in your block; UNRELIABLE = the sheet cannot be planned on), checked, wrong, corrections (<= 12, each <= 260 characters), summary <= 400 characters.`, { agentType: T.type, model: 'sonnet', effort: 'high', schema: VS, phase: 'Re-read', label: 'reread:' + T.key })
    .then(v => ({ key: T.key, file: T.file, facts: f, reread: v }))
// RESUME NOTE (run wf_684eec91-661): a call's cache key depends on the ORDER of the agent() calls, not only on its prompt. The first leg ran as a pipeline: facts in TOPICS order, re-reads in the order the facts came back (REREAD_ORDER). Issuing the ten calls in that same order makes the resume serve all ten from the cache.
const fres = await parallel(TOPICS.map(T => () => factsOf(T)))
const REREAD_ORDER = ['resolume', 'presets-delta', 'actions-open', 'takes-bpm-fire', 'cue-today']
const facts = await parallel(REREAD_ORDER.map(k => () => { const i = TOPICS.findIndex(T => T.key === k); return rereadOf(fres[i], TOPICS[i]) }))
const sheets = facts.filter(Boolean)
log('fact sheets back: ' + sheets.map(s => s.key + '=' + (s.facts ? s.facts.status : 'none') + '/' + (s.reread ? s.reread.verdict : 'none')).join(', '))
const SHEETLIST = TOPICS.map(T => { const s = sheets.find(x => x.key === T.key); return `- ${T.file} (${T.key}): author ${s && s.facts ? s.facts.status : 'NO RESULT'}; re-read ${s && s.reread ? s.reread.verdict + ', ' + s.reread.wrong + ' wrong of ' + s.reread.checked + ' checked' : 'NO RESULT'}. Unknowns: ${JSON.stringify((s && s.facts && s.facts.unknowns) || [])}. Surprises: ${JSON.stringify((s && s.facts && s.facts.surprises) || [])}. Corrections: ${JSON.stringify((s && s.reread && s.reread.corrections) || [])}` }).join('\n')

const CHAT = `WHAT HARMONY ALREADY TOLD HIM IN CHAT on 2026-10-05 (he asked for these four; the page repeats them in a short block and does not ask them again):
R114 -- it is about the live show's tempo row, not about actions. The row's pause and stop are for the whole show; each clip also has its own pause button; the row never flips a clip's own pause. A clip he paused himself is still paused after a row stop and a re-fire; a clip that was playing plays when re-fired. A clip's own pause IS saved with the show (already ruled); what is not saved is the ROW's state (a beat that was paused or stopped).
R116 -- two things about old files only: (1) an old show's Quantize setting is ignored and dropped at the next save; (2) an old recording made with Quantize on wrote down his press, not the bar line the clip was held to, so replayed now the clip changes at his press. Both fall away by his words on R117 (nothing saved is in use).
R120 -- in the keyboard and MIDI mapping (HIS name for the list where functions are put on keys and MIDI pads), two old entries, "Stop" (stops routines) and "Play / Pause" (plays / pauses the audio file), get longer names ("Stop actions", "Audio play / pause") so that they are not taken for the new "Beat stop" / "Beat play". Names only.
R121 -- where presets stand: nothing built; ruled twice on paper; re-planned on his Resolume pictures. Stays: the name stays after a change, no mark. Changes: the effect shows its own name; a preset button with a drop-down above its sliders (Default, his presets, "Manage...", "Save"); a small Save button appears when a slider leaves the preset (a small window, a name, Save); the effects tab lists each effect's presets under it; Rename and Delete move into "Manage...". Rename -> every effect of the open show that carries the preset reads the new name; Delete -> those effects read "Default" and keep their settings.`
const NEWMSG = `A SECOND MESSAGE OF HIS, 2026-10-05 14:16 (it arrived after this workflow's fact sheets were written; byte-exact ${RS}/boris-msg-raw-2.txt; filed as the last two bullets of today's section of ${BIND} and as an "ADDED" block at the end of the last section of ${BACKLOG}), verbatim, two lines: "r120 we call it keyboard and midi 'mapping' lets use this term" and "ask me questions about anything that is unclear when you are ready". CONSEQUENCE, binding for every text he reads: the list where functions are put on keys and MIDI pads is called "keyboard and MIDI mapping" -- never "the key / pad list", "the key and pad list", "bindings" or "the overlay". ONE new reading (numbered like any new reading) says so: look up what that list or window is titled on screen today (the string in the source, file:line as its source) and say what it reads today and that it is called "keyboard and MIDI mapping" from now on. His second line is the invitation this page answers: the intro says so in one short line, quoting it.`
const SEEDS = `HARMONY'S SEED LIST (what she saw open in his answers; not exhaustive; a seed a fact sheet settles is dropped with the fact named; each seed that survives becomes a question, a reading, a "decided, not asked" line or a design-page item):
 1 [154] Between his press and the next "1" for a BPM-mode clip: what the layer shows (the old clip plays on until the "1" / the new clip shows at once, held on its first frame / the case of an empty layer).
 2 [R111] Does ANY fired clip start a stopped beat or only a BPM-mode clip; is his press the "1"; is a column click the same; while PAUSED, a clip that is NOT in BPM mode: does it play at once (his earlier words: pause holds the beat and the BPM-synced clips).
 3 [cue] What the preview shows for a cued layer: the layer before its fader (so he can see it with the fader down, as a DJ hears a track that is not in the mix yet)? with the layer's effects? with or without the global effects? several cued layers mixed with their blend modes?
 4 [cue] A clip previewed by a click on its name: moving or a still; with its own effects; alone or over the cued layers; how the preview returns to the layers; does that click still select the clip for the Clip tab; what a click on the thumbnail does.
 5 [cue] The preview monitor: always shown or foldable; on a second screen or not.
 6 [150] The save window: the name it starts with; saving under a name that exists; does the small Save button also appear on an effect that still reads "Default". Where he said emulate Resolume, Resolume's facts answer.
 7 [169, presets] Dragging a preset from the effects tab; what "Manage..." is. Resolume's facts answer.
 8 [169, review] "a row in the recording for every parameter and button that can be adjusted": rows of controls that never moved in the take -- always shown, or folded under their effect's name.
 9 [170] Where the review screen's picture comes from: re-made from the recorded moves (then a mended curve changes the picture) or a film of the night -- technical, but its consequence is his. While the review screen is open, does the live output go on? Is there still a way to play a whole take back through the live output?
10 [BF127] Paste: onto what can a copied action be pasted; onto a clip that lacks the effect the action moves; what cut means.
11 [BF128] "save an option with the ignore action items not in it": is "option" an action; saved as a NEW action or over the old one.
12 [159 B] "where they were before the action started": after he moved the slider by hand during the action; with two actions on one slider (160 A); with a global action over a layer's (156 A).
13 [160] The light on "the first one that is conflicted": on that action's button; what it says in one sentence.
14 [164] Where the 8 / 8 / 16 buttons and their "+" sit (today eight routine pads sit above the column numbers; a clip cell is narrow).
15 [R117] No carrying-over of old routines, recordings or shows is built; the show-file protection stays.
16 [157 A + 154 + R123] An action on a BPM-mode clip starts with the clip on the "1" and follows the tempo: say it once, as one reading.
17 [R114] The state of the beat when a show is opened.
18 [161] A lamp beside EVERY slider and button costs room on every row (the layer strip is almost full).`
const ITEMS = RS + '/boris-open2-items.json'
const CLAR = RS + '/boris-clarify-172-plus.md'
const QRULES = `WHAT MAKES A GOOD QUESTION FOR HIM. (a) Only what is HIS: what he sees, hears or does on stage, taste, product behaviour, anything costly to undo. NEVER a technical question (which file, which thread, how it is stored): those are decided by the architects and listed under "decided, not asked" in one plain line each with the consequence he would notice. (b) Where he said "emulate" Resolume, a Resolume FACT is the answer: write it as a reading that begins "As in Resolume:" -- ask only where the fact sheet says UNKNOWN or where the app cannot do what Resolume does. (c) A question he has already answered is never asked again; a question already shown to him (numbers up to 171) is never re-worded or re-lettered: a narrower follow-up gets a NEW number and names the old one. (d) Each question is a concrete moment in his show in the second person ("You fire a BPM-mode clip half-way through a bar while another clip plays on that layer."), then two or three options, each at most 45 words, A = the default with the reason it is the default (closest to his words, or what Resolume does, or least surprise), then one "why it matters" line. No code names, no file names, no stage ids, no "quantize-out", no "delta"; his vocabulary: clip, layer, deck, column, the tempo row, the "1", BPM mode, action, preset, the review screen, the preview monitor, cue. (e) As FEW questions as are truly needed: a point with one sensible answer is a READING he corrects only if wrong. Order: the ones that hold up the most building first. Group by topic: A firing clips and the tempo row; B the cue system; C presets; D actions in a show; E the review screen and recordings. (f) Where two of his OWN statements disagree, quote both and ask which wins -- unless the later one plainly replaces the earlier, then it is a reading that says so. (g) Things that need a PICTURE to be judged (where buttons sit, sizes, colours, how the review screen is laid out) are NOT questions: they go on the list "comes next as pictures" for the design page, each with the two or three variants worth drawing.`
const ITEMSHAPE = `THE ITEMS FILE is ONE JSON object (valid JSON, UTF-8, written with a bash heredoc with a quoted delimiter; verify it with python3 -c "import json;json.load(open(...))"):
{ "session": "s-rta-1005", "first_question": 172, "last_question": N, "last_reading": N,
  "intro": [short lines for the top of his page: what this page is; how to answer ("172 a"); that nothing is being built, in his own words quoted verbatim],
  "told_in_chat": [{"r": "R114", "text": "..."}, ...],
  "readings": [{"r": "R127", "topic": "A|B|C|D|E", "about": "150", "text": "...", "state": "as filed | revised | new", "why_revised": "", "label": "his words | As in Resolume (VERIFIED) | INFERRED", "source": "file:line or BD line", "picture": "" }],
  "questions": [{"n": 172, "topic": "A", "about": "154", "situation": "...", "options": [{"k": "A", "text": "...", "default": true, "why_default": "..."}, {"k": "B", "text": "..."}], "why": "...", "his_words": ["verbatim quote", ...], "source": "...", "picture": "" }],
  "conflicts": [{"a": "verbatim quote", "a_where": "BD:line", "b": "verbatim quote", "b_where": "BD:line", "handled_as": "question 17x | reading R1xx"}],
  "decided_not_asked": [{"text": "plain line with the consequence he would notice", "by": "the fact or ruling that settles it"}],
  "design_page": [{"what": "...", "variants": ["...", "..."]}],
  "defaults_taken": "the line listing 151 A, 155 A, ... as he accepted them",
  "seeds": [{"seed": 1, "became": "question 172 | reading R150 | decided | design | dropped: <fact>"}] }
"picture" is a file name under ${IMG}/ or "" (resolume-monitors-menu.jpg, resolume-monitors.jpg, resolume-effects-tab-presets.png, resolume-effect-panel-presets-menu.png) or "../s-rta-1004b/boris-images/review-screen-reference.png". Readings R127-R147 KEEP their numbers (their filed text is in the last section of ${BACKLOG}); where a fact sheet shows a filed reading to be wrong or incomplete, correct its text and set state "revised" with why. New readings start at R148. Questions start at 172 and run without gaps.`
const SS = { type: 'object', required: ['status', 'items_path', 'clarify_path', 'questions', 'last_question', 'last_reading', 'summary'], properties: { status: { type: 'string', enum: ['DONE', 'PARTIAL', 'BLOCKED'] }, items_path: { type: 'string' }, clarify_path: { type: 'string' }, questions: { type: 'number' }, first_question: { type: 'number' }, last_question: { type: 'number' }, readings: { type: 'number' }, readings_revised: { type: 'array', items: { type: 'string' } }, last_reading: { type: 'number' }, decided_not_asked: { type: 'number' }, design_page_items: { type: 'number' }, conflicts: { type: 'array', items: { type: 'string' } }, summary: { type: 'string' } } }

phase('Questions')
const syn = await agent(`${WHO}
YOUR TASK (architect, read-only except your two files). Turn Boris's answers of 2026-10-05 into (1) READINGS -- what Harmony understood, in his words, one plain sentence or two each, so that he corrects only what is wrong; (2) the QUESTIONS his answers open, numbered from 172; (3) what the architects decide without asking him; (4) what must wait for pictures. The bar he set: Harmony must be "100% sure of what everything means" before anything is built. So: every sentence of his message must end up covered by a reading, a question, a decided line or a design-page item, and every point where a builder would have to GUESS must be found now.
TURN BUDGET: you stop silently at 120 turns. Write a skeleton of BOTH files by your 8th tool call; rewrite them about every 10 calls; be done by 90.
READ FIRST, whole: his message ${RAW}; the last section of ${BIND}; the last section of ${BACKLOG} (the readings R127-R147 as filed); ${RB}/boris-clarify-150-plus.md (the questions he answered, as asked, and the ANSWERS block). Then the five fact sheets, each WHOLE including its "## CORRECTIONS" block at the end (a correction wins over the line it corrects):
${SHEETLIST}
${HIS}
${CHAT}
${NEWMSG}
${SEEDS}
${QRULES}
${ITEMSHAPE}
ALSO WRITE the filing record ${CLAR}: a plain text file in the form of ${RB}/boris-clarify-150-plus.md (read its first 30 lines for the form): a first line saying what it is and that next free question and reading follow from the items file; each question as asked (number, topic, situation, options with the default marked, why); the readings; the decided lines; the design-page list; and a last heading "## ANSWERS" followed by "(none yet)".
${RULES}
REPORT_FILE: ${ITEMS}
(Second file you may write: ${CLAR}.)
RETURN: status, items_path, clarify_path, questions (count), first_question, last_question, readings (count), readings_revised (which numbers and why, each <= 200 characters), last_reading, decided_not_asked (count), design_page_items (count), conflicts (<= 8, each <= 220 characters), summary <= 700 characters.`, { agentType: 'architect', model: 'opus', effort: 'high', schema: SS, phase: 'Questions', label: 'questions:synthesis' })
if (!syn || syn.status === 'BLOCKED') { log('synthesis did not return a usable result'); return { sheets: sheets.map(s => ({ key: s.key, status: s.facts && s.facts.status, reread: s.reread && s.reread.verdict })), synthesis: syn || { status: 'NO_RESULT' } } }
log('synthesis: ' + syn.questions + ' questions (' + syn.first_question + '..' + syn.last_question + '), ' + syn.readings + ' readings to R' + syn.last_reading)

const FIND = { type: 'object', required: ['severity', 'item', 'issue', 'fix'], properties: { severity: { type: 'string', enum: ['MUST', 'SHOULD', 'NIT'] }, item: { type: 'string' }, issue: { type: 'string' }, fix: { type: 'string' } } }
const AS = { type: 'object', required: ['verdict', 'findings', 'summary'], properties: { verdict: { type: 'string', enum: ['PASS', 'PASS_WITH_NITS', 'FAIL'] }, findings: { type: 'array', items: FIND }, missing: { type: 'array', items: { type: 'string' } }, summary: { type: 'string' } } }
const SEATS = [
  { key: 'his-eyes', read: `ONLY the items file ${ITEMS} and his four pictures under ${IMG}/ -- do NOT read the fact sheets, the rulings or the source: you read as HE will.`,
    job: `You are a working VJ who knows Resolume well and is not a programmer. Read every reading, every question, every decided line and every design-page item as he will, on a page. For each: is there a word you would not use on stage; a situation you cannot picture; an option you cannot tell from another; a default that pushes you; two questions that are really one; a question you would have to ask a programmer to answer; a reading that says two things so that "correct only what is wrong" is hard; anything longer than it needs to be. Also: reading the whole list top to bottom, is the ORDER the order in which the answers matter, and would you get through it in one sitting (say how many minutes).` },
  { key: 'nothing-missed', read: `his message ${RAW} sentence by sentence; the last section of ${BIND}; ${RB}/boris-clarify-150-plus.md; the items file ${ITEMS}; the five fact sheets with their CORRECTIONS blocks: ${TOPICS.map(T => T.file).join(', ')}.`,
    job: `The bar is his: "100% sure of what everything means". (1) Map EVERY sentence of his message to a reading, a question, a decided line or a design-page item: a sentence with no home is a MUST. (2) Every point where a builder would have to guess -- including the pairs of his own statements the sheet facts-actions-open.md lists, every UNKNOWN of the sheets, and all 18 seeds -- must be a question, a reading, a decided line or a design item: a gap is a MUST. (3) A question that a Resolume fact already answers where he said "emulate", or that an earlier answer of his already settles (search binding-decisions.md), is a MUST (it should be a reading). (4) A "decided, not asked" line that is really his to decide (he would see or hear the difference and might want the other way) is a MUST. (5) The defaults he accepted (151 A, 155 A, 156 A, 157 A, 158 A, 165 A, 166 A, 167 A, 171 A) against his new words: any that his new words quietly overturn must be said.` },
  { key: 'facts-and-words', read: `the items file ${ITEMS}; ${CLAR}; the fact sheets with their CORRECTIONS blocks: ${TOPICS.map(T => T.file).join(', ')}; ${BIND}; ${BACKLOG}; the earlier filing records ${R4}/boris-clarify-*.md and ${RB}/boris-clarify-*.md.`,
    job: `(1) Every statement in the items about what the app does TODAY or what Resolume does must rest on a sheet line that survived its re-read: a statement that rests on a corrected or INFERRED line and is worded as a fact is a MUST. (2) Every phrase attributed to Boris ("his_words", the conflicts, any quotation inside a text) must be verbatim in binding-decisions.md or the backlog: grep each; one changed character is a MUST. (3) NUMBERS: no question number from 172 on exists in any earlier filing record; readings R127-R147 carry the topics they were filed with (compare with the last section of the backlog); new readings start at R148; no gaps, no repeats. (4) A question that was already shown to him under a number up to 171 and is asked again or re-worded is a MUST. (5) The filing record ${CLAR} says the same as the items file, item for item. (6) The JSON is valid and has every key of its shape.` },
]
phase('Seats')
const papers = (await parallel(SEATS.map(S => () => agent(`${WHO}
BLIND SEAT "${S.key}" on the list of readings and questions that will be put to Boris. You do not know what the other seats say. Read-only: you write NO file; your paper is your return value.
READ: ${S.read}
YOUR JOB. ${S.job}
SEVERITY: MUST = he would be misled, could not answer, or something he said is lost; SHOULD = it would cost him time or a second round; NIT = wording. For each finding name the item ("Q174", "R131", "decided 3", "design 2", "intro"), say what is wrong in one or two sentences, and give the fix as the exact new wording or the exact thing to add.
${NEWMSG}
${QRULES}
${RULES.replace('except the ONE file named on your REPORT_FILE line (write it with a bash heredoc with a QUOTED delimiter to the literal absolute path; create a skeleton within your first ~8 tool calls, then fill it and rewrite it as you learn)', '(you write no file at all)')}
RETURN: verdict, findings (every one you have; no cap), missing (things that should be on the list and are not; each <= 300 characters), summary <= 500 characters.`, { agentType: 'authored-council-seat', model: 'sonnet', effort: 'high', schema: AS, phase: 'Seats', label: 'seat:' + S.key }).then(p => p ? { seat: S.key, verdict: p.verdict, findings: p.findings || [], missing: p.missing || [], summary: p.summary } : null)))).filter(Boolean)
const PAPERS = JSON.stringify(papers, null, 1)
log('seat papers WHOLE to the ruling: ' + PAPERS.length + ' characters; ' + papers.map(p => p.seat + '=' + p.verdict + ' (' + p.findings.length + ' findings, ' + p.findings.filter(f => f.severity === 'MUST').length + ' MUST, ' + p.missing.length + ' missing)').join('; '))

const US = { type: 'object', required: ['status', 'accepted', 'rejected', 'questions', 'last_question', 'last_reading', 'summary'], properties: { status: { type: 'string', enum: ['DONE', 'PARTIAL', 'BLOCKED'] }, accepted: { type: 'number' }, partial: { type: 'number' }, rejected: { type: 'number' }, rejected_notes: { type: 'array', items: { type: 'string' } }, questions: { type: 'number' }, first_question: { type: 'number' }, last_question: { type: 'number' }, readings: { type: 'number' }, last_reading: { type: 'number' }, decided_not_asked: { type: 'number' }, design_page_items: { type: 'number' }, question_titles: { type: 'array', items: { type: 'string' } }, still_unsure: { type: 'array', items: { type: 'string' } }, summary: { type: 'string' } } }
phase('Rule')
const rule = await agent(`${WHO}
YOUR TASK (architect; a RULING on three blind papers, then the final list). An architect drafted the readings and questions that go to Boris: ${ITEMS} and its filing record ${CLAR}. Three blind seats attacked the draft; their papers are below, WHOLE. Rule on EVERY finding and every "missing" line: ACCEPT (do it), PARTIAL (do part, say which), REJECT (say why in one line -- a rejection needs a fact or a word of his, not a preference). Then REWRITE both files in place so that they are final. You are bound by the same rules as the draft's author (below). Where two seats pull opposite ways (the "his-eyes" seat wants fewer and shorter, the "nothing-missed" seat wants more), the rule is: nothing he said may be lost and no builder may be left guessing -- but a point with one sensible answer is a READING, not a question, and a point that needs a picture goes to the design page.
TURN BUDGET: you stop silently at 120 turns. Read the two files and the papers first; write your rulings table to the end of ${CLAR} under "## RULING ON THE SEATS' PAPERS" (one line per finding: seat, item, ACCEPT / PARTIAL / REJECT, what changed) BEFORE the "## ANSWERS" heading, which stays last with "(none yet)"; rewrite the items file by your 40th call; be done by 90. Verify the JSON loads.
THE SOURCES, should a finding need them: his message ${RAW}; ${BIND} (last section); ${BACKLOG} (last section); ${RB}/boris-clarify-150-plus.md; the fact sheets with their CORRECTIONS blocks: ${TOPICS.map(T => T.file).join(', ')}.
${HIS}
${CHAT}
${NEWMSG}
${QRULES}
${ITEMSHAPE}
LAST CHECK before you return: read your final list once as Boris would. For each question ask: could he answer this in ten seconds from his own experience on stage? For the whole list: is there any sentence of his message whose meaning Harmony would still have to guess after he answers? List those under still_unsure.
${RULES}
REPORT_FILE: ${ITEMS}
(Second file you may write: ${CLAR}.)
THE THREE PAPERS, WHOLE (${PAPERS.length} characters):
${PAPERS}
RETURN: status, accepted, partial, rejected, rejected_notes (each <= 220 characters), questions (count), first_question, last_question, readings (count), last_reading, decided_not_asked (count), design_page_items (count), question_titles (one per question: "172 [topic] <= 12 words"), still_unsure (each <= 240 characters), summary <= 700 characters.`, { agentType: 'architect', model: 'opus', effort: 'max', schema: US, phase: 'Rule', label: 'rule:final-list' })
if (!rule || rule.status === 'BLOCKED') { log('the ruling pass did not return a usable result; the DRAFT list is on disk, unruled'); return { sheets: sheets.map(s => ({ key: s.key, status: s.facts && s.facts.status, reread: s.reread && s.reread.verdict })), synthesis: syn, seats: papers.map(p => ({ seat: p.seat, verdict: p.verdict, findings: p.findings.length })), rule: rule || { status: 'NO_RESULT' } } }

const PAGE = RS + '/boris-open2.html'
const PS = { type: 'object', required: ['status', 'page_path', 'bytes', 'questions_on_page', 'readings_on_page', 'summary'], properties: { status: { type: 'string', enum: ['DONE', 'PARTIAL', 'BLOCKED'] }, page_path: { type: 'string' }, bytes: { type: 'number' }, questions_on_page: { type: 'number' }, readings_on_page: { type: 'number' }, pictures_on_page: { type: 'number' }, summary: { type: 'string' } } }
phase('Page')
const page = await agent(`${WHO}
YOUR TASK. Write Boris's page: ONE self-contained HTML file (inline CSS, no script that fetches anything, no external font or link) from the items file ${ITEMS} (final; read it whole). He reads it in his browser and answers in chat ("172 a"). "As usual" means: it looks and reads like his last page -- open ${RB}/boris-open.html and reuse its look (colours, type, the card for a question, how a default is marked, how readings are listed) so that he recognises it.
ORDER ON THE PAGE: (1) a short top: what this page is; how to answer; that nothing is being built, with his own words quoted exactly as the items file's intro gives them; how many questions and about how long. (2) "What I understood from your answers -- correct only what is wrong": the readings, grouped by topic in the order A (firing clips and the tempo row), B (the cue system), C (presets), D (actions in a show), E (the review screen and recordings); a reading marked "revised" shows one small line saying what changed. Put his picture beside the readings it belongs to (the "picture" field), small, a click opens it full size. (3) "Questions" in number order under the same topic headings: the number large, the situation, the options with the default marked and its reason, the "why it matters" line, his own words where the item quotes them. (4) "Decided without asking you -- say so if one is wrong". (5) "Comes next as pictures" (the design page list). (6) "What I told you in chat" (the four short blocks). (7) the line of defaults he accepted. Every text comes from the items file CHARACTER FOR CHARACTER (escape & < > only); you add no question, no reading, no opinion and no technical word of your own; headings and the few linking words are yours.
PICTURES: the page lives in ${RS}/ ; reference pictures by RELATIVE path ("boris-images/resolume-monitors.jpg", "../s-rta-1004b/boris-images/review-screen-reference.png"); check that each file exists (ls) before you reference it.
CHECK YOUR OWN PAGE before returning: parse it with python3 html.parser (no unclosed tag), count the question cards and the readings and compare with the items file, and grep the page for "undefined", "null", "[object".
${RULES}
REPORT_FILE: ${PAGE}
RETURN: status, page_path, bytes, questions_on_page, readings_on_page, pictures_on_page, summary <= 400 characters.`, { agentType: 'general-purpose', model: 'sonnet', effort: 'high', schema: PS, phase: 'Page', label: 'page:boris-open2' })

const CS = { type: 'object', required: ['verdict', 'questions_on_page', 'readings_on_page', 'mismatches_found', 'problems_left', 'summary'], properties: { verdict: { type: 'string', enum: ['SOUND', 'FIXED', 'UNRELIABLE'] }, questions_on_page: { type: 'number' }, readings_on_page: { type: 'number' }, mismatches_found: { type: 'number' }, fixed: { type: 'array', items: { type: 'string' } }, problems_left: { type: 'array', items: { type: 'string' } }, summary: { type: 'string' } } }
phase('Check')
const chk = page && page.status !== 'BLOCKED' ? await agent(`${WHO}
CHECK Boris's page against its sources before he sees it (you did not write it). The page: ${PAGE}. Its only source of text: ${ITEMS}. The filing record: ${CLAR}.
(1) ITEM FOR ITEM: every question, option, default mark, "why" line, reading, decided line, design-page item, chat block and the defaults line of the items file is on the page, character for character (after HTML un-escaping), in the right place; nothing is on the page that is not in the items file except headings and linking words. Do it with a script (python3: load the JSON, strip the page's tags, un-escape, and test each text as a substring), not by eye; report the count tested and each miss.
(2) HIS WORDS: every phrase the page attributes to Boris is verbatim in ${BIND} or ${BACKLOG} (grep each).
(3) NUMBERS: questions run from the items file's first_question to last_question without a gap; no question number exists in an earlier filing record (${R4}/boris-clarify-*.md, ${RB}/boris-clarify-*.md) as a different question; readings: none repeats a number below R127 with a different text.
(4) PICTURES: every img src resolves to an existing file relative to ${RS}/ .
(5) PLAIN WORDS: flag any code name, file name, stage id, or the words "delta", "ruling", "lane", "quantize-out", "packet" in a text he reads; and any name for the keyboard and MIDI mapping other than that one ("the key / pad list", "bindings": his words of 2026-10-05 14:16, the last bullets of today's section of binding-decisions.md).
(6) THE HTML parses (python3 html.parser), has no script that loads anything, no external link.
You MAY FIX the page yourself for a mechanical defect of (1), (2), (4) or (6) (a dropped character, a wrong escape, a broken path) -- say exactly what you changed; anything else you report and do not edit. You may NOT edit the items file or the filing record.
${RULES}
REPORT_FILE: ${RS}/boris-open2-check.md (your findings; the page is the only other file you may touch, and only for the fixes named above)
RETURN: verdict (SOUND = nothing wrong; FIXED = only mechanical defects, all fixed by you; UNRELIABLE = a defect is left), questions_on_page, readings_on_page, mismatches_found, fixed (each <= 200 characters), problems_left (<= 8, each <= 240 characters), summary <= 400 characters.`, { agentType: 'general-purpose', model: 'sonnet', effort: 'high', schema: CS, phase: 'Check', label: 'check:boris-open2' }) : null

return {
  sheets: sheets.map(s => ({ key: s.key, file: s.file, status: s.facts ? s.facts.status : 'NO_RESULT', verified: s.facts && s.facts.lines_verified, unknowns: ((s.facts && s.facts.unknowns) || []).slice(0, 6).map(x => cut(x, 200)), surprises: ((s.facts && s.facts.surprises) || []).slice(0, 5).map(x => cut(x, 200)), reread: s.reread ? s.reread.verdict : 'NO_RESULT', wrong: s.reread && s.reread.wrong, checked: s.reread && s.reread.checked })),
  synthesis: { status: syn.status, questions: syn.questions, readings: syn.readings, conflicts: (syn.conflicts || []).slice(0, 8).map(x => cut(x, 220)) },
  seats: papers.map(p => ({ seat: p.seat, verdict: p.verdict, findings: p.findings.length, must: p.findings.filter(f => f.severity === 'MUST').length, missing: p.missing.length })),
  rule: { status: rule.status, accepted: rule.accepted, partial: rule.partial, rejected: rule.rejected, rejected_notes: (rule.rejected_notes || []).slice(0, 8).map(x => cut(x, 220)), questions: rule.questions, first_question: rule.first_question, last_question: rule.last_question, readings: rule.readings, last_reading: rule.last_reading, decided_not_asked: rule.decided_not_asked, design_page_items: rule.design_page_items, question_titles: (rule.question_titles || []).map(x => cut(x, 120)), still_unsure: (rule.still_unsure || []).slice(0, 8).map(x => cut(x, 240)), summary: cut(rule.summary, 700), items_path: ITEMS, clarify_path: CLAR },
  page: page ? { path: page.page_path, status: page.status, bytes: page.bytes, questions: page.questions_on_page, readings: page.readings_on_page, pictures: page.pictures_on_page } : { status: 'NO_RESULT' },
  check: chk ? { verdict: chk.verdict, questions_on_page: chk.questions_on_page, readings_on_page: chk.readings_on_page, mismatches_found: chk.mismatches_found, fixed: (chk.fixed || []).slice(0, 6).map(x => cut(x, 200)), problems_left: (chk.problems_left || []).slice(0, 8).map(x => cut(x, 240)), summary: cut(chk.summary, 400) } : { verdict: 'NO_RESULT' },
}
