export const meta = {
  name: 'rta-1003-bf9b-fix5',
  description: 'Audio-DNA s-rta-1003: lane bf9b FIX-5 -- the Layer tab after Remove Deck (visual-gate finding), 1 opus builder, then a pinned delta review and two critics on the new captures (sonnet)',
  phases: [{ title: 'Build' }, { title: 'Review' }],
}
const A = args || {}
const MAIN = '/Users/boriskarpman/projects/RealTimeAudio'
const MAIN_APP = MAIN + '/build/AudioDNA_artefacts/Release/Audio-DNA.app'
const RPT = '.harmony/.reports/s-rta-1003'
const OLD = '.harmony/.reports/s-rta-1002b'
const SP = '/private/tmp/claude-501/-Users-boriskarpman-projects-RealTimeAudio/a868a537-8200-4641-a63f-f3029b3cf7ee/scratchpad'
const W = MAIN + '/.claude/worktrees/bf9b'
const BR = 'lane/bf9b'
const LANE = 'bf9b-fix'
const PIN = 'a7491d4'
const REPORT = W + '/' + RPT + '/' + LANE + '.md'
const RULING = MAIN + '/' + RPT + '/ruling-bf9b-merge.md'
const PLAN = MAIN + '/' + RPT + '/plan-bf9b-merge.md'

function RULES(lane) {
  return `
RIG RULES (binding; breaking any one = lane FAIL):
- Your worktree WT=${W} (branch ${BR}) exists with build dirs ${W}/build-lane (Release app + tests) and ${W}/build-tsan. Work ONLY inside it with absolute paths (git -C ${W}; cmake -S ${W} -B ${W}/build-lane; cmake --build ${W}/build-lane -j6). A NEW build dir (build-asan for the unit gate, build-asan-app for the ASan app, a scratch mutant dir) is configured like the others: -DFETCHCONTENT_FULLY_DISCONNECTED=ON plus -DFETCHCONTENT_SOURCE_DIR_<DEP>=${MAIN}/build/_deps/<dep>-src for each FetchContent dep (JUCE, HTTPLIB, CATCH2, MELATONIN_INSPECTOR, SYPHON; read-only use), -DAUDIODNA_BUILD_TEST_SERVER=ON -DAUDIODNA_BUILD_SYPHON=ON, and the patched libprojectM at ~/.local/opt/projectm-4.1.1-fbo1 is found by the project's CMake (never rebuild or touch it). df -h /System/Volumes/Data before any new build dir (stop and report if < 30 GB free). No build may outlive the stage that started it (no background build left running when you return). NEVER edit the main checkout ${MAIN} or its build/ (read-only use of ${MAIN_APP} = the PRE-bf9b main app, and of ${SP}/apps/pre-bf9b.app = its frozen copy, is allowed). NEVER cd in a command; multi-step sequences go in script files under ${SP}/${lane}/ run with bash <file>. zsh does not split a command held in a variable. Stamp times from date, never estimate.
- No other lane is building in this worktree. Probes fall back to the main checkout's .venv (${MAIN}/.venv, read-only); if you create a .venv symlink in the worktree, REMOVE it before every commit.
- LIVE APP: at most ONE Audio-DNA on the machine. Use the helper: LANE=${lane} . ${SP}/lib/lock.sh (acquire_lock / release_lock / start_app APP OUTDIR [test] / quit_app / outwins / wait_quiet / adna / acquire_quiet_lock). A failed mkdir means WAIT; never remove another owner's lock; after releasing wait >= 45 s before re-acquiring (the helper enforces it). Hold the lock per run or small batch (<= ~15 min). Probes REFUSE without AUDIODNA_LOCK_OWNER matching (the helper exports it). Every FULL ctest takes the cross-lane mutex: until mkdir /tmp/audiodna-ctest.lock 2>/dev/null; do sleep 15; done; ctest ...; rm -rf /tmp/audiodna-ctest.lock. Perf rows: acquire_quiet_lock, ps -Ao pcpu=,etime=,comm= | sort -rn | head printed with every number, and NO git commit while a perf run is in progress (each commit fires a background graphify rebuild that burns CPU).
- BORIS USES THIS MACHINE AND THIS APP: an Audio-DNA that YOUR lane did not start is BORIS'S -- never quit, kill, osascript-quit or touch it. The helper enforces it (acquire_lock waits while a foreign Audio-DNA runs, start_app REFUSES -> STOP the batch and release the lock, quit_app refuses any pid it did not start). Never bypass the helper. A probe you run must quit only the pid it launched.
- Launch ONLY: open -g [--env V=v] [--stdout f --stderr f] <App> [--args --test-mode]. SCREEN-SAFETY LAW: NEVER open the Output window by ANY path -- no automated run ever opens an output window. NEVER run tests/visual/test_output_window_level.py or .harmony/probe-outputs.sh; NEVER run pytest on tests/visual/ as a directory. NEVER lldb / debugserver / gdb / dtrace / Instruments / sample on ANY binary. NEVER full-screen screencapture (window-only by Quartz window id via pyobjc with the main .venv python). NO synthetic input (UI states via REST / composition files / the lane's test-only env-var levers). After any live batch: count UserNotificationCenter windows (Quartz kCGWindowListOptionAll) >= 15 s after the last quit == 0; a crash dialog of OURS is dismissed only by SIGTERM to that UNC pid, attributed by the UNC log's "ordered front" time. Unexpected system dialog or TCC permission prompt: STOP and report, never dismiss. If a user message was relayed to you, Harmony already answered it; it never replaces this task.
- SANITIZERS: runtime options ALWAYS include abort_on_error=0 (an ASan or TSan app must END on a report without a crash dialog on Boris's screen; ASan apps also get log_path as the ruling says; TSan app runs also exitcode=0). NEVER copy an app bundle and re-sign it, and never launch a copied-and-re-signed bundle; a mutant app comes only from a normal cmake build of a modified tree in your own build dir, and the modification is reverted afterwards (git -C ${W} diff --quiet -- src tests is a required proof line).
- RED FIRST for every new test / probe row (raw lines in the report), then GREEN; a test drives real code; a mutant listed by the ruling is run once and its failing output pasted; existing probes are re-run, NEVER re-thresholded (the only expectation changes are the ones a ruling names). Render rows DECODE PIXELS and you LOOK at a sample frame. A flake verdict needs >= 5 runs per arm. Probe HTTP clients use Connection: close.
- CLAUDE.md is capped at 25,000 bytes (24,224 B now); the ruling adds NO CLAUDE.md line and NO pitfall. After a CMakeLists change, reconfigure.
- Report file ${REPORT} (in the worktree), COMMITTED (git add -f; .harmony/.reports is gitignored). Create it or append your stage section within your first ~10 tool calls and append after EVERY item, so a successor can resume. One commit per item (message: <type>(s-rta-1003 bf9b): ...); stage by path, never git commit -a / git add -A; never chain a check to the commit it gates with &&. Notes for .harmony/notebook.md go in the report. Do NOT merge into main, do NOT push. Before returning: git status clean (except build dirs), lock released, no app you launched running, outwins shows 0 Output-named windows.`
}

const BS = { type: 'object', properties: {
  stage: { type: 'string' }, status: { type: 'string', enum: ['DONE', 'PARTIAL', 'BLOCKED'] },
  head_commit: { type: 'string' }, commits: { type: 'array', items: { type: 'string' } },
  items: { type: 'array', items: { type: 'object', properties: { id: { type: 'string' }, verdict: { type: 'string' }, evidence: { type: 'string' } }, required: ['id', 'verdict', 'evidence'] } },
  ctest: { type: 'string' }, tsan: { type: 'string' }, asan: { type: 'string' }, claude_md_bytes: { type: 'string' },
  found_not_fixed: { type: 'array', items: { type: 'string' } }, stop_items_for_harmony: { type: 'array', items: { type: 'string' } },
  facts_measured: { type: 'array', items: { type: 'string' } },
  next_stage_notes: { type: 'string' }, report_path: { type: 'string' }, summary: { type: 'string' },
  lock_released: { type: 'boolean' }, app_left_running: { type: 'boolean' }, output_window_opened: { type: 'boolean' },
  errors_or_deviations: { type: 'string' } },
  required: ['stage', 'status', 'head_commit', 'items', 'ctest', 'report_path', 'summary', 'lock_released', 'app_left_running', 'output_window_opened'] }
const RS = { type: 'object', properties: { verdict: { type: 'string', enum: ['PASS', 'PASS_WITH_NITS', 'FAIL'] }, reviewed_commit: { type: 'string' }, report_path: { type: 'string' }, findings: { type: 'array', items: { type: 'object', properties: { severity: { type: 'string', enum: ['MUST', 'SHOULD', 'NIT'] }, issue: { type: 'string' }, fix: { type: 'string' } }, required: ['severity', 'issue'] } } }, required: ['verdict', 'reviewed_commit', 'findings'] }

const CONTEXT = `CONTEXT. Lane bf9b = "decks are boxes of clips; the layers are ONE shared playing stack" (Boris's ruling, BORIS_DECISIONS.md "Decks are boxes of clips"). Built and reviewed twice at ${PIN}; today main was merged INTO the lane and three merge-in stages ran (M1 merge, M2 by-name-quit sweep, M3 MilkDrop deck-switch row + post-merge probes): their report is ${W}/${RPT}/bf9b-merge.md (read its last "HAND-OVER TO THE FIX STAGE" section and its stop / found_not_fixed items first).
THE SPEC FOR YOUR WORK: the architect RULING ${RULING} -- READ IT IN FULL (it is the working document: section 3 amendments AM-1..AM-18, section 4 FINAL BUILD STAGES, section 5 gate list, section 6 Boris page, section 8 side findings) -- and the HARMONY ADOPTION section at the END of ${PLAN} (adoption > ruling > plan body; read the plan BODY only where the ruling points into it by item or line). The review findings it answers: ${MAIN}/${OLD}/review-bf9b-state-r2.md, review-bf9b-live-r2.md, review-bf9b-gates-r2.md. Harmony's earlier rulings stay binding: ${MAIN}/${OLD}/rulings-bf9b-merge.md, ${MAIN}/${RPT}/rulings-bf9b-mergein.md.
Boris's words (quote only verbatim): ${MAIN}/.harmony/binding-decisions.md sections "2026-10-03 (s-rta-1003)" -- "The layer strip does not need to show the deck a clip is playing from." and, asked whether the deck-tab dot stays: "drop".
If a structural assumption of the ruling is broken by the code you find, STOP that item and report it in stop_items_for_harmony with evidence (do not improvise a redesign). The ruling's STOP clauses are binding.`


const FH1 = '4137f60'
const SHOTS = MAIN + '/' + RPT + '/bf9b-shots'
phase('Build')
const r = await agent(`LANE ${LANE}, stage FIX-5, worktree ${W}, branch ${BR}. CONTINUE from commit ${FH1} (git -C ${W} log -1; no reset; build dirs exist: build-lane Release app + tests, build-asan unit gate, build-tsan, build-asan-app = the ASan app). FIRST read the lane report's last sections (${REPORT}: "HAND-OVER TO HARMONY") and the visual gate's evidence: ${SHOTS}/manifest.md (sections S3, S10, S12, P1) and LOOK at ${SHOTS}/P1-layer-tab-after-remove-deck0-inspector.png.
${CONTEXT}
WHY THIS STAGE EXISTS: Harmony's visual gate (B7) found one fault on the lane's own model. With a layer selected and the Layer tab open, Remove Deck leaves the Layer tab BROKEN: the title still reads "Layer 3", the dashboard knobs are drawn with their values cut off, and "No layer selected" is printed across them; the strip keeps its highlight; Undo restores it. It happens even for an empty deck nobody plays from (capture P1; /api/debug/ui_text inspected_layer reads "" after POST /api/debug/remove_deck). On this lane the layers are ONE shared stack and a deck is only a box of clips, so removing a deck must not take the Layer tab off its layer. Boris's own check page walks into it (select a layer, open the Layer tab, later Remove Deck).
YOUR STAGE'S SCOPE (keep it this small):
 A. Remove Deck -- and its Undo and Redo -- leave the Layer tab on the selected layer (same layer, same highlight). The Clip tab keeps the existing rule (owned, or clear). Use the lane's existing hook function (src/ui/InspectorRepoint.h) rather than a new mechanism; removeDeck must no longer empty the Layer inspector. RED FIRST: a headless case (in the file that holds AS1-AS7 / N1; under the asan label if it touches moved storage) that binds the Layer inspector to a layer, runs RemoveDeckCmd through the same hand-over the app uses, and REQUIREs the inspector is still bound to that layer -- RED at ${FH1}, GREEN after; one mutant that restores the old emptying must fail it. LIVE RED / GREEN: lever-selected layer, POST /api/debug/remove_deck of an empty deck and of a deck a layer plays from, then /api/debug/ui_text inspected_layer == the selected layer's name (RED on the ${FH1} app: ""), and after POST /api/debug/undo the same.
 B. The Layer inspector's NO-LAYER state must paint cleanly wherever it is legitimately reached (a composition load unbinds the Layer tab -- the manifest says so): no stale title, no dashboard knobs under the "No layer selected" words. FIRST establish whether this lane caused it: git -C ${W} diff a7491d4..${FH1} -- src/ui/LayerInspector.cpp src/ui/LayerInspector.h and git -C ${W} show main:src/ui/LayerInspector.cpp for the same code -- say plainly REGRESSION OF THIS LANE (which commit) or PRE-EXISTING ON MAIN. If it is a regression: fix it, with a headless case (after setLayer(nullptr): title empty, the dashboard controls not visible), RED first. If it is pre-existing: fix it ONLY if the fix is a contained visibility / layout change of at most ~15 lines with the same headless case; otherwise do not touch it and report it in found_not_fixed with the capture.
 C. Docs: BORIS_DECISIONS.md lines ~358-359 (this lane's "Built (bf9b ...)" sentence) still says a strip badge names the deck, a deck tab shows a dot and old shows convert with a yellow note: rewrite that ONE sentence to what is built now (the strip shows the clip only; no mark on a tab; no on-screen note; Boris's words of 2026-10-03 are in ${MAIN}/.harmony/binding-decisions.md -- quote only verbatim). performance-controls.md: one sentence that Remove Deck leaves the Layer tab on its layer, if the doc describes Remove Deck's effect on the inspectors.
 D. PROVE at the new head (raw lines): cmake --build ${W}/build-lane -j6 rc 0; full ctest SERIAL under the mutex (count = 1249 + added, names listed); .harmony/probe-tsan-unit.sh 5 / 5, 0 warnings; .harmony/probe-asan-unit.sh GREEN; REBUILD the ASan app (cmake --build ${W}/build-asan-app --target AudioDNA -j6: print how many objects compiled -- it must be >= 1 -- and the binary sha256, which must differ from 62028411683ee8a8) and run ASAN_LIVE_APP=<that app> bash .harmony/probe-asan-live.sh: exactly PROBE-ASAN-LIVE GREEN (7 steps, 0 INVALID, 0 "ERROR: AddressSanitizer", app alive at the end) (a RED at L4 / L5 whose report is a container-overflow in ApiServer::handleComposition is the known http-thread reader race SF-12: re-run once and say so); probe-boxes on the lane app: the exact line PROBE-BOXES BLOCKED 1 [k5_queue_link_on] (0 FAIL; 1 pre-registered bar(s) did not run -- not a pass) and its exit code (print rc on its own line: rc=$? right after the command); probe-ui-files-rename 54 / 0.
 E. NEW CAPTURES for the critics, with the visual gate's driver (${SP}/b7/ holds the capture scripts the gate used; reuse them): P1a Layer tab after Remove Deck of an empty deck, P1b after Remove Deck of a deck a layer plays from, P1c after Undo, P2 the Layer tab right after POST /api/load_composition of bf9b-check.json (the no-layer state), each as a full-window PNG (half size) + an inspector crop + a strip crop, saved under ${SHOTS}/ with the prefix F5- ; append a section "F5" to ${SHOTS}/manifest.md (what was done, the ui_text facts, the files); decode and LOOK at each and say what it shows.
 Report: append "FIX-5" to ${REPORT} (git add -f), commit per item, final head, git status clean (build-asan-app is untracked: leave it).
RETURN: the structured result; summary <= 1200 characters; items A-E with verdict + key evidence; stop_items_for_harmony for anything you did not fix.
${RULES(LANE + '-FIX-5')}`, { agentType: 'builder', model: 'opus', effort: 'high', schema: BS, phase: 'Build', label: 'build:' + LANE + ':FIX-5' })
if (!r) return { failed: 'FIX-5' }
log('FIX-5: ' + r.status + ' @ ' + r.head_commit)
const slim = Object.assign({}, r, { summary: String(r.summary || '').slice(0, 1400), next_stage_notes: '', errors_or_deviations: String(r.errors_or_deviations || '').slice(0, 1000), items: (r.items || []).map(x => ({ id: x.id, verdict: String(x.verdict || '').slice(0, 140), evidence: String(x.evidence || '').slice(0, 320) })), found_not_fixed: (r.found_not_fixed || []).map(x => String(x).slice(0, 300)), stop_items_for_harmony: (r.stop_items_for_harmony || []).map(x => String(x).slice(0, 400)) })
if (r.status !== 'DONE') return { build: slim }
phase('Review')
const VS = { type: 'object', properties: { seat: { type: 'string' }, answer: { type: 'string', enum: ['yes', 'no'] }, verdict: { type: 'string', enum: ['PASS', 'PASS_WITH_NITS', 'FAIL'] }, reason: { type: 'string' }, findings: { type: 'array', items: { type: 'object', properties: { severity: { type: 'string', enum: ['MUST', 'SHOULD', 'NIT'] }, file: { type: 'string' }, issue: { type: 'string' } }, required: ['severity', 'issue'] } } }, required: ['seat', 'answer', 'verdict', 'reason', 'findings'] }
const CB = `VISUAL CRITIC (read-only; you LOOK at pictures; do not read source, do not run anything). Audio-DNA, a live VJ app; lane "decks are boxes of clips": the layers are one shared playing stack, a deck is only a box of clips. Evidence: ${SHOTS}/manifest.md section "F5" (read it first) and the PNG files it lists (prefix F5-), plus the BEFORE of this fix: ${SHOTS}/P1-layer-tab-after-remove-deck0-inspector.png (broken: stale title, cut-off knobs, "No layer selected" printed across them). Open every F5 file with the Read tool; cite the file for each observation. REPORT_FILE: ${RPT}/critic-bf9b-f5-SEAT.md (under ${MAIN}/${RPT}/; at most 30 lines). MUST = something the owner would see as broken; SHOULD = a real flaw he may notice; NIT = polish. RETURN seat, answer (yes / no), verdict (FAIL only for a MUST), reason (<= 400 chars), findings.`
const out = await parallel([
  () => agent(`INDEPENDENT SOURCE REVIEW (read-only), lane bf9b, FIX-5 delta. PINNED: worktree ${W}, branch ${BR}, base ${FH1} (approved by four lenses with 0 MUST), head ${r.head_commit}. Read ONLY through git: git -C ${W} diff ${FH1}..${r.head_commit}, git -C ${W} show ${r.head_commit}:<path>, git -C ${W} grep. Spec: the stage brief is in the lane report (git -C ${W} show ${r.head_commit}:${RPT}/bf9b-fix.md, section FIX-5); the ruling ${RULING} (AM-1, AM-2: forget-first inside setLayer / setClip, the hook function) still binds. CHECK: (1) after Remove Deck / its Undo / Redo the Layer inspector stays bound to the selected layer and NO path reads a binding into freed storage (Remove Deck retires or erases a deck: can the Layer inspector or the Clip inspector keep a pointer into what was erased? the Clip tab's owned-or-clear rule intact); (2) the new headless case can fail (its RED line and its mutant in the report) and drives the app's real hand-over, not a copy; (3) the no-layer state change, if any, is a visibility / layout change only; (4) the delta touches NO render-thread, compositor or audio code (list the files changed: Harmony keeps the performance result of ${FH1} only if this is true); (5) nothing stray (no mutant, no hook, no .venv link); docs sentence correct; Boris quoted only verbatim. You may run read-only git and greps; do not build or run.
REPORT_FILE: ${RPT}/review-bf9b-merge-fix5-r1.md (write it under ${MAIN}/${RPT}/). FAIL only for a MUST. Cite file:line at the head; label VERIFIED / INFERRED.`, { agentType: 'reviewer', model: 'sonnet', effort: 'high', schema: RS, phase: 'Review', label: 'review:bf9b:fix5' }),
  () => agent(`${CB.replace(/SEAT/g, 'ux')}
YOUR QUESTION (UX): "After Remove Deck with a layer selected and the Layer tab open (F5-P1a, F5-P1b), does the Layer tab still show that layer, complete and readable, with its strip still highlighted -- and after Undo (F5-P1c) too? Is there no button and no sentence about the removal anywhere?"`, { agentType: 'reviewer', model: 'sonnet', effort: 'high', schema: VS, phase: 'Review', label: 'critic:bf9b:f5:ux' }),
  () => agent(`${CB.replace(/SEAT/g, 'visual-design')}
YOUR QUESTION (visual design): "Is every Layer-tab picture free of overlapping text, cut-off controls and stale titles -- in the bound state (F5-P1a/b/c) and in the no-layer state after a composition load (F5-P2)? If F5-P2 still shows knobs under the words 'No layer selected', say whether it reads as broken or as an acceptable empty state, and compare it with the BEFORE picture."`, { agentType: 'reviewer', model: 'sonnet', effort: 'high', schema: VS, phase: 'Review', label: 'critic:bf9b:f5:visual' }),
])
return { build: slim, review: out[0] ? { verdict: out[0].verdict, findings: (out[0].findings || []).map(f => ({ severity: f.severity, issue: String(f.issue || '').slice(0, 450) })) } : null, critics: out.slice(1).map(c => c ? { seat: c.seat, answer: c.answer, verdict: c.verdict, reason: String(c.reason || '').slice(0, 400), findings: (c.findings || []).filter(f => f.severity !== 'NIT').map(f => ({ severity: f.severity, issue: String(f.issue || '').slice(0, 350) })) } : null) }
