export const meta = {
  name: 'rta-1003-bf9b-fixplan',
  description: 'Audio-DNA s-rta-1003: plan the open bf9b review items + strip-badge removal (architect opus high), attack it with 4 blind seats (sonnet), rule it (architect opus max)',
  phases: [{ title: 'Plan' }, { title: 'Attack' }, { title: 'Ruling' }],
}
const MAIN = '/Users/boriskarpman/projects/RealTimeAudio'
const RPT = '.harmony/.reports/s-rta-1003'
const OLD = '.harmony/.reports/s-rta-1002b'
const W = MAIN + '/.claude/worktrees/bf9b'
const PIN = 'a7491d4'
const PLAN_FILE = RPT + '/plan-bf9b-merge.md'
const RULING_FILE = RPT + '/ruling-bf9b-merge.md'
const PAPERS_FILE = RPT + '/attack-bf9b-merge-papers.md'

const READS = `HOW TO READ (binding): you are read-only. A builder is merging main into the lane's WORKING TREE right now, so NEVER read files under ${W} directly for source: read the lane ONLY at the pinned commit -- git -C ${W} show ${PIN}:<path> | sed -n 'A,Bp' and git -C ${W} grep -n '<pattern>' ${PIN} -- src tests -- and main ONLY as git -C ${MAIN} show main:<path>. Reports under ${MAIN}/${OLD}/ and ${MAIN}/${RPT}/ are plain files. Never build, never run a test, never launch the app, never run a probe. Never cd in a command.`

const INPUTS = `INPUTS (read what your part needs; the big files are indexed -- grep the headings, then read ranges):
- ${MAIN}/${OLD}/review-bf9b-state-r2.md, review-bf9b-live-r2.md, review-bf9b-gates-r2.md (round-2 reviews of ${PIN}: 0 MUST, 7 SHOULD, NITs) -- IN FULL.
- ${MAIN}/${OLD}/rulings-bf9b-merge.md and ${MAIN}/${RPT}/rulings-bf9b-mergein.md (Harmony's rulings already made; binding) -- IN FULL.
- ${MAIN}/${OLD}/ruling-bf9b.md: "FINAL CONSOLIDATED GATE LIST" (:463-609), "WHAT ONLY BORIS CAN CHECK" (:611), amendments 9, 10, 16, 18, 24. ${MAIN}/${OLD}/plan-bf9b.md: sections 4.B (:447) and the final HARMONY ADOPTION (:629).
- The lane report at the pin: git -C ${W} show ${PIN}:${OLD}/bf9b.md (170 KB; grep -n '^#' first) -- "S2b deviations" item 3 (the 4.B omissions), "S3" (badge / tab dot / B7 machine checks M-a..M-f and live states), "LANE GATE STATUS", "Fix round", "found_not_fixed".
- ${MAIN}/BORIS_DECISIONS.md "Decks are boxes of clips" and ${MAIN}/.harmony/binding-decisions.md "2026-10-03 (s-rta-1003)" (Boris's words of today, in quotes).
- ${MAIN}/.harmony/probe-tsan-unit.sh and tests/CMakeLists.txt at the pin for how ADNA_SANITIZE builds are configured.`

const ITEMS = `ITEMS TO PLAN (each: is the finding TRUE at ${PIN}? -- a finding can be wrong, say so with evidence; the forks; the choice; the change by file / function (no code); RED-first tests and mutants; the pre-registered gate):
P1 USE-AFTER-FREE READ after a layer-stack move (state-r2 finding 1; reproduced by the reviewer under ASan: UniversalParamControl.cpp:349 <- LayerInspector.cpp:911 <- :734 <- UndoService.cpp:78). The round-1 MUST fix re-points the Layer inspector AFTER the mutation freed the old Composition::layers buffer, and the re-point path still reads the control's old conn_. The reviewer says the same stale read exists on main at MainComponent.cpp:2958 (refreshUiAfterModelSwap) and in the Remove-Layer-undo re-point. Design ONE fix for the class (candidates the reviewer named: unbind BEFORE the mutation through a pre-fence hook; or make the inspector / UniversalParamControl drop the old pointers WITHOUT dereferencing them when the storage moved) covering every holder of a Layer* or of a pointer into a Layer (LayerInspector, EffectStackView, UniversalParamControl::conn_, LayerStrip, anything else you find at the pin -- enumerate them). Say what happens to a routine hand's grip (the release() the old code calls) so no grip is left stuck. PROOF DESIGN: a headless ASan case per site that is RED before and GREEN after; and whether an ASan build of the APP driven live through the real call chain (Layer tab open through the lane's test-only ADNA_INSPECT_LAYER lever, POST /api/debug/load_deck of a deck wider than the show, duplicate_deck, add / remove layer + /api/debug/undo, stderr grep "ERROR: AddressSanitizer" == 0) is feasible and worth its cost as Harmony's call-chain gate (Iron Law: a full-tier gate exercises the real call chain, not the component alone). Sanitizer options must include abort_on_error=0 (no crash dialog on Boris's screen).
P2 UNDO of Add Deck / Load Deck / Duplicate Deck erases the deck even when a layer plays from it (state-r2 finding 2 = live-r2 NIT-2; INFERRED by both, not run): DeckCommands.h AddDeckCmd::undo (:717) and InsertDeckCmd::undo (:824). Boris's default Q1: a deleted deck's playing clip keeps playing until replaced. Decide: retire-or-erase symmetric with RemoveDeckCmd (and what redo does with a retired deck), or a documented exception. Tests (T6 family), probe row if any.
P3 THE WIRING LINE IS UNTESTED (live-r2 SHOULD-1 = gates-r2 SHOULD-1): MainComponent.cpp:~1800 undoService_.onLayerStackMoved = ... and repointLayerInspector (:5304-5320) are exercised by no test (the headless case installs its own lambda). Pin it (text lint in the test_render_thread_lint style + a mutant that deletes the line and must fail a test; and / or P1's live ASan row) -- consistent with P1's design.
P4 K5 WITH LINK ON is BLOCKED on both arms (no Link build: AUDIODNA_BUILD_LINK is OFF, its FetchContent source is not in build/_deps and lanes build with FETCHCONTENT_FULLY_DISCONNECTED; the Link toggle is a TopBar button only). ruling-bf9.md K5: "Queued triggers survive a switch ... PASS iff it fires on that bar (REST and frame), with Link off and with Link on." Position: a driver (what exactly, cost, can it have a RED arm) or a reasoned "covered by" (which unit / probe evidence covers the Link-on half, and what the merge gate prints -- the probe must keep printing BLOCKED, never GREEN, per R-N3). Harmony decides; give the strongest case for each side.
P5 THE S2b 4.B OMISSIONS (lane report "S2b deviations" item 3: six assertion groups the builder re-pointed because the plan body made them impossible but section 4.B did not pre-register them): rule each ACCEPT or REVERT with the plan clause that decides it.
P6 GRID on a deck switch: (a) pre-existing DeckView::rebuildGrid leaves the fired column's header unlit until the next refresh (lane report S3 found_not_fixed); (b) live-r2 NIT-1: showDeck() calls rebuildGrid() when the target deck's numColumns differs, destroying and recreating every LayerStrip and the tabs on a switch -- against "nothing on screen moves on a switch except the grid's cells" (Boris: "when I switch between decks, do not change the clips playing in the layers or how they are playing"); does a rebuilt strip lose any live state (routine bands, fader positions, a rename box per Pitfall 65)? (c) state-r2 NIT-7: the cell selection and the Clip inspector keep the previous deck's Clip* across a switch -- a dangling-pointer risk when that deck is then removed / reaped, or only a UX mismatch? Decide what is fixed in this lane and what is filed.
P7 BF14 -- Boris today (verbatim): "The layer strip does not need to show the deck a clip is playing from." Harmony's consequence: REMOVE the strip's source-deck badge and the badge click (ruling-bf9b amendment 16(a) and 16(c)); the deck-TAB dot (16(b)) STAYS by default (Boris has been asked; default keep). List exactly what goes (code, tests, B7 machine checks M-b / M-d / M-f, docs lines, the Boris-page steps that mention the number on the strip, B7 live states and critic questions that name the badge) and what stays or changes (M-a lit cells, M-c snapshot -- now byte-equal over the WHOLE strip column across showDeck(0) / showDeck(5) / showDeck(0), M-e tab dots, the undo hint naming the layers, the load notice, how a removed deck's still-playing clip looks with no "x" badge). Rewrite B7's live-state list and critic questions accordingly.
P8 NIT DISPOSITIONS: state-r2 NITs 3, 4, 5 and gates-r2 NITs 5, 8 -- fix here, file, or drop, one line each. (state-r2 NIT 6 and gates-r2 NITs 4, 6, 7 are already ruled: see rulings-bf9b-mergein.md.)
P9 HARMONY'S MERGE GATE LIST at the final lane head (after the merge-in stages M1-M3 and your fix stages): ONE consolidated, pre-registered list Harmony runs herself -- which rows of ruling-bf9b's FINAL CONSOLIDATED GATE LIST still apply as written, which change because of P1-P7 (state the new string / bar), the new rows (ASan gate, H1 m9b_deck_switch_live), the order, and the RED arm for each (Harmony constraint: RED arm = a copy of the PRE-MERGE main app, taken before the merge; live rows under the app lock, open -g --args --test-mode, never an Output window, no synthetic input, window captures only by Quartz window id of our pid; perf verdicts only on a quiet machine, interleaved arms, >= 5 runs per arm; a bar whose teeth equal the drift is INFO). B6 perf: name the driver script that exists at the pin or say none exists. B7: the visual work gate (critic panel: visual-design, UX, graphic-design, logic, interaction-logic) runs on decoded captures before Boris sees anything.
P10 BUILD STAGES for the fix: one builder context each, dependency order, what each stage must prove before the next starts.`

const PS = { type: 'object', properties: { plan_path: { type: 'string' }, status: { type: 'string', enum: ['DONE', 'PARTIAL'] }, summary: { type: 'string' }, findings_false: { type: 'array', items: { type: 'string' } }, forks: { type: 'array', items: { type: 'object', properties: { id: { type: 'string' }, choice: { type: 'string' }, runner_up: { type: 'string' } }, required: ['id', 'choice'] } } }, required: ['plan_path', 'status', 'summary', 'forks'] }
const AS = { type: 'object', properties: { seat: { type: 'string' }, attacks: { type: 'array', items: { type: 'object', properties: { id: { type: 'string' }, target: { type: 'string' }, claim: { type: 'string' }, evidence: { type: 'string' }, severity: { type: 'string', enum: ['MUST', 'SHOULD', 'NIT'] }, proposed_change: { type: 'string' } }, required: ['id', 'target', 'claim', 'evidence', 'severity'] } }, strongest_point: { type: 'string' }, citations_rechecked: { type: 'boolean' } }, required: ['seat', 'attacks', 'strongest_point', 'citations_rechecked'] }
const RS = { type: 'object', properties: { ruling_path: { type: 'string' }, papers_path: { type: 'string' }, status: { type: 'string', enum: ['DONE', 'PARTIAL'] }, verdict: { type: 'string' }, amendments: { type: 'number' }, stages: { type: 'array', items: { type: 'object', properties: { key: { type: 'string' }, scope: { type: 'string' } }, required: ['key', 'scope'] } }, boris_questions: { type: 'array', items: { type: 'string' } }, facts_harmony_must_measure: { type: 'array', items: { type: 'string' } }, strongest_counterargument: { type: 'string' } }, required: ['ruling_path', 'status', 'verdict', 'amendments', 'stages'] }

phase('Plan')
const plan = await agent(`PLAN AUTHORING (architect) -- lane bf9b "decks are boxes of clips", the FIX + MERGE-GATE delta plan. You author the position; a blind council attacks it; an architect ruling follows; Harmony decides.
GOAL: lane bf9b (branch lane/bf9b, pinned head ${PIN}) passed two review rounds with 0 MUST but with SHOULD items that must not ship as they are, and Boris changed one UI decision today. Plan the fix so that the lane can merge into main today: every item below either fixed with a test that can fail, or ruled out with evidence, plus the one consolidated gate list Harmony runs before and after the merge.
${READS}
${INPUTS}
${ITEMS}
OUTPUT: write the plan to REPORT_FILE (literal path below, relative to ${MAIN}; write it with a bash heredoc to exactly that path). Sections: 1 GOAL; 2 ESTABLISHED FACTS (ONLY lines you verified at ${PIN} or on main, each with file:line or the command you ran; anything else is labelled INFERRED or ASSUMED where it is used); 3 ITEMS P1-P8 (finding true? / forks: every defensible alternative, the choice, why the runner-up loses / the change / tests RED-first + mutants / gate); 4 BUILD STAGES (P10); 5 HARMONY'S MERGE GATE LIST (P9; exact strings and bars); 6 DOCS (which docs/claude/*.md lines change; CLAUDE.md stays <= 25,000 bytes); 7 WHAT ONLY BORIS CAN CHECK (plain words; do -> expect -> what wrong looks like); 8 QUESTIONS FOR BORIS (plain words, each with a default so the build never waits; only questions that are genuinely his: taste, behaviour he would notice); 9 RISKS (the strongest counterargument to this plan first, and the cheapest test that would refute each choice).
RULES OF THE DOCUMENT: Boris is quoted ONLY verbatim (his words are in binding-decisions.md and BORIS_DECISIONS.md); anything Harmony requires is written as "Harmony constraint:". No code blocks longer than a signature. Real-time rules of the project hold (no allocation / lock / syscall on the audio callback; no new mutex; the render thread never waits; shared model fields are Relaxed<T>, Pitfall 63). Prefer the smallest change that is correct; say explicitly what is NOT in this lane.
TURN BUDGET (the architect role stops SILENTLY at 120 turns): write a SKELETON of the plan file with all section headings by your turn 8; rewrite the file with what you have every ~10 turns; be DONE by turn 90. If you run short, write status PARTIAL and list what is missing at the top of the file.
REPORT_FILE: ${PLAN_FILE}
RETURN: plan_path, status, a summary <= 1500 characters, findings_false (review findings you found to be wrong), forks (id, choice, runner_up).`, { agentType: 'architect', model: 'opus', effort: 'high', schema: PS, phase: 'Plan', label: 'plan:bf9b-merge' })
if (!plan) return { failed: 'plan' }
log('plan: ' + plan.status + ' -> ' + plan.plan_path)

phase('Attack')
const SEATS = [
  { key: 'memory-safety', temper: 'You are the MEMORY-SAFETY SKEPTIC: assume every raw pointer dangles until the plan proves who owns the storage and when it moves. Attack P1, P2, P3 and P6(c): a holder the plan did not enumerate; an ordering in which the fix still reads freed memory; a routine-hand grip left stuck or released twice; an undo / redo sequence that resurrects or loses a retired deck; a hook that fires on the wrong thread or re-enters. Re-derive each claim from the code at the pin.' },
  { key: 'gates', temper: 'You are the GATE PROSECUTOR: a test that cannot fail is not a test. Attack every test, mutant, bar and gate string in the plan (sections 3, 4, 5): no RED arm; a bar whose teeth equal the noise; a lint that pins text while behaviour is free to break; an ASan gate that would pass with the bug present (wrong build type, case not linked, options that hide the report); a BLOCKED bar dressed as covered (P4); a 4.B omission accepted without the clause that decides it (P5); a merge gate row with no pre-registered string.' },
  { key: 'live-show', temper: 'You are the STAGE OPERATOR: Boris performs live with this app; nothing may move, flash or vanish that he did not ask for. Attack P6 and P7 and sections 7-8: a deck switch that still rebuilds strips or loses a fader / band / rename box; a removed deck whose playing clip has no visible trace once the badge is gone; a tab dot that lies; a Boris check he cannot actually perform; a question that is not his to answer or lacks a default; anything in the fix that changes what he sees beyond his words.' },
  { key: 'scope', temper: 'You are the MINIMALIST: this lane must merge today and four other lanes rebase on it. Attack scope and risk: a fix wider than its finding; work that belongs in a follow-up lane; a stage order that leaves the tree not building; a gate that costs an hour and proves what a cheaper one already proves; a change to main-side code (ui / bf10 / mkvidx features) that the merge does not require. For each cut you propose, name what is lost and why that is acceptable -- and also name the ONE thing in the plan that must NOT be cut.' },
]
const papers = (await parallel(SEATS.map(s => () => agent(`BLIND COUNCIL SEAT "${s.key}" -- attack ONE plan from ONE temperament. You do not see the other seats.
${s.temper}
THE PLAN UNDER ATTACK: ${MAIN}/${PLAN_FILE} (read it IN FULL first).
${READS}
${INPUTS}
MANDATORY CITATION RE-CHECK: before you return, re-open every file:line you cite at the pin and confirm it says what you claim; set citations_rechecked accordingly and drop any attack whose evidence did not survive. An attack without evidence (a file:line at ${PIN} or on main, a quoted plan line, or a quoted ruling line) is not an attack.
Do NOT write any file. RETURN (StructuredOutput): seat, attacks (id like ${s.key.slice(0, 2).toUpperCase()}-1..; target = the plan item / section; claim; evidence; severity MUST = the plan would ship a defect or a gate that cannot fail, SHOULD, NIT; proposed_change), strongest_point (the one attack you would stake the seat on), citations_rechecked. At most 10 attacks; fewer and sharper is better.`, { agentType: 'authored-council-seat', model: 'sonnet', effort: 'high', schema: AS, phase: 'Attack', label: 'attack:' + s.key })))).filter(Boolean)
log('seats returned: ' + papers.length + ' of ' + SEATS.length + '; attacks: ' + papers.reduce((n, p) => n + (p.attacks || []).length, 0))

phase('Ruling')
const ruling = await agent(`ARCHITECT RULING on a blind council's attacks (row 2r; you run on opus at max effort because Fable is out of usage -- Boris, verbatim, 2026-10-02: "just so you know, we are out of fable usage so you will need to do all fable work with opus 5.5"). Harmony decides after you; your ruling is her working document.
THE PLAN: ${MAIN}/${PLAN_FILE} (read IN FULL).
THE SEAT PAPERS (${papers.length} of ${SEATS.length} seats returned; verbatim JSON): ${JSON.stringify(papers).slice(0, 60000)}
UPDATE FROM BORIS (received 14:02 today, AFTER the plan and the seat papers were written; it OVERRIDES both where they differ; the verbatim record is ${MAIN}/.harmony/binding-decisions.md section "Boris's answers to the 14 clarifying questions"):
(1) Harmony asked: "Deck tab dot (small dot on a deck's tab when one of its clips is playing): keep or drop?" Boris: "drop". So the deck-TAB dot (ruling-bf9b amendment 16(b), machine check M-e, every B7 live state and critic question that names a dot, the docs lines, the Boris-page steps) is REMOVED in this lane together with the strip badge (plan item P7, which assumed the dot stays). With both gone, nothing on screen shows which deck a playing clip came from -- that is what Boris asked for. Rule what, if anything, must remain so that a removed deck's still-playing clip and "no lit cell on the shown deck" do not read as a fault (the Remove Deck undo hint naming the layers stays), and restate M-a / M-c, B7's live-state list and the critic questions for the final design. Judge every attack against the dot being gone.
(2) Harmony asked: "A video you played, replaced, then fire again: continue where it left off (today), or restart?" Boris: "restart". Harmony constraint: that change is NOT built in this lane (a transport lane builds it right after the merge, with a pre-registered expectation change for K10 (ii)); in THIS lane the C3 resume contract and row K10 stay as built (it is today's behaviour on main as well), and the Boris page DROPS ruling-bf9b's step 8.11 ("A video you played, replaced, then fire again continues from where it was") so he is not asked to confirm a behaviour he has just reversed. Say so in sections 5 and 6.
${READS}
${INPUTS}
DO, IN THIS ORDER:
1. FIRST write the seat papers verbatim (pretty-printed, one section per seat) to ${PAPERS_FILE} (literal path, relative to ${MAIN}, bash heredoc).
2. For every attack: re-derive the evidence yourself at the pin (never trust a seat's citation, never trust the plan's); verdict ACCEPT / PARTIAL / REJECT with the line that decides it. Where two seats conflict, RECONCILE them (do not relay both). Where the outcome turns on ONE fact nobody can establish by reading (it needs a build, a run or a measurement), do NOT guess: list it in facts_harmony_must_measure with the cheapest discriminating test, and give the ruling for each outcome.
3. Write the ruling to REPORT_FILE: 0 VERDICT; 1 FACTS RE-DERIVED; 2 ATTACK RULINGS (table); 3 AMENDMENTS (numbered; each OVERRIDES the plan body where they differ); 4 FINAL BUILD STAGES (one builder context each; what each must prove; which run in which order after the merge-in stages M1-M3); 5 FINAL CONSOLIDATED GATE LIST (pre-registered; Harmony copies gate strings ONLY from here: the full list, not a diff -- rows of ruling-bf9b's list that stay are restated by reference with their id, changed rows are restated in full); 6 WHAT ONLY BORIS CAN CHECK (plain words); 7 BORIS QUESTIONS (plain words, each with a default); 8 SIDE FINDINGS (outside this lane); 9 RISKS OF THIS RULING (the strongest counterargument first).
RULES: Boris quoted only verbatim; Harmony's requirements labelled "Harmony constraint:"; no code beyond a signature; prefer the smallest correct change; a pre-registered bar is never loosened -- it is met, or reported.
TURN BUDGET (the role stops SILENTLY at 120 turns): papers file by turn 4; a SKELETON ruling with all headings by turn 10; rewrite every ~10 turns; DONE by turn 90; if short, status PARTIAL with what is missing at the top.
REPORT_FILE: ${RULING_FILE}
RETURN: ruling_path, papers_path, status, verdict (<= 1200 characters), amendments (count), stages (key + one-line scope), boris_questions, facts_harmony_must_measure, strongest_counterargument.`, { agentType: 'architect', model: 'opus', effort: 'max', schema: RS, phase: 'Ruling', label: 'ruling:bf9b-merge' })
return { plan: { path: plan.plan_path, status: plan.status, summary: String(plan.summary || '').slice(0, 1500), findings_false: plan.findings_false || [], forks: plan.forks || [] }, seats: papers.map(p => ({ seat: p.seat, n: (p.attacks || []).length, must: (p.attacks || []).filter(a => a.severity === 'MUST').length, strongest: String(p.strongest_point || '').slice(0, 300) })), ruling: ruling || { failed: true } }
