export const meta = {
  name: 'rta-1003-bf9b-mergein',
  description: 'Audio-DNA s-rta-1003: merge main into lane bf9b, sweep by-name app quits, add the MilkDrop deck-switch row and re-run the post-merge probes (3 sequential opus builders, one worktree)',
  phases: [{ title: 'Build' }],
}
const MAIN = '/Users/boriskarpman/projects/RealTimeAudio'
const MAIN_APP = MAIN + '/build/AudioDNA_artefacts/Release/Audio-DNA.app'
const RPT = '.harmony/.reports/s-rta-1003'
const OLD = '.harmony/.reports/s-rta-1002b'
const SP = '/private/tmp/claude-501/-Users-boriskarpman-projects-RealTimeAudio/a868a537-8200-4641-a63f-f3029b3cf7ee/scratchpad'
const W = MAIN + '/.claude/worktrees/bf9b'
const BR = 'lane/bf9b'
const LANE = 'bf9b-merge'
const REPORT = W + '/' + RPT + '/' + LANE + '.md'

function RULES(lane) {
  return `
RIG RULES (binding; breaking any one = lane FAIL):
- Your worktree WT=${W} (branch ${BR}) already exists with build dirs ${W}/build-lane (Release app + tests) and ${W}/build-tsan. Work ONLY inside it with absolute paths (git -C ${W}; cmake -S ${W} -B ${W}/build-lane; cmake --build ${W}/build-lane -j6). If a configure is needed: -DCMAKE_BUILD_TYPE=Release -DAUDIODNA_BUILD_TEST_SERVER=ON -DAUDIODNA_BUILD_SYPHON=ON -DFETCHCONTENT_FULLY_DISCONNECTED=ON plus -DFETCHCONTENT_SOURCE_DIR_<DEP>=${MAIN}/build/_deps/<dep>-src for each FetchContent dep (JUCE, HTTPLIB, CATCH2, MELATONIN_INSPECTOR, SYPHON; read-only use); main now also needs the patched libprojectM at ~/.local/opt/projectm-4.1.1-fbo1 (installed; never rebuild or touch it). NEVER edit the main checkout ${MAIN} or its build/ (read-only use of ${MAIN_APP} = the PRE-bf9b main app is allowed). NEVER cd in a command; multi-step sequences go in script files under ${SP}/${lane}/ run with bash <file>. zsh does not split a command held in a variable. Stamp times from date, never estimate. Disk: df -h /System/Volumes/Data before any new build dir (stop and report if < 30 GB free).
- No other lane is building right now; a read-only planner reads this branch at commit a7491d4 through git show (it never touches the working tree).
- Probes need python: they fall back to the main checkout's .venv (${MAIN}/.venv, read-only). If you create a .venv symlink in the worktree, REMOVE it before every commit.
- LIVE APP: at most ONE Audio-DNA on the machine. Use the helper: LANE=${lane} . ${SP}/lib/lock.sh (acquire_lock / release_lock / start_app APP OUTDIR [test] / quit_app / outwins / wait_quiet / adna / acquire_quiet_lock). A failed mkdir means WAIT (never open another copy: the same bundle id reaches the running app); never remove another owner's lock; after releasing wait >= 45 s before re-acquiring (the helper enforces it). Hold the lock per run or small batch (<= ~15 min), release between batches. Probes REFUSE without AUDIODNA_LOCK_OWNER matching (the helper exports it). Every FULL ctest takes the cross-lane mutex: until mkdir /tmp/audiodna-ctest.lock 2>/dev/null; do sleep 15; done; ctest ...; rm -rf /tmp/audiodna-ctest.lock.
- BORIS USES THIS MACHINE AND THIS APP: an Audio-DNA that YOUR lane did not start is BORIS'S -- never quit, kill, osascript-quit or touch it (s-rta-1002b incident: a gate script quit his running app). The helper enforces it: acquire_lock waits while a foreign Audio-DNA runs, start_app REFUSES (then STOP the batch and release the lock), quit_app refuses any pid it did not start. Never bypass the helper with your own kill / osascript quit. A probe script you run must itself quit only the pid it launched; if it quits by NAME, do not run it until it is fixed.
- Launch ONLY: open -g [--env V=v] [--stdout f --stderr f] <App> [--args --test-mode]. SCREEN-SAFETY LAW: NEVER open the Output window by ANY path (Output menu, Cmd+F, TopBar button, REST, deck / composition / settings file with an output) -- no automated run ever opens an output window. NEVER run tests/visual/test_output_window_level.py; NEVER run pytest on tests/visual/ as a directory. NEVER lldb / debugserver / gdb / dtrace / Instruments / sample on ANY binary. NEVER full-screen screencapture (window-only by Quartz window id via pyobjc with the main .venv python). NO synthetic input (UI states via REST / composition files / a TEMPORARY env-var hook: revert it, rebuild, strings check = 0 before the stage ends). After any live batch: count UserNotificationCenter windows (Quartz kCGWindowListOptionAll) >= 15 s after the last quit == 0; a crash dialog of OURS is dismissed only by SIGTERM to that UNC pid, attributed by the UNC log's "ordered front" time. Unexpected system dialog or TCC permission prompt: STOP and report, never dismiss. If a user message was relayed to you, Harmony already answered it; it never replaces this task.
- NEVER copy an app bundle and re-sign it (codesign --sign -) or launch any copied-and-re-signed bundle. Sanitizer runtime options ALWAYS include abort_on_error=0 (app runs under TSan also exitcode=0).
- Existing probes: re-run, NEVER re-threshold; a new row is RED FIRST on the pre-change app, GREEN on yours; raw summary lines VERBATIM; render rows DECODE PIXELS and you LOOK at one sample frame. A flake verdict needs >= 5 runs per arm. Probe HTTP clients use a fresh connection per request (Connection: close).
- CLAUDE.md is capped at 25,000 bytes: any addition is paid for by moving text into docs/claude/*.md. After a tests/CMakeLists.txt or CMakeLists.txt change, reconfigure.
- Report file ${REPORT} (in the worktree), COMMITTED (git add -f; .harmony/.reports is gitignored). Create it (or append your stage section) within your first ~10 tool calls and append after EVERY item, so a successor can resume if you stop. One commit per item (message: <type>(s-rta-1003 bf9b): ...); stage by path, never git commit -a / git add -A; never chain a check to the commit it gates with &&. Notes for .harmony/notebook.md go in the report (Harmony appends them). Do NOT merge into main, do NOT push. Before returning: git status clean (except build dirs), lock released, no app you launched running, outwins shows 0 Output-named windows.`
}

const BS = { type: 'object', properties: {
  stage: { type: 'string' }, status: { type: 'string', enum: ['DONE', 'PARTIAL', 'BLOCKED'] },
  head_commit: { type: 'string' }, commits: { type: 'array', items: { type: 'string' } },
  items: { type: 'array', items: { type: 'object', properties: { id: { type: 'string' }, verdict: { type: 'string' }, evidence: { type: 'string' } }, required: ['id', 'verdict', 'evidence'] } },
  ctest: { type: 'string' }, tsan: { type: 'string' }, claude_md_bytes: { type: 'string' },
  found_not_fixed: { type: 'array', items: { type: 'string' } }, stop_items_for_harmony: { type: 'array', items: { type: 'string' } },
  next_stage_notes: { type: 'string' }, report_path: { type: 'string' }, summary: { type: 'string' },
  lock_released: { type: 'boolean' }, app_left_running: { type: 'boolean' }, output_window_opened: { type: 'boolean' },
  errors_or_deviations: { type: 'string' } },
  required: ['stage', 'status', 'head_commit', 'items', 'ctest', 'report_path', 'summary', 'lock_released', 'app_left_running', 'output_window_opened'] }

const CONTEXT = `CONTEXT (read these first): lane bf9b = "decks are boxes of clips; the layers are ONE shared playing stack" (Boris's ruling, BORIS_DECISIONS.md "Decks are boxes of clips"). It was built S0-S4 plus a fix round on branch ${BR}, head a7491d4, and reviewed twice (round-2: 3 x PASS_WITH_NITS, 0 MUST). Since its base (11820fa) main received four merges: hyg (log cleanup), mkvidx (MKV / WebM reverse, Pitfall 64), ui (codec info + Show in Finder + double-click deck rename, Pitfall 65) and bf10 (MilkDrop fills the canvas through a patched libprojectM, Pitfall 66). main head = 5abdf01.
Read IN FULL: ${MAIN}/${OLD}/rulings-bf9b-merge.md (Harmony's rulings R-S1 / R-S2 / R-S3 / R-N1 / R-N3) and ${MAIN}/${RPT}/rulings-bf9b-mergein.md (today's rulings H-1..H-5). Read the lane report's "Fix round", "found_not_fixed (fix round)" and "Resume point (after the fix round)" sections: ${W}/${OLD}/bf9b.md (search for those headings; the file is 170 KB -- do not read it whole). The adopted plan and ruling are ${W}/${OLD}/plan-bf9b.md (its final HARMONY ADOPTION section) and ${W}/${OLD}/ruling-bf9b.md (FINAL CONSOLIDATED GATE LIST) -- consult the parts your stage needs.
ESTABLISHED (verified by Harmony today): git merge-tree main ${BR} reports exactly 6 conflicted files -- .harmony/APP-INVENTORY.md, CLAUDE.md, docs/claude/performance-controls.md, docs/claude/pitfalls.md, src/ui/DeckTabRow.h, src/ui/DeckView.cpp; auto-merged with changes on both sides: CMakeLists.txt, docs/claude/architecture.md, docs/claude/rendering.md, src/MainComponent.cpp/.h, src/api/ApiServer.cpp/.h, src/media/VideoPlayer.cpp/.h, src/ui/DeckView.h, tests/CMakeLists.txt. No Audio-DNA was running and both locks were free at 13:24.
OUT OF SCOPE for this workflow (a later FIX stage builds them from a ruled plan; do NOT start them): the use-after-free read left by the round-1 MUST fix, Undo of Add / Load / Duplicate Deck, the wiring lint, K5 with Link on, the S2b 4.B omissions, the grid NITs, and the removal of the layer strip's source-deck badge. If you trip over one of them, record it in found_not_fixed and continue.`

const STAGES = [
  { key: 'M1', task: `MERGE-IN + R-S3 (rulings H-1, R-S3). No live app in this stage.
1. STEP 0: git -C ${W} status (clean), git -C ${W} log -1 (a7491d4), git -C ${W} rev-parse main (5abdf01...). Then git -C ${W} merge --no-ff --no-commit main.
2. Resolve the 6 conflicted files PRESERVING BOTH SIDES' BEHAVIOUR. main's side: the ui lane's double-click rename-in-place of the SHOWN deck tab (Pitfall 65: a rename box over a rebuilt row), right-click tab menu, Show in Finder, the clip codec-info line; bf10's MilkDrop canvas FBO (Pitfall 66); mkvidx (Pitfall 64); hyg's logLine sweep. The lane's side: decks are boxes (no per-deck layers, no Persistent, no deck fade), DeckView::showDeck, deck-tab dots, the strip badge, the load notice, retired decks. Read docs/claude/pitfalls.md entries 64-66 on main and the ui / bf10 lane reports' relevant parts (${MAIN}/${OLD}/ui.md, ${MAIN}/${OLD}/bf10.md -- search, do not read whole) before resolving DeckTabRow.h / DeckView.cpp.
3. SEMANTIC conflicts in AUTO-MERGED files: code that main added after 11820fa and that still uses an API the lane deleted or changed (per-deck layers such as getActiveDeck().layers / activeDeckIndex in render code, Persistent identifiers, DeckClock, compositeDeck, the deck fade, the old trigger tuple), and code the lane added that uses something main changed. The compiler, the lane's B4 text lints (in ctest) and test_render_thread_lint find them. Fix each on the lane so that main's feature keeps its behaviour on the shared layer stack. bf10's MilkDrop code walks layers: adoption item H3 says the preset-playlist advance must walk the PLAYING layers whatever deck is shown, H2 says a deck switch never calls ProjectMSource::loadPreset / resize / releaseGL -- keep both true after the merge (the lane pinned H3 with a text lint in tests/test_render_thread_lint.cpp).
4. R-S3: "Pitfall NN" -> 67 in CLAUDE.md's index and docs/claude/pitfalls.md (final order 64 mkvidx, 65 ui, 66 bf10, 67 bf9b; 68 stays free for bf2). ONE POST /api/debug/undo route = main's (ui lane): drop the lane's duplicate registration and its handler if main's performs the same Cmd+Z; point probe-boxes' rows (k1a undo, k9c) at it; keep the lane's /api/debug/remove_deck and /api/debug/save_composition. docs/claude/testing-eyes.md lists each test-only route once.
5. CLAUDE.md <= 25,000 bytes after the merge (wc -c; main 23,962 B, lane 24,264 B); the lane's rule-15 rewording and main's lines both survive; pay for overflow by moving text into docs/claude/*.md. .harmony/APP-INVENTORY.md: both sides' rows kept, counts re-derived (never inherited).
6. Commit the merge (one merge commit: merge(s-rta-1003 bf9b): main into lane/bf9b -- <what was resolved>), then separate commits for R-S3 items that are not conflict resolutions.
7. GATES for this stage (raw summary lines verbatim): reconfigure + cmake --build ${W}/build-lane -j6 (rc 0, ALL targets: the app and every test target); full ctest SERIAL under the mutex (ctest --test-dir ${W}/build-lane --output-on-failure) -> 0 failures, and explain the count: count(merged) vs count(main 5abdf01) = 1191, count(lane a7491d4) = 1157, count(base 11820fa) -- report the arithmetic and any test both sides added; .harmony/probe-tsan-unit.sh on ${W}/build-tsan -> exit 0, 5 / 5, zero "WARNING: ThreadSanitizer"; the lane's B4 text lints PASS inside ctest (name them); git -C ${W} grep for conflict markers == 0.
8. Report: a TABLE of every conflict hunk and every semantic fix (file, what main wanted, what the lane wanted, the resolution), the gate lines, CLAUDE.md bytes, and next_stage_notes for the M2 builder.` },
  { key: 'M2', task: `BY-NAME-QUIT SWEEP (ruling R-N1; H-3, H-4). Boris uses this machine and this app: no script may ever quit or kill an Audio-DNA it did not start.
1. Inventory: grep over ${W}/.harmony and ${W}/tests (and ${W}/cmake, ${W}/scripts if they exist) for every way a script quits / kills Audio-DNA by NAME: tell application "Audio-DNA" to quit | pkill.*Audio-DNA | killall.*Audio-DNA | adna_kill | kill .*pgrep.*Audio-DNA | pkill -f AudioDNA | similar. The lane report's fix round lists 31 (gate-s165.sh probe-beatclock.sh probe-async-load.sh probe-btguard.sh probe-capture.sh probe-crossfade.sh probe-deck-path.sh probe-deck-tabs.sh probe-downbeat-level.sh probe-effects-parity.sh probe-finalize-loop.sh probe-fitmode.sh probe-idle-paint.sh + .py probe-image-load.sh probe-lane3.sh probe-manual-bpm.sh probe-mastersignal.sh probe-media-open.sh probe-outputs.sh probe-onset-render.sh probe-routines.sh probe-seq-vram.sh probe-routine-display.sh probe-resync.sh probe-tempo-silence.sh probe-tempo-start.sh probe-step3.sh probe-tsan.sh probe-video.sh probe-vupload.sh); re-count after M1's merge (main brought more scripts) and print the list with the matching line of each.
2. Convert EVERY one to the lane's shared helper .harmony/probe-quit-ours.sh: record_ourpid right after the launch and BEFORE the health-wait loop (gates-r2 NIT 6: today probe-canvas.sh records it after the 60 s loop -- fix there too), quit_ours for every quit; a script REFUSES TO START (non-zero exit, a clear line naming the foreign pid) when an Audio-DNA it did not start is already running -- never "kill the stale one first"; a script that ATTACHES to a running app follows bf10's attach-refusal pattern (see probe-milkdrop on main). Same edit shape everywhere; change NO threshold, row, timing or fixture. probe-outputs.sh opens Output windows: convert its quit path but NEVER run it. H-3: quit_ours itself is not changed (see the ruling).
3. gates-r2 NIT 4: register k1b_duplicate as its own row in probe-boxes' row list (it stays callable from k1b_switch_video's flow if that is how the fixture is shared; a row filter of k1b_duplicate must select it).
4. PROOF (all printed in the report): (a) the by-name grep over the same tree == 0 hits outside probe-quit-ours.sh's only-ours branch and comment lines; (b) bash -n on every edited .sh and python -m py_compile on every edited .py; (c) extend the helper's selftest so every refusal branch is exercised WITHOUT any real foreign Audio-DNA (a dummy process and the helper's injectable name / pid seam, the bf10 selftest pattern): foreign running at start -> refuse; foreign appears before quit -> refuse and leave it alone; ours only -> quits; no pid recorded -> quits nothing and says so; run it and paste the summary; (d) live smoke under the lock: run THREE converted probes end to end on the lane app (pick cheap ones that open no Output window, e.g. probe-deck-tabs, probe-image-load, probe-crossfade) and show each launched and quit only its own pid (pid lines) with its normal verdict line; (e) 0 Audio-DNA / Output / UserNotificationCenter windows after.
5. Commit per logical group (helper + selftest; the sweep; the NITs). If src or tests changed (they should not), rebuild + ctest serial.` },
  { key: 'M3', task: `MILKDROP DECK-SWITCH ROW (ruling R-S1; adoption H1-H3 -- a REQUIRED merge gate row) + POST-MERGE PROBE RE-RUNS (H-5).
1. Add row m9b_deck_switch_live to .harmony/probe-milkdrop.py (it came from main in M1): a 20-deck show; a MilkDrop clip fired from deck 0 into layer 0 and playing; walk POST /api/switch_deck 1..19 and back to 0 with a dwell on each. PRE-REGISTERED BARS (use the probe's EXISTING floors and readers for "live MilkDrop picture" and "current preset" -- name them in the report; never invent a looser one): (H1) at every switch the canvas (POST /api/render_frame, decoded) is still a live MilkDrop picture: above the probe's existing non-black floor, and two captures 0.5 s apart differ by at least the probe's existing motion floor; (H3) the preset playlist ADVANCES at least once while a deck other than 0 is shown (set the playlist to its shortest interval; read the current preset the way the existing rows do); (H2) a deck switch triggers no ProjectMSource::loadPreset / resize / releaseGL: read it through whatever the existing rows read (a log line or a counter). If NO reader exists for H2, add a TEST_SERVER-only, read-only counter set to GET /api/state (the lane's /api/debug pattern; no behaviour change), document it in docs/claude/testing-eyes.md, and keep the audio callback / render-thread rules (an atomic counter, no lock). RED FIRST on the PRE-bf9b main app ${MAIN_APP} (expected RED by behaviour: there a deck switch shows another deck's layers); GREEN on the lane app. If the RED arm is not RED, STOP the row and report it in stop_items_for_harmony (never re-threshold). LOOK at one RED frame and one GREEN frame and say what they show; save both under ${SP}/bf9b-merge-M3/frames/.
2. Post-merge live re-runs under the lock, each probe launching and quitting only its own app, raw verdict lines verbatim, arms never mixed in one launch:
   a) .harmony/probe-boxes (all rows) on the RED arm = ${MAIN_APP} (pre-merge main; it has per-deck layers like STAGE_P) and on the GREEN arm = the lane app (follow the lane report's "Resume point" item 6 for the k7_old_take ordering and BOXES_OLD_TAKE). Compare the RED pattern with the lane report's S4.1 STAGE_P table: any row that differs because main still has Persistent or gained ui / bf10 code is LISTED with the reason. K5 with Link on stays BLOCKED (verdict line prints BLOCKED, rc 3) -- do not build a Link driver here.
   b) .harmony/probe-canvas non-perf rows on the lane app (f2_deck_transition is RETIRED by ruling R-S2).
   c) .harmony/probe-milkdrop full on the lane app: every bf10 row GREEN as on main (20 PASS / 0 FAIL there) plus m9b.
   d) the three probes the ui lane added or changed for deck tabs / rename / codec info (find them from ${MAIN}/${OLD}/ui.md "G3") on the lane app: the ui lane's verdict (53 / 0 on main) must hold after the merge.
3. If step 1 touched src or tests: rebuild, full ctest serial under the mutex, probe-tsan-unit (5 / 5). Commit per item. Final: git status clean, lock released, 0 Audio-DNA / Output / UNC windows.
4. Report: RED / GREEN lines per row, the frames' paths and what they show, the list from 2a, and a "HAND-OVER TO THE FIX STAGE" section (head commit, build dirs' state, anything the fix builder must know).` },
]

phase('Build')
const out = []
let prev = null
for (let i = 0; i < STAGES.length; i++) {
  const s = STAGES[i]
  const head = i === 0
    ? `LANE ${LANE}, stage ${s.key} (${i + 1} of ${STAGES.length}), worktree ${W}, branch ${BR}.`
    : `LANE ${LANE}, stage ${s.key} (${i + 1} of ${STAGES.length}), worktree ${W}. CONTINUE on branch ${BR} from commit ${prev.head_commit} (no reset, no re-checkout; the build dirs exist -- rebuild incrementally). FIRST read the lane report so far (${REPORT}) and git -C ${W} log --oneline a7491d4..HEAD. The previous stage's hand-over: ${String(prev.next_stage_notes || '').slice(0, 4000)}`
  const r = await agent(`${head}
${CONTEXT}
YOUR STAGE'S SCOPE: ${s.task}
RETURN: the structured result; summary <= 1200 characters (the full detail lives in the report file); items = one entry per numbered step with its verdict and the key evidence line.
${RULES(LANE + '-' + s.key)}`, { agentType: 'builder', model: 'opus', effort: 'high', schema: BS, phase: 'Build', label: 'build:' + LANE + ':' + s.key })
  if (!r) { log(LANE + ' ' + s.key + ': builder returned null'); return { stages: out, failedStage: s.key } }
  const slim = Object.assign({}, r, { summary: String(r.summary || '').slice(0, 1400), next_stage_notes: String(r.next_stage_notes || '').slice(0, 1500), errors_or_deviations: String(r.errors_or_deviations || '').slice(0, 1200), items: (r.items || []).map(x => ({ id: x.id, verdict: String(x.verdict || '').slice(0, 160), evidence: String(x.evidence || '').slice(0, 300) })) })
  out.push(slim)
  log(LANE + ' ' + s.key + ': ' + r.status + ' @ ' + r.head_commit)
  if (r.status !== 'DONE') return { stages: out, stoppedAt: s.key }
  prev = r
}
return { stages: out, head: prev.head_commit }
