export const meta = {
  name: 'rta-1003-recon-facts',
  description: 'Audio-DNA s-rta-1003: seven read-only fact sheets (sonnet) for Boris feedback items BF11-BF29, written to .harmony/.reports/s-rta-1003/facts-*.md',
  phases: [{ title: 'Recon' }],
}
const MAIN = '/Users/boriskarpman/projects/RealTimeAudio'
const RPT = '.harmony/.reports/s-rta-1003'
const OLD = '.harmony/.reports/s-rta-1002b'
const SRC = MAIN + '/.claude/worktrees/recon'
const BF2 = MAIN + '/.claude/worktrees/bf2'

const COMMON = `READ-ONLY FACT SHEET. You establish facts for a planner; you propose no design and fix nothing.
WHERE TO READ: the source tree ${SRC} -- a detached, source-only checkout of commit a7491d4 (branch lane/bf9b: the app AFTER the "decks are boxes of clips" change, which merges into main today). Read source ONLY there (plain files; grep / read freely). Do NOT read source from ${MAIN} (older model) or from ${MAIN}/.claude/worktrees/bf9b (a builder is editing it). Reports and plans are plain files under ${MAIN}/${OLD}/ and ${MAIN}/${RPT}/. Boris's words: ${MAIN}/.harmony/boris-feedback-backlog.md section "Boris feedback of 2026-10-03" (verbatim block) and ${MAIN}/.harmony/binding-decisions.md "2026-10-03 (s-rta-1003)". Project docs: ${SRC}/docs/claude/*.md, ${SRC}/.harmony/APP-INVENTORY.md, ${SRC}/.harmony/gotchas.md.
RULES: never build, never run a test, never launch the app or a probe, never edit any file except your one report, never cd in a command, absolute paths only. Label every line VERIFIED (you read the code: cite file:line in ${SRC}) or INFERRED (reasoned, not read end to end) or UNKNOWN-NEEDS-A-RUN (say the cheapest discriminating test, e.g. which REST route + what to capture). Quote Boris only verbatim.
REPORT FORMAT (write with the Write tool or a bash heredoc to the literal path given as REPORT_FILE): 1 QUESTIONS ANSWERED (one block per question below: the answer, the evidence lines); 2 TABLES where asked; 3 WHAT EXISTS TODAY vs WHAT BORIS ASKED (plain gaps, no design); 4 UNKNOWN-NEEDS-A-RUN list; 5 FILES A BUILDER WOULD TOUCH (paths only); 6 EXISTING TESTS / PROBES that cover this area (names) and which REST routes can drive it without synthetic input (the app has a production REST API on 7070 and a test server on 8080 -- docs/claude/integration.md, testing-eyes.md).
RETURN (StructuredOutput): report_path, key_facts (<= 8 short lines, the ones a planner must not miss), unknowns (<= 6 short lines).`

const FS = { type: 'object', properties: { report_path: { type: 'string' }, key_facts: { type: 'array', items: { type: 'string' } }, unknowns: { type: 'array', items: { type: 'string' } } }, required: ['report_path', 'key_facts'] }

const TOPICS = [
  { key: 'keying', q: `TOPIC: the KEYING menu, the Keying slider, and the COMPOSITING (blend) menu -- Boris (verbatim): "Can you figure out how to get everything working in the keying menu? Does the keying slider actually do anything? Maybe we get rid of it. Some elements in the keying menu work and some don't. Should we use the transparency slider to do the work for keying elements? Also review the compositing menu, right slider in layer strip. These elements don't work: Creative, 3D,"
QUESTIONS: (1) Where is the keying menu built (LayerStrip / LayerInspector / elsewhere)? List EVERY entry in menu order with its enum value (KeyingMode or whatever it is) and label. (2) For each entry: the model field it sets, the uniform(s), and the shader code that implements it (file:line of the branch). Which entries have NO implementing branch, share a branch with another entry, or are overwritten elsewhere? See .harmony/gotchas.md "KeyingMode enum != Layer::Type". (3) The Keying slider on the layer strip: UI -> model field -> uniform -> shader use, per keying entry: in which modes does the value change the picture, in which is it ignored? (4) The opacity ("transparency") slider's path, and how keying amount and opacity combine in the compositor. (5) "The compositing menu, right slider in layer strip": identify it (the blend-mode menu? what is the right-hand slider?). List every GROUP and every entry (about 55 blend modes are documented); for each entry say where its blend function is implemented (shader file:line / case) or that it falls through to a default. Give special detail for every entry in the groups named "Creative" and "3D": what each needs (a depth value? a second texture? a uniform nobody sets?) and why it would show no effect. (6) Does a transition use the same blend table (transitions list ~55 blends)? Are the broken ones broken there too?
TABLES: T1 keying entries (entry | enum | implemented where | slider used? | status WORKS-BY-CODE / NO-BRANCH / SUSPECT + why); T2 blend entries by group (entry | enum | implemented where | status).` },
  { key: 'transport', q: `TOPIC: clip TRANSPORT -- Boris (verbatim): "Firing a column that is already playing should restart its videos" / "When I grab the play head and move the timeline, I do not want it to jump back to where it was or where it should be playing before I grabbed it. I wanted to keep playing at the same speed, but play from wherever I drop the play head." / "As far as a video clip is concerned, it is in two categories, either BPM synced throughout the whole thing, or just playing with a speed control. If it is BPM synced, regardless of the length, it is synced to the current playing BPM and it has bars that the user can set. We automatically set bars for a cliff, but the user can change the bars in it by amount." / "Regardless of the clip being BPM or speed controlled, if we are in Qantize mode, it is triggered on time by the Qantize method."
QUESTIONS: (1) Trace a CELL trigger and a COLUMN trigger of a clip that is already the playing clip of its layer (handleColumnTrigger, triggerClip*, the ClipRef trigger tuple, hasBeenTriggered, Pitfall 7, Pitfall 2): what restarts a video on a cell re-fire, and where does a column re-fire differ so that the videos keep running? (2) What happens to a video that played, was replaced, and is fired again (resume from where it was vs restart): where is that decided (the lane calls it C3)? (3) The playhead drag: which UI component (the Clip tab's timeline bar?) handles the drag, what does it write (model field / command / VideoPlayer call) during the drag and on release, and which clock or sync path writes the position afterwards -- list every writer of the clip's playhead position per transport mode, and name the candidates for the jump-back (label INFERRED vs VERIFIED). Pitfalls 56, 62, 64 (video decode thread, reverse, seek) -- what a seek does on the decode side. (4) Transport modes: the enum, the "BPM Sync" mode (docs/claude/history.md says "BPM Sync transport mode for video/image sequences with beat division presets"; architecture.md beatDivision "beats per playback cycle"): how position / speed are computed from the beat clock, what happens when BPM changes, what the UI offers (presets? a number box?), whether any automatic length exists, and what the speed-control mode does. (5) Quantize: where a trigger is queued and released; does it treat both transport modes alike? (6) What the UI shows for a clip's length today and in which unit; the removed "Beats/Duration" row (plan-bf7 / ruling-bf7 mention it).` },
  { key: 'quantize-units', q: `TOPIC: QUANTIZE choices and BARS / BEATS wording -- Boris (verbatim): "Quantize 1 bar, 1/2 bar, 1/4, 1/8, 1/6" / "Let's get rid of beats and just have bars in most places unless beats are necessary. For setting a clips beats, these are done with beats and not bars. For most other things, we will use bars. For the circle at the top that counts off 1234 and then starts over, those are beats as well." / "I have beats and seconds in the milkdrop editor. I only need beats."
QUESTIONS: (1) The top-bar Quantize menu: entries today, the enum, where the value is read. The per-clip / per-routine snap granularity enum (docs/claude/performance-controls.md "beat snap granularity"). (2) The trigger queue: how the release boundary is computed (Pitfall 42: totalBeatCount + beatPhase); can it already release on 1/2 bar, 1/4 bar (= 1 beat in 4/4), 1/8 bar, 1/16 bar boundaries, or only whole beats / bars? What would sub-beat boundaries need (analysis hop is ~10.7 ms; the render thread releases triggers?). (3) The adopted "bars everywhere" plan: ${MAIN}/${OLD}/plan-bf7.md and ruling-bf7.md (read the item list, the HARMONY ADOPTION section at the end of the plan, and its Boris questions): list every item, and mark the ones that CONFLICT with or are CHANGED by today's words (clip length stays in beats; the top circle counts beats; the Quantize list; MilkDrop: no seconds). (4) The MilkDrop editor / jukebox: every control that shows beats or seconds (labels, what they really drive -- the plan says "30 sec / 60 sec" were 32 / 64 bars), file:line. (5) A table of every UI label in src/ui that shows "beat(s)" or "bar(s)" (file:line, the label text, what it sets) -- reuse plan-bf7's inventory where it is VERIFIED at a7491d4, re-check 10 of its lines.` },
  { key: 'topbar-sync', q: `TOPIC: the TOP BAR (Gain slider, where Sync goes) and how the SYNC setting is stored -- Boris (verbatim): "Sync lives in top bar" / "For sync control we should have a way to remember it as part of a composition save. I imagine if a user is doing this professionally, they will set up the venue and save it in case of a computer crash or something and if they come back to that venue, they have the settings already." / "Gain slider in top bar could be twice as long. I have very little space to move it because I start at a quarter from the left edge and move down from there so I have very little distance to make a lot of fine adjustment."
QUESTIONS: (1) TopBar layout in ${SRC}/src/ui (TopBar.*): every section left to right with its width rule (fixed px / proportional), the Gain slider's width and range and where its default sits, the minimum window width, what the removal of the deck "Fade:" section (done on this branch) freed, and which sections would have to shrink to double the Gain slider and add a Sync control (a number box with - / + buttons and a drag bar). ResettableSlider rule (CLAUDE.md UI Patterns) and Pitfall 57 / 59 (timer repaints) constraints for a new top-bar widget. (2) The sync-dial lane: worktree ${BF2} (branch lane/bf2 at 4a1f240; plain files, nobody is editing it): where the sync offset lives (AppSettings venue profiles? field names), the REST / OSC routes that set it, how it is applied (analysis delay line vs beat-clock lead), what its plan says about the on-screen control "S5" and about venues (${MAIN}/${OLD}/plan-bf2.md, ruling-bf2.md, the plan's HARMONY ADOPTION section). (3) Composition save / load: where a composition file is written and read at a7491d4 (the serializer, the file's top-level keys, the version / migration mechanism -- ShowMigration.h), and where a per-composition "venue name + sync ms" pair would sit; what happens today to app-level settings when a composition loads. (4) What the top bar's beat wheel reads (which clock) and what the sync offset shifts on lane/bf2: does the wheel follow the shifted or the unshifted beat? (Boris: "The music is in time and the visuals should be delayed or a little ahead depending on how the system is wired.")` },
  { key: 'record-codec', q: `TOPIC: RECORD TO CLIP changes and the CODEC choice -- Boris (verbatim): "When record to clip, we want to see the recording in the layer it is recording to while it is being recorded. Can you do that?" / "Recording a clip should be prominently displayed, so it can be recorded as long as the user likes. There's no limit except hard drive Space." / "The recording should look exactly like the output. If there's a logo, it should look exactly as it's displayed." / "The recording will always play like a regular clip once it is recorded." / "We should pick the most optimal Kodex to use and not worry about the other ones. Web M is not necessary. I want codecs that decode easily and play well"
QUESTIONS: (1) The adopted record-to-clip plan: ${MAIN}/${OLD}/plan-bf1.md + ruling-bf1.md + the plan's final HARMONY ADOPTION section: summarize the stages (S1 / S2 / S3), where the automatic end (64 bars) is specified, how see-through (alpha) is handled, where the finished clip lands, which codec / container the recording uses, and what is shown on screen while recording. Mark every item today's words CHANGE. (2) VideoRecorder at a7491d4 (src/...; docs/claude/integration.md "video recording"): encoders available (H.264 / ProRes / MJPEG via FFmpeg), pixel formats, whether any path can write ALPHA (ProRes 4444, HAP Alpha, PNG / QuickTime Animation), how frames are captured (Pitfall 25, Pitfall 37: the canvas), and any existing limit or disk-space check. (3) VideoPlayer decode paths per codec (Pitfalls 56, 60, 62, 64; docs/claude/rendering.md): which codecs decode through VideoToolbox / IOSurface, which in software, which are intra-only (cheap reverse / scrub), HAP support, alpha support on playback. Build a table: codec | decode path | reverse / ping-pong cost per the docs | alpha playback | notes. (4) What the app does today with a see-through layer in the compositor (premultiplied? keying pass?) -- what "looks exactly as it's displayed" would require from a recorded single layer. (5) A LIVE picture in a grid cell while recording: how cell thumbnails are produced (ClipThumbnails, Pitfall 51: "a deck-grid refresh never decodes a file") and what a live-updating cell would need under Pitfall 57 / 59 (repaint cost). (6) Is there any measured decode-cost data in the repo (${MAIN}/${OLD}/mkvidx.md, probe-vupload*, .harmony/.reports/*) comparing codecs on this Mac? List what exists; do not invent numbers.` },
  { key: 'envelope', q: `TOPIC: the ENVELOPE EDITOR -- Boris (verbatim): "How do I access the bigger envelope, editor? I don't think I need it? I am fine using the envelope editor in the signal tab. I want all of the controls to work in that one rather than an extra bigger envelope window." / "Long samples: ... Default: the whole sample. I want to be able to use the whole thing or to shorten it manually but clicking to timing marks." / "Explain this to me. Where do I draw the timeline curve?"
QUESTIONS: (1) The adopted envelope plan: ${MAIN}/${OLD}/plan-bf45.md + ruling-bf45.md + the plan's final HARMONY ADOPTION section: list the stages and items; which stage builds the BIG VIEW (Stage E?), and every item in the OTHER stages that assumes the big view exists (the moving position line "only in the big view", editing precision, Esc behaviour, header buttons). What is left if the big view is dropped, and which controls would then have to fit in the Signal tab's editor. (2) The Signal tab's envelope editor at a7491d4: component, size (the plan says a 100 px canvas inside a Viewport), what it can edit today (points? segments? length in beats / bars? play once?), which controls exist but do nothing. Constraints: Pitfall 57 / 59 (a timed repaint costs the whole window; NativeLayerHost), the Viewport. (3) Sample envelopes (envelope extracted from an audio sample): what the plan specifies for length (up to 10 minutes), bands, and where a manual TRIM of the sample (start / end snapped to timing marks = bar lines at the current BPM) would attach; does the plan have timing marks drawn over the sample? (4) The drawable Timeline curve: binding-decisions.md "BUILD THE DRAWABLE TIMELINE CURVE" (around line 258) and ${MAIN}/${OLD}/plan-bf6.md / ruling-bf6.md: where would Boris draw it (which editor, which tab), what exists today (AutomationCurve, ConnSource::Kind::Envelope / Timeline), and what bf6 Stage 1 changes. (5) Is anything of bf45 or bf6 already on this branch or on main (git -C ${MAIN} log --oneline -5 --grep=bf45; --grep=bf6)?` },
  { key: 'deck-names', q: `TOPIC: characters in DECK NAMES and file names -- Boris (verbatim): "If there are '/' characters in a decks file name, do not worry about adding sub folders. They are just characters. If there are characters that are no good, then let me know and we will create a fix together". Known bug (Harmony's page, 2026-10-02): a "/" in a deck name makes Save Deck As propose a sub-folder instead of a file name.
QUESTIONS: (1) Every place a deck name or composition name becomes a file name or path at a7491d4: Save Deck As, Save Deck, Save Composition (As), autosave / restore, the Audio store, recordings, takes / routines exports, the lane's POST /api/debug/save_composition; for each: how the default file name is built (file:line), whether any sanitizing exists (juce::File::createLegalFileName, replaceCharacters, ...), and what happens with "/" , ":" , a leading ".", a trailing space, an empty name, a 255+ byte name, emoji. (2) The reverse direction: loading a deck file -- is the deck's NAME taken from the file name or from inside the JSON? (3) Rename in place (double-click a deck tab, Pitfall 65, on MAIN not on this branch: read it as git -C ${MAIN} show main:src/ui/DeckTabRow.h and main:docs/claude/performance-controls.md): what characters does the rename box accept? (4) macOS facts needed for a fix: which characters a file NAME cannot contain at the POSIX level and how Finder displays ":" -- label these INFERRED unless you verify them with a harmless test in your own temp dir under $TMPDIR (allowed: mkdir / touch / ls / rm inside $TMPDIR only).` },
]

phase('Recon')
const res = await parallel(TOPICS.map(t => () => agent(`${COMMON}
${t.q}
REPORT_FILE: ${RPT}/facts-${t.key}.md (relative to ${MAIN}; absolute: ${MAIN}/${RPT}/facts-${t.key}.md)`, { agentType: 'general-purpose', model: 'sonnet', effort: 'high', schema: FS, phase: 'Recon', label: 'recon:' + t.key })))
return TOPICS.map((t, i) => ({ topic: t.key, ok: !!res[i], path: res[i] ? res[i].report_path : null, key_facts: res[i] ? (res[i].key_facts || []).slice(0, 8).map(x => String(x).slice(0, 260)) : [], unknowns: res[i] ? (res[i].unknowns || []).slice(0, 6).map(x => String(x).slice(0, 200)) : [] }))
