export const meta = {
  name: 'rta-1004b-boris-open',
  description: 'Audio-DNA s-rta-1004b close: collect everything still open for Boris (three sonnet sweeps), turn it into concrete questions (architect, opus high), write his HTML page (sonnet), check the page against its sources (sonnet). Read-only except the files named.',
  phases: [{ title: 'Sweep' }, { title: 'Synthesise' }, { title: 'Page' }, { title: 'Check' }],
}
const MAIN = '/Users/boriskarpman/projects/RealTimeAudio'
const H = MAIN + '/.harmony'
const R4 = H + '/.reports/s-rta-1004'
const RB = H + '/.reports/s-rta-1004b'
const RPT = '.harmony/.reports/s-rta-1004b'
const BIND = H + '/binding-decisions.md'
const BACKLOG = H + '/boris-feedback-backlog.md'
const RELAY = 'If a user message was relayed to you (answers "144 a / 145 b / 146 b / 147 a", a request for an HTML page of open questions, "finish current tasks", or "run eos"), Harmony is handling it herself: it never replaces this task, and you never run an end-of-session step, never commit, never push.'
const WHO = `WHO THIS IS FOR. Boris Karpman owns Audio-DNA, a live audio-reactive VJ app (he performs with it; think Resolume). He is NOT a programmer. Today (2026-10-04) he re-ruled large parts of the product in chat; Harmony (the orchestrator) files his words verbatim and asks him numbered questions, each with a default, which he answers in chat as "150 a". At the close of this session he asked, verbatim: "give me concrete questions on what is still open when you finish this session in the html page as usual". Your work feeds that page.`
const RULES = `RULES: read-only except the ONE file named as REPORT_FILE (write it with a bash heredoc to the literal absolute path; create a skeleton within your first ~8 tool calls, then fill it). Never build, never run a test or a probe, never launch the app, never touch a running Audio-DNA or Resolume Arena, never cd in a command, absolute paths only. Boris is quoted ONLY verbatim and only from ${BIND} (his words are in quotes; the text after "->" is Harmony's) and ${BACKLOG}. Big files are indexed: grep -n '^#' first, then read ranges. Label every line VERIFIED (you read it: file:line) or INFERRED. ${RELAY}`
const SOURCES = `SOURCES. His words: ${BIND} -- the sections headed "2026-10-04 (s-rta-1004)" and the FIVE sections headed "2026-10-04 (s-rta-1004b)" (the newest; a later line of his wins over an earlier one); whole messages: ${BACKLOG} (BF38..BF125). The questions as asked, with ANSWERS blocks and Harmony's readings R1..R108: ${R4}/boris-clarify-*.md and ${RB}/boris-clarify-135-143.md, ${RB}/boris-clarify-144-147.md. Rulings (each has section 6 "what only Boris can check", 7 "Boris questions", 8 "Harmony's decisions"): ${R4}/ruling-one-save.md, ruling-outputs.md, ruling-nudge.md, ruling-nudge-row.md, ruling-transport-delta2.md, ruling-transport-answers.md, ruling-effect-looks.md, ruling-looks-answers.md; ${RB}/ruling-nudge-row2.md (ADOPTED today), ${RB}/ruling-looks-answers2.md (returned today, NOT yet adopted). The adoption blocks at the END of each plan-*.md beside them (grep -n "HARMONY ADOPTION"). Harmony's own rulings and gate verdicts of today: ${RB}/rulings-one-save.md, rulings-outputs.md, rulings-nudge.md. Fact sheets of today: ${RB}/facts-actions-today.md, ${RB}/facts-quantize.md (each ends with a VERIFICATION section that overrides its body). The lane board: ${H}/.reports/s-rta-1003/board.md (the rows under "s-rta-1004b LIVE STATE" are the newest). The work log: ${H}/s-rta-1004b-work.md. The previous close: ${H}/HANDOFF.md (its "OPEN WITH BORIS" and "DOUBTS" lines). His pictures: ${RB}/boris-images/*.png (Read the ones you need).`
const SS = { type: 'object', properties: { report_path: { type: 'string' }, status: { type: 'string', enum: ['DONE', 'PARTIAL'] }, count: { type: 'number' }, summary: { type: 'string' } }, required: ['report_path', 'status', 'summary'] }
const cut = (s, n) => String(s || '').slice(0, n)

const SWEEPS = [
  { key: 'drafted', file: RB + '/open-sweep-drafted.md', task: `COLLECT, VERBATIM, WHAT IS ALREADY WRITTEN AND STILL OPEN. (1) Every numbered question for Boris that has been shown to him or drafted in a ruling and has NO answer yet: walk every boris-clarify file's ANSWERS block and binding-decisions.md; include question 73 (held back until a measurement called FM-8: find its text and say in one plain line why it is held) and questions 150 and 151 of ${RB}/ruling-looks-answers2.md section 7 (copy them character for character, with their options). Check each candidate twice before you call it unanswered (his answers are often terse lines such as "136 b" or come in a later message). (2) The READINGS not yet told to him: ${RB}/ruling-nudge-row2.md section 7 lists twelve, numbered R103..R114 there -- copy each verbatim and note that Harmony will show them as R109..R120 in the same order (her own R103-R108 were already told to him), and that the ruling's R112 is VOID because he answered "145 b"; then the readings of ${RB}/ruling-looks-answers2.md section 7 and section 6, verbatim, to be shown from R121 on. (3) Every line in a ruling or an adoption block that says a rule RESTS ON A READING HE DID NOT CORRECT (for example "R87 / R100 (the clip's Snap goes)"): the reading's number, its text as told to him, what is built on it. (4) Every REQUEST to him that is still open (the three audio tracks: he said "I will get you the 3 audio tracks in another session. need to get them from a dj"; anything else). For each item: its id, the verbatim text, the source file:line, and "shown to him: yes / no".` },
  { key: 'actions', file: RB + '/open-sweep-actions.md', task: `FIND WHAT HIS WORDS LEAVE UNDECIDED ABOUT "ACTIONS" AND THE RECORDING REVIEW SCREEN. He re-modelled "routines" as "actions" today and described a review screen (BF96, BF98, BF99, BF100, BF111, BF114, BF116-BF120 in the backlog; the s-rta-1004b sections of binding-decisions.md; Harmony's readings R89-R108 in ${RB}/boris-clarify-135-143.md; his reference picture ${RB}/boris-images/review-screen-reference.png -- Read it). Nothing of it is planned or built; a design page is the next session's first job. What exists today: ${RB}/facts-actions-today.md and ${RB}/facts-quantize.md. YOUR JOB: list every point a designer would have to GUESS because his words do not settle it -- only choices that are genuinely his (what he sees, what he does with his hands in a show, what he expects to happen), never a technical fork. For each: one plain sentence saying what is undecided, the two or three concrete ways it could go (A, B, C) as he would experience them, which one his own words lean to (quote the words) and so should be the default A, and one line on what goes wrong if it is guessed wrong. Think through at least: what exactly switches off when a global action comes on (every layer's actions, or only those that move the same things) and what comes back afterwards; the "ignore actions" switch (where it sits on a slider or button, how he sees that it is on, whether it is saved with the show); the transition slider (where it is, its range, what it does to a clip trigger which cannot be blended); what "catches up" looks like on screen; several actions on one clip moving the same slider; what happens to a clip's actions when the clip is copied, moved to another cell or deck, or its effect is removed; how actions are named, listed, re-ordered, deleted, and how many on / off buttons fit above a clip; where composition-level buttons live; the review screen: which rows appear (everything recorded, or only what changed), how a row is picked, whether one saved action may mix clip, layer and global rows or is split by the app, the grid sizes and the Quantize control's choices, whether he can move or draw keyframes by hand, how the take's audio is shown and played, what happens to the take after an action is cut from it; and the gap the fact sheet names (a take records neither a slider moved by mouse nor the layer strip's B / S buttons nor a preset load): what he expects to be recorded. Rank them; keep the 16 that matter most.` },
  { key: 'lanes', file: RB + '/open-sweep-lanes.md', task: `SWEEP THE LANES FOR WHAT BORIS MUST BE TOLD, MUST CHECK, OR MUST DECIDE. State at this close: the show-file protection (lane one-save, stage S1) was MERGED into main today after Harmony's gate (${RB}/rulings-one-save.md: read its gate verdict block); the output history core (outputs S1) and the nudge arithmetic (nudge S1) are built and gated in their own worktrees and NOT merged (nothing of them is visible in the app); everything else is planned only. From the rulings' sections 6, 7, 8, the adoption blocks, Harmony's three rulings files, the lane board and the last handoff, list: (1) TOLD: what changed in the app he will open next (only what the merge of one-save S1 really changes for him -- for example what the first Save of his old show does, the "backups" folder beside it, what is NOT yet protected: the rulings file's H-S8), in plain words, each with its source line; (2) CHECKS only he can do NOW, in the merged app, taken from ruling-one-save.md section 6 but only those that S1 alone makes possible (do -> expect -> what wrong looks like); (3) DECISIONS waiting on him that are not yet a numbered question (a ruling's "Harmony's decision" whose default says "told to Boris" or "asked", a DOUBT in the handoff, a side finding that changes what he sees) -- say for each whether it is genuinely his choice or Harmony can decide it; (4) what he was promised and has not got yet (a page, a measurement, a design). Do not repeat numbered questions (another sweep collects those).` },
]

phase('Sweep')
const sweeps = (await parallel(SWEEPS.map(s => () => agent(`${WHO}
SWEEP "${s.key}" (one of three; you do not see the others).
${s.task}
${SOURCES}
${RULES}
REPORT_FILE: ${s.file}
RETURN: report_path, status, count (items listed), summary <= 500 characters.`, { agentType: 'general-purpose', model: 'sonnet', effort: 'high', schema: SS, phase: 'Sweep', label: 'sweep:' + s.key }).then(r => r ? Object.assign({ key: s.key }, r) : null)))).filter(Boolean)
log('sweeps returned: ' + sweeps.length + ' of ' + SWEEPS.length + ' -- ' + sweeps.map(s => s.key + '=' + s.status + '/' + s.count).join(' '))
if (sweeps.length < SWEEPS.length) log('MISSING SWEEP: ' + SWEEPS.filter(s => !sweeps.some(x => x.key === s.key)).map(s => s.key).join(', '))

phase('Synthesise')
const JS = { type: 'object', properties: { items_path: { type: 'string' }, clarify_path: { type: 'string' }, status: { type: 'string', enum: ['DONE', 'PARTIAL'] }, questions: { type: 'number' }, first_new_question: { type: 'number' }, last_question: { type: 'number' }, readings: { type: 'number' }, last_reading: { type: 'string' }, dropped: { type: 'array', items: { type: 'string' } }, summary: { type: 'string' } }, required: ['items_path', 'clarify_path', 'status', 'questions', 'last_question', 'readings', 'last_reading', 'summary'] }
const syn = await agent(`${WHO}
YOU WRITE THE CONTENT OF HIS PAGE (architect; a page writer lays it out after you; a checker compares it with your file).
INPUT: three sweep sheets -- ${SWEEPS.map(s => s.file).join(', ')} (${sweeps.length} of 3 exist: ${sweeps.map(s => s.key).join(', ')}). Read all of them in full, then verify against the sources every item you keep.
${SOURCES}
WHAT TO PRODUCE, in the file REPORT_FILE as ONE JSON object (valid JSON, UTF-8, written with a bash heredoc with a quoted delimiter):
{ "stamp_note": "...", "questions": [ { "n": 150, "area": "Presets" | "Tempo row" | "Actions" | "Review screen" | "Recording" | "Other", "text": "...", "options": [ { "letter": "A", "text": "...", "default": true }, { "letter": "B", "text": "..." } ], "why": "one plain line: what it changes for him", "verbatim": true | false, "source": "file:line" } ], "readings": [ { "r": "R109", "text": "...", "source": "file:line", "from": "nudge-row2 R103" } ], "void_readings": [ ... ], "told": [ { "text": "...", "source": "..." } ], "checks": [ { "do": "...", "expect": "...", "wrong": "..." } ], "requests": [ { "id": "RQ-0", "text": "..." } ], "not_on_the_page": [ { "what": "...", "why": "..." } ] }
RULES FOR THE CONTENT.
- QUESTIONS 150 and 151 are copied CHARACTER FOR CHARACTER from ${RB}/ruling-looks-answers2.md section 7 ("verbatim": true). Question 73, if still open, keeps its number and its text as shown to him. NEW questions are numbered from 154 upward, in page order; a number that already exists in any boris-clarify file is never reused and a question already shown is never re-worded.
- "Concrete" is his word: every question names ONE situation he can picture ("You switch a global action on while two layers have actions running.") and offers A (the default, marked "default": true) and B (and C only when a real third way exists). A default must be what his own words lean to; when nothing leans, the simplest to build that he can undo later. No question may need a programmer to answer: no code names, no file names, no stage ids, no "tuple", "atomic", "serializer". Test each one: would a VJ who has never seen the code know his answer from how he performs? If not, it is Harmony's to decide: put it in "not_on_the_page" with one line why.
- KEEP IT ANSWERABLE IN ONE SITTING: at most 22 questions. Order: what unblocks a build first (Presets 150-151, anything on the tempo row or Quantize), then Actions, then the Review screen, then the rest. Merge near-duplicates. For the actions and review-screen questions prefer the points whose wrong guess would cost a re-design.
- READINGS: the twelve of ruling-nudge-row2.md become R109..R120 in their order, text verbatim, WITHOUT the one his answer "145 b" made void (the ruling's R112): list that one under "void_readings" and do not renumber the others (R118 is then simply not used). Also drop or correct any reading that his answers "144 a", "146 b", "147 a" changed (say so in "void_readings"). The readings of ruling-looks-answers2.md follow from R121, verbatim. A new reading of your own (a consequence of his words that he should see) continues the numbers and is marked "from": "new".
- TOLD and CHECKS: only what is TRUE of the app he will open next -- the show-file protection is merged; nothing else of today is in the app. Plain words. Include what is NOT protected yet (rulings-one-save.md H-S8) and the measured fact that before today a Save onto a full disk emptied the show file.
- REQUESTS: the three tracks (he will bring them in another session; nothing waits but the first clip-transport measurement).
ALSO WRITE the filing record ${RB}/boris-clarify-150-plus.md (a second file you may write): a header line "# Questions put to Boris on the page boris-open.html at the close of session s-rta-1004b (2026-10-04)", then every question exactly as in the JSON (number, text, options with the default marked), then the readings with their numbers, then "## ANSWERS" and "(none yet)".
${RULES}
TURN BUDGET (the architect role stops SILENTLY at 120 turns): a skeleton JSON by your turn 10; done by turn 70. Validate the JSON before you return: python3 -c "import json,sys; d=json.load(open(sys.argv[1])); print(len(d['questions']), len(d['readings']))" <file>.
REPORT_FILE: ${RB}/boris-open-items.json
RETURN: items_path, clarify_path, status, questions (count), first_new_question, last_question, readings (count), last_reading, dropped (<= 8 lines: what you left off the page and why), summary <= 700 characters.`, { agentType: 'architect', model: 'opus', effort: 'high', schema: JS, phase: 'Synthesise', label: 'synthesise:open' })
if (!syn) return { failed: 'synthesis', sweeps: sweeps.map(s => ({ key: s.key, status: s.status, count: s.count })) }
log('synthesis: ' + syn.status + ' -- ' + syn.questions + ' questions (to ' + syn.last_question + '), ' + syn.readings + ' readings (to ' + syn.last_reading + ')')

phase('Page')
const PS = { type: 'object', properties: { page_path: { type: 'string' }, status: { type: 'string', enum: ['DONE', 'PARTIAL'] }, bytes: { type: 'number' }, summary: { type: 'string' } }, required: ['page_path', 'status', 'summary'] }
const page = await agent(`${WHO}
YOU LAY OUT HIS PAGE. Content: ${RB}/boris-open-items.json (read it whole; it is the ONLY source of text -- you add no question, no reading, no claim, and you change no word of a "text" field). Template: the page of the previous close, ${R4}/boris-open.html -- same look, same structure, same way of showing a question and its default ("as usual" is his word). Write ONE self-contained HTML file (inline CSS, no script that loads anything, no external font, image or link), readable on a laptop screen, light and dark by prefers-color-scheme if the template does so.
ORDER ON THE PAGE: a title with the date 2026-10-04 and "close of session s-rta-1004b"; one short paragraph "How to answer: in chat, the number and the letter, like 150 a. Every question has a default: if you say nothing, A is built."; 1 QUESTIONS, grouped by "area" in the JSON's order, each with its number, its text, its options (the default visibly marked), and its "why" line in smaller type; 2 HOW I READ YOU (the readings, numbered as in the JSON; one line on top: "Correct only what is wrong."); 3 WHAT IS IN YOUR APP NOW ("told"); 4 WHAT ONLY YOU CAN CHECK NOW ("checks": do -> expect -> what wrong looks like); 5 REQUESTS. Nothing from "not_on_the_page" or "void_readings" is shown. Escape HTML in every text (&, <, >, quotes) and keep his quoted words inside the texts exactly as they are.
${RULES}
REPORT_FILE: ${RB}/boris-open.html
RETURN: page_path, status, bytes, summary <= 300 characters.`, { agentType: 'general-purpose', model: 'sonnet', effort: 'high', schema: PS, phase: 'Page', label: 'page:open' })
if (!page) return { failed: 'page', synthesis: { status: syn.status, questions: syn.questions, items_path: syn.items_path } }

phase('Check')
const CS = { type: 'object', properties: { verdict: { type: 'string', enum: ['SOUND', 'FIXED', 'UNRELIABLE'] }, questions_on_page: { type: 'number' }, readings_on_page: { type: 'number' }, mismatches_found: { type: 'number' }, fixed: { type: 'array', items: { type: 'string' } }, problems_left: { type: 'array', items: { type: 'string' } }, summary: { type: 'string' } }, required: ['verdict', 'questions_on_page', 'readings_on_page', 'mismatches_found', 'problems_left', 'summary'] }
const chk = await agent(`${WHO}
ADVERSARIAL CHECK of his page before he sees it. Page: ${RB}/boris-open.html. Its content file: ${RB}/boris-open-items.json. The filing record: ${RB}/boris-clarify-150-plus.md. Find what is WRONG; default to "wrong" when you cannot confirm.
(1) BY MACHINE (write a small python script in your scratch space and run it): strip the tags from the page and unescape it; every question "text", every option "text" and every reading "text" of the JSON must appear in it character for character (whitespace runs collapsed on both sides); count the questions and readings shown; the numbers are unique. The same texts must appear in boris-clarify-150-plus.md.
(2) Questions 150 and 151: compare with ${RB}/ruling-looks-answers2.md section 7 character for character.
(3) NUMBERS: no question number on the page exists in any earlier boris-clarify file as a DIFFERENT question (grep ${R4}/boris-clarify-*.md and ${RB}/boris-clarify-1*.md); readings start at R109 and none repeats R1..R108.
(4) HIS WORDS: every quoted phrase attributed to Boris on the page exists verbatim in ${BIND} or ${BACKLOG} (grep each).
(5) ALREADY ANSWERED: for each question, search his answers (the ANSWERS blocks, binding-decisions.md's s-rta-1004b sections) for something that already settles it; a settled question on the page is a defect.
(6) PLAIN WORDS: flag any question a non-programmer could not answer, any code or file name, any stage id.
(7) TRUTH OF "IN YOUR APP NOW": each line against ${RB}/rulings-one-save.md's gate verdict block; a claim about something not merged is a defect.
You MAY FIX the page yourself for a mechanical defect of (1), (2) or (4) (a dropped character, a wrong escape) -- say exactly what you changed; anything else you report and do not edit. You may NOT edit the JSON or the filing record.
${RULES}
REPORT_FILE: ${RB}/boris-open-check.md (your findings; the page is the only other file you may touch, and only for the fixes named above)
RETURN: verdict (SOUND = nothing wrong; FIXED = only mechanical defects, all fixed by you; UNRELIABLE = a defect is left), questions_on_page, readings_on_page, mismatches_found, fixed, problems_left (<= 8, each <= 240 characters), summary <= 400 characters.`, { agentType: 'general-purpose', model: 'sonnet', effort: 'high', schema: CS, phase: 'Check', label: 'check:open' })
return { sweeps: sweeps.map(s => ({ key: s.key, status: s.status, count: s.count, summary: cut(s.summary, 260) })), synthesis: { status: syn.status, questions: syn.questions, first_new: syn.first_new_question, last_question: syn.last_question, readings: syn.readings, last_reading: syn.last_reading, dropped: (syn.dropped || []).slice(0, 8).map(x => cut(x, 220)), summary: cut(syn.summary, 700), items_path: syn.items_path, clarify_path: syn.clarify_path }, page: { path: page.page_path, status: page.status, bytes: page.bytes }, check: chk ? { verdict: chk.verdict, questions_on_page: chk.questions_on_page, readings_on_page: chk.readings_on_page, mismatches_found: chk.mismatches_found, fixed: (chk.fixed || []).slice(0, 6).map(x => cut(x, 200)), problems_left: (chk.problems_left || []).slice(0, 8).map(x => cut(x, 240)), summary: cut(chk.summary, 400) } : { verdict: 'NO_RESULT' } }
