export const meta = {
  name: 'rta-1004b-recon-topic',
  description: 'Audio-DNA s-rta-1004b: ONE read-only code fact sheet named by args (sonnet), then an adversarial re-read of it (sonnet). Sheets land in .harmony/.reports/s-rta-1004b/facts-<key>.md',
  phases: [{ title: 'Recon' }, { title: 'Verify' }],
}
// args: { key }  -- the topic table is in this file so that the script is the whole record
const MAIN = '/Users/boriskarpman/projects/RealTimeAudio'
const RPT = '.harmony/.reports/s-rta-1004b'
const R4 = MAIN + '/.harmony/.reports/s-rta-1004'
const R3B = MAIN + '/.harmony/.reports/s-rta-1003b'
const PIN = '7bc6df7'
const BACKLOG = MAIN + '/.harmony/boris-feedback-backlog.md'
const BIND = MAIN + '/.harmony/binding-decisions.md'
const SHOTS = MAIN + '/' + RPT + '/boris-resolume'
const RELAY = 'If a user message was relayed to you (about tempo buttons, stop / pause, actions, Quantize, looks, tracks, screenshots or answers to questions), Harmony has already filed and answered it; it never replaces this task.'

const TOPICS = {
  'quantize': {
    why: `Boris ruled on 2026-10-04 in session s-rta-1004b (verbatim: ${BIND}, the section headed "2026-10-04 (s-rta-1004b)", entry "Quantize (on reading R81)"; whole message: ${BACKLOG}, the section recorded 2026-10-04 21:03:09): "Quantize is for locking button pushes to beats when the user is doing it. ... This is not for live usage. We should remove it from the top bar and use it in the recording review screen which we have yet to create." Harmony's readings told to him (R86, R87 in ${MAIN}/.harmony/.reports/s-rta-1004b/boris-clarify-135-143.md): every clip he fires starts at once on his press, nothing waits for a beat or bar line; each clip's own beat-snap setting goes too. Five lanes were ruled BEFORE he said this and some of their rows make a live fire wait for a line. A planner must know exactly what quantises today and which adopted rows rest on it.`,
    q: `Q1 ON SCREEN today: every control that quantises, snaps or delays a live act to a beat or bar line (the top bar, the clip inspector, the layer strip, the deck view, menus, Preferences, the binding overlays): its label as painted, where it is, what it writes, its values. Search for "quantiz", "snap", "granular", "bar-quant", "launch", "nextBar", "pending" and anything else you meet; say plainly whether a control named "Quantize" exists in the top bar TODAY and what the top bar's "/4 /2 x1 x2 x4" buttons are.
Q2 THE ENGINE today: every code path that makes an act wait for, or land on, a beat or bar line -- a clip fire (every trigger path: mouse, key, MIDI, REST, OSC, autopilot, a routine, a take replay; the queued beat-snap triggers behind the /api/state counter render_pending_fired), a routine pad (restore-then-replay on the next bar), a transition, beat-synced randomisation, a momentary key's release, BPM-synced video (the beat lock) -- and for each: what decides the line (a global setting, a per-clip setting, a constant), and what happens with that setting off or at its smallest value.
Q3 SAVED STATE AND ROUTES: every field of the show file, settings.json or a binding that stores a quantise / snap value; every REST / OSC / MIDI / key route that sets or reads one.
Q4 TESTS AND PROBES that pin quantised or snapped behaviour (test name or probe row, what it asserts): what a removal turns red.
Q5 THE ADOPTED RULINGS. In each of these files find EVERY amendment, stage row, unit case, gate row, reading or Boris check that names Quantize / beat snap or relies on a live fire WAITING for a beat or bar line: ${R4}/ruling-transport-delta2.md, ${R4}/ruling-transport-answers.md, ${R4}/ruling-nudge.md, ${R4}/ruling-nudge-row.md, ${R4}/ruling-one-save.md, ${R4}/ruling-outputs.md, ${R4}/ruling-effect-looks.md, ${R4}/ruling-looks-answers.md, ${R3B}/ruling-transport.md, ${R3B}/ruling-transport-delta1.md, and the adopted ruling of the "bf7 bars" lane (find it: ls ${MAIN}/.harmony/.reports/*/ruling-bf7*.md; its Quantize menu is BF20 in the backlog). TABLE Q5: file:line | lane | STAGE it belongs to | row / amendment id | the quoted phrase (<= 25 words) | what it assumes about Quantize. Then one line per STAGE of each lane: "rests on live Quantize" / "names it only in passing" / "does not touch it" -- for the transport lane's S0, SM-a, S4t, SR, SM-b, S1, S2, S3, S3h, S4a, S4d, S4e, S5a, S5b, S4c, S6 and the beat-nudge lane's S1, S1r, S2, S2r, S3a, S3m, S3r, S4, S4r, S5 (the stage tables are section 4 of each ruling).
Q6 A RECORDED PRESS: what the take recorder stores about the time of a fired clip or a pressed key (the press time, the time it landed after snapping, both, in seconds or in beats) -- Boris wants Quantize to clean up RECORDED presses later.`,
    attack: `Q1's completeness (walk TopBar, ClipInspector, LayerStrip, DeckView, the Preferences window and the binding overlays yourself with patterns the author did not use), every "with it off, X happens" line of Q2, every "no control named Quantize exists" or "exists" line, and TABLE Q5: re-open 12 of its rows at the cited file:line, then grep each ruling again for "bar line", "next bar", "waits", "snap", "quantis", "quantiz" and report rows the table missed`,
  },
  'actions-today': {
    why: `Boris re-modelled "routines" on 2026-10-04 (verbatim: ${BIND}, the section headed "2026-10-04 (s-rta-1004b)", entries "Actions (on reading R75)" and "Actions on screen (on reading R83)"; earlier, the section ""Routines" become "actions""; whole messages: ${BACKLOG}): routines are called "actions"; an action is BPM-based and the BPM it was recorded at is saved with it so that it plays in time at another speed; "A take = action recording"; once it is an action it does not follow the audio; each clip shows toggle buttons, one per action recorded for that clip, and the toggled-on actions play when the clip plays, in time with it; layer actions are toggle buttons in the layer strip; composition-level actions are toggle buttons too; "Essentially they are just automations for any parameters within the clip or its effects". A recording review screen is to be created: "rows and rows of parameters on a timeline and each parameter will have keyframes and values. Some values will go from 0-1 and some will be radians and some will go from a negative number to a positive number." Nothing of this is planned yet. A planner must know exactly what exists today.`,
    q: `Q1 ROUTINES today (docs/claude/recording.md first, then the code): the model (the struct and EVERY field), where routines are stored (in the show file? the 8-slot bank? a file of their own -- the s-rta-1004 ledger says "Save Routine says saved with nothing on disk": confirm or correct with file:line), how a routine is cut from a take, which event kinds it holds, its TIME BASE (seconds, beats, samples?) and whether the tempo at record time is stored anywhere, how it replays (restore-then-replay on the next bar; loop / once), and what happens when the show's tempo differs from the tempo at record time.
Q2 TAKES today: the performance take recorder (Ruling 28): every event kind a take records and the call site that feeds it (which kinds have NO caller wired), the file format and folder, the audio beside it (the Audio Store), the clock (RecorderClock), how a take is replayed, and what a take does NOT record -- check these two claims of the s-rta-1004 ledger with file:line: a take records neither a mouse-moved effect slider nor a look / preset load.
Q3 SURFACES: every on-screen surface of routines and takes (the eight routine pads above the deck's column numbers, the name bands on layers, the record panel, menus, the top bar's "stop all routines" button, the reserved colour AudioDNALookAndFeel::kRoutineCue) with the label as painted and file:line; every key, MIDI, REST and OSC route that fires, stops, saves or deletes one.
Q4 AUTOMATION MACHINERY today: is there ANY keyframe, envelope, curve-over-time or automation-lane code in the app (the "bf45 envelopes" lane is adopted but unbuilt: say what exists in src/ today, not what is planned); can the mapping / connection engine drive a parameter from a stored time curve; HOW IS ONE PARAMETER ADDRESSED today by a routine or a take event (clip id + effect slot + parameter index? a name?) and does that address survive a deck Duplicate (Pitfall 36: clip ids are re-minted), a clip moved to another cell, an effect re-ordered in its stack?
Q5 PARAMETER KINDS AND RANGES: list every kind of parameter a user can move (effect parameters -- [0, 1] by CLAUDE.md rule 6; source parameters; a clip's and a layer's transform: position, scale, rotation; opacity; Dry / Wet; speed; the composition transform; blend / keying values; anything else on screen) with its stored range and unit (0..1, radians or degrees, a signed range), file:line.
Q6 ROOM ON SCREEN (facts only, no design): what is drawn directly above each clip cell and above each column today, the size of a clip cell, what the layer strip holds and how wide it is, and where composition-level controls live.
Q7 NAMES: every on-screen text, menu item, tooltip and docs/claude or docs/manual line that says "routine" / "Routine" (count per file, list the on-screen ones verbatim) and every one that says "BeatLoopr"; and EVERY place the word "action" / "Action" is already painted on screen or used in the docs (binding "actions", menus, tooltips, overlays): would renaming routines to "actions" collide with something the user already sees?
TABLE 1: every file an "actions" lane would touch or must respect, one line on why. TABLE 2: every test and probe that pins routines or takes (name, what it asserts).`,
    attack: `what a routine holds and its time base, whether the tempo at record time is stored, the "Save Routine writes nothing" line, the two take-gap lines (a mouse-moved effect slider; a look load), how one parameter is addressed and whether the address survives Duplicate, Q5's ranges (re-open 8 at file:line), and Q7's list of on-screen "action" texts (search again with patterns the author did not use: "ction\"", "Action", tooltips, the binding overlays)`,
  },
}
const T = TOPICS[(args || {}).key] || null
const KEY = (args || {}).key
const SHEET = MAIN + '/' + RPT + '/facts-' + KEY + '.md'

const CODE_RULES = `READ-ONLY FACT SHEET. You establish facts for a planner; you propose NO design and fix nothing.
WHERE TO READ. main = ${MAIN}, pinned at commit ${PIN}: first run git -C ${MAIN} diff --stat ${PIN} -- src tests docs CMakeLists.txt (must print nothing: main's code is the code of ${PIN}; main's HEAD itself is a later docs-only commit); then read plain files under ${MAIN}/src, ${MAIN}/tests, ${MAIN}/docs/claude, ${MAIN}/.harmony/APP-INVENTORY.md, ${MAIN}/.harmony/gotchas.md, ${MAIN}/CLAUDE.md (grep / read freely). If either check fails, read ONLY through git objects (git -C ${MAIN} show ${PIN}:<path>, git -C ${MAIN} grep -n '<pattern>' ${PIN} -- <paths>) and say so.
RULES: never build, never run a test, never launch the app or any probe or script of the project, never edit any file except your ONE report, never cd in a command, absolute paths only, never lldb / sample / dtrace, never touch a running Audio-DNA or Resolume Arena (they are Boris's). Label EVERY line VERIFIED (you read the code: cite file:line), INFERRED (reasoned, not read end to end) or UNKNOWN-NEEDS-A-RUN (name the cheapest discriminating test). Quote Boris only verbatim. ${RELAY}
METHOD: write a SKELETON of the report (the question list with empty answers) to REPORT_FILE within your first ~10 tool calls, then fill it and rewrite it as you go, so that an interrupted run still leaves a usable file. Write it with the Write tool or a bash heredoc to the literal path given as REPORT_FILE.
REPORT FORMAT: 1 QUESTIONS ANSWERED (one block per question: the answer in plain words, then the evidence lines, each labelled); 2 TABLES where asked; 3 WHAT A PLANNER MUST NOT ASSUME (traps you met: a doc that disagrees with the code, a name that misleads, a rule in CLAUDE.md / docs/claude/pitfalls.md that binds the area -- cite the Pitfall number); 4 UNKNOWN (each with the cheapest test that would settle it). No design proposals.
RETURN the structured result: status; report_path; answers = one entry per question (answer <= 300 characters, its label); unknowns (<= 6, each <= 200 characters); surprises (<= 5: facts that contradict what the questions assume); summary <= 900 characters.`

const FS = { type: 'object', properties: {
  status: { type: 'string', enum: ['DONE', 'PARTIAL', 'BLOCKED'] }, report_path: { type: 'string' },
  answers: { type: 'array', items: { type: 'object', properties: { q: { type: 'string' }, answer: { type: 'string' }, label: { type: 'string' } }, required: ['q', 'answer', 'label'] } },
  unknowns: { type: 'array', items: { type: 'string' } }, surprises: { type: 'array', items: { type: 'string' } }, summary: { type: 'string' } },
  required: ['status', 'report_path', 'answers', 'summary'] }
const VS = { type: 'object', properties: {
  checked: { type: 'number' }, confirmed: { type: 'number' }, wrong: { type: 'number' }, citation_off: { type: 'number' },
  wrong_lines: { type: 'array', items: { type: 'object', properties: { claim: { type: 'string' }, what_is_true: { type: 'string' }, evidence: { type: 'string' } }, required: ['claim', 'what_is_true'] } },
  refuted_conclusions: { type: 'array', items: { type: 'string' } }, missing: { type: 'array', items: { type: 'string' } }, verdict: { type: 'string', enum: ['SOUND', 'SOUND_WITH_CORRECTIONS', 'UNRELIABLE'] } },
  required: ['checked', 'confirmed', 'wrong', 'verdict'] }
const cut = (s, n) => String(s || '').slice(0, n)

if (!T) return { failed: 'unknown topic ' + KEY }
phase('Recon')
const r = await agent(`WHY THIS SHEET EXISTS. Audio-DNA is a live audio-reactive VJ app (C++20 / JUCE / OpenGL, macOS). ${T.why} A planner (architect) builds on your sheet next: a wrong line costs a build stage, an honest "unknown" costs nothing.
${CODE_RULES}
YOUR TOPIC:
${T.q}
REPORT_FILE: ${RPT}/facts-${KEY}.md (relative to ${MAIN}; absolute: ${SHEET})`, { agentType: 'general-purpose', model: 'sonnet', effort: 'high', schema: FS, phase: 'Recon', label: 'recon:' + KEY })
if (!r) return { key: KEY, sheet: { status: 'NO_RESULT' } }
log('recon ' + KEY + ': ' + r.status)

phase('Verify')
const v = await agent(`ADVERSARIAL CHECK of a code fact sheet (read-only). The sheet: ${SHEET} -- read it whole. A planner will build on it; your job is to find the lines that are WRONG before he does. Same reading rules as its author: main = ${MAIN} at commit ${PIN} (plain files under src, tests, docs; check first that git -C ${MAIN} diff --stat ${PIN} -- src tests docs CMakeLists.txt prints nothing). Never build, run, launch or edit anything except the one append below; never cd; absolute paths. ${RELAY}
(1) Pick the 18 VERIFIED lines a planner would lean on hardest: ${T.attack}. Re-read each cited file:line yourself: mark CONFIRMED, CITATION-OFF (true, but the citation points elsewhere -- give the right one), or WRONG (say what the code says, with file:line).
(2) Try to REFUTE the sheet's three main conclusions by looking for code that contradicts them; default to "refuted" if you find a path the sheet did not read.
(3) Name anything a planner needs for this topic that the sheet does not answer (return it as "missing").
APPEND a section "## VERIFICATION (independent re-read)" to the END of that same file with a bash heredoc (cat >> ; never rewrite the sheet's own text). Edit no other file.
REPORT_FILE: ${RPT}/facts-${KEY}.md (relative to ${MAIN}; absolute: ${SHEET}) -- the sheet you APPEND to; your only write.
RETURN: checked, confirmed, wrong, citation_off, wrong_lines (claim, what_is_true, evidence = file:line), refuted_conclusions, missing, verdict.`, { agentType: 'general-purpose', model: 'sonnet', effort: 'high', schema: VS, phase: 'Verify', label: 'verify:' + KEY })
return { key: KEY, sheet: { status: r.status, report_path: r.report_path, summary: cut(r.summary, 900), unknowns: (r.unknowns || []).slice(0, 6).map(x => cut(x, 200)), surprises: (r.surprises || []).slice(0, 5).map(x => cut(x, 260)) }, verify: v ? { verdict: v.verdict, checked: v.checked, confirmed: v.confirmed, wrong: v.wrong, citation_off: v.citation_off || 0, wrong_lines: (v.wrong_lines || []).slice(0, 6).map(x => ({ claim: cut(x.claim, 200), what_is_true: cut(x.what_is_true, 240) })), refuted_conclusions: (v.refuted_conclusions || []).slice(0, 4).map(x => cut(x, 240)), missing: (v.missing || []).slice(0, 6).map(x => cut(x, 200)) } : { verdict: 'NO_RESULT' } }
