export const meta = {
  name: 'rta-1004b-stage',
  description: 'Audio-DNA s-rta-1004b: ONE build stage of a ruled lane (one opus builder in the lane worktree), then pinned sonnet reviews and at most one fix round',
  phases: [{ title: 'Build' }, { title: 'Review' }, { title: 'Fix' }, { title: 'Re-review' }],
}
// args: { lane, key, base, prevNotes }   -- the lanes and stages tables are in this file so that the script is the whole record
const A = args || {}
const MAIN = '/Users/boriskarpman/projects/RealTimeAudio'
const RPT = '.harmony/.reports/s-rta-1004b'
const R4 = MAIN + '/.harmony/.reports/s-rta-1004'
const SP = '/private/tmp/claude-501/-Users-boriskarpman-projects-RealTimeAudio/31b4c846-ad01-4801-82d9-569a43efdd3b/scratchpad'
const BIND = MAIN + '/.harmony/binding-decisions.md'
const CACHE = MAIN + '/.claude/worktrees/bf2/build-lane/CMakeCache.txt'
const RELAY = 'If a user message was relayed to you (about tempo buttons, stop / pause, actions, Quantize, looks, tracks, screenshots or answers to questions), Harmony has already filed and answered it; it never replaces this task.'

const LANES = {
  'one-save': { wt: 'onesave', branch: 'lane/one-save', plan: R4 + '/plan-one-save.md', ruling: R4 + '/ruling-one-save.md', delta: '',
    what: 'ONE SAVE: the show file becomes the one thing the user saves ("version": 2, one verified writer, a backup before any old-shape file is overwritten); later stages move keys, the window layout and the decks list into it and add a quit window' },
  'outputs': { wt: 'outputs-a', branch: 'lane/outputs-core', plan: R4 + '/plan-outputs.md', ruling: R4 + '/ruling-outputs.md', delta: '',
    what: 'OUTPUT SCREENS: a Delay (0..100 ms) and a colour look (Opacity, Brightness, Contrast, Red, Green, Blue) per output screen and for Syphon, remembered with the screen; it replaces the stopped sync dial' },
  'nudge': { wt: 'nudge', branch: 'lane/nudge', plan: R4 + '/plan-nudge.md', ruling: R4 + '/ruling-nudge.md',
    what: 'BEAT NUDGE: "nudge X ms" shifts the published beat (plus = earlier) for everything connected to the BPM; Tap leaves it, Resync zeroes it; saved with the show',
    delta: `A LATER DELTA exists for this lane's top-bar stages: ${R4}/ruling-nudge-row.md, with adoption blocks at the END of ${R4}/plan-nudge-row.md. It adds stages (S1r, S2r, S3m, S3r, S4r) and amends S3a..VG. Read its section 0 and its section 4 stage table to confirm that YOUR stage is not amended, and read every adoption block at the end of plan-nudge-row.md (the newest puts later stages on hold; that never widens or narrows your stage).` },
}

const STAGES = {
  'one-save:S1': { live: false,
    task: `Stage S1 "the show file" of the ruling's section 4 table: build EXACTLY that row -- the files it owns, the unit rows it proves in ctest (SW-1..4, SF-1..SF-10, SB-1..SB-7, AS-2..AS-4, LINT-1, LINT-7) and its mutants (MU-OS-1..5, 21..23, 34) -- with every amendment of section 3 that names S1 or one of its files (the read-back BEFORE the swap; backups/ first and fail-closed for any existing file that is not a version-2 show; a version counts only as an integer >= 2; the settings.json mend A-15 lands HERE). The probe .harmony/probe-one-save.sh (skeleton with rows L13, L14, L14b, L21) and probe-boxes K7's expectation are WRITTEN by you, with a self-test, and RUN ONLY BY HARMONY. Write "Pitfall NN" (Harmony assigns the number at merge). N_main = 1252 (ctest -N on main's build, measured by Harmony 2026-10-04): your full ctest is 1252 + your new entries, the count stated in the report. Nothing of S7, S2, S3, S4a, S4b, S5 is built. Boris's real files are never touched by any test or script: his folders ~/Library/AudioDNA and ~/Library/Audio-DNA are read by nothing you run.`,
    lenses: [
      { key: 'data-safety', focus: 'every path that writes a show file or settings.json in this diff: is the new content verified by READ-BACK before the swap; is an existing file that is not a version-2 show copied to backups/ first, and does a failed copy STOP the save (fail-closed); can any path still overwrite an old-shape file without a backup (search every caller of every old writer at the head); the version rule (an integer >= 2 only); the settings.json mend (an unreadable file is never read as empty and written back); what a full disk, a failed rename or a crash between two steps leaves on disk. Pitfall 46 (FileOutputStream opens an existing file at its END) and Pitfall 58 (a staged load) wherever the diff touches them. No test or script reads or writes the real ~/Library/AudioDNA or ~/Library/Audio-DNA.' },
      { key: 'ruling-tests', focus: 'ruling conformance item by item for stage S1 (the section 3 amendments that name S1 or its files, the section 4 row, the section 5 unit rows and mutants): every unit row named for S1 exists under its pre-registered name / string, drives real code and CAN FAIL (its named mutant MU-OS-n is shown RED in the report with raw lines, then reverted, with >= 1 object recompiled after the revert); the LINT rows really scan the tree; no existing test was edited beyond what the ruling names (the three saveToFile call sites passing {}); the full ctest count in the report is 1252 + the new entries.' },
      { key: 'threads-api-fence', focus: 'threads and surface: which thread each new write runs on and whether it can block the render or the audio thread (CLAUDE.md sacred rules 1-4; no new mutex); the two routes (save_composition {"plain"}, GET /api/debug/show_file): the debug route exists ONLY in a build with the test server (check the guard); the stage touched ONLY the files the S1 row owns (list every other file of the diff as a finding); no on-screen text that announces an event or a failure was added; docs changed as the row says; the probe script quits only the pid it launched (it sources .harmony/probe-quit-ours.sh) and holds no kill-by-name line.' } ] },
  'outputs:S1': { live: false,
    task: `Stage S1 "HISTORY CORE (pure + pool)" of the ruling's section 4: EXACTLY its "Owns" list (NEW src/output/FrameHistory.h; NEW src/output/OutputLook.h, the word only; the SurfacePool part of src/output/SharedFrameSet.h; src/output/SurfacePool.cpp; NEW tests/test_frame_history.cpp, tests/test_output_look.cpp; tests/test_surface_pool.cpp; tests/CMakeLists.txt) and its "Proves" list (U-H1..U-H10, U-P1..U-P6, U-L1, U-L4, U-L5, U-L6), with every amendment of section 3 that names them. MEASURED BY HARMONY (G0, 2026-10-04 20:52, main's build, test mode, raw log ${MAIN}/${RPT}/gate-g0/g0-run1.log): M1 publish_hz = 93.52 / 96.41 / 98.96 on the only display (built-in, 120 Hz), measured while another GPU app ran (a lower bound; a vsync-bound render cannot pass 120) -> kSizingHz = 120 as ruled (HD-7); M2: Syphon is available on this rig. The Delay range is 0..100 ms (Boris, verbatim: "51 default is good"). THE APP'S BEHAVIOUR IS UNCHANGED after this stage (nobody asks for depth): the report says how you showed it. N_main = 1252 (ctest -N on main's build): your full ctest is 1252 + your new entries. Write "Pitfall NN" (Harmony assigns the number at merge). Nothing of S2..S7 is built.`,
    lenses: [
      { key: 'history-pool', focus: 'the pure history code and the pool: FrameLog / pick / extraSlots / reachMs / DepthPolicy at the edges (0 ms, 100 ms, one frame, an empty log, wrap of serials and of timestamps, a publish rate above kSizingHz, a clock that steps back); the SurfacePool change: which thread creates, binds and releases IOSurfaces and GL objects, no allocation or lock added on the render path, no GL call off the GL thread, the lifetime of a slot a reader still shows (Pitfalls 54 and 60: the shown slot is never evicted); Pitfall 37 (a size comes from the canvas, never from a Component).' },
      { key: 'ruling-tests', focus: 'ruling conformance item by item for stage S1 (the section 3 amendments that name its files, the section 4 "Owns" and "Proves" lists, the section 5 unit rows): every U-row named for S1 exists under its pre-registered name / string, drives real code and CAN FAIL (RED first with raw lines in the report -- the RED arm section 5 names for it -- then GREEN; after a mutant revert >= 1 object recompiled); the constants are the ruled ones (Delay 0..100 ms, kSizingHz 120); the full ctest count in the report is 1252 + the new entries.' },
      { key: 'fence-unchanged', focus: 'the stage touched ONLY its Owns list (list every other file of the diff as a finding); the app is unchanged: every existing caller passes what it passed before, the existing shared-frame and surface-pool cases are green and edited only where the ruling says, kSlots is still 4; nothing in src/ui, src/analysis, FeatureSnapshot, src/recording, src/model/AppSettings.cpp, TopBar (the fence with the beat-nudge lane, the last paragraph of section 4); no on-screen text added; nothing stray (no mutant, no instrumentation).' } ] },
  'nudge:S1': { live: false,
    task: `Stage S1 "THE ARITHMETIC" of the ruling's section 4 table. STEP 0 (amendment A9) FIRST, and committed FIRST and ALONE: tests/test_analysis_nudge_golden.cpp, recorded on a tree of commit 185147b -- make a scratch worktree with git -C ${MAIN} worktree add --detach ${MAIN}/.claude/worktrees/nudge-golden 185147b, configure a build dir inside it as the rig rules say, build ONLY what the golden needs, record; before you return remove it with git -C ${MAIN} worktree remove --force ${MAIN}/.claude/worktrees/nudge-golden and say so. That first commit holds ONLY the golden file and its two CMake lines (Harmony then runs her own row G-N0 on a pristine 185147b tree with exactly that commit's content): the report gives its hash and the two "[golden] ..." lines, three runs, and whether the raw 384-byte hash was stable. THEN: src/analysis/BeatShift.h/.cpp (new), src/model/BeatNudge.h (new), src/analysis/BPMTracker.h/.cpp (the two views and adoptCounters, A4), tests/test_beat_shift.cpp (new), CMakeLists.txt + tests/CMakeLists.txt (the new sources and targets only). EXIT: T-N1..T-N9, T-N11..T-N16 RED on a stub apply that writes nothing, then GREEN; the unit mutants M1-M11, M19-M23, M27, M28 each RED; the golden green on the lane. NOTHING IS WIRED: the app is unchanged after S1. THE SIGN -- Boris, verbatim: "61 b but lets call it "nudge X ms"" -> PLUS MOVES THE BEAT EARLIER (the ruling's section 7: "61 -> the constant of A8"): build B. THE RULING'S OWN CAVEAT binds you: its arithmetic "rests on a python paper model"; where a unit case on the REAL BPMTracker disagrees with the ruled rule, that is a STOP ITEM for Harmony with the raw lines -- never your re-design. N_main = 1252 (ctest -N on main's build, measured by Harmony 2026-10-04). You are the ONLY builder allowed in BPMTracker.h/.cpp on this machine now. From the stopped branches (worktrees ${MAIN}/.claude/worktrees/bf2 and bf2keys, READ-ONLY) parts are RE-TYPED, never merged or cherry-picked: the ruling names them.`,
    lenses: [
      { key: 'real-time', focus: 'the ruling\'s real-time lens (section 4, "Reviews"): no allocation, lock or system call in BeatShift::apply or in anything it calls, nor in the two BPMTracker views or adoptCounters; any CAS loop is lock-free and bounded; NOTHING IS WIRED -- grep every use of the new symbols at the head: outside tests there is none in src/ besides their own definitions (adoptCounters has no caller yet and will get exactly one in S2); BPMTracker\'s existing behaviour is bit-identical (the golden\'s two constants are untouched by every commit after the first, and the golden is green at the head per the report).' },
      { key: 'arithmetic-tests', focus: 'the amended rule as sections 3 and 5 of ruling-nudge.md state it (A1-A24 where they name S1): the shifted beat\'s count, phase, beat-in-bar and bar position are seated at the shifted beat\'s OWN edges in both regimes (Auto, where the tracker moves its count and its beat-in-bar on different hops; Manual); the sign is plus = earlier (A8 with Boris\'s 61 B); clamp and wrap at the ends of the range; a nudge of 0 is bit-identical. Every unit case T-N1..T-N9, T-N11..T-N16 exists under its pre-registered name, drives a REAL BPMTracker sequence where the ruling says so, and CAN FAIL: RED on the stub apply (raw lines in the report), and each unit mutant M1-M11, M19-M23, M27, M28 RED on the case named for it, reverted, >= 1 object recompiled after each revert.' },
      { key: 'golden-fence', focus: 'step 0: the FIRST commit of the stage (git log --first-parent --reverse) holds only tests/test_analysis_nudge_golden.cpp and its two CMake lines; its constants are what a 185147b tree prints (the report\'s raw lines, three runs; the raw 384-byte hash only if it was stable, A9); the scratch worktree is gone (git worktree list). Fence: the stage touched ONLY the files of the S1 row -- no AnalysisThread, FeatureSnapshot, MainComponent, ApiServer, TopBar, binding or recording file; the parts carried from the stopped branches are re-typed with their origin named (the [golden] case of lane/bf2\'s tests/test_analysis_sync_thread.cpp, the accessor appliedResyncs()) and nothing else of lane/bf2 or lane/bf2-keys came along; no on-screen text added.' } ] },
}

const LANE = A.lane
const KEY = A.key
const L = LANES[LANE] || null
const S = STAGES[LANE + ':' + KEY] || null
if (!L || !S || !A.base) return { failed: 'unknown lane / stage or no base: ' + LANE + ':' + KEY + ' base ' + A.base }
const W = MAIN + '/.claude/worktrees/' + L.wt
const BR = L.branch
const BASE = A.base
const RNAME = LANE + '-' + KEY + '.md'
const REPORT = W + '/' + RPT + '/' + RNAME
const TAG = LANE + '-' + KEY

function RULES(tag) {
  const live = S.live
    ? `- LIVE APP: at most ONE Audio-DNA on the machine. Use the helper: LANE=${tag} . ${SP}/lib/lock.sh (acquire_lock / release_lock / start_app APP OUTDIR [test] / quit_app / outwins / wait_quiet / adna / acquire_quiet_lock). A failed mkdir means WAIT (never open another copy: the same bundle id reaches the running app); never remove another owner's lock; hold the lock per run or small batch (<= ~15 min). Launch ONLY: open -g [--env V=v] [--stdout f --stderr f] <App> [--args --test-mode]. After any live batch: count UserNotificationCenter windows (Quartz kCGWindowListOptionAll) >= 15 s after the last quit == 0. A production-mode run leaves ~/Library/Audio-DNA/settings.json byte-identical (sha256 before and after, printed). NO synthetic input (UI states via REST / composition files / the lane's test-only routes). Window-only captures by Quartz window id.`
    : `- NO APP LAUNCH IN THIS STAGE: you never open Audio-DNA by any path (no open, no probe run, no live row). Every live row, every mutant arm on a live row and every gate verdict is HARMONY'S. A probe or gate script you write is delivered with a self-test that runs WITHOUT the app (stub server or recorded responses) and with the exact command line Harmony runs.`
  return `
RIG RULES (binding; breaking any one = lane FAIL):
- Your worktree WT=${W} (branch ${BR}). Work ONLY inside it, with absolute paths (git -C ${W} ...). Build dir: ${W}/build-lane, configured by you: -DCMAKE_BUILD_TYPE=Release -DAUDIODNA_BUILD_TEST_SERVER=ON -DAUDIODNA_BUILD_SYPHON=ON -DFETCHCONTENT_FULLY_DISCONNECTED=ON plus -DFETCHCONTENT_SOURCE_DIR_<DEP>=${MAIN}/build/_deps/<dep>-src for each FetchContent dep (JUCE, HTTPLIB, CATCH2, MELATONIN_INSPECTOR, SYPHON; read-only use); the patched libprojectM at ~/.local/opt/projectm-4.1.1-fbo1 is found by the project's CMake (never rebuild or touch it); read ${CACHE} (an earlier lane's cache, read-only) for the exact settings rather than guessing. df -h /System/Volumes/Data before any new build dir (stop and report if < 30 GB free). Build with -j 6 (three lanes compile at once on 10 cores). No build may outlive the stage that started it. NEVER edit the main checkout ${MAIN} or its build/, and never another worktree. NEVER cd in a command; multi-step sequences go in script files under ${SP}/${tag}/ run with bash <file>; NEVER type rm in a command line (it prompts and stalls an unattended run): a removal lives inside such a script file. Capture a return code on its own line (rc=$? right after the command, and never after a pipe) -- a line like "$(date) ... rc=$?" prints 0 always. zsh does not split a command held in a variable. Stamp times from date, never estimate.
- OTHER LANES ARE ACTIVE on this machine in OTHER worktrees (one-save, outputs, beat nudge; Harmony runs live rows on main's app). You share with them only the ctest mutex and the live-app lock. Every FULL ctest goes through the mutex helper: bash ${SP}/lib/ctest-mutex.sh ${W}/build-lane [ctest args] (it waits for /tmp/audiodna-ctest.lock, runs ctest --test-dir, releases, prints "ctest rc=<n>"; exit 99 = the mutex was held for 60 min: STOP and report, never remove another owner's lock). A filtered ctest (-R) of your own new targets needs no mutex. Each git commit fires a background graph rebuild that burns CPU: commit per item as below, never in a loop.
- BORIS USES THIS MACHINE AND THIS APP: an Audio-DNA that YOUR lane did not start is BORIS'S -- never quit, kill, osascript-quit or touch it; never touch Resolume Arena. His folders ~/Library/AudioDNA and ~/Library/Audio-DNA are never read or written by anything you run. NEVER copy a lock.sh or gate script out of an archived .harmony/.reports/s-rta-0927..0930 directory. A probe quits only the pid it launched (.harmony/probe-quit-ours.sh; selftest .harmony/probe-quit-ours-selftest.sh).
${live}
- SCREEN-SAFETY LAW: NEVER open the Output window by ANY path. NEVER run tests/visual/test_output_window_level.py or .harmony/probe-outputs.sh; NEVER run pytest on tests/visual/ as a directory. NEVER lldb / debugserver / gdb / dtrace / Instruments / sample on ANY binary. NEVER full-screen screencapture. Unexpected system dialog or TCC permission prompt: STOP and report, never dismiss. NEVER copy an app bundle and re-sign it. ${RELAY}
- MUTANTS: a unit-test mutant lives in your build dir only between its edit and its revert; after the revert, touch the reverted file, rebuild, and show >= 1 object compiled and the test green again (a restore rebuild in the same mtime second compiles NOTHING). A mutant APP for one of Harmony's live RED arms is built in its OWN dir ${W}/build-mut-<name> (ignored by .gitignore) only where the ruling orders it for your stage, the source reverted the moment that build ends (git -C ${W} diff --quiet -- src tests; then rc on its own line), and the lane app is never built from mutant source; keep the mutant app dir and name it in the hand-over. SANITIZERS: runtime options ALWAYS include abort_on_error=0 (TSan app runs also exitcode=0).
- RED FIRST for every new test / probe row (raw lines in the report), then GREEN; a test drives real code; existing tests and probes are re-run, NEVER re-thresholded (the only expectation changes are the ones a named amendment makes). A flake verdict needs >= 5 runs per arm. Probe HTTP clients use Connection: close.
- DOCS: lane detail goes to docs/claude/*.md as the ruling's stage row says; CLAUDE.md is capped at 25,000 bytes and is touched only where the stage row names it. No on-screen text that announces an event or a failure is added by any stage (Boris, binding).
- Report file ${REPORT} (in YOUR worktree), COMMITTED. The stash-guard hook treats a path that starts with a dot as a whole-tree add and scans the whole command line: stage report files as git -C ${W}/.harmony/.reports add -f s-rta-1004b/<file>, keep a git add / commit in its OWN Bash call, commit with explicit paths (git -C ${W} commit -m "<msg>" -- <path> <path>), never git commit -a / git add -A, never chain a check to the commit it gates with &&. Create the report within your first ~10 tool calls and append after EVERY item, so a successor can resume. One commit per item (message: <type>(s-rta-1004b ${LANE} ${KEY}): ...). Do NOT merge into main or into another lane branch, do NOT push. The report ENDS with a "HAND-OVER TO HARMONY" block: the head commit, which build dir holds which app, the full ctest line with its count, and for EVERY gate row of your stage the exact command line Harmony runs, the exact PASS line it prints, and what its RED arm is. Before returning: git -C ${W} status clean (except ignored build dirs), no app running that you started, no stray worktree.`
}

const BS = { type: 'object', properties: {
  stage: { type: 'string' }, status: { type: 'string', enum: ['DONE', 'PARTIAL', 'BLOCKED'] },
  head_commit: { type: 'string' }, commits: { type: 'array', items: { type: 'string' } },
  items: { type: 'array', items: { type: 'object', properties: { id: { type: 'string' }, verdict: { type: 'string' }, evidence: { type: 'string' } }, required: ['id', 'verdict', 'evidence'] } },
  ctest: { type: 'string' },
  found_not_fixed: { type: 'array', items: { type: 'string' } }, stop_items_for_harmony: { type: 'array', items: { type: 'string' } },
  facts_measured: { type: 'array', items: { type: 'string' } }, harmony_commands: { type: 'array', items: { type: 'string' } },
  next_stage_notes: { type: 'string' }, report_path: { type: 'string' }, summary: { type: 'string' },
  app_launched: { type: 'boolean' }, output_window_opened: { type: 'boolean' },
  errors_or_deviations: { type: 'string' } },
  required: ['stage', 'status', 'head_commit', 'items', 'report_path', 'summary', 'app_launched', 'output_window_opened'] }
const RS = { type: 'object', properties: { verdict: { type: 'string', enum: ['PASS', 'PASS_WITH_NITS', 'FAIL'] }, reviewed_commit: { type: 'string' }, report_path: { type: 'string' }, findings: { type: 'array', items: { type: 'object', properties: { severity: { type: 'string', enum: ['MUST', 'SHOULD', 'NIT'] }, issue: { type: 'string' }, fix: { type: 'string' } }, required: ['severity', 'issue'] } } }, required: ['verdict', 'reviewed_commit', 'findings'] }

const SPEC = `THE SPEC. Lane "${LANE}" of Audio-DNA (a live audio-reactive VJ app: C++20 / JUCE / OpenGL, macOS) = ${L.what}. It was planned by an architect, attacked by blind seats, ruled, and adopted by Harmony. Nothing of it is built yet unless NOTES FROM EARLIER STAGES say so.
PRECEDENCE: Boris's verbatim words (${BIND}: the sections headed "2026-10-04 (s-rta-1004)" and "2026-10-04 (s-rta-1004b)"; his words are in quotes, the text after "->" is Harmony's) > the HARMONY ADOPTION blocks at the END of ${L.plan} (grep -n "HARMONY ADOPTION" and read from the first hit to the end of the file FIRST: they are short and they bind) > ${L.ruling} > the plan's body (read it only where the ruling points into it: "PL:nnn" is a line of the plan).
READ THE RULING ${L.ruling} IN FULL for your stage: section 0 (verdict), 1 (facts re-derived), 3 (EVERY amendment: each overrides the plan body), 4 (the stage table: your row, and what Harmony runs and when), 5 (your stage's tests and gate rows: copy a name or a string ONLY from there), 9 (side findings), 10 (risks). ${L.delta}
If a structural assumption of the ruling is broken by the code you find, or a reader / caller exists that the plan and the ruling did not name, STOP that item and report it in stop_items_for_harmony with evidence (file:line, raw lines) -- do not improvise a redesign. A STOP clause of the ruling is binding. Quote Boris only verbatim.`

const slimB = r => Object.assign({}, r, { summary: String(r.summary || '').slice(0, 1400), next_stage_notes: String(r.next_stage_notes || '').slice(0, 1500), errors_or_deviations: String(r.errors_or_deviations || '').slice(0, 1200), items: (r.items || []).map(x => ({ id: x.id, verdict: String(x.verdict || '').slice(0, 140), evidence: String(x.evidence || '').slice(0, 260) })), found_not_fixed: (r.found_not_fixed || []).map(x => String(x).slice(0, 300)), stop_items_for_harmony: (r.stop_items_for_harmony || []).map(x => String(x).slice(0, 600)), facts_measured: (r.facts_measured || []).map(x => String(x).slice(0, 320)), harmony_commands: (r.harmony_commands || []).map(x => String(x).slice(0, 420)) })
const slimR = rs => rs.map(x => ({ lens: x.lens, verdict: x.verdict, reviewed_commit: x.reviewed_commit, findings: (x.findings || []).map(f => ({ severity: f.severity, issue: String(f.issue || '').slice(0, 500), fix: String(f.fix || '').slice(0, 250) })) }))

const LENSES = S.lenses || []
const review = (lens, base, head, n, extra) => agent(`INDEPENDENT SOURCE REVIEW (read-only), Audio-DNA lane "${LANE}", stage ${KEY}, lens ${lens.key}, round ${n}. PINNED: worktree ${W}, branch ${BR}, base ${base}, head ${head}. Read the change ONLY through git objects: git -C ${W} diff ${base}..${head} -- <paths>, git -C ${W} log --first-parent --oneline ${base}..${head}, git -C ${W} show ${head}:<path>, git -C ${W} grep -n '<pattern>' ${head} -- <paths> (NEVER the working tree -- a builder may be editing it -- and never main's checkout for lane code).
SPEC: the HARMONY ADOPTION blocks at the END of ${L.plan} (read them first: binding; a point Harmony or Boris has ruled is not a finding), then ${L.ruling}: section 3 (amendments), section 4 (the stage table: the row of stage ${KEY}), section 5 (its tests and gate rows). ${L.delta} Boris's words: ${BIND} (the 2026-10-04 sections). The stage's report at the head: git -C ${W} show ${head}:${RPT}/${RNAME}.
THE STAGE'S SCOPE, as the builder was given it: ${S.task}
FOCUS: ${lens.focus}
${extra || ''}
Always also check: each new test or self-test case RED before and GREEN after per the report, and driving real code; nothing stray (no mutant, no instrumentation left, no .venv link); no on-screen text that announces an event or a failure added; docs as the ruling says. You may run read-only git commands and text greps; do NOT build, run tests, launch the app or run a probe; never cd; absolute paths. ${RELAY}
REPORT_FILE: ${RPT}/review-${TAG}-${lens.key}-r${n}.md (write it in the MAIN checkout: ${MAIN}/${RPT}/review-${TAG}-${lens.key}-r${n}.md). Verdict FAIL only for a MUST (a defect that ships, a missed ruling item, a gate or test that cannot fail, a file outside the stage's fence, a script that can quit an app it did not start or touch Boris's folders). Cite file:line at the pinned head for every finding; label each VERIFIED (read / grepped by you) or INFERRED.`, { agentType: 'reviewer', model: 'sonnet', effort: 'high', schema: RS, phase: n === 1 ? 'Review' : 'Re-review', label: 'review:' + TAG + ':' + lens.key + ':r' + n }).then(x => x ? Object.assign({ lens: lens.key }, x) : { lens: lens.key, verdict: 'NO_RESULT', reviewed_commit: head, findings: [] }).catch(() => ({ lens: lens.key, verdict: 'NO_RESULT', reviewed_commit: head, findings: [] }))

phase('Build')
const b1 = await agent(`LANE ${LANE}, stage ${KEY}, worktree ${W}, branch ${BR} (base ${BASE}). STEP 0: git -C ${W} status (clean) and git -C ${W} log --first-parent --oneline -6; if ${REPORT} exists read it first (you are resuming an interrupted stage: continue it, do not redo finished items).
${SPEC}
YOUR STAGE'S SCOPE: ${S.task}
${A.prevNotes ? 'NOTES FROM EARLIER STAGES: ' + String(A.prevNotes).slice(0, 4000) : ''}
RETURN: the structured result; summary <= 1200 characters (full detail lives in the report file); items = one entry per ruling item of your stage with its verdict and the key evidence line; facts_measured = each fact you measured with its raw line; harmony_commands = the exact command lines Harmony runs for your stage's gate rows; next_stage_notes <= 1500 characters.
${RULES(TAG)}`, { agentType: 'builder', model: 'opus', effort: 'high', schema: BS, phase: 'Build', label: 'build:' + TAG })
if (!b1) return { failedStage: TAG }
log(TAG + ': ' + b1.status + ' @ ' + b1.head_commit)
if (b1.status === 'BLOCKED' || !LENSES.length) return { stage: slimB(b1) }

phase('Review')
const r1 = await Promise.all(LENSES.map(l => review(l, BASE, b1.head_commit, 1, '')))
const all1 = r1.flatMap(x => (x.findings || []).map(f => Object.assign({ lens: x.lens }, f)))
const musts1 = all1.filter(f => f.severity === 'MUST')
const shoulds1 = all1.filter(f => f.severity === 'SHOULD')
log(TAG + ' r1: ' + musts1.length + ' MUST, ' + shoulds1.length + ' SHOULD; verdicts ' + r1.map(x => x.lens + '=' + x.verdict).join(' '))
if (!musts1.length && !shoulds1.length) return { stage: slimB(b1), head: b1.head_commit, reviews1: slimR(r1) }
if (b1.status !== 'DONE' && !musts1.length) return { stage: slimB(b1), head: b1.head_commit, reviews1: slimR(r1) }

phase('Fix')
const b2 = await agent(`LANE ${LANE}, stage ${KEY}, FIX ROUND after the pinned reviews, worktree ${W}. CONTINUE on branch ${BR} from commit ${b1.head_commit} (no reset). FIRST read your stage report ${REPORT}.
${SPEC}
The round-1 review reports are ${MAIN}/${RPT}/review-${TAG}-<lens>-r1.md (lenses ${r1.map(x => x.lens).join(', ')}): READ THEM IN FULL. VERIFY each finding against the code before fixing (a finding can be wrong -- say so with evidence, and then do not fix it). Fix every verified MUST; fix a verified SHOULD only when it is small, local and needs no design choice; anything that needs a design choice or changes what Boris sees goes to stop_items_for_harmony, NOT fixed. For every fix: RED first where a test is added (or the named mutant), GREEN after; then the stage's own end checks again (raw lines). Commit per fix; append "Fix round (review r1)" with a per-finding verdict table to ${REPORT} and commit it; refresh the HAND-OVER TO HARMONY block.
THE STAGE'S SCOPE, unchanged: ${S.task}
FINDINGS (whole): ${JSON.stringify([...musts1, ...shoulds1])}
RETURN the structured result (stage = '${KEY}-R1').
${RULES(TAG + '-R1')}`, { agentType: 'builder', model: 'opus', effort: 'high', schema: BS, phase: 'Fix', label: 'fix:' + TAG + ':r1' })
if (!b2) return { stage: slimB(b1), head: b1.head_commit, reviews1: slimR(r1), fixRoundFailed: true }
const r2 = await Promise.all(LENSES.map(l => review(l, BASE, b2.head_commit, 2, `ROUND 2: the round-1 report is ${MAIN}/${RPT}/review-${TAG}-${l.key}-r1.md; the fix round is git -C ${W} diff ${b1.head_commit}..${b2.head_commit}. Check that every round-1 MUST is fixed as found (not documented away), that each new test can fail, and that the fix introduced no new defect; re-read your whole lens only where the fix touched it.`)))
return { stage: slimB(b1), fix: slimB(b2), firstHead: b1.head_commit, head: b2.head_commit, reviews1: slimR(r1), reviews2: slimR(r2) }
