export const meta = {
  name: 'rta-0928b-diag-lane',
  description: 'Audio-DNA s-rta-0928b: one instrumentation-based diagnosis lane in its worktree (opus builder, temporary instrumentation, live runs under the shared lock), then an independent method audit',
  phases: [{ title: 'Diagnose' }, { title: 'Audit' }],
}
// args: { lane: 'diag-idle' | 'diag-media', wt }
const A = args
const MAIN = '/Users/boriskarpman/projects/RealTimeAudio'
const MAIN_APP = MAIN + '/build/AudioDNA_artefacts/Release/Audio-DNA.app'
const RPT = '.harmony/.reports/s-rta-0928b'
const OLDRPT = MAIN + '/.harmony/.reports/s-rta-0928'
const SP = '/private/tmp/claude-501/-Users-boriskarpman-projects-RealTimeAudio/e9ff9dc6-f159-4d37-b0a9-871bf522d258/scratchpad'
const W = MAIN + '/.claude/worktrees/' + A.wt
const L = SP + '/' + A.lane
const D = MAIN + '/build/_deps'

const RULES = `
RIG RULES (binding; breaking any one = lane FAIL):
- NOT an isolated worktree. Work ONLY inside W=${W} with absolute paths (git -C ${W} ...; cmake -S ${W} -B ${W}/build-lane; cmake --build ${W}/build-lane --target AudioDNA -j3). Configure: -DCMAKE_BUILD_TYPE=Release -DAUDIODNA_BUILD_TEST_SERVER=ON -DAUDIODNA_BUILD_SYPHON=ON -DFETCHCONTENT_FULLY_DISCONNECTED=ON -DFETCHCONTENT_SOURCE_DIR_JUCE=${D}/juce-src -DFETCHCONTENT_SOURCE_DIR_HTTPLIB=${D}/httplib-src -DFETCHCONTENT_SOURCE_DIR_CATCH2=${D}/catch2-src -DFETCHCONTENT_SOURCE_DIR_MELATONIN_INSPECTOR=${D}/melatonin_inspector-src -DFETCHCONTENT_SOURCE_DIR_SYPHON=${D}/syphon-src (read-only use; a lane that must instrument JUCE copies juce-src into its scratch dir and points the JUCE source dir there). NEVER edit the main checkout ${MAIN} or its build/ (read-only use of ${MAIN_APP} = the unmodified app is allowed). NEVER cd in a command; multi-step sequences go in script files under ${L}/ run with bash <file>. zsh does not split a command held in a variable. Stamp times from date, never estimate.
- Python: use ${MAIN}/.venv/bin/python directly (never create a .venv symlink in the worktree).
- LIVE APP: at most ONE Audio-DNA on the machine (another lane shares it). Use the helper: put LANE=${A.lane} on its own line, then . ${SP}/lib/lock.sh (it pins LOCK_LANE by a real assignment; functions: acquire_lock / release_lock / start_app APP OUTDIR [test] / quit_app / outwins / wait_quiet / adna). A failed mkdir means WAIT (never open another copy: same bundle id reaches the running app); never remove another lane's lock; after releasing wait >= 45 s before re-acquiring (the helper enforces it). Hold the lock per launch or small batch (<= ~15 min), release between batches. Probes REFUSE without AUDIODNA_LOCK_OWNER matching (the helper exports it).
- Launch ONLY: open -g [--env V=v] [--stdout f --stderr f] <App> [--args --test-mode] (start_app does this). SCREEN-SAFETY LAW: NEVER open the Output window by ANY path (Output menu, Cmd+F, TopBar button, REST, deck/composition/settings file with an output) — no automated gate ever opens an output window; check outwins after every launch (must read Output-named 0). Quit via quit_app (osascript quit; kill only after 30 s). NEVER lldb/debugserver/gdb/dtrace/Instruments/sample/spindump on ANY binary. NEVER full-screen screencapture (window-only by Quartz window id via pyobjc with the main .venv python). NO synthetic input (UI states via REST / composition files / a TEMPORARY env-var hook). Unexpected system dialog: STOP and report. NEVER write persistent system or user defaults (no defaults write).
- Perf numbers only when no compiler runs (wait_quiet) with the load average printed at start and end of each launch; other lanes may be compiling — wait, do not measure through it. A verdict needs >= 5 launches per arm. Probe HTTP clients use a fresh connection per request (Connection: close).
- DIAGNOSIS ONLY: no product change is committed. All instrumentation is TEMPORARY: before reverting, save it as ${L}/instr.diff (git -C ${W} diff, plus new files) and keep your drivers/analyzers under ${L}/tools/ with paths fixed; revert with git -C ${W} apply -R of your own diff and delete the files you added (NEVER git checkout -- . / git stash / git reset --hard: the stash-guard hook blocks them); rebuild build-lane from the clean tree; strings check (strings <binary> | grep -c <your markers>) must be 0. End state: git -C ${W} status clean except build-lane/ (KEEP build-lane), lock released, no app you launched running, 0 Output-named windows, any fixture files you put under ~/Documents or ~/Library moved to ${L}/ (say which).
- Label every claim VERIFIED (measured / read in source, cite the evidence file or file:line) / INFERRED / ASSUMED. A cause without a counterfactual run is INFERRED.
- Report: write ${L}/report.md (BUILDER REPORT shape: STATUS, RESULT, FACTS, METHOD, CONFIDENCE+VERIFY, UNKNOWNS, then the deliverable sections, found_not_fixed, notebook lines for Harmony, PACKET QUALITY) and return it IN FULL in report_markdown. Evidence under ${L}/runs/<tag>/.`

const PACKETS = {
  'diag-idle': `LANE diag-idle (lane-name: diag-idle). DIAGNOSIS ONLY. Worktree W (detached at main): STEP 0 git -C ${W} checkout -B diag/idle main.

THE QUESTION. With NO routine running and nothing being clicked, the Audio-DNA message thread shows an always-present background stall. s-rta-0928 measured it with a heartbeat (a background thread keeps one juce::MessageManager::callAsync ping in flight, re-posts it 2 ms after it is served, and logs serve-minus-post latency >= 2 ms): per-500-ms-window max lag median 19.9-23.1 ms, p90 23.2-26.4 ms, max 28.5 ms; lags >= 2 ms median 6.3-8.1 ms, p90 14.3-19.0 ms; read then as "busy 17-25 ms about every 70 ms (~15 Hz)". The instrumented scopes then (DeckView/LayerStrip/ClipCell paint >= 0.25 ms, InspectorPanel refresh, MainComponent::timerCallback and tickFeaturePipeline sub-scopes) summed <= 1 ms inside those windows: the time is OUTSIDE every instrumented scope. Source: ${OLDRPT}/restore-diag.md sections 1, 3 and 7.1 (read them). It is the floor under every UI-hitch measurement and a stall Boris feels. ATTRIBUTE IT DEFINITIVELY.

DELIVERABLE (report sections): (1) BUSY time or DELAYED WAKE (or both, with shares)? (2) the attribution table: cause -> file:line or JUCE/OS mechanism -> ms per event (median/p90/max) -> events per second -> share of the idle heartbeat lag and of main-thread busy ms/s; (3) for EVERY cause claimed, the COUNTERFACTUAL that proves it: a TEMPORARY env-var toggle that removes that cause alone, >= 5 launches per arm (each >= 30 s idle measured after a >= 5 s settle), before/after numbers; (4) what remains unattributed after all proven causes (ms and share) — keep bisecting until it is under ~2 ms or you can name why you cannot; (5) fix options per cause (NOT implemented): what moves where, expected lag after, risks vs CLAUDE.md's Sacred Rules and UI patterns, and the RED-able gate a fix lane would use (the heartbeat numbers as a probe row: what threshold, what it reads on current main); (6) the reusable tools, paths fixed (${L}/tools).

METHOD (required, in this order):
M1. Tools: copy ${OLDRPT}/restore-tools/ (instr.diff = src/diag/DiagTrace.h heartbeat + diag::Scope + the restore scopes; drive.py; analyze.py; run1.sh; build.sh) to ${L}/tools/ and fix the hard-coded paths (old scratchpad cfd08720..., worktree rta0928-w4). instr.diff was cut on a pre-fix tree and will not apply cleanly: re-port DiagTrace.h + the heartbeat, and only the scopes you need.
M2. BUSY vs DELAYED WAKE first: add a CFRunLoopObserver (kCFRunLoopAllActivities) on the main run loop (CFRunLoopGetMain, kCFRunLoopCommonModes) that timestamps every activity transition, so main-thread wall time splits into sleeping (BeforeWaiting -> AfterWaiting) and busy spans binned by phase (AfterWaiting / BeforeTimers / BeforeSources / BeforeWaiting — CoreAnimation commit and the window display pass run in BeforeWaiting observers). Also sample the main thread's CPU time (mach thread_info THREAD_BASIC_INFO user+system of the main thread, per 500 ms window). Log each busy span >= 2 ms with its phase; line the heartbeat lags up against them. If lags occur while the main thread sleeps it is delayed wake: test App Nap / timer coalescing with a TEMPORARY env-var hook that calls [[NSProcessInfo processInfo] beginActivityWithOptions:(NSActivityUserInitiated | NSActivityLatencyCritical) reason:@"diag"] at startup (nothing persistent). Lanes launch with open -g (background app, window not frontmost): say whether the result depends on that and how Boris's foreground use would differ (you may NOT bring the window forward by synthetic input; a TEMPORARY hook that calls juce::Process::makeForegroundProcess() is allowed ONLY if it does not steal focus from Boris's work — prefer not to; if you judge it necessary, measure it in one short batch and say so).
M3. Attribute the busy spans: scope EVERY juce::Timer::timerCallback in src/ (grep), every AsyncUpdater / callAsync handler that fires at idle, VBlank/OpenGL callbacks that touch the message thread, and the paint path end to end. If app-level scopes cannot reach the time (the window display pass, the JUCE peer's drawRect -> handlePaint, the OpenGLContext), instrument a PRIVATE copy of JUCE: cp -R ${D}/juce-src ${L}/juce-src and configure build-lane with -DFETCHCONTENT_SOURCE_DIR_JUCE=${L}/juce-src (NEVER edit ${D}). HARMONY HYPOTHESES — UNVERIFIED, test them, never trust them: H1 the JUCE OpenGLContext paints the component tree on the GL thread under a MessageManager::Lock (component painting / renderComponents) — measure how long the GL thread holds the message lock per frame and whether the app attaches a context with component painting on; H2 a large software repaint in the display pass by uninstrumented components (meters, spectrum/waveform, readouts, top bar) invalidated by a timer; H3 an app timer's own work; H4 delayed wake (App Nap / timer coalescing of a background app); H5 something else — the run-loop bins decide.
M4. Counterfactual bisection with TEMPORARY env-var toggles (ADNA_DIAG_*), one suspect per arm, same fixture, >= 5 launches per arm. Report per arm: heartbeat lags >= 2 ms per second, their median/p90, the per-500-ms-window max median/p90/max, main-thread busy ms/s by phase, main-thread CPU ms/s, load average.
M5. Fixtures: (a) the app's default startup state; (b) the probe fixture the old drive.py builds ('card'); (c) a deck with ~16 image cells (4K JPEGs you make with ffmpeg or python into ${L}/media). Production mode (no --test-mode) is what Boris runs; say which mode each arm used and whether it matters.

A SECOND LANE (diag-media) runs concurrently in another worktree, measuring media decodes / file I/O on the hot threads (incl. ClipCell::paint stat()ing every image/video file on every paint); it shares the live-app lock with you. You attribute whether that site is part of the IDLE floor; you do not rank its cost at scale.
${RULES}`,

  'diag-media': `LANE diag-media (lane-name: diag-media). DIAGNOSE-RANK ONLY. Worktree W (detached at main): STEP 0 git -C ${W} checkout -B diag/media main.

THE QUESTION. s-rta-0928 moved still-image decoding off the GL thread (the ImageDecode::Decoder pool; Pitfalls 52/53 in docs/claude/pitfalls.md; design and found_not_fixed in ${OLDRPT}/plan-renderleft.md incl. its HARMONY ADOPTION section, ${OLDRPT}/renderleft.md, ${OLDRPT}/renderleft-fix.md — read the design sections and found_not_fixed). Media decodes and file I/O remain on the two hot threads. Known sites:
 S1 video decodes on the GL render thread (F16);
 S2 ImageSequence::open / openMediaForDeck decode frame 0 on the message thread;
 S3 sequence first-frame thumbnails decode on the message thread at load / drop / append;
 S4 existsAsFile() per image clip per frame on the GL thread;
 S5 ClipCell::paint stats every image/video file on every paint (message thread).
Plus a SWEEP for any other decode or file I/O (juce::File exists / getSize / getLastModificationTime / isDirectory / findChildFiles / read, ImageFileFormat::loadFrom / ImageCache, FFmpeg avformat_open_input / av_read_frame / avcodec_* / sws_scale, std::ifstream, fopen, stat) reachable (a) per frame on the GL thread, (b) per paint / timer tick / trigger / refresh on the message thread, (c) at composition / deck load or media drop on the message thread. Cite file:line and the call path from the hot entry point.

DELIVERABLE: a ranked table: site -> file:line -> thread -> trigger & frequency (per frame / per paint / per event) -> MEASURED cost per call (median/p90/max, live, instrumented) at representative media -> impact (GL frame time vs the 8 ms chain budget and the 16.67 ms VSync; message-thread hold ms) -> user-visible symptom (dropped frames, UI freeze, stutter at a clip trigger, slow load) -> rank score (cost x frequency x visibility; show the arithmetic). For each site: fix options (NOT implemented) — where the work moves (the ImageDecode::Decoder pool? a dedicated video decode thread per playing clip? a cached stat with invalidation?), constraints (FFmpeg context thread affinity, GL upload stays on the GL thread, Pitfall 35 a crossfading layer has two live clip chains, Pitfall 53 pending semantics, the render thread never waits, CLAUDE.md rule 15 an inactive deck keeps time), expected gain; and a RED-able gate per site (a counter or probe row that fails on current main and would pass after the fix — say what it measures and what it reads today).
Also note (for a separate lane that is being PLANNED now): an ImageSequence currently keeps every frame's texture for its lifetime; a bounded texture window is being planned. Record anything you see about ImageSequence decode/upload that such a plan must respect, but do not design it.
Media fixtures (make them in ${L}/media with ffmpeg; brew ffmpeg is installed): 1080p30 and 4K30 H.264 10 s (testsrc2), a ProRes 422 1080p clip, a 300-frame 1080p PNG sequence and a JPEG one (in the folder layout the app treats as an image sequence — read how it detects one), 16 image cells (4K JPEG) and 16 video cells. Measure with a message-thread heartbeat and GL-thread frame-time scopes (the Renderer / CompositorEngine frame, per-layer media sync), >= 5 launches per arm for any number you rank on. Measure S5 at scale (stat calls per second, ms per paint).
Tools: the s-rta-0928 heartbeat + scope header is in ${OLDRPT}/restore-tools/instr.diff (src/diag/DiagTrace.h); the old drive.py / run1.sh show how to drive the app over REST and launch under the lock (paths hard-code an old scratchpad; copy to ${L}/tools and fix). The existing .harmony/probe-image-load.* and probe-capture.* show the TEST_SERVER counters renderleft added.
A SECOND LANE (diag-idle) is attributing the app's idle message-thread background stall (~20-28 ms at ~15 Hz) concurrently; you share the live-app lock. Subtract that background when you attribute message-thread holds to a site (measure the no-media baseline in the same launch).
${RULES}`,
}

const DS = { type: 'object', properties: {
  lane: { type: 'string' }, status: { type: 'string', enum: ['DONE', 'PARTIAL', 'BLOCKED'] }, worktree_path: { type: 'string' }, base_commit: { type: 'string' },
  headline: { type: 'string' },
  causes: { type: 'array', items: { type: 'object', properties: { id: { type: 'string' }, site: { type: 'string' }, thread: { type: 'string' }, trigger_frequency: { type: 'string' }, cost_ms: { type: 'string' }, share_or_rank: { type: 'string' }, proof: { type: 'string' }, label: { type: 'string', enum: ['VERIFIED', 'INFERRED', 'ASSUMED'] } }, required: ['id', 'site', 'cost_ms', 'proof', 'label'] } },
  unattributed: { type: 'string' }, fix_options: { type: 'string' }, gates: { type: 'string' },
  report_path: { type: 'string' }, tools_dir: { type: 'string' }, report_markdown: { type: 'string' },
  lock_released: { type: 'boolean' }, app_left_running: { type: 'boolean' }, output_window_opened: { type: 'boolean' }, tree_clean: { type: 'boolean' }, instrumentation_strings_zero: { type: 'boolean' },
  errors_or_deviations: { type: 'string' } },
  required: ['lane', 'status', 'headline', 'causes', 'report_markdown', 'lock_released', 'app_left_running', 'output_window_opened', 'tree_clean', 'instrumentation_strings_zero'] }

phase('Diagnose')
const d = await agent(PACKETS[A.lane], { agentType: 'builder', model: 'opus', effort: 'high', schema: DS, phase: 'Diagnose', label: 'diag:' + A.lane })
if (!d) return { diag: null }
log(`${A.lane}: ${d.status} — ${String(d.headline).slice(0, 200)}`)

phase('Audit')
const AS = { type: 'object', properties: { verdict: { type: 'string', enum: ['SOUND', 'SOUND_WITH_GAPS', 'UNSOUND'] }, findings: { type: 'array', items: { type: 'object', properties: { severity: { type: 'string', enum: ['MUST', 'SHOULD', 'NIT'] }, issue: { type: 'string' }, fix: { type: 'string' } }, required: ['severity', 'issue'] } } }, required: ['verdict', 'findings'] }
const audit = await agent(`INDEPENDENT METHOD AUDIT (read-only) of diagnosis lane ${A.lane}. Read the lane's report ${L}/report.md, its evidence under ${L}/runs/, its tools under ${L}/tools/ and instr.diff (${L}/instr.diff), and the source it cites (in ${W} or ${MAIN}; the tree is at main). Do NOT re-run the app. Judge: is each claimed cause PROVEN (a counterfactual with >= 5 launches per arm, numbers that move as predicted) or only inferred; could the instrumentation itself have created or hidden the effect (observer cost, log I/O on the message thread, heartbeat perturbation); is the arithmetic right (shares sum, per-event x rate = busy ms/s); does any evidence file contradict the report; is anything left unattributed that the report calls attributed; are the RED-able gates it proposes real (would they read RED on current main?). Write your paper via Bash heredoc. REPORT_FILE: ${RPT}/audit-${A.lane}.md`, { agentType: 'reviewer', model: 'sonnet', effort: 'high', schema: AS, phase: 'Audit', label: 'audit:' + A.lane })
return { diag: d, audit }
