export const meta = {
  name: 'rta-1004-plan-lane',
  description: 'Audio-DNA s-rta-1004: plan ONE lane named by args from Boris\'s rulings of 2026-10-04 and the verified fact sheets -- architect plan (opus high), four blind council seats (sonnet), architect ruling (opus max). Read-only.',
  phases: [{ title: 'Plan' }, { title: 'Attack' }, { title: 'Ruling' }],
}
// args: { key, title, goal, items, seats: [{ key, temper }], sheets: [names], qFirst, qLast, constraints, ruleFirst: [3 short labels] }
const GATES_SEAT = { key: 'gates', temper: `You are the GATE PROSECUTOR: a test that cannot fail is not a test. Attack every test, mutant, bar and gate string in the plan: a claim "proven" by index arithmetic alone when the thing claimed is what a screen or a reader actually gets; a RED arm that does not exist or cannot go red; a bar nobody measures or that is stated after the run; a "bit-identical at the default" gate that compares the wrong two things; a live row that passes when the code under test is never reached; a "what only Boris can check" entry that hides a claim a machine could test; a count or pin left stale by an added case. The screen-safety law forbids any gate from opening an Output window, taking a full-screen capture or sending synthetic input: attack every row that quietly needs one of them.` }
const SCOPE_SEAT = { key: 'scope', temper: `You are the MINIMALIST: other lanes (the clip transport, the messages removal, recording) wait behind this one, and Boris asked for "simpler". Attack scope and order: a mechanism bigger than the request; a model copied from Resolume that Audio-DNA's own structure does not need; a range, a row or a window paid for and never used; parts carried from the stopped sync-dial branches that nothing needs, or parts dropped that would have saved a stage; a stage order that makes something wait when it need not; a question put to Boris that is not his. For each cut, name what is lost -- and name the ONE thing in the plan that must NOT be cut.` }
const LANES = {
  outputs: {
    title: `a settings window for every output screen -- Device, Delay, Opacity, Brightness, Contrast, Red, Green, Blue, as Resolume's Screen window -- for display outputs and for Syphon (it replaces the stopped sync dial)`,
    goal: `Boris replaced the sync dial with a Delay per output screen, set in that output's display properties as Resolume has it, "so the video matches the audio at the soundboard or wherever the vj is stationed in middle of room preferably"; he then asked for ALL of Resolume's Screen settings ("yes add all of those output settings") and ruled "syphon is an output and treated with same output settings as a screen". Produce the plan a builder can execute stage by stage: the mechanism that shows an output a picture N milliseconds old without ever blocking the shared GL thread, its memory bill, the colour stage, how a screen's settings are remembered with the screen, the window he sets them in, and how all of it is proven without a gate ever opening an Output window.`,
    sheets: ['outputs', 'resolume-screen-delay', 'syncdial-parts', 'saves'],
    qFirst: 51, qLast: 59,
    constraints: `Harmony constraint (lane outputs): the delay never blocks, waits or allocates per frame on the shared GL thread; its memory is bounded, stated per output and per canvas size, and clamped or refused by a stated rule when it would exceed the budget; an output at Delay 0 with every colour setting at its default shows exactly what it shows today (the same newest frame, no added copy, no added frame of latency) and a gate proves it; the in-app preview, recordings, snapshots and the Eyes capture are never delayed or coloured by an output's settings; a screen's settings are per machine (question 38's default), never in the show file.`,
    ruleFirst: [`the Delay's range and its memory bill (Resolume stops at 100 ms; Boris's purpose is sound travelling to mid-room, about 3 ms per metre; his earlier dial went to 500)`, `how "the same screen" is recognised so that two identical projectors never swap settings silently`, `how an output's picture is proven without opening an Output window`],
    items: `OA1 THE DELAY MECHANISM. Today each OutputWindow presents the NEWEST completed frame from a 4-slot IOSurface pipeline that is a pipeline, not a history (facts-outputs). Where does a picture N ms old come from: a ring of frames per output, one ring shared by all outputs with a read index per output, or a deeper shared pipeline? State for each: the memory at 1920x1080 and 3840x2160 for 100, 250 and 500 ms at 60 fps with one, two and three outputs; what it costs the shared GL thread per frame; what an output shows while the ring is still filling, when the Delay is dragged (no black, no jump back in time, no stutter), at a canvas-size change, at open / close, at a display hot-plug; a 120 Hz display fed by a 60 fps canvas. Rule the mechanism and the RANGE with its bill.
OA2 THE COLOUR STAGE. Opacity, Brightness, Contrast, Red, Green, Blue per output: the range and meaning of each as Resolume documents them (facts-resolume-screen-delay Q3; say what is NOT documented), the exact arithmetic, where it runs (each output's present step), what "0" means for the centred ones, what Opacity fades towards on a physical screen, and the proof that all-default is a no-op.
OA3 SYPHON AS AN OUTPUT (his ruling). How Syphon publishes today (build-flag gated, Pitfall 26; where it taps the canvas), and what "the same output settings as a screen" takes: its own delay read point and colour pass before publishing, its identity (it has no display), its entry in the window. Resolume's own Syphon / NDI outputs showed no Delay row (facts sheet): his ruling outranks that.
OA4 IDENTITY AND MEMORY OF SETTINGS. A screen's settings are remembered "with the screen, whatever show is open" (question 38's default). Today a display is known only by a geometry fingerprint (x, y, w, h, scale, main) and JUCE gives no id or name. Rule the identity (is a native display id / UUID / name reachable on macOS without a new dependency; what survives a re-plug, a resolution change, a reboot; two identical projectors), the settings.json schema for it (settings.json is read-modify-write and an unreadable file reads as empty -- facts-saves: respect it or mend it, say which), what happens to the settings of a screen that is not connected, and the dead outputDisplay field in the show file.
OA5 THE WINDOW. Audio-DNA has no output properties window; outputs are one item list shared by the Output menu and the TopBar "Outputs" button, one borderless window per display, never key, never opened by the app itself (CLAUDE.md "Outputs", Pitfall 40). Rule: one window listing every output with its eight rows, or one panel per output; where it opens from; what the "Device" row is in a model where an output IS a display (a read-only name, or a way to move an output to another display -- say what Resolume's Device menu does and whether Boris's words need it); the rows as ResettableSliders with defaults; what the window shows for Syphon and for a screen that is saved but not connected. List every state the visual gate must capture.
OA6 WHAT IS NEVER DELAYED OR COLOURED. The in-app preview, the video recorder, the PNG snapshot, the Eyes capture, the future record-into-a-cell: where each taps the path (facts-outputs Q5) and the proof that an output's settings cannot reach them.
OA7 PROOF WITHOUT AN OUTPUT WINDOW. The screen-safety law forbids a gate from opening one. Design the tests: the ring's index and age arithmetic (unit, with mutants); the present step run offscreen against a known frame sequence and decoded pixel by pixel (which target, which route, test-server only); the Delay-0 / all-default identity gate; the memory bar and how it is measured; the settings round trip. Then what is left that only Boris can check on real screens (a camera test of the delay; two projectors).
OA8 THE STOPPED BRANCHES. facts-syncdial-parts: the dial delays audio into the analysis, globally; there is no picture-frame delay in it. Say what, if anything, this lane carries (with commits) and what is dropped; the three stale docs on main the lane had fixed (testing-eyes.md kill advice, architecture.md's triple-buffer lines, APP-INVENTORY's count) go into a small docs stage here or are named for another lane.
OA9 STAGES AND ORDER. One builder context per stage, the files each owns, what each proves; the visual gate before Boris sees the window; the docs (docs/claude/integration.md "Output windows", rendering.md), the new Pitfall (number NN; Harmony assigns 68); what the beat-nudge lane (planned beside this one; it owns the tempo area of the top bar) and this lane must not both touch.`,
    seats: [
      { key: 'gl-thread', temper: `You are the GL-THREAD SKEPTIC: everything the picture does happens on ONE shared GL thread at VSync, with IOSurface slots that are a pipeline and not a history. Attack the delay mechanism and the colour stage: a ring that blocks, waits or allocates per frame; memory that is unbounded or unstated at 3840x2160 with three outputs; a Delay-0 path that is no longer the newest frame or costs an extra copy; a Delay change, canvas resize, output open / close or display hot-plug that shows black, a stale frame, a frame from the future of the ring, or a torn frame; a 60 fps canvas on a 120 Hz display; a texture or surface lifetime that breaks Pitfalls 37, 40, 57 or 60; Syphon published from the wrong point of the path. Re-derive each claim from the code.` },
      GATES_SEAT,
      { key: 'stage-hands', temper: `You are the VJ AT THE DESK in a dark room with two projectors and an LED wall, ten minutes before doors. Attack the window and the model from what Boris does and sees: finding the settings of the RIGHT screen; two identical projectors swapping their settings after a re-plug; the laptop's own screen used as an output; a screen unplugged mid-show and returned; a Delay that makes the picture jump or freeze while he drags it; values lost at relaunch, or wrongly carried into the next venue; Syphon listed or not listed where he looks; a row that silently does nothing; a default he cannot get back to; any text that announces an event or a failure (forbidden). Every attack names what Boris sees on the wall or in the window.` },
      SCOPE_SEAT,
    ],
  },
  nudge: {
    title: `the beat nudge -- the user moves the main beat earlier or later by milliseconds, shown as "off beat by [+/- X] ms"`,
    goal: `Boris: "user can nudge main bpm forward or back and this needs to be displayed as "off beat by [+/- X] ms'"; "A nudge just moves the placement of the downbeat in time not the tempo."; "If we are shifted forward or back, everything that is connected to BPM shifts forward or back. I mean everything. If the user twist the knob in real time, or triggers a clip, that is not affected unless it's set to be quantized". No such control exists today: Tap, Resync and (in Auto) the detector can only snap the beat to "now" (facts-beat-controls). Produce the plan a builder can execute stage by stage: where ONE signed offset is applied so that every beat-driven reader sees the same shifted beat at 1 ms precision, the two controls and the text in the top bar, what Tap, Resync, Manual, Auto and Link do to it, where it is remembered, how it goes on a key or a pad, what a recorded take does with it, and how it is proven.`,
    sheets: ['beat-controls', 'syncdial-parts', 'saves', 'resolume-screen-delay'],
    qFirst: 61, qLast: 69,
    constraints: `Harmony constraint (lane nudge): ONE shifted beat for every reader -- a design in which any beat-driven reader (a quantised fire, a routine, autopilot, a slideshow, a shader or mapping that reads the beat or the bar, the bar counter, the beat circle, the take recorder's beat) can see the un-shifted beat is rejected; the published beat fields stay mutually consistent after a shift in either direction (no beat fired twice, none skipped, no count running backwards); the step is 1 ms whatever the 10.67 ms hop; at 0 the published values are bit-identical to today's and a gate proves it; what follows the sound itself (loudness, onsets, bands) never shifts; a knob turned or a clip fired by hand is not shifted, and a quantised fire lands on the shifted beat.`,
    ruleFirst: [`WHERE the offset is applied (in the tracker per hop, where the snapshot is published, or where it is read) and why every reader then agrees`, `what Auto mode's own re-alignment on every confident beat does to the offset`, `which way "+" points in "off beat by +12 ms" and how Boris reads it at a glance`],
    items: `NB1 WHERE THE OFFSET LIVES. Every beat consumer reads one published FeatureSnapshot clock (facts-beat-controls table T2 and its re-read, section C items 2 and 5): beatPhase, beat-in-bar, barPhase, phrasePhase, totalBeatCount, the bar counts, downbeatDetected; some readers use a wrap test, some a counter, the take recorder builds its own continuous beat. A tempo or phase request lands only on a hop boundary (10.67 ms); in Auto a confident detected beat re-aligns the phase by itself, so a one-shot shift is erased within a beat. Lay out the forks (shift inside the tracker; rewrite the beat fields where the snapshot is published; shift at each reader) and rule one: how a SIGNED offset in ms becomes a consistent set of fields at 1 ms precision in both directions, at any tempo, across a bar line, while the tempo changes, in Manual, in Auto and under Link. The stopped branch's BeatLead rewrites nine beat fields for "earlier" only (facts-syncdial-parts): say exactly what of it is carried, with commits, and what "later" needs that it lacks.
NB2 WHAT IT MUST NOT MOVE. Loudness, onsets and bands follow the sound and stay; a knob turned or a clip fired by hand is immediate; a quantised fire waits for the shifted beat. List the readers on each side with file:line, and the ones that are ambiguous (the take recorder's beat stamps, routines replayed from a take, Link, the inject / test path that writes beat fields directly) with a ruling for each.
NB3 THE CONTROLS AND THE TEXT. Two controls beside the tempo in the top bar (earlier, later) and the text "off beat by +12 ms" -- his words: "off beat by [+/- X] ms". Harmony's readings told to him and not corrected: 1 ms per press, a held key keeps moving, a number can be typed, -500 to +500, always shown ("off beat by 0 ms" when untouched), the tempo number does not change. Rule the sign convention, the exact text at 0 and at the ends, where a typed value goes, the top bar's width budget (it already holds the beat wheel, "Bar N", the tempo, Tap, Resync, Manual, Link, the BPM field, five /4 /2 x1 x2 x4 buttons that do nothing today, Quantize), and what the 15 Hz top-bar timer means for a beat circle that must "move with the nudge" (his answer 46). List every state the visual gate must capture.
NB4 TAP, RESYNC, MANUAL, AUTO, LINK. His words: "If I tapped the tempo again, to set the tempo, the time does not change. If I press re-sync, then it does re-sync and that changes by how far off the beat we are." Tap leaves the number; what the number reads after a Resync is question 49 (default 0): build so that either answer is one line. Say what turning Manual on or off, Auto's own re-alignment, and a Link tempo do to the number and to the shifted beat.
NB5 WHERE IT IS REMEMBERED. Harmony's reading told to him: with the show ("every show remembers it's sync"). The composition field, what opening / New / a staged load does to it (no on-screen text), what an old show without the field reads.
NB6 A KEY OR A PAD. "Key and pad is fine, knobs can skip the sync": two binding targets (earlier, later), a held key repeating, no knob or fader. The stopped branch lane/bf2-keys built exactly this for the dial (SyncNudge, bindingIsLive, MIDI learn refusing a CC, two test-only routes, test_binding_sync_nudge; rulings-bf2.md H-15, H-16): say what is carried as it is, what is renamed, what is dropped, with commits; H-16's three open items (a label bar false on 15 old buttons, no test route for the keyboard bind overlay, the learn title's em dash) are ruled here if the overlay targets are carried.
NB7 TAKES AND REPLAY. A take records actions and replays them; "tempo" actions are captured (facts-beat-controls re-read, C7). Is a nudge an action that is captured and replayed, a setting the take stores once, or neither? Rule it with what Boris would see on replay.
NB8 PROOF. Unit cases on the field arithmetic (both signs, a bar line, a tempo change, Auto's re-alignment, zero = bit-identical), each RED first with a mutant; a REST route to set and read the offset for live rows (name it); a live row that a quantised fire and the bar counter land on the shifted beat; the inject path. Every live row is Harmony's. What only Boris can check (the feel against a real room; the text at a glance).
NB9 STAGES AND ORDER. One builder context per stage, the files each owns, what each proves; the visual gate; docs (docs/claude/effects.md "Manual BPM Mode", performance-controls.md); the first entry of a user manual (none exists: facts-beat-controls Q6) telling the user how to line the beat up with the picture from where he stands; what the output-settings lane (planned beside this one; it owns the Outputs button and the output windows) and this lane must not both touch. The five inert /4 /2 x1 x2 x4 buttons sit in this lane's area: a Boris question (remove or wire) with a default, not a silent change.`,
    seats: [
      { key: 'beat-clock', temper: `You are the BEAT-CLOCK SKEPTIC: the beat is several published fields (phase, beat-in-bar, bar phase, counts, a downbeat level) written once per 10.67 ms hop, read by many consumers at different rates, and in Auto re-aligned by the detector on every confident beat. Attack the mechanism: a reader that still sees the un-shifted beat; fields that disagree after a shift (the phase moved, a count did not); a shift quantised to the hop when the control is 1 ms; a one-shot shift erased by Auto's own re-alignment; a negative shift that makes a count run backwards, fires a beat twice or skips one (Pitfalls 30, 32, 38, 42, 48); the tempo changing while shifted; the inject and test paths; Link; the take recorder's own beat. Re-derive each claim from the code.` },
      GATES_SEAT,
      { key: 'stage-hands', temper: `You are the VJ MID-SET: the picture lags the kick; you tap, you resync, you nudge with a key while watching the wall. Attack from what Boris does and sees: "off beat by +12 ms" read the wrong way round (which way is +?); a nudge that changes the tempo number; a number that silently returns to 0, or silently survives, when he expects the other; what a held key does and how fast; what opening another show does to it mid-set; a beat circle refreshed 15 times a second hiding a 5 ms nudge; dead buttons beside the new ones; the control learned onto a knob doing nothing; a fired clip or a turned knob that waits for the beat when it should not; any text that announces an event or a failure (forbidden). Every attack names what Boris sees or hears.` },
      SCOPE_SEAT,
    ],
  },
  'transport-delta2': {
    title: `the clip transport, SECOND DELTA on the ruled plan -- the Clip panel's Transport section mimics Resolume's (Timeline and BPM Sync), a clip's length is set in BARS (4, 8, 12, 16 ...), Random and BeatLoopr are built, the timeline shows bars only, a fired paused clip stays paused, and a dropped playhead slides back onto the BAR`,
    goal: `The transport lane was planned and ruled on 2026-10-03 (30 amendments, then 10 delta amendments on Boris's first answers) and nothing of it is built. On 2026-10-04 Boris changed its ground: "I want you to study these images and mimic exactly how resolume is doing. It's transport control."; "lets do bars here not beats. I know I said beats before but lets do bars"; "always work with multiples of 4. If it is uneven, then move the outpoint in to keep those multiples."; "Timeline only shows bars."; "build random and beatloopr"; a fired paused clip "stays in layer strip paused"; and for a playhead dropped mid-bar he chose that the clip slides until its bars sit on the music's bars, asking "can you program this reliably or should we change the plan?". Produce the SECOND DELTA: one verdict for every earlier amendment, the panel as he now wants it, the bars arithmetic with worked examples, the measurement that answers his reliability question BEFORE anything that depends on it is built, and the new stage list.`,
    sheets: ['resolume-transport', 'beat-controls'],
    qFirst: 71, qLast: 79,
    extraInputs: `- THE RULED CHAIN THIS DELTA AMENDS (big; grep -n '^#' first): ${'/Users/boriskarpman/projects/RealTimeAudio'}/.harmony/.reports/s-rta-1003b/plan-transport.md, ruling-transport.md (amendments AM-1..AM-30; its section 4 stages and section 5 gate rows), plan-transport-delta1.md, ruling-transport-delta1.md (DA-1..DA-10; its section 4 FINAL STAGES, section 5 gate rows, the facts FM-1..FM-6 that need a run, the beat lock and its 6 % bound) in the same folder; the fact sheets they stand on: ${'/Users/boriskarpman/projects/RealTimeAudio'}/.harmony/.reports/s-rta-1003/facts-transport.md and facts-quantize-units.md (read at an older commit: re-check any line you lean on against main at the pin).
- BORIS'S ANSWERS that already shaped that chain: binding-decisions.md sections "2026-10-03 (s-rta-1003)" and "2026-10-03 (s-rta-1003b)". Where a 2026-10-04 line says REPLACES or REVERSES, the later line wins.
- THE BEAT NUDGE is planned beside this lane (plan-nudge.md / ruling-nudge.md in ${'/Users/boriskarpman/projects/RealTimeAudio'}/.harmony/.reports/s-rta-1004/ when they exist): a BPM-synced clip reads the SHIFTED beat, like every other beat-driven reader.`,
    constraints: `Harmony constraint (lane transport): this is a DELTA on a ruled chain -- every amendment AM-1..AM-30 and DA-1..DA-10 gets exactly ONE verdict (STANDS / AMENDED / DROPPED) with the line of Boris's that decides it; nothing is silently kept and nothing silently lost. Where Boris's ruling differs from what Resolume does (bars, not beats; 4, 8, 12, 16 ... bars, not powers of two; the out point moved in, never a stretched clip, except a clip shorter than 4 bars; no trigger-style menu, every fire starts at the beginning; a scrubbed clip slides back onto the bar instead of staying off it), HIS ruling is built and each difference is listed in section 6 so that he sees it. The beat lock is MEASURED before it is promised: the first stage is the measurement with a pre-registered decision table (each outcome -> what is built, and the fallback named with what Boris would see), Harmony runs it, and no stage that depends on its outcome starts before she has.`,
    ruleFirst: [`the reconciliation table of AM-1..AM-30 and DA-1..DA-10`, `the first Bars number and the out point for a clip of any length, with worked examples at 120 BPM for clips of 2 s, 7.3 s, 9 s and 45 s`, `the measurement that answers "can you program this reliably or should we change the plan?", and the fallback if it fails`],
    items: `TD1 RECONCILE. One table: every amendment AM-1..AM-30 of ruling-transport.md and DA-1..DA-10 of ruling-transport-delta1.md -- STANDS / AMENDED / DROPPED, the 2026-10-04 line that decides it, and what replaces it. Then the same for every gate row and every stage of the chain.
TD2 THE PANEL. Resolume's Transport section as his screenshots 1, 2, 7 and 8 show it and as facts-resolume-transport documents it: the mode menu (Timeline and BPM Sync live; SMPTE 1, SMPTE 2, Denon DJ, Pioneer DJ LISTED AND GREYED -- "leave a dropdown menu for those items and grey them out for now"); the time readout (a click switches to remaining time); the timeline bar with its playhead and the in and out markers; play backwards, pause, play forwards; the loop-style menu with Resolume 7's options; NO trigger-style menu (his "42 default": every fire starts at the beginning); the Speed row (number, minus, plus, slider); the second row -- "Duration" in seconds in Timeline mode, "Bars" in BPM Sync (minus, plus, /2, x2); no BPM box on the clip (question 30's default). Drawn in Audio-DNA's own colours and fonts (reading R1). Say what of today's Clip panel it replaces (the Beats / Duration row and the Restart / Continue / Relative menu that never did anything), how the layer strip's play / reverse / pause buttons and its S fader relate to the panel's, and list every state the visual gate must capture. Where the documentation is silent (facts sheet: "NOT DOCUMENTED"), say so and name the one screenshot of Boris's own Arena that would settle it.
TD3 BARS. One bar = 4 beats. The set is 4, 8, 12, 16 ... (his "47 default"); 4 is the least. On switching a clip to BPM Sync the app works at 120 BPM: the largest multiple of 4 bars that fits the marked part, and the OUT POINT IS MOVED IN to it (never a stretched clip); a clip shorter than 4 bars is fitted WHOLE into 4 bars and plays slower (the one exception, his answer 43 / 47). With the bar count unchanged, moving the in or out point changes how fast the video looks (his answer 20). Rule: what minus and plus step by, what /2 does at 4 and at 12, the upper end, what the timeline's bar lines are drawn from ("Timeline only shows bars"), and whether the 120 used for the first number is 120 or the app's tempo at that moment (his words: "default all bpms to 120").
TD4 SPEED. In BPM Sync the Speed row and the layer strip's S fader step through Resolume's list -- 0, 1/8, 1/4, 1/2, 1, 2, 4, 8, 16 on its official page (his answer 25: "doubles and halves and then smaller fractions to higher multiples, just like resolume does"). Rule what 0 does, what the slider between two steps does, and the Timeline-mode range.
TD5 FIRES AND PAUSE. Every fire starts a clip at its beginning; a clip set to play backwards starts at its end. A paused clip that is fired stays paused -- read as: on the frame it was paused on (Resolume staff say the same; told to Boris as reading R16, not corrected); another clip fired on that paused layer shows its first frame and waits (INFERRED reading: a Boris check). Rule where "paused" lives (the clip or the layer) so that both hold, and what a column fire does to a paused layer.
TD6 THE PLAYHEAD. While he holds it still the picture waits; it cannot leave the ends of the timeline, nor the in and out points once they are moved; a click outside does nothing; a click inside moves it there. On release the clip plays on from there; in BPM Sync it then slides until the clip's bars sit on the music's BARS (his answer 33 B) -- the chain's beat lock, re-aimed from the beat to the bar: at most half a bar to make up, which at the chain's 6 % bound is about 17 seconds at 120 BPM. State the arithmetic at 90, 120 and 174 BPM, what he sees while it slides, and whether a faster slide or a jump on the next bar line is the fallback.
TD7 THE MEASUREMENT FIRST. His question: "can you program this reliably or should we change the plan?" Nothing of the lock is built or measured (the chain's facts FM-3, FM-4, FM-5 need runs and carry STOP clauses). Design the first stage as an instrument, not a feature: what is built behind a test-only switch, what is logged, the runs (how long, which tempi, a drop mid-bar, a Tap, a Resync, a nudge), the pre-registered decision table (each outcome -> build as ruled / build the named fallback / stop and ask), and what Harmony tells Boris for each outcome in one plain sentence.
TD8 STAYING ON THE BAR. His "9 b": the app keeps a BPM-synced clip in time by itself. With bars: the clip's bar lines stay on the music's bars over many minutes, across a tempo change, a Tap, a Resync and a nudge (it reads the shifted beat). What the chain already rules that carries, and what "bar" adds (beat-in-bar must be right: a Tap re-aligns the phase but not the beat-in-bar today -- facts-beat-controls).
TD9 RANDOM AND BEATLOOPR ("build random and beatloopr"). Random as Resolume 7 has it (a loop-menu option with Interval and Distance; what it does in each mode). BeatLoopr: what the documentation gives and what it does not (its option list is NOT documented): design it with the list as data, and ask Boris for the one screenshot of his Arena that fixes the list. In BARS or beats? ("The only place we see beats is in the circle with 4 positions in top bar".)
TD10 UNDO. The chain's undo-live rules (Cmd+Z never touches the layer strip; a removed layer comes back not playing; a fire is not an undo step) and today's defaults on questions 21, 22, 23: confirm each stands or say what changes.
TD11 STAGES AND ORDER. The new stage list (it replaces ruling-transport-delta1.md section 4), one builder context each, the files each owns, what each proves; the gate rows changed or added; the visual gate; the docs; what the output-settings lane and the beat-nudge lane (planned beside this one) must not both touch; and what waits for the nudge lane to merge first.`,
    seats: [
      { key: 'video-clock', temper: `You are the VIDEO-CLOCK SKEPTIC: a clip's position that is worked out from the beat clock has to be served by a decoder that runs off the GL thread, picks the newest frame not after its clock, keeps a GOP cache for reverse and ping-pong, and seeks by keyframe (Pitfalls 53, 54, 56, 62, 64); and the beat clock itself jumps on a Tap, a Resync, a nudge and Auto's own re-alignment. Attack: a bar lock whose arithmetic makes the clip jump, stall or run backwards for a frame; a slide that takes 17 seconds stated as "a few"; a first Bars number that is wrong for a clip shorter than 4 bars, or exactly 4 bars, or one frame over; an out point moved in to a frame that does not exist; Speed 0 or 16 against the decoder; a paused clip whose position moves; the measurement stage that cannot tell "reliable" from "not". Re-derive each claim from the code.` },
      GATES_SEAT,
      { key: 'stage-hands', temper: `You are the VJ WHO KNOWS RESOLUME BY HAND and now performs on Audio-DNA. Attack from what Boris does and sees: every place the panel looks like Resolume's and behaves differently without telling him (bars where Resolume says beats; a clip cut at its out point where Resolume would have fitted it; no "continue" on a re-fire; a scrubbed clip that slides); a 45-second clip that silently loses its last 5 seconds; a short loop that starts in slow motion; a greyed menu entry that looks broken; a paused clip he cannot get going; a playhead that will not go where he drags it; a number in bars he must convert in his head; Random or BeatLoopr options that do not match the Arena on the same desk; any text that announces an event or a failure (forbidden). Every attack names what Boris sees.` },
      SCOPE_SEAT,
    ],
  },
  'one-save': {
    title: `one Save -- the show holds its decks, its key and MIDI settings, its window layout and its routines; the separate saves go; the list of shows opens each show to its decks; quitting asks first`,
    goal: `Boris: "All of these things should be saved when a show is saved. There's no reason to save them separately". Decks are reached through the list of shows, each show opening to its decks -- "like this is how resolume does it" (his screenshot resolume-show-decks-list.png). Key and MIDI settings live in the show: opening a show switches to its set ("yes but you import the setup from the most recent show"), a show made from scratch "can import the settings from another show file". The window layout is in the show. Collect Media and Snapshot stay commands of their own. The effects looks are NOT this lane ("these are saved with the app. always."). And quitting opens a window as Resolume's does ("Do you really want to quit? All unsaved progress will be lost." -- Quit / Cancel / Save & Quit; his screenshot resolume-quit-dialog.png). Produce the plan a builder can execute stage by stage: what the show file holds afterwards, how each thing is read back, which commands, buttons, code, tests and docs go, how the list of shows opens to decks, the quit window, and how none of his existing files is harmed.`,
    sheets: ['one-save', 'saves', 'beat-controls'],
    qFirst: 91, qLast: 99,
    constraints: `Harmony constraint (lane one-save): Boris has ONE saved show, in the OLD shape, and four deck files in the v1 format (facts-one-save, the disk paragraph, confirmed by its re-read): nothing in this lane may make a file he has unreadable, and the first Save of an old-shape show must not destroy the only copy without a way back -- rule how (today a plain Save overwrites it in the new shape with no backup: the re-read's M-3). The show file gets a VERSION field, so that the next change of shape is never guessed from a key's presence. A show whose keys or layout block is absent, old or unreadable still OPENS -- the show loads and that block is skipped, never the reverse. Applying a show's keys never leaves a held key stuck or a learn screen half open. A command that goes takes its menu item, its button, its code, its tests and its docs with it in the same stage: no dead control stays on screen. The effects looks (the small Save and Load, FX Save, the ten slots) are not kept or removed by this lane beyond Boris's answer to question 86 (.harmony/.reports/s-rta-1004/boris-clarify-86.md when it exists): say what the lane does for each answer. Test mode never shows the quit window (gates quit the app by pid).`,
    ruleFirst: [`what is in the show file after this lane (the exact new keys, the version field) and what an old-shape and a version-less file read as`, `how the list of shows opens a show to its decks without loading a whole show on the message thread (no names-only reader exists today), and how a deck is taken from another show`, `the quit window: when it appears, what "Save & Quit" does for a show that has no file yet, and what it does while a take or a recording is running`],
    items: `OS1 THE SHOW FILE. Its top-level keys today (facts-one-save Q3): no version field; no key or MIDI settings; no layout; several keys that are saved and loaded and read by nothing. Rule: the version field and how a version-less or old-shape file is read; the new blocks; which dead keys are dropped now and which belong to another lane (bpmMultiplier sits with the beat-nudge lane's question on the inert /4 /2 x1 x2 x4 buttons); the protection for an old-shape show on its first Save.
OS2 KEYS AND MIDI. Today: bindings live only in memory, are empty at every launch, and only Export / Import to a file keeps them (facts-one-save Q4; facts-saves). Boris's rules, in order of time: saved with the show; opening a show switches to that show's set; a new show takes "the setup from the most recent show"; "Import settings" reads them from another show file he picks. Rule each case with what he sees: Save; Open of a show that has a set, and of one that has none; New; the LAUNCH (what is live before any show is opened -- "most recent" needs a memory: where, and is it the last show saved or the last opened); Import from a show file (menu item, chooser, replace or merge); Export / Import to their own file go. What applying a set does while a key is held or a learn screen is open. Side question to rule, not to build blindly: the eight Link macros and the user signals have no serializer although saved connections and one binding action name them (the re-read's M-6) -- in this lane, another lane, or a finding for Boris.
OS3 THE WINDOW LAYOUT. Today a layout is two numbers and three fractions, applied only by Load Layout / Reset Layout, never at launch (facts-one-save Q5). Harmony's reading told to Boris: opening a show arranges the window the way that show was saved. Rule: what a show without a layout does, what New does, whether Reset Layout stays, and what applying a layout while the show plays touches (the preview's GL context, keyboard focus, output windows -- the sheet's unknowns).
OS4 DECKS THROUGH THE LIST OF SHOWS. Today the list shows a name and a date per show file, sorted by name, and a click loads the whole show after a confirm; a separate Decks section lists deck files; no code reads a show's deck names without loading it (facts-one-save Q1, Q2). Boris's screenshot: the show's name with its size at the right, "4 Decks" with its date, then one row per deck name. Rule: the row layout and what opens / closes it; how deck names are read off the message thread, cached and refreshed; how a deck is TAKEN from another show's file into the current show (a click, a drag, a menu -- as close to the screenshot's Resolume as his words need) and what that does to deck ids, clip ids, layers the deck needs, routines, media paths and Undo (Pitfalls 36, 58; the wide-deck rule); an old-shape show in the list (his one show); Save Deck and Save Deck As go -- and with them the hole where a show loaded as a deck could be overwritten by Save Deck; what becomes of the Decks section and of v2 and v1 deck files on disk; the sort order. List every state the visual gate must capture.
OS5 THE QUIT WINDOW. Today every quit path ends in a bare quit: nothing is asked, only a running take and a video recording are finalised, and no "changed since the last save" flag exists anywhere (facts-one-save Q8). Rule: the window's text and three buttons as his screenshot; whether it appears on EVERY quit (no flag exists; Harmony's reading R18 told to him: every time) or only when something changed (which needs a flag: say what it would cost and whether his words ask for it); every path that must reach it (the menu item, Cmd+Q, the app menu, the window's close button, a system shutdown); "Save & Quit" for a show with no file; a failed Save inside it; a take or a recording running; New and Open keep their own confirm or take this one.
OS6 WHAT GOES AND WHAT STAYS. Table 1 of facts-one-save, row by row: stays / goes / changes, with the file:line; Table 2: every test and probe that turns red and what replaces it; the REST and OSC routes that save or load; the docs.
OS7 PROOF. Unit: the round trip of each new block; an old-shape file, a version-less file, a show with a broken keys block, a show from a later version. Live rows through test-server routes (name them): open a show and read the live keys; New; launch; take a deck from another show and read ids and layers; the quit window's logic without synthetic input (how). Mutants for each. Every live row is Harmony's.
OS8 STAGES AND ORDER. One builder context per stage, the files each owns, what each proves; the visual gate (the list of shows, the quit window); what waits on, or must not collide with, the lanes planned beside this one: messages (which failure box stays: a failed Save of the show), beat nudge (its number is a show field too), output settings (per machine, never in the show), transport.`,
    seats: [
      { key: 'data-safety', temper: `You are the FILE-FORMAT SKEPTIC: a show file is a performer's only copy of weeks of work. Attack: an old-shape or version-less file that opens differently or not at all after this lane; a first Save that overwrites the only copy of an old show; a version field that nothing checks; a keys or layout block whose damage takes the whole show down with it; a show carried to another machine whose keys name a controller that is not there; "the most recent show" when that file was moved, deleted or is on a drive that is not mounted; a write that reports success on a full disk (facts-saves: replaceWithText); a deck taken from another show whose ids collide, whose media paths point nowhere, or whose routines name decks that did not come along; a removed command whose old files become unreachable. Re-derive each claim from the code and from the listing of Boris's own files in the fact sheet.` },
      GATES_SEAT,
      { key: 'stage-hands', temper: `You are the VJ BETWEEN TWO ACTS, opening the next act's show with one hand on the controller. Attack from what Boris does and sees: keys and MIDI changing under his fingers when a show opens, or not changing when he expects them to; the window re-arranging itself mid-set; a new show that starts with no keys at all; finding last month's deck in a list sorted the wrong way; a show row that will not open, or opens and loads the whole show by mistake; the quit window appearing when he did not ask, not appearing when he hit Cmd+Q by accident, or "Save & Quit" quitting without having saved; a Save button that is gone with nothing saying where its job went; any text that announces an event or a failure (forbidden). Every attack names what Boris sees.` },
      SCOPE_SEAT,
    ],
  },
  'effect-looks': {
    title: `looks per effect -- every effect has many looks (parameter setups), kept by the app for every show; a small menu on each effect; the old Save, Load, FX Save and the ten slots go`,
    goal: `Boris: "every effect has many looks with specific parameter setups. these are saved with the app. always." Harmony's reading, told to him and not corrected: a look belongs to ONE effect -- a small menu on each effect to pick a look or to keep the current settings as a new look -- kept by the app for every show, the moment it is made. He also ruled ("86 default yes") that the OLD look buttons go now: the small Save and Load, FX Save and the ten numbered slots, which snapshot a hidden legacy effect chain and not the effects on a clip or a layer. Nothing like a per-effect look exists today: no per-effect menu, no copy / paste, no reset-all, no store (facts-effect-looks). Produce the plan a builder can execute stage by stage: what one look holds, where the looks live and how that store survives a bad file and a later version, the menu on an effect's row, what loading a look does to Undo, to a playing layer and to a take being recorded, the removal of the old buttons, and how it is proven.`,
    sheets: ['effect-looks', 'one-save', 'saves'],
    qFirst: 101, qLast: 109,
    constraints: `Harmony constraint (lane effect-looks): a look names its effect and its parameters BY NAME -- the show stores an effect's values as a bare positional array (facts-effect-looks), and a look must survive a parameter being added, removed or re-ordered in a later version (a missing name keeps the effect's current value; an unknown name is ignored; neither is an error and neither shows a text). The store is never a single read-modify-write file in which one unreadable read can drop every other effect's looks (facts-saves: settings.json does exactly that). "always" means a look is on disk the moment it is made: no separate Save step. Loading a look is ONE step, whole or not at all, and one undo step if anything about an effect is undoable at all -- rule it against the facts (parameter edits are not undoable today; a structural undo restores whole slots and overwrites later slider edits). It never changes anything in the layer strip (Boris: Cmd+Z and the strip), never writes a row the engine owns (Pitfall 33) except through the engine's own path, and what a take being recorded sees of it is MEASURED, not assumed (the sheet's unknown). The old buttons are removed EXACTLY ONCE: this lane and the one-save lane (plan-one-save.md / ruling-one-save.md in the same folder, when they exist) must not both own it -- rule which, and say what the other does.`,
    ruleFirst: [`what ONE look holds (parameter values only, or also Dry / Wet, bypass and the signal connections on its parameters) and why`, `where the looks live on disk and how that store survives an unreadable file, a renamed parameter and two versions of the app`, `which lane removes the old Save, Load, FX Save and the ten slots, so that they are removed exactly once`],
    items: `EL1 WHAT A LOOK HOLDS. One effect instance is a Clip::EffectSlot in a clip's, a shared layer's or the global vector (facts-effect-looks Q1): list its fields and rule which a look carries -- the parameter values; Dry / Wet; bypass; the signal connections and their curve / range / smoothing on its parameters (Q2: where they are stored and keyed). Forks: values only; values + Dry / Wet; values + connections. Rule one, and say what Boris gets when he loads a look onto an effect that has a signal wired to a parameter. Is there a "Default" look (the library's defaults) that cannot be deleted? Does the app SHIP looks, or only hold the ones he makes -- his words "every effect has many looks" can be read both ways: a Boris question with a default.
EL2 THE STORE. Where (the app-data folder has two spellings in the code -- say which code uses which and pick one), one file per effect or one store, keyed by which name of the effect (display name or shader key -- Pitfall 1), the format with names, the write (atomic; what a full disk does: facts-saves on replaceWithText), an unreadable or half-written file, an effect that is renamed or removed in a later version, the 135 effects times many looks at launch (read when, on which thread). Nothing shows on a failed write unless Boris's rules name it (only an unsaved clip or show recording, a failed Save of the show, no disk space to record, the quit window): rule what a look that could not be written looks like to him, as a STATE.
EL3 THE MENU ON AN EFFECT. The effect's header today (Q3): what it holds, that a right-click already folds it because the handler tests no button, how much room is left. Rule: where the looks control sits in every inspector that shows a stack (clip, layer, composition, EffectStackView); what the menu lists; how a look is named when it is made (an in-place name box: Pitfall 65) or whether it is numbered by itself; rename and delete; what shows which look is loaded, and what shows that the settings were changed since (a state, not a message); the PopupMenu rule; the drag-and-drop rules that must keep working (Pitfall 16). List every state the visual gate must capture.
EL4 LOADING A LOOK. What it writes and through which path (engine-driven rows, Pitfall 33); what it does while the layer plays; what Cmd+Z does afterwards (parameter edits are not undoable today, add / remove / bypass are, and a structural undo restores whole slots and overwrites later slider edits -- the re-read's finding: rule whether this lane mends that or only does not make it worse); what a take being recorded and a routine being replayed see; a look made for an effect on a clip loaded onto the same effect on a layer.
EL5 SOURCES. The procedural sources also have parameters (Q4). Boris spoke of effects: rule that sources are out of this lane, and say in one line what it would take later.
EL6 THE OLD BUTTONS GO. The small Save and Load, FX Save, the ten slots and their code, tests and docs (facts-one-save Q6 lists them). Which lane removes them. The hidden legacy chain they wrote into still renders after the deck compositor and is still driven by randomise, OSC and REST: NOT asked for removal -- a side finding with a recommendation, not a silent change. His four files in Presets/ become unreachable: say so in section 6.
EL7 PROOF. Unit: the store's round trip by name; a parameter added, removed, re-ordered; an unreadable file beside good ones; load = whole or nothing; the undo rule. Live rows through REST (the sheet: production REST reaches only clip effects of the shown deck -- name the test-server routes needed). The measurement of what a take sees. Mutants for each. Every live row is Harmony's.
EL8 STAGES AND ORDER. One builder context per stage, the files each owns, what each proves; the visual gate; docs (docs/claude/effects.md; CLAUDE.md's "instant preset save/recall" line names the feature that goes); what must not collide with the lanes planned beside this one (one-save: the top row of buttons and the show file; transport and its Undo rules, which are not built yet; messages).`,
    seats: [
      { key: 'data-safety', temper: `You are the STORE SKEPTIC: looks are small files a performer builds up over years and never thinks about until they are gone. Attack: a store keyed by a name that changes between versions (display name against shader key); values stored by position so that a parameter added in the next version shifts every look; one unreadable file that empties the others; a write that reports success on a full disk; a half-written file after a crash; 135 effects read on the message thread at launch; a look made on one machine that means something else on another; two looks with one name; a deleted effect's looks; the two spellings of the app-data folder; the old Presets files silently orphaned. Re-derive each claim from the code and the fact sheets.` },
      GATES_SEAT,
      { key: 'stage-hands', temper: `You are the VJ MID-SET with one hand on a fader: you want the look you made last week on this effect, now. Attack from what Boris does and sees: how many clicks to a look; a menu that hides the effect's fold or its remove button, or that a right-click no longer opens what it used to; a look that also resets the signal he wired to a parameter, or that does not when he expects it; a picture that jumps when a look loads while the layer plays; Cmd+Z after a look bringing back something else entirely; no sign of which look is on, or of having changed it; naming a look with the keyboard while keys are bound to clips; the old Save button gone with nothing saying where its job went; any text that announces an event or a failure (forbidden). Every attack names what Boris sees.` },
      SCOPE_SEAT,
    ],
  },
}
// ---- deltas on Boris's answers to a ruled lane's questions: the same shape (draft -> blind seats -> ruling), two seats
const ROOT = '/Users/boriskarpman/projects/RealTimeAudio/.harmony/.reports/s-rta-1004'
LANES['transport-answers'] = {
  title: `the transport lane, DELTA ON BORIS'S ANSWERS to questions 71, 72 and 74 -- no slide (one cut on the next "1"), pause is the clip's and is saved with the show, Timeline Speed goes to 10`,
  goal: `The transport lane is ruled and adopted (${ROOT}/ruling-transport-delta2.md; the HARMONY ADOPTION and its UPDATE at the end of ${ROOT}/plan-transport-delta2.md -- read both first). Nothing of it is built. Boris then answered: "71 b" (no slide: "the clip plays on from where it is and cuts once, on the next "1", into time"); 72: "new clip plays, the old clip is permanently paused and if comp is saved, it is saved as paused. the clip is now paused until the user changes that setting."; "74 b" (Timeline Speed goes to 10). Three of the ruling's choices fall (the slide, pause on the layer, Speed 0..4). Produce the DELTA: for every stage, unit case, gate row, visual state and Boris check of the ruling that these answers touch, the replacement text; for everything else, one line saying it stands. No stage is re-designed by a builder.`,
  sheets: ['resolume-transport', 'beat-controls', 'effect-looks'],
  qFirst: 121, qLast: 124,
  extraInputs: `- THE RULING THIS DELTA AMENDS: ${ROOT}/ruling-transport-delta2.md (sections 3 amendments RA-1..RA-17, 4 stages, 5 gate rows, 6 Boris checks, 8 decisions, the decision table O1..O7 and the measurements N1, R1, X1..X8) and its plan ${ROOT}/plan-transport-delta2.md with the two adoption blocks at its end. The questions as asked: ${ROOT}/boris-clarify-71-74.md. The beat-nudge ruling beside it: ${ROOT}/ruling-nudge.md and the adoption blocks at the end of ${ROOT}/plan-nudge.md (a BPM-synced clip reads the SHIFTED beat; the tempo row's play / pause / stop run the BPM timer: "the BPM goes to zero nothing moves" -- say what a BPM-synced clip does then).`,
  constraints: `Harmony constraint (transport answers): this is a DELTA -- it names every line of the ruling it replaces and leaves the rest standing by saying so; it adds no feature Boris did not ask for. His reliability question is still answered by MEASUREMENT: without a slide the question becomes "how often does the picture CUT" -- the first measurement (how often the app's "1" moves in Auto, three real tracks) stays first and its bar and STOP-AND-ASK stand; say plainly which of the instrument's parts and bars are still needed and which are void. A paused clip is a saved state of the show: an old show without the key opens with nothing paused; Cmd+Z never changes it (it is in the layer strip); a take or a routine replayed over it follows a rule you state.`,
  ruleFirst: [`what "in time" means with no slide: when a clip cuts, how often it can cut, and what Boris sees when the app's "1" moves in Auto`, `where the clip's pause lives, what writes it, and what the strip's and the panel's buttons show`, `Speed to 10: the slider's law and what the decoder is asked to do`],
  items: `TA1 NO SLIDE (71 B). Re-state stage S4c as the design, not the fallback: a BPM-synced clip that is out of time plays on and seeks ONCE, on the next "1", to the place the bar grid gives it. Rule: what "out of time" is (the bar of error that asks for a cut), whether an unquantised fire, a playhead drop, a Tap, a Resync, a nudge, a tempo change and Auto's own move of the "1" each lead to a cut and when; what keeps a clip in time BETWEEN cuts (his "9 b": the app keeps it in time by itself) without the slide's speed law -- a position worked out from the beat, or a rate that follows the tempo plus a cut when the error passes a bar; how many cuts a 10-minute track may show (N1's bar) and what he sees at each; what of SM-b's instrument, of X1..X8 and of the decision table O1..O7 stands, changes or is void. The picture at the cut: one seek (X8: within 3 render frames).
TA2 PAUSE IS THE CLIP'S, AND SAVED (72). The ruling put pause on the layer (F38) with TransportPause.h keeping the other answers small. Re-state: the field on the clip, the show key (absent = not paused), what sets and clears it (the strip's pause and play buttons act on the layer's playing clip; the Clip panel's buttons on the shown clip), a fired paused clip stays paused on its frame (his answer 26), a different clip fired on that layer plays (72) while the first keeps its pause, a column fire, what a paused clip shows in its grid cell (a state he can see -- he will open a show next week with clips saved paused), Clip::playing and hasBeenTriggered (Pitfalls 2, 7), takes and routines, and that Cmd+Z never changes it.
TA3 SPEED TO 10 (74 B). The Timeline-mode Speed slider and the strip's S fader in Timeline mode: range, law (Resolume's is non-linear: what the fact sheet documents and what it does not), the minus / plus step, a speed saved in an old show, what x10 asks of the decoder forward, reversed and in ping-pong (a measurement row beside X6), REST clamps.
TA4 THE CHANGE LIST. A table: every stage, unit case (TL-U..), lint, live row (TR..), visual state (W.., C..) and Boris check of ruling-transport-delta2.md that TA1..TA3 change -- old text, new text; and the count of what stands. Then the order of stages again, with what waits on what.`,
  seats: [GATES_SEAT, LANES['transport-delta2'].seats[2]],
}
LANES['nudge-row'] = {
  title: `the beat-nudge lane, DELTA ON BORIS'S ANSWERS to questions 61, 62 and 111 -- plus moves the beat earlier, the text reads "nudge X ms", and the tempo row of the top bar is rebuilt "similar to resolume"`,
  goal: `The beat-nudge lane is ruled and adopted (${ROOT}/ruling-nudge.md; the HARMONY ADOPTION and its UPDATE at the end of ${ROOT}/plan-nudge.md -- read both first). Nothing of it is built. Boris then answered: "61 b but lets call it "nudge X ms""; "62 do a similar to resolume: beatWheel play pause stop bpm# bpm- bpm+ nudgeBack nudgeForward /2 *2 tap resync"; "63 good (this is just nudge amount)"; and on what play / pause / stop run: "just the bpm timer. If most of the show is set up to BPM, and the BPM goes stop, the BPM goes to zero nothing moves. If there are clips that are not BPM based, then they play just as they were and are unaffected". The engine stages stand with one constant flipped. The top-bar stages do not: the row is his list, with five controls the ruling never planned (play, pause, stop, BPM minus, BPM plus) and two it had removed (/2 and *2, now to WORK). Produce the DELTA for the row and the text, stage by stage.`,
  sheets: ['beat-controls', 'resolume-screen-delay', 'one-save'],
  qFirst: 125, qLast: 129,
  extraInputs: `- THE RULING THIS DELTA AMENDS: ${ROOT}/ruling-nudge.md (sections 3 amendments, 4 stages S3a / VG-0 / S3b / VG, 5 gate rows, 6 Boris checks, 7, 8) and its plan ${ROOT}/plan-nudge.md with the two adoption blocks at its end. The questions as asked and Harmony's readings R69..R73 told to him: ${ROOT}/boris-clarify-61-63.md and boris-clarify-111.md. What Resolume's tempo row has and does: ${ROOT}/facts-resolume-screen-delay.md Q7 (Tap, Resync, plus / minus, x2, /2, nudge, pause -- with its VERIFICATION section's corrections). The transport ruling beside it: ${ROOT}/ruling-transport-delta2.md (BPM-synced clips read the beat this row can stop).`,
  constraints: `Harmony constraint (nudge row): the row is HIS list in HIS order -- beat wheel, play, pause, stop, BPM number, BPM minus, BPM plus, nudge back, nudge forward, /2, *2, tap, resync; nothing is added to it and nothing left out; Manual, Link and Quantize stay to its right (reading R69 told to him). Every control in it does something (no inert control ships: the five multiplier buttons are inert today). A stopped or paused BPM timer is a STATE he can see in the row; "nothing moves" covers every beat-driven reader at once (the one-shifted-beat rule of the ruling extends to one stopped beat), and what is not BPM-based is untouched. The tracker folds every tempo into 60..200 today (facts-beat-controls): say exactly what /2, *2, BPM minus and BPM plus do at the edges and in Auto, as facts, before choosing. The engine stages of the ruling (G-N0, S1, S2) and the key / pad stage S4 are not re-opened except where the stopped timer needs a field.`,
  ruleFirst: [`what a stopped and a paused BPM timer publish (the nine beat fields, the tempo) and what each beat-driven reader then does -- a quantised fire, a BPM-synced clip, a routine, autopilot`, `what /2, *2, BPM minus and BPM plus do in Auto and in Manual, against the tracker's 60..200 fold`, `the row's width at the window size Boris runs, with Manual, Link and Quantize to its right`],
  items: `NR1 SIGN AND TEXT (61 B). Plus moves the beat EARLIER; the text is "nudge X ms" (his words) -- rule the exact strings at 0, at a positive and a negative value and at the ends, where the text sits in the row (reading R70: between nudge back and nudge forward), and list every gate string, ui_text key and visual state of the ruling that carries the old text or the old sign.
NR2 THE BPM TIMER'S PLAY, PAUSE, STOP (62, 111). Nothing like it exists (facts-beat-controls: the top bar has a "Stop" button today -- read what it does and say whether it is this stop, stays beside it, or goes). Rule: what stop, pause and play each do to the published beat (his words: stopped, "the BPM goes to zero nothing moves"; stop back on the "1" and held, pause held where it is -- Harmony's question 111 A, which he took in his own words), in Auto (does the detector keep listening, and does it re-start the timer by itself), in Manual and under Link; what Tap and Resync do while stopped; what a quantised fire does while stopped (wait, or fire at once -- a Boris question if his words do not settle it); what a take records; where the state is kept (not in the show unless his words say so) and how the row shows it.
NR3 BPM NUMBER, MINUS, PLUS, /2, *2. The number shown and typed (today the BPM field appears only while Manual is on; a typed tempo is folded into 60..200 and the label shows the typed text); minus and plus (the step; Resolume's, from the fact sheet); /2 and *2 against the fold (120 *2 = 240 folds back to 120 today: what they must do instead, and what happens to the fold); what each does in Auto (switch to Manual? refuse as a greyed state?). /4, x1, x4 and the dead composition key bpmMultiplier go.
NR4 THE ROW ON SCREEN. Order, widths, the top bar's width budget (the ruling's FM-5: is today's bar already over 1280), what happens at a narrow window, tooltips, which controls can go on a key or a pad (Tap and Resync can today; nudge back / forward by the ruling's S4; the new ones: rule it), every state the visual gate must capture (the baseline VG-0 first).
NR5 THE CHANGE LIST. A table: every stage, unit case, live row, visual state and Boris check of ruling-nudge.md that NR1..NR4 change -- old text, new text; new stages if the row needs them (one builder context each, the files each owns); and what stands.`,
  seats: [GATES_SEAT, LANES['nudge'].seats[2]],
}
LANES['looks-answers'] = {
  title: `the per-effect looks lane, DELTA ON BORIS'S ANSWERS to questions 101-104 and 106 -- a look also carries the signals that drive its sliders, a changed look is a new look by default with "save over" offered, a name box opens holding "Look X"`,
  goal: `The per-effect looks lane is ruled and adopted (${ROOT}/ruling-effect-looks.md; the HARMONY ADOPTION at the end of ${ROOT}/plan-effect-looks.md -- read both first). Nothing of it is built. Boris then answered: 101 "I will build them later myself, but when the app is finished"; "102 B" (the look also remembers which signal drives each slider, and loading it plugs them in again); 103 "For a default behavior I will want to create a look 3 when I change look 2 and save a differnt version of look 2. look 2 remains unchanged but I need to have a way to save look 2 if I tweak it a little."; 104 "open a name box but with default name look x that can easily be changed"; 106 "delete them. this is a new build" (his two old preset files: done, nothing is converted). 102 B overrules the ruling's first ruled point ("no signal connections") -- the ruling itself called B "a later build with its own plan: it re-opens 'never a connection'". Produce the DELTA: what a look holds now, what loading does to the signals on an effect, the file format, the menu and the name box, and the list of every stage, case, row, state and Boris check of the ruling that changes.`,
  sheets: ['effect-looks', 'one-save', 'saves'],
  qFirst: 131, qLast: 134,
  extraInputs: `- THE RULING THIS DELTA AMENDS: ${ROOT}/ruling-effect-looks.md (section 0's three ruled points, 3 amendments, 4 stages, 5 gate rows, 6 Boris checks, 7 -- its lines "What changes with each answer", 8) and its plan ${ROOT}/plan-effect-looks.md with the adoption block at its end. The questions as asked: ${ROOT}/boris-clarify-101-106.md. What a signal connection is and where it is stored: ${ROOT}/facts-effect-looks.md Q2 (and its VERIFICATION section); that the user signals and the eight Link macros have NO serializer although saved connections name them by index and name: ${ROOT}/facts-one-save.md, the re-read's M-6.`,
  constraints: `Harmony constraint (looks answers): a look that names a signal must still load on an effect in a show where that signal does not exist -- whole or nothing for the slider values, and a stated rule for a connection that cannot be made (never a half-plugged effect, never a text that announces a failure; a STATE he can see is allowed). Loading a look onto a playing layer never makes the picture black or stutter (the plan's own reason against connections: assignment clears grips and engine state -- measure it, do not assume it away). "Default" and a look made from an effect with no signals: say exactly what each does to signals that are plugged in, and ask Boris only if his words do not settle it. Look files written by the ruling's format stay readable. "Save over" is a verified write (never a file left half-written): the ruling's "no file is ever rewritten" changes -- say what replaces it. The name box takes the keyboard while it is open and hands it back; the looks button itself still never does.`,
  ruleFirst: [`what a look holds now, and what loading one does to every signal already plugged into that effect`, `a look that names a signal the current show does not have`, `"save over": how the file is replaced safely, and how the menu tells "New Look" from "Save over Look 2"`],
  items: `LA1 SIGNALS IN A LOOK (102 B). What a connection on a parameter is in the show (the object, its fields: source signal, curve, range, smoothing, enabled), what it names (a built-in audio signal, a user signal, a macro) and how (index, name). Rule: which connections a look captures (those on this effect's parameters), the file format (the ruling's "one optional key per params entry"), what loading does -- to a parameter the look wires, to one the look leaves unwired while the effect has a signal on it (unplug, or leave), to "Default" -- and what it costs on a playing layer (the plan said assignment clears grips and engine state: read it, state it, and name the measurement). A signal the show does not have. EffectLookCmd as one undo step with connections in it. What a take sees.
LA2 A CHANGED LOOK (103). Default: the change is kept as a NEW look and the loaded one stays as it was. Also offered: save the tweak back into the loaded look. Rule the menu's wording and order, what "the loaded look" is when the button's name is derived from the values (after a tweak the values match no look: which look does "Save over" name?), the verified replace, and Undo of a save-over (is there one?).
LA3 THE NAME BOX (104). Making a look opens a name box already holding "Look X" (the next free number), selected so that typing replaces it; Return keeps, Esc makes no look; an empty or illegal or taken name; keyboard focus in and out (his keys launch clips: nothing may fire while he types); the same window for Rename.
LA4 NOTHING SHIPS (101), HIS OLD PRESETS ARE GONE (106). No looks ship; no conversion stage; one line each on what the ruling drops for it (HD-2, question 106's B path).
LA5 THE CHANGE LIST. A table: every stage, unit case, lint, live row, visual state and Boris check of ruling-effect-looks.md that LA1..LA4 change -- old text, new text; new stages if signals need them (one builder context each, the files each owns); what stands; and whether S1 (the store, headless) can still start first unchanged.`,
  seats: [LANES['effect-looks'].seats[0], GATES_SEAT, LANES['effect-looks'].seats[2]],
}
const A = Object.assign({ key: (args || {}).key }, LANES[(args || {}).key] || {})
const MAIN = '/Users/boriskarpman/projects/RealTimeAudio'
const RPT = '.harmony/.reports/s-rta-1004'
const PIN = '185147b'
const BF2 = MAIN + '/.claude/worktrees/bf2'
const KEYS = MAIN + '/.claude/worktrees/bf2keys'
const KEY = A.key
const PLAN_FILE = RPT + '/plan-' + KEY + '.md'
const RULING_FILE = RPT + '/ruling-' + KEY + '.md'
const PAPERS_FILE = RPT + '/attack-' + KEY + '-papers.md'
const SHEETS = (A.sheets || []).map(s => MAIN + '/' + RPT + '/facts-' + s + '.md')

const READS = `HOW TO READ (binding): you are read-only. main = ${MAIN}, pinned at commit ${PIN}: first run git -C ${MAIN} rev-parse --short HEAD (must print ${PIN}) and git -C ${MAIN} status --short -- src tests docs CMakeLists.txt (must print nothing); then read plain files under ${MAIN}/src, ${MAIN}/tests, ${MAIN}/docs/claude, ${MAIN}/CLAUDE.md (if either check fails, read only through git -C ${MAIN} show ${PIN}:<path> and say so). The STOPPED sync-dial branches are a source of parts only, each in a clean worktree nobody edits: lane/bf2 at 740b6d6 in ${BF2}, lane/bf2-keys at 9eab9bd in ${KEYS} (check git -C <worktree> rev-parse --short HEAD and status --short before reading plain files there). Reports and Boris's records under ${MAIN}/.harmony/ are plain files. Never build, never run a test, never launch the app or a probe, never touch a running Audio-DNA or Resolume Arena (they are Boris's). Never cd in a command; absolute paths only. If a user message was relayed to you, Harmony has already filed and answered it; it never replaces this task.`

const INPUTS = `INPUTS (big files are indexed -- grep -n '^#' first, then read ranges):
- BORIS'S WORDS, binding, read first: ${MAIN}/.harmony/binding-decisions.md, every section headed "2026-10-04 (s-rta-1004)" (his words in quotes; the text after "->" is Harmony's consequence text, not his). The whole messages with the questions as asked: ${MAIN}/.harmony/boris-feedback-backlog.md, the sections stamped 2026-10-04 (BF38..BF60). Quote him ONLY verbatim and only from these two files.
- THE QUESTIONS AS ASKED, Harmony's readings R1..R32 told to him, and what is still OPEN: ${MAIN}/${RPT}/boris-clarify-26-37.md, -38-41.md, -42-44.md, -45-46.md, -47-49.md, -50.md. OPEN at this moment: 47 (the set of bar counts), 48 (which Record boxes), 49 (what the nudge number reads after a Resync; default 0), 50 (key and MIDI settings between launches; default: the app remembers them). Where your lane touches an open one, design so that either answer is a small change and say which line changes.
- THE FACT SHEETS (verified today; each ends with a "VERIFICATION" section -- its corrections OVERRIDE the sheet's own body): ${SHEETS.join(', ')}. Others exist in the same folder (ls ${MAIN}/${RPT}/facts-*.md). Resolume screenshots Boris sent: ${MAIN}/${RPT}/boris-resolume/*.png (Read the ones your lane concerns).
- HARMONY'S RULINGS on the stopped sync dial: ${MAIN}/.harmony/.reports/s-rta-1003b/rulings-bf2.md (H-17: the lane is superseded; what is void, what is kept as parts).
- PROJECT RULES: ${MAIN}/CLAUDE.md (sacred rules, UI patterns, the pitfall index), ${MAIN}/docs/claude/pitfalls.md (read the numbered entries your lane touches), the topic docs under ${MAIN}/docs/claude/, ${MAIN}/.harmony/RIG-RULES.md (how live gates run on a machine Boris is using) and the SCREEN-SAFETY LAW in ${MAIN}/.harmony/HANDOFF.md (no gate ever opens an Output window; no full-screen capture; no synthetic input).
- THE FORM a ruling takes in this project (mirror its section list, not its content): ${MAIN}/.harmony/.reports/s-rta-1003b/ruling-bf2-stops.md.${A.extraInputs ? '\n' + A.extraInputs : ''}`

const RULES = `RULES OF THE DOCUMENT: Boris is quoted ONLY verbatim; anything Harmony requires is written as "Harmony constraint:". No code blocks longer than a signature. The real-time rules hold (no allocation / lock / syscall on the audio callback; analysis steady state allocation-free; the render thread never waits; no new mutex without saying so). A pre-registered bar is never loosened: it is met, or reported. Every new test or gate row is RED first and has a named RED arm (a mutant or the tree before the change). Prefer the smallest change that is correct; say what is NOT in this lane. No on-screen text that announces an event or a failure (Boris 2026-10-03 and 2026-10-04: only an unsaved clip recording, an unsaved show recording, a failed Save of a show or deck, not enough disk space to record, and the quit window); a STATE display is allowed. Every slider is a ResettableSlider with a default; popup menus use showMenuAsync with the top-level parent. Anything Boris will SEE goes through the visual gate (a capture builder, then five critic seats) before he sees it: name the states to capture. Questions for Boris are numbered ${A.qFirst}..${A.qLast} (new numbers; a question already shown to him is never re-worded), each in plain words with a default A, and only what is genuinely his (taste, behaviour he performs with); a technical fork is ruled here, not asked.
${A.constraints || ''}`

const PS = { type: 'object', properties: { plan_path: { type: 'string' }, status: { type: 'string', enum: ['DONE', 'PARTIAL'] }, summary: { type: 'string' }, forks: { type: 'array', items: { type: 'object', properties: { id: { type: 'string' }, choice: { type: 'string' }, runner_up: { type: 'string' } }, required: ['id', 'choice'] } }, not_verified: { type: 'array', items: { type: 'string' } } }, required: ['plan_path', 'status', 'summary', 'forks'] }
const AS = { type: 'object', properties: { seat: { type: 'string' }, attacks: { type: 'array', items: { type: 'object', properties: { id: { type: 'string' }, target: { type: 'string' }, claim: { type: 'string' }, evidence: { type: 'string' }, severity: { type: 'string', enum: ['MUST', 'SHOULD', 'NIT'] }, proposed_change: { type: 'string' } }, required: ['id', 'target', 'claim', 'evidence', 'severity'] } }, strongest_point: { type: 'string' }, citations_rechecked: { type: 'boolean' } }, required: ['seat', 'attacks', 'strongest_point', 'citations_rechecked'] }
const RS = { type: 'object', properties: { ruling_path: { type: 'string' }, papers_path: { type: 'string' }, status: { type: 'string', enum: ['DONE', 'PARTIAL'] }, verdict: { type: 'string' }, amendments: { type: 'number' }, attacks_ruled: { type: 'number' }, stages: { type: 'array', items: { type: 'object', properties: { key: { type: 'string' }, scope: { type: 'string' } }, required: ['key', 'scope'] } }, boris_questions: { type: 'array', items: { type: 'string' } }, harmony_decisions: { type: 'array', items: { type: 'string' } }, facts_harmony_must_measure: { type: 'array', items: { type: 'string' } }, strongest_counterargument: { type: 'string' } }, required: ['ruling_path', 'status', 'verdict', 'amendments', 'attacks_ruled', 'stages'] }

phase('Plan')
const plan = await agent(`PLAN AUTHORING (architect) -- Audio-DNA (C++20 / JUCE / OpenGL live audio-reactive VJ app, macOS), lane "${KEY}": ${A.title}. You author the position; a blind council attacks it; an architect ruling follows; Harmony decides.
GOAL: ${A.goal}
${READS}
${INPUTS}
ITEMS. For each: what is VERIFIED (a file:line at ${PIN}, or a row of a fact sheet whose VERIFICATION section did not overturn it), the forks, the choice, why the runner-up loses, the change by file / function (no code), the RED-first tests and their mutants, the gate row.
${A.items}
OUTPUT: write the plan to REPORT_FILE (literal path below, relative to ${MAIN}; bash heredoc to exactly that path). Sections: 1 GOAL; 2 ESTABLISHED FACTS (ONLY verified lines, each with file:line or the sheet and row; anything else is labelled INFERRED or ASSUMED where it is used); 3 ITEMS; 4 STAGES + ORDER (one builder context per stage; what each proves; which files each owns; what Harmony runs herself -- every live row and every gate verdict is hers, never a builder's); 5 TESTS + GATE ROWS (exact strings and bars, pre-registered; each with its RED arm); 6 WHAT ONLY BORIS CAN CHECK (do -> expect -> what wrong looks like; on his real screens and by his ear); 7 QUESTIONS FOR BORIS; 8 RISKS (the strongest counterargument first; the cheapest refuting test for each choice); 9 WHAT IS NOT IN THIS LANE (incl. what is carried from, and what is dropped with, the stopped sync-dial branches, each with its commit).
${RULES}
TURN BUDGET (the architect role stops SILENTLY at 120 turns): write a SKELETON of the plan file with all headings by your turn 8; rewrite it with what you have every ~10 turns; be DONE by turn 90; if short, status PARTIAL with what is missing at the top.
REPORT_FILE: ${PLAN_FILE}
RETURN: plan_path, status, summary <= 1500 characters, forks (id, choice, runner_up), not_verified (what you could not establish by reading).`, { agentType: 'architect', model: 'opus', effort: 'high', schema: PS, phase: 'Plan', label: 'plan:' + KEY })
if (!plan) return { failed: 'plan' }
log('plan: ' + plan.status + ' -> ' + plan.plan_path)

phase('Attack')
const SEATS = A.seats || []
const papers = (await parallel(SEATS.map(s => () => agent(`BLIND COUNCIL SEAT "${s.key}" -- attack ONE plan from ONE temperament. You do not see the other seats.
${s.temper}
THE PLAN UNDER ATTACK: ${MAIN}/${PLAN_FILE} (read it IN FULL first).
${READS}
${INPUTS}
MANDATORY CITATION RE-CHECK: before you return, re-open every file:line, sheet row or record line you cite and confirm it says what you claim; set citations_rechecked accordingly and drop any attack whose evidence did not survive. An attack without evidence (a file:line at ${PIN}, a fact-sheet row, a quoted plan line, or a quoted line of Boris's verbatim record) is not an attack.
Do NOT write any file. RETURN (StructuredOutput): seat, attacks (id like ${s.key.slice(0, 2).toUpperCase()}-1..; target = the plan item / section; claim; evidence; severity MUST = the plan would ship a defect, contradict Boris's verbatim words, break a real-time or screen-safety rule, or carry a gate that cannot fail, SHOULD, NIT; proposed_change), strongest_point, citations_rechecked. At most 8 attacks, each field under 900 characters; fewer and sharper is better.`, { agentType: 'authored-council-seat', model: 'sonnet', effort: 'high', schema: AS, phase: 'Attack', label: 'attack:' + KEY + ':' + s.key })))).filter(Boolean)
const papersJson = JSON.stringify(papers)
const nAtt = papers.reduce((n, p) => n + (p.attacks || []).length, 0)
log('seats returned: ' + papers.length + ' of ' + SEATS.length + '; attacks: ' + nAtt + '; papers ' + papersJson.length + ' characters (passed WHOLE, no cut)')
if (papers.length < SEATS.length) log('MISSING SEATS: ' + SEATS.filter(s => !papers.some(p => String(p.seat || '').indexOf(s.key) >= 0)).map(s => s.key).join(', '))

phase('Ruling')
const ruling = await agent(`ARCHITECT RULING on a blind council's attacks, lane "${KEY}": ${A.title} (you run on opus at max effort because Fable is out of usage -- Boris, verbatim, 2026-10-02: "just so you know, we are out of fable usage so you will need to do all fable work with opus 5.5"). Harmony decides after you; your ruling is her working document.
THE PLAN: ${MAIN}/${PLAN_FILE} (read IN FULL).
THE SEAT PAPERS (${papers.length} of ${SEATS.length} seats returned; verbatim JSON, WHOLE -- ${papersJson.length} characters; if the text below does not end with a closed JSON array, STOP and return status PARTIAL saying so): ${papersJson}
${READS}
${INPUTS}
DO, IN THIS ORDER:
1. FIRST write the seat papers verbatim (pretty-printed, one section per seat) to ${PAPERS_FILE} (literal path, relative to ${MAIN}, bash heredoc).
2. For every attack: re-derive the evidence yourself in the code at ${PIN}, in the fact sheets or in Boris's record (never trust a seat's citation, never the plan's); verdict ACCEPT / PARTIAL / REJECT with the line that decides it. Reconcile seats that conflict. Where an outcome turns on a fact that only a run can establish, do NOT guess: name the measurement, who runs it (Harmony runs every live row), and give the ruling for EACH outcome. Where it turns on what Boris wants and his words do not settle it, it is a BORIS QUESTION with a default.
3. Write the ruling to REPORT_FILE: 0 VERDICT; 1 FACTS RE-DERIVED; 2 ATTACK RULINGS (table: one row per attack id); 3 AMENDMENTS (numbered; each OVERRIDES the plan body); 4 FINAL STAGES + ORDER (one builder context each; the files each owns; what each proves; what Harmony runs herself and when); 5 TESTS + GATE ROWS (pre-registered; exact strings and bars; each row's RED arm); 6 WHAT ONLY BORIS CAN CHECK; 7 BORIS QUESTIONS (numbers ${A.qFirst}..${A.qLast}; each with a default); 8 HARMONY'S DECISIONS (each with a default); 9 SIDE FINDINGS; 10 RISKS (the strongest counterargument first).
${RULES}
RULE FIRST, and state plainly at the top of section 0: ${(A.ruleFirst || []).join('; ')}.
TURN BUDGET (the role stops SILENTLY at 120 turns): papers file by turn 4; a SKELETON ruling with all headings by turn 10; rewrite every ~10 turns; DONE by turn 90; if short, status PARTIAL with what is missing at the top.
REPORT_FILE: ${RULING_FILE}
RETURN: ruling_path, papers_path, status, verdict (<= 1200 characters), amendments (count), attacks_ruled (count), stages (key + one-line scope), boris_questions, harmony_decisions, facts_harmony_must_measure, strongest_counterargument.`, { agentType: 'architect', model: 'opus', effort: 'max', schema: RS, phase: 'Ruling', label: 'ruling:' + KEY })
const cut = (s, n) => String(s || '').slice(0, n)
return { lane: KEY, plan: { path: plan.plan_path, status: plan.status, summary: cut(plan.summary, 1500), forks: (plan.forks || []).map(f => ({ id: f.id, choice: cut(f.choice, 260), runner_up: cut(f.runner_up, 200) })), not_verified: (plan.not_verified || []).map(x => cut(x, 240)) }, seats: papers.map(p => ({ seat: p.seat, n: (p.attacks || []).length, must: (p.attacks || []).filter(a => a.severity === 'MUST').length, strongest: cut(p.strongest_point, 300) })), attacks_sent: nAtt, papers_chars: papersJson.length, ruling: ruling ? { ruling_path: ruling.ruling_path, status: ruling.status, verdict: cut(ruling.verdict, 1200), amendments: ruling.amendments, attacks_ruled: ruling.attacks_ruled, stages: (ruling.stages || []).map(s => ({ key: s.key, scope: cut(s.scope, 300) })), boris_questions: (ruling.boris_questions || []).map(x => cut(x, 400)), harmony_decisions: (ruling.harmony_decisions || []).map(x => cut(x, 300)), facts_harmony_must_measure: (ruling.facts_harmony_must_measure || []).map(x => cut(x, 300)), strongest_counterargument: cut(ruling.strongest_counterargument, 500) } : { failed: true } }
